-- Targeted migration: standardize Cisco CCNP ENCOR 350-401-P1/P2 to spec.
-- 1) Bump questionCount to 100 (official 90-110 midpoint).
-- 2) Insert 37 grounded fill questions across 5 under-served ENCOR domains.
-- Does NOT touch published or deletedAt on any row.
-- Idempotent: UPDATEs filter on current value; INSERTs guarded by WHERE NOT EXISTS.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1) Standardize questionCount
UPDATE "Exam" SET "questionCount" = 100
  WHERE code IN ('350-401-P1', '350-401-P2') AND "questionCount" <> 100;

-- 2) Insert grounded fill questions
-- 350-401-P1: 26 new questions
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network architect is designing a large enterprise campus network that must support thousands of endpoints across multiple buildings. The design requires clear separation between the access layer, a distribution layer for policy enforcement, and a high-speed backbone. Which campus architecture model BEST satisfies these requirements?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"Two-tier (collapsed core) architecture"},{"id":"b","text":"Three-tier (access, distribution, core) architecture"},{"id":"c","text":"Single-tier flat architecture"},{"id":"d","text":"SD-Access fabric architecture without any physical tiering"}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$The source material states: 'Three-tier (campus): access -> distribution -> core; large enterprise.' This model explicitly provides three distinct layers — access for endpoint connectivity, distribution for policy enforcement and aggregation, and core for high-speed backbone forwarding — making it the correct choice for a large enterprise campus. The two-tier (collapsed core) model merges distribution and core, which is suited for smaller networks, not large enterprises with thousands of endpoints. A single-tier flat architecture lacks scalability and policy enforcement boundaries. SD-Access is an overlay fabric technology but does not replace the need for physical tiering in a traditional campus design context.$patch$, $patch$Architecture$patch$,
         4, $json$[{"url":"https://learningnetwork.cisco.com/s/encor-exam-topics","label":"Cisco ENCOR 350-401 Official Cert Guide – Campus Network Design"},{"url":"https://www.cisco.com/c/en/us/td/docs/solutions/Enterprise/Campus/campover.html","label":"Cisco Design Zone – Campus LAN Design Guide"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network architect is designing a large enterprise campus network that must support thousands of endpoints across multiple buildings. The design requires clear separation between the access layer, a distribution layer for policy enforcement, and a high-speed backbone. Which campus architecture model BEST satisfies these requirements?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$In a Cisco SD-WAN (Viptela) deployment, a network engineer needs to identify which component is responsible for distributing routing and policy information (OMP routes) to all vEdge/cEdge routers in the overlay fabric. Which SD-WAN component fulfills this role?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"vBond"},{"id":"b","text":"vManage"},{"id":"c","text":"vSmart"},{"id":"d","text":"cEdge"}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$The source material identifies the Cisco SD-WAN components as: 'vManage (orchestration), vSmart (control), vBond (orchestrator/zero-touch), vEdge/cEdge routers.' The vSmart controller is the control-plane component that runs the Overlay Management Protocol (OMP) and distributes routing information, policies, and crypto key material to all WAN edge devices. vManage is the centralized management and orchestration GUI. vBond handles initial authentication and zero-touch provisioning of edge devices. cEdge/vEdge routers are the data-plane forwarding devices. Therefore, vSmart is the correct answer for control-plane (routing/policy) distribution.$patch$, $patch$Architecture$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/routers/sdwan/configuration/sdwan-xe-gs-book/system-overview.html","label":"Cisco SD-WAN Design Guide – Controller Functional Overview"},{"url":"https://learningnetwork.cisco.com/s/encor-exam-topics","label":"Cisco ENCOR 350-401 Exam Topics"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$In a Cisco SD-WAN (Viptela) deployment, a network engineer needs to identify which component is responsible for distributing routing and policy information (OMP routes) to all vEdge/cEdge routers in the overlay fabric. Which SD-WAN component fulfills this role?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$An enterprise is deploying Cisco SD-Access. The network architect states that the underlay network uses a specific routing protocol and the overlay uses LISP for control-plane functions with VXLAN for data-plane encapsulation. Which routing protocol does the SD-Access underlay use by default, and which protocol handles host-mobility control-plane functions in the overlay?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"Underlay: OSPF; Overlay control-plane: BGP EVPN"},{"id":"b","text":"Underlay: IS-IS (routed); Overlay control-plane: LISP"},{"id":"c","text":"Underlay: EIGRP; Overlay control-plane: VXLAN"},{"id":"d","text":"Underlay: BGP; Overlay control-plane: GRE"}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$The source material explicitly states: 'SD-Access / Cisco DNA: fabric architecture with underlay (routed IS-IS) + overlay (LISP/VXLAN), separation of control/data plane via LISP, GRE/VXLAN encapsulation.' IS-IS is the default underlay routing protocol used by Cisco DNA Center to automate the routed access design. LISP (Locator/ID Separation Protocol) provides the control-plane for endpoint location and mobility tracking in the overlay, while VXLAN provides the data-plane encapsulation. OSPF, EIGRP, BGP, BGP EVPN, and GRE are not the default SD-Access underlay/overlay combination as described in the source material.$patch$, $patch$Architecture$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/solutions/CVD/Campus/cisco-sda-design-guide.html","label":"Cisco SD-Access Solution Design Guide – Fabric Overlay and Underlay"},{"url":"https://developer.cisco.com/docs/dna-center/#!sd-access-overview","label":"Cisco DNA Center SD-Access Overview"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$An enterprise is deploying Cisco SD-Access. The network architect states that the underlay network uses a specific routing protocol and the overlay uses LISP for control-plane functions with VXLAN for data-plane encapsulation. Which routing protocol does the SD-Access underlay use by default, and which protocol handles host-mobility control-plane functions in the overlay?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network engineer is configuring a first-hop redundancy protocol on a distribution layer switch pair. The requirement states that the solution must support active load balancing of traffic across both gateway routers simultaneously using a single virtual IP address and a single virtual MAC address. Which FHRP should the engineer implement?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"HSRP version 1"},{"id":"b","text":"VRRP version 3"},{"id":"c","text":"GLBP"},{"id":"d","text":"HSRP version 2"}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$The source material states: 'GLBP (Cisco proprietary, supports load balancing across AVF).' GLBP (Gateway Load Balancing Protocol) is the only FHRP that provides true active/active load balancing. It uses a single virtual IP address while multiple Active Virtual Forwarders (AVFs) each have their own virtual MAC address, distributing host traffic across all gateways simultaneously. HSRP (both v1 and v2) uses an active/standby model where only one router forwards traffic at a time — the standby router is idle until failover. VRRP similarly uses a master/backup model with only one active forwarder. Neither HSRP nor VRRP natively load-balances across both routers without additional per-VLAN/group tricks.$patch$, $patch$Architecture$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipapp_fhrp/configuration/xe-16/fhp-xe-16-book/fhp-glbp.html","label":"Cisco IOS Gateway Load Balancing Protocol (GLBP) Configuration Guide"},{"url":"https://www.cisco.com/c/en/us/support/docs/ip/hot-standby-router-protocol-hsrp/9234-hsrpglbp.html","label":"Cisco FHRP Comparison – HSRP, VRRP, GLBP"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network engineer is configuring a first-hop redundancy protocol on a distribution layer switch pair. The requirement states that the solution must support active load balancing of traffic across both gateway routers simultaneously using a single virtual IP address and a single virtual MAC address. Which FHRP should the engineer implement?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A wireless engineer is deploying access points in a remote branch office that has limited WAN bandwidth to the central data center. The design requires that client data traffic be switched locally at the branch and only management/control traffic traverse the WAN to the Wireless LAN Controller. Which AP operational mode should be configured to meet this requirement?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"Local mode"},{"id":"b","text":"Monitor mode"},{"id":"c","text":"FlexConnect mode"},{"id":"d","text":"Sniffer mode"}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$The source material describes AP modes as follows: 'Local (default, traffic tunneled to WLC via CAPWAP)' and 'FlexConnect (local switching).' FlexConnect (formerly H-REAP) is specifically designed for branch office deployments where the AP can switch client data traffic locally at the branch without hairpinning it across the WAN to the WLC. Only control and management traffic uses the CAPWAP tunnel to the central WLC, conserving WAN bandwidth. Local mode tunnels ALL client data via CAPWAP to the WLC, which would consume significant WAN bandwidth — the opposite of what is required. Monitor mode is used for passive RF monitoring and does not serve clients. Sniffer mode captures 802.11 frames and forwards them to a packet analyzer — it also does not serve clients.$patch$, $patch$Architecture$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/wireless/controller/technotes/flexconnect-dg.html","label":"Cisco FlexConnect Design and Deployment Guide"},{"url":"https://www.cisco.com/c/en/us/support/docs/wireless/catalyst-9800-series-wireless-controllers/213485-catalyst-9800-ap-modes-overview.html","label":"Cisco Wireless LAN Controller AP Modes – Configuration Guide"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A wireless engineer is deploying access points in a remote branch office that has limited WAN bandwidth to the central data center. The design requires that client data traffic be switched locally at the branch and only management/control traffic traverse the WAN to the Wireless LAN Controller. Which AP operational mode should be configured to meet this requirement?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network engineer is designing a data center fabric that requires Layer 2 extension across Layer 3 boundaries and must support approximately 10 million logical network segments. Which encapsulation technology best satisfies both requirements?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"GRE (Generic Routing Encapsulation)"},{"id":"b","text":"VXLAN (Virtual Extensible LAN)"},{"id":"c","text":"IPsec in transport mode"},{"id":"d","text":"802.1Q VLAN trunking"}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$The source material states that VXLAN uses MAC-in-UDP encapsulation and provides a 24-bit VNI (Virtual Network Identifier), which yields up to 16 million logical segments — far exceeding the 4,094 limit of 802.1Q VLANs. VXLAN is explicitly noted as used for DC fabric and SD-Access overlays, making it the correct choice. GRE is a simpler IP-in-IP tunnel that carries no segment identifier at this scale. IPsec transport mode encrypts the payload between two endpoints but does not provide multi-tenancy segmentation identifiers. 802.1Q is limited to 4,094 VLANs and cannot span Layer 3 boundaries natively.$patch$, $patch$Virtualization$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/white-paper-c11-729383.html","label":"Cisco VXLAN Overview – Cisco Documentation"},{"url":"https://datatracker.ietf.org/doc/html/rfc7348","label":"RFC 7348 – Virtual eXtensible Local Area Network (VXLAN)"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network engineer is designing a data center fabric that requires Layer 2 extension across Layer 3 boundaries and must support approximately 10 million logical network segments. Which encapsulation technology best satisfies both requirements?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$An enterprise is deploying DMVPN to enable dynamic spoke-to-spoke tunnels. After initial deployment in Phase 1, the team upgrades to Phase 3. What is the primary functional enhancement introduced in DMVPN Phase 3 compared to Phase 2?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"Phase 3 replaces NHRP entirely with a BGP-based next-hop resolution mechanism."},{"id":"b","text":"Phase 3 uses NHRP Redirect messages to allow spokes to build direct tunnels via a single-hop shortcut, regardless of summarization boundaries."},{"id":"c","text":"Phase 3 introduces IPsec AH authentication to replace ESP encryption on spoke-to-spoke tunnels."},{"id":"d","text":"Phase 3 changes the hub role to a passive reflector that no longer participates in data-plane forwarding."}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$The source material explicitly lists DMVPN phases: 'phase 1 (hub-spoke), phase 2 (spoke-to-spoke), phase 3 (NHRP redirect).' In Phase 3, the hub sends an NHRP Redirect to the originating spoke, instructing it to build a direct shortcut tunnel to the destination spoke. The key advantage over Phase 2 is that Phase 3 works correctly even when the hub is summarizing routes, because the redirect mechanism decouples next-hop resolution from routing summarization constraints. NHRP is not replaced by BGP (option A is false). IPsec mode selection is independent of DMVPN phase (option C is false). The hub continues to participate in forwarding until the shortcut is established (option D is false).$patch$, $patch$Virtualization$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/solutions/Enterprise/WAN_and_MAN/DMVPN_2_Phase3/DMVPN_Phase3.html","label":"Cisco DMVPN Design Guide – Phase 1, 2, and 3 Explained"},{"url":"https://datatracker.ietf.org/doc/html/rfc2332","label":"RFC 2332 – NBMA Next Hop Resolution Protocol (NHRP)"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$An enterprise is deploying DMVPN to enable dynamic spoke-to-spoke tunnels. After initial deployment in Phase 1, the team upgrades to Phase 3. What is the primary functional enhancement introduced in DMVPN Phase 3 compared to Phase 2?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A service provider wants to run multiple customers' routing tables on a single physical router while keeping their traffic completely isolated. The engineer also needs to selectively share specific routes between two customer VRFs. Which combination of VRF features should be used?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"VRF-Lite with VLAN sub-interfaces only; no additional configuration is required for route sharing."},{"id":"b","text":"Multiple VRF instances for isolation, with route-target import/export configured for route leaking between the desired VRFs."},{"id":"c","text":"A single global routing table partitioned by administrative distance values to separate customer routes."},{"id":"d","text":"GRE tunnels between each customer VRF with static routes to achieve selective route sharing."}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$The source material states: 'VRF: Multiple routing tables on the same device; route leaking via route-target import/export. Used for multi-tenancy on a single physical router.' VRF provides the necessary isolation by giving each customer its own routing table instance. Route leaking — the mechanism for selectively sharing routes between VRFs — is accomplished through the route-target import/export extended community attributes in MP-BGP. Option A (VLAN sub-interfaces alone) provides L2 separation but does not create independent routing tables. Option C (administrative distance partitioning) does not isolate routing tables; it only influences path selection within a single table. Option D (GRE tunnels) is an overly complex workaround that does not natively use the VRF construct for leaking.$patch$, $patch$Virtualization$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_bgp/configuration/xe-16/irg-xe-16-book/bgp-mpls-vpns.html","label":"Cisco VRF and Route Leaking Configuration Guide – IOS XE"},{"url":"https://www.ciscopress.com/store/ccnp-and-ccie-enterprise-core-encor-350-401-official-9780138216764","label":"Cisco ENCOR (350-401) Official Cert Guide – Virtualization Chapter"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A service provider wants to run multiple customers' routing tables on a single physical router while keeping their traffic completely isolated. The engineer also needs to selectively share specific routes between two customer VRFs. Which combination of VRF features should be used?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network architect is evaluating hypervisor options for a new branch virtualization deployment. The security policy mandates that the hypervisor must not rely on an underlying host operating system and must run directly on bare-metal hardware. Which of the following hypervisor products satisfies this requirement?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"VMware Workstation"},{"id":"b","text":"Oracle VirtualBox"},{"id":"c","text":"VMware ESXi"},{"id":"d","text":"Microsoft Hyper-V running inside Windows 11 Desktop Edition"}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$The source material defines Type 1 hypervisors (bare metal) as those that run directly on hardware without a host OS, listing 'ESXi, KVM, Hyper-V' as examples. Type 2 hypervisors (hosted) require a host OS and are exemplified by 'VMware Workstation, VirtualBox.' VMware ESXi is a Type 1 bare-metal hypervisor and therefore satisfies the security policy. VMware Workstation (option A) and Oracle VirtualBox (option B) are explicitly listed as Type 2 hosted hypervisors and rely on an underlying OS. Hyper-V is a Type 1 hypervisor by architecture, but the question qualifies it as 'running inside Windows 11 Desktop Edition,' which describes the hosted client Hyper-V experience dependent on a general-purpose OS — making option D incorrect in this specific deployment context.$patch$, $patch$Virtualization$patch$,
         4, $json$[{"url":"https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-esxi-installation/GUID-B2F01BF5-078A-4C7E-B505-5DFFED0B8C38.html","label":"VMware ESXi Product Overview – VMware Documentation"},{"url":"https://learningnetwork.cisco.com/s/encor-exam-topics","label":"Cisco ENCOR 350-401 Exam Topics – Virtualization (1.0)"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network architect is evaluating hypervisor options for a new branch virtualization deployment. The security policy mandates that the hypervisor must not rely on an underlying host operating system and must run directly on bare-metal hardware. Which of the following hypervisor products satisfies this requirement?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network engineer needs to monitor jitter and packet loss between two branch routers and automatically trigger a routing change when the measured loss exceeds a defined threshold. Which Cisco feature best satisfies both requirements with a single configuration?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"Embedded Packet Capture (EPC) with a capture filter on ICMP traffic"},{"id":"b","text":"IP SLA with a track object linked to a static route or HSRP priority"},{"id":"c","text":"SNMPv3 traps sent to a central NMS whenever interface error counters increment"},{"id":"d","text":"Flexible NetFlow (FNF) exporting jitter records to a flow collector"}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$The source material states: 'IP SLA: active probe configured on a router to measure latency, jitter, loss, reachability; tracks objects can trigger HSRP/EEM/route changes.' IP SLA is the only listed tool that both actively measures jitter and packet loss AND can trigger automated network changes (via track objects tied to static routes or HSRP priority adjustments). EPC is a passive capture tool with no threshold/reaction capability. SNMPv3 traps are reactive notifications from the device OS, not active probes measuring jitter. FNF exports flow telemetry but does not natively measure jitter or trigger routing changes.$patch$, $patch$Network Assurance$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipsla/configuration/xe-17/sla-xe-17-book/sla_overview.html","label":"Cisco IP SLA Configuration Guide – Cisco IOS XE"},{"url":"https://learningnetwork.cisco.com/s/encor-exam-topics","label":"Cisco ENCOR 350-401 Exam Topics"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network engineer needs to monitor jitter and packet loss between two branch routers and automatically trigger a routing change when the measured loss exceeds a defined threshold. Which Cisco feature best satisfies both requirements with a single configuration?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$An organization wants to replace frequent SNMP polling of high-frequency interface metrics with a more scalable, push-based collection mechanism that uses YANG data models. Which technology should the network engineer deploy?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"SNMPv2c with a reduced polling interval of 10 seconds"},{"id":"b","text":"NetFlow v9 exported to a dedicated flow collector"},{"id":"c","text":"Model-driven streaming telemetry over gRPC or NETCONF"},{"id":"d","text":"RSPAN mirroring all management traffic to an out-of-band monitoring server"}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$The source material explicitly states: 'Streaming telemetry over gRPC/NETCONF (model-driven, push-based, YANG-defined). Replaces SNMP polling for high-frequency metrics.' Model-driven telemetry pushes data from the device to the collector at defined intervals without waiting for a poll request, making it far more scalable for high-frequency metrics. SNMPv2c is pull-based and does not use YANG models; reducing its polling interval worsens scalability. NetFlow v9 provides flow-level data, not per-interface counters, and is not YANG-defined. RSPAN is a packet-mirroring technology unrelated to metric collection.$patch$, $patch$Network Assurance$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/prog/configuration/1612/b_1612_programmability_cg/model_driven_telemetry.html","label":"Cisco Model-Driven Telemetry Configuration Guide – IOS XE"},{"url":"https://learningnetwork.cisco.com/s/encor-exam-topics","label":"Cisco ENCOR 350-401 Exam Topics"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$An organization wants to replace frequent SNMP polling of high-frequency interface metrics with a more scalable, push-based collection mechanism that uses YANG data models. Which technology should the network engineer deploy?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A security team requires that all SNMP communications between network devices and the NMS be authenticated and encrypted to prevent credential interception on the management network. The team also wants unsolicited event notifications that do NOT require acknowledgment from the NMS. Which combination of SNMP version and notification type meets both requirements?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"SNMPv2c using community strings and SNMP informs"},{"id":"b","text":"SNMPv3 with authPriv security level and SNMP traps"},{"id":"c","text":"SNMPv3 with authPriv security level and SNMP informs"},{"id":"d","text":"SNMPv2c using community strings and SNMP traps"}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$The source material states: 'SNMPv2c (community string, plaintext) vs SNMPv3 (auth+priv, USM)' and 'Traps (unsolicited) vs informs (acknowledged).' The requirement is for authentication AND encryption (ruling out SNMPv2c, which is plaintext) combined with unsolicited notifications that do NOT require acknowledgment (ruling out informs, which are acknowledged). SNMPv3 with authPriv provides both authentication (auth) and encryption (priv) via USM. Traps are unsolicited and unacknowledged, satisfying the second requirement. Option C uses informs, which are acknowledged — the opposite of what is required. Options A and D use SNMPv2c, which transmits community strings in plaintext.$patch$, $patch$Network Assurance$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/snmp/configuration/xe-17/snmp-xe-17-book/nm-snmp-cfg-snmp-support.html","label":"Cisco SNMP Configuration Guide – SNMPv3"},{"url":"https://learningnetwork.cisco.com/s/encor-exam-topics","label":"Cisco ENCOR 350-401 Exam Topics"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A security team requires that all SNMP communications between network devices and the NMS be authenticated and encrypted to prevent credential interception on the management network. The team also wants unsolicited event notifications that do NOT require acknowledgment from the NMS. Which combination of SNMP version and notification type meets both requirements?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network administrator needs to capture live packets directly on a Cisco IOS XE router for troubleshooting, without connecting an external packet analyzer to any physical port. The captured traffic must be exportable as a .pcap file for offline analysis. Which Cisco feature should the administrator use?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"SPAN (Switched Port Analyzer) configured on the router's uplink interface"},{"id":"b","text":"ERSPAN tunneling the mirrored traffic over GRE to a remote collector"},{"id":"c","text":"Embedded Packet Capture (EPC) storing packets in router memory for export"},{"id":"d","text":"Flexible NetFlow (FNF) with a custom flow record capturing full packet payloads"}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$The source material states: 'EPC (Embedded Packet Capture) for on-device pcap.' EPC allows a Cisco IOS XE router to capture packets directly in device memory and export them as a standard .pcap file — no external analyzer or additional physical port is required. SPAN mirrors traffic to a physical port and requires an external device connected to that port; it cannot export a .pcap file on its own. ERSPAN encapsulates mirrored traffic in GRE and sends it to a remote IP destination, still requiring an external capture station and a physical or logical destination. FNF records flow-level metadata (5-tuple and statistics) but does not capture full packet payloads or produce .pcap output.$patch$, $patch$Network Assurance$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/epc/configuration/xe-17/epc-xe-17-book/nm-packet-capture.html","label":"Cisco Embedded Packet Capture Configuration Guide – IOS XE"},{"url":"https://learningnetwork.cisco.com/s/encor-exam-topics","label":"Cisco ENCOR 350-401 Exam Topics"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network administrator needs to capture live packets directly on a Cisco IOS XE router for troubleshooting, without connecting an external packet analyzer to any physical port. The captured traffic must be exportable as a .pcap file for offline analysis. Which Cisco feature should the administrator use?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network engineer needs to protect the Route Processor CPU on a Cisco router from high-rate traffic floods originating from the network. Which Cisco IOS feature should be implemented to rate-limit traffic destined to the Route Processor?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"Management Plane Protection (MPP)"},{"id":"b","text":"Control Plane Policing (CoPP)"},{"id":"c","text":"Control Plane Protection (CPPr)"},{"id":"d","text":"Cisco TrustSec SGT enforcement"}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$Control Plane Policing (CoPP) is the correct answer. Per the source material, 'CoPP: rate-limit traffic destined to RP CPU.' CoPP uses a service policy applied to the control plane to police aggregate traffic sent to the Route Processor, protecting it from DoS-style floods. CPPr (option C) is a more granular extension of CoPP that sub-categorizes control-plane traffic; it is a subset feature, not the primary rate-limiting feature described. MPP (option A) restricts which interfaces are allowed to carry management traffic but does not rate-limit control-plane traffic. TrustSec SGTs (option D) are used for micro-segmentation and policy enforcement, not CPU protection.$patch$, $patch$Security$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/qos_copp/configuration/xe-17/qos-copp-xe-17-book/qos-copp-ctrl-plane-plcng.html","label":"Cisco IOS XE Control Plane Policing Configuration Guide"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network engineer needs to protect the Route Processor CPU on a Cisco router from high-rate traffic floods originating from the network. Which Cisco IOS feature should be implemented to rate-limit traffic destined to the Route Processor?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$An enterprise security policy requires that SSH and SNMP management access to core routers must only be accepted on the dedicated out-of-band management interface (GigabitEthernet0/0). All other interfaces must silently drop management traffic. Which Cisco feature enforces this requirement?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"Control Plane Policing (CoPP)"},{"id":"b","text":"Control Plane Protection (CPPr) with sub-interfaces"},{"id":"c","text":"Management Plane Protection (MPP)"},{"id":"d","text":"802.1X port-based authentication"}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$Management Plane Protection (MPP) is correct. The source material states that MPP is used to 'restrict management traffic to specific interfaces.' By configuring MPP, an administrator designates one or more interfaces as management interfaces; all management protocols (SSH, SNMP, Telnet, etc.) are then rejected on non-designated interfaces. CoPP (option A) can rate-limit management traffic in aggregate but cannot restrict it to a single interface. CPPr (option B) provides sub-categorization of control-plane traffic, not interface-level management restriction. 802.1X (option D) is an access-layer authentication mechanism and is unrelated to restricting management plane access to specific router interfaces.$patch$, $patch$Security$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/sec_data_mpp/configuration/xe-17/sec-data-mpp-xe-17-book/sec-mpp.html","label":"Cisco IOS XE Management Plane Protection Configuration Guide"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$An enterprise security policy requires that SSH and SNMP management access to core routers must only be accepted on the dedicated out-of-band management interface (GigabitEthernet0/0). All other interfaces must silently drop management traffic. Which Cisco feature enforces this requirement?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A security architect is comparing TACACS+ and RADIUS for device administration AAA. Which statement correctly distinguishes TACACS+ from RADIUS?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"TACACS+ uses UDP port 1812 and encrypts only the password field in its packets."},{"id":"b","text":"TACACS+ uses TCP port 49 and encrypts the entire payload, supporting per-command authorization."},{"id":"c","text":"RADIUS uses TCP port 49 and encrypts the entire payload for stronger security."},{"id":"d","text":"RADIUS uses TCP and natively supports command-by-command authorization for network devices."}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$Option B is correct. The source material explicitly states: 'TACACS+ (TCP/49, encrypts whole payload, command authorization) vs RADIUS (UDP/1812/1813, encrypts only password).' TACACS+ separates Authentication, Authorization, and Accounting into distinct functions and uses TCP port 49 with full-payload encryption, making it the preferred protocol for device administration where per-command authorization is required. Option A incorrectly attributes UDP/1812 and password-only encryption to TACACS+ — those are RADIUS characteristics. Option C incorrectly states RADIUS uses TCP/49 and full-payload encryption. Option D is incorrect because RADIUS does not natively support per-command authorization; that is a TACACS+ capability.$patch$, $patch$Security$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/support/docs/security-vpn/remote-authentication-dial-user-service-radius/13838-10.html","label":"Cisco TACACS+ and RADIUS Comparison"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A security architect is comparing TACACS+ and RADIUS for device administration AAA. Which statement correctly distinguishes TACACS+ from RADIUS?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$In an 802.1X deployment, a network printer that does not support an 802.1X supplicant must still gain controlled port access. Which mechanism should the network engineer configure on the authenticator switch to handle this device?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"EAP-TLS mutual certificate authentication"},{"id":"b","text":"PEAP with MSCHAPv2 username/password"},{"id":"c","text":"MAC Authentication Bypass (MAB)"},{"id":"d","text":"SXP peer session to a TrustSec-capable switch"}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$MAC Authentication Bypass (MAB) is correct. The source material states: 'MAB (MAC Authentication Bypass) for non-802.1X devices.' When a device cannot respond to EAP Identity Requests (as a printer typically cannot), the switch can fall back to MAB, which uses the device's MAC address as both the username and password submitted to the RADIUS server for authentication. EAP-TLS (option A) and PEAP (option B) require the supplicant to actively participate in an EAP exchange, which the printer cannot do. SXP (option D) is a TrustSec protocol for propagating Security Group Tags between devices and is not an authentication fallback mechanism for non-802.1X clients.$patch$, $patch$Security$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/products/collateral/ios-nx-os-software/identity-based-networking-services/config_guide_c17-663759.html","label":"Cisco MAC Authentication Bypass Deployment Guide"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$In an 802.1X deployment, a network printer that does not support an 802.1X supplicant must still gain controlled port access. Which mechanism should the network engineer configure on the authenticator switch to handle this device?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A large enterprise wants to deploy micro-segmentation across its campus network so that users in a 'Finance' group are denied access to servers in a 'Development' group, regardless of VLAN or IP addressing. The solution must scale without requiring per-device ACLs. Which Cisco technology best satisfies this requirement?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"Control Plane Policing (CoPP) with aggregate traffic policies"},{"id":"b","text":"Cisco TrustSec with Security Group Tags (SGTs)"},{"id":"c","text":"WPA3 Opportunistic Wireless Encryption (OWE)"},{"id":"d","text":"DMVPN with IPsec tunnel encryption per branch"}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$Cisco TrustSec with Security Group Tags (SGTs) is correct. The source material states: 'Cisco TrustSec: SGT (Security Group Tags), SXP propagation, micro-segmentation.' TrustSec assigns a numerical SGT to users/devices upon authentication; Security Group ACLs (SGACLs) enforce policy based on source and destination SGTs rather than IP addresses or VLANs, enabling scalable micro-segmentation. CoPP (option A) protects the router CPU and cannot enforce user-group segmentation. OWE (option C) is a WPA3 feature providing encryption for open wireless networks and is irrelevant to LAN segmentation. DMVPN (option D) provides WAN branch connectivity and does not address intra-campus micro-segmentation.$patch$, $patch$Security$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/solutions/Enterprise/Security/TrustSec_1-99/TrustSec_HowTo/TrustSec_HowTo.html","label":"Cisco TrustSec How-To Guide: Deploying SGTs"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A large enterprise wants to deploy micro-segmentation across its campus network so that users in a 'Finance' group are denied access to servers in a 'Development' group, regardless of VLAN or IP addressing. The solution must scale without requiring per-device ACLs. Which Cisco technology best satisfies this requirement?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A wireless network engineer is upgrading a corporate guest Wi-Fi network from WPA2-Personal to WPA3. Users on the guest network should not be able to decrypt each other's traffic even if they share the same network password. Which WPA3 feature specifically provides this individualized encryption on an open or PSK-style network?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"WPA3-Enterprise 192-bit security suite"},{"id":"b","text":"WPA3 Simultaneous Authentication of Equals (SAE)"},{"id":"c","text":"WPA3 Opportunistic Wireless Encryption (OWE)"},{"id":"d","text":"AES-CCMP with 802.1X EAP-TLS authentication"}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$Opportunistic Wireless Encryption (OWE) is correct. The source material lists WPA3 features as: 'SAE replaces PSK, OWE for open networks, 192-bit suite for enterprise.' OWE (defined in RFC 8110) provides unauthenticated encryption for open-style networks — each client negotiates a unique pairwise encryption key via a Diffie-Hellman exchange, so one client cannot decrypt another's traffic even without a passphrase. SAE (option B) is the WPA3 replacement for the PSK handshake, providing forward secrecy for password-based authentication, but its primary purpose is resisting offline dictionary attacks, not per-client isolation. The 192-bit suite (option A) is for high-security enterprise environments using 802.1X. AES-CCMP with EAP-TLS (option D) is WPA2-Enterprise and does not apply to a guest/open scenario.$patch$, $patch$Security$patch$,
         4, $json$[{"url":"https://www.wi-fi.org/discover-wi-fi/security","label":"Wi-Fi Alliance WPA3 Specification Overview"},{"url":"https://www.rfc-editor.org/rfc/rfc8110","label":"RFC 8110 – Opportunistic Wireless Encryption"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A wireless network engineer is upgrading a corporate guest Wi-Fi network from WPA2-Personal to WPA3. Users on the guest network should not be able to decrypt each other's traffic even if they share the same network password. Which WPA3 feature specifically provides this individualized encryption on an open or PSK-style network?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$An enterprise security team needs a VPN solution for connecting multiple branch offices over a private MPLS WAN. The solution must preserve IP multicast routing across all sites and avoid the overhead of a hub-and-spoke design. Which Cisco VPN technology is specifically designed for this use case?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"Remote-access SSL VPN using AnyConnect"},{"id":"b","text":"DMVPN Phase 3 with IPsec profile"},{"id":"c","text":"Group Encrypted Transport VPN (GETVPN)"},{"id":"d","text":"IKEv2 route-based site-to-site IPsec with VTIs"}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$Group Encrypted Transport VPN (GETVPN) is correct. The source material explicitly states: 'GETVPN (Group Encrypted Transport): for private MPLS, preserves multicast.' GETVPN is a tunnel-less, any-any encryption technology that uses a Group Domain of Interpretation (GDOI) key server; because it does not encapsulate packets in a new IP header, the original source and destination addresses are preserved, enabling native multicast and broadcast forwarding across the MPLS fabric. AnyConnect SSL VPN (option A) is a remote-access solution for individual users, not branch interconnection. DMVPN (option B) is designed for public internet connectivity and requires GRE tunnels that add overhead; multicast support is possible but complex and DMVPN is not optimized for private MPLS. Standard IKEv2 site-to-site VTIs (option D) create point-to-point tunnels that do not natively preserve multicast across an MPLS core.$patch$, $patch$Security$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/solutions/Enterprise/WAN_and_MAN/GETVPN/GETVPN_DIG.html","label":"Cisco GET VPN Design and Implementation Guide"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$An enterprise security team needs a VPN solution for connecting multiple branch offices over a private MPLS WAN. The solution must preserve IP multicast routing across all sites and avoid the overhead of a hub-and-spoke design. Which Cisco VPN technology is specifically designed for this use case?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A SOC analyst suspects that a compromised internal host is performing slow, low-volume data exfiltration by making slightly abnormal connections to external IPs. No signature-based IDS alert has fired. Which Cisco security solution is best suited to detect this threat by analyzing behavioral anomalies in network flow data?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"Cisco Umbrella performing cloud-based DNS inspection"},{"id":"b","text":"Cisco AMP (Advanced Malware Protection) sandboxing"},{"id":"c","text":"Cisco Stealthwatch (Secure Network Analytics) analyzing NetFlow"},{"id":"d","text":"Cisco ISE posture assessment of the endpoint"}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$Cisco Stealthwatch (now Secure Network Analytics) is correct. The source material states: 'Stealthwatch / Secure Network Analytics: behavioral anomaly detection from NetFlow.' Stealthwatch ingests NetFlow, IPFIX, and other telemetry from routers and switches to build behavioral baselines; it can detect slow-burn exfiltration, insider threats, and command-and-control callbacks that generate no IDS signature. Umbrella (option A) provides DNS-layer security to block connections to known malicious domains but cannot detect anomalous behavior for destinations not in its threat feed. Cisco AMP (option B) performs file reputation analysis and sandboxing at the endpoint/file level, not network-flow behavioral analytics. ISE posture (option D) validates endpoint compliance (patch level, AV status) at connection time; it does not perform ongoing behavioral traffic analysis.$patch$, $patch$Security$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/products/collateral/security/stealthwatch/datasheet-c78-739398.html","label":"Cisco Secure Network Analytics (Stealthwatch) Data Sheet"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A SOC analyst suspects that a compromised internal host is performing slow, low-volume data exfiltration by making slightly abnormal connections to external IPs. No signature-based IDS alert has fired. Which Cisco security solution is best suited to detect this threat by analyzing behavioral anomalies in network flow data?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network engineer needs to programmatically modify the configuration of a Cisco IOS-XE device using a standards-based protocol that operates over SSH on port 830 and uses XML-encoded YANG data models. Which protocol best meets these requirements?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"RESTCONF over HTTPS"},{"id":"b","text":"NETCONF over SSH"},{"id":"c","text":"gRPC with Protocol Buffers"},{"id":"d","text":"REST API with JSON payloads"}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$The source material states: 'NETCONF (RFC 6241): XML-based, runs over SSH (port 830), uses YANG models.' This precisely matches all three requirements — SSH transport, port 830, and XML-encoded YANG data. RESTCONF (option A) uses HTTPS, not SSH on port 830, and while it also leverages YANG, it wraps operations over HTTP. gRPC (option C) uses Protocol Buffers and is primarily used for streaming telemetry, not standard configuration management via SSH/830. REST with JSON (option D) is stateless and HTTP-based, with no native YANG or SSH-on-830 transport.$patch$, $patch$Automation$patch$,
         4, $json$[{"url":"https://www.rfc-editor.org/rfc/rfc6241","label":"RFC 6241 – Network Configuration Protocol (NETCONF)"},{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/prog/configuration/1612/b_1612_programmability_cg/configuring_yang_datamodel.html","label":"Cisco IOS XE NETCONF/YANG Configuration Guide"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network engineer needs to programmatically modify the configuration of a Cisco IOS-XE device using a standards-based protocol that operates over SSH on port 830 and uses XML-encoded YANG data models. Which protocol best meets these requirements?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A Python developer is writing a script to retrieve interface statistics from a Cisco device's REST API. The script receives an HTTP response code of 403. What is the correct interpretation of this status code, and what should the developer investigate first?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"The request succeeded but returned an empty body; investigate the payload parsing logic."},{"id":"b","text":"The server encountered an internal error; retry the request after a delay."},{"id":"c","text":"The client sent an invalid request syntax; check the URL formatting."},{"id":"d","text":"The client is authenticated but lacks permission for the resource; investigate authorization credentials or roles."}]$json$::jsonb, $json$["d"]$json$::jsonb, $patch$The source material groups HTTP status codes as follows: '2xx success, 3xx redirect, 4xx client error, 5xx server error.' A 403 Forbidden is a 4xx client error indicating the client is authenticated but not authorized to access the requested resource — the server understood the request but refuses to fulfill it. The developer should investigate the user's role, token scope, or OAuth permissions, not syntax (400 Bad Request would indicate that). Option B describes a 5xx server-side error. Option A describes a 2xx scenario. Option C describes a 400 Bad Request scenario.$patch$, $patch$Automation$patch$,
         4, $json$[{"url":"https://developer.cisco.com/learning/tracks/devnet-express-network-fund/networking-basics/dnav3-101/step/1","label":"Cisco DevNet – REST API Fundamentals"},{"url":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403","label":"MDN Web Docs – HTTP Response Status Codes"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A Python developer is writing a script to retrieve interface statistics from a Cisco device's REST API. The script receives an HTTP response code of 403. What is the correct interpretation of this status code, and what should the developer investigate first?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$An automation engineer wants to deploy consistent configurations across a large fleet of Cisco IOS devices without installing any agent software on the managed devices. The team already uses YAML-based playbooks for their workflows. Which configuration management tool aligns with both of these constraints?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"Puppet, using its agent-based Ruby DSL architecture"},{"id":"b","text":"Chef, using its agent-based cookbook model"},{"id":"c","text":"Ansible, using agentless SSH/NETCONF transport with YAML playbooks"},{"id":"d","text":"Terraform, using a declarative state-file approach with HCL"}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$The source material explicitly states: 'Ansible: agentless, YAML playbooks, SSH/NETCONF.' This satisfies both constraints — no agent software is required on managed Cisco devices, and playbooks are written in YAML. Puppet (option A) and Chef (option B) are both described as 'agent-based, Ruby DSL,' which violates the agentless requirement. Terraform (option D) is described as 'declarative infrastructure with state file' and uses HCL, not YAML playbooks; it is also primarily an infrastructure provisioning tool rather than a network device configuration management tool.$patch$, $patch$Automation$patch$,
         4, $json$[{"url":"https://docs.ansible.com/ansible/latest/network/user_guide/platform_ios.html","label":"Ansible Network Automation – Cisco IOS Platform Guide"},{"url":"https://developer.cisco.com/network-automation/detail/ansible/","label":"Cisco DevNet – Network Automation with Ansible"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$An automation engineer wants to deploy consistent configurations across a large fleet of Cisco IOS devices without installing any agent software on the managed devices. The team already uses YAML-based playbooks for their workflows. Which configuration management tool aligns with both of these constraints?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network operations team needs a high-performance telemetry solution to stream real-time operational data from Cisco routers to an external collector. The solution must support efficient binary encoding and a remote procedure call framework. Which technology from the source material best satisfies these requirements?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"NETCONF, because it supports streaming subscriptions over SSH"},{"id":"b","text":"gRPC with Protocol Buffers, because it is designed for high-performance RPC and streaming telemetry"},{"id":"c","text":"RESTCONF, because it wraps NETCONF operations over HTTPS for efficient delivery"},{"id":"d","text":"EEM applets, because they can trigger on-device scripts when telemetry thresholds are crossed"}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$The source material states: 'gRPC: high-performance RPC with Protocol Buffers; used by streaming telemetry.' Protocol Buffers provide compact binary encoding (far more efficient than XML or JSON), and gRPC's streaming capabilities are purpose-built for real-time telemetry data. NETCONF (option A) is XML-based and primarily designed for configuration management, not high-throughput telemetry streaming. RESTCONF (option C) is an HTTPS JSON wrapper around NETCONF/YANG operations — useful for configuration, not optimized for binary streaming. EEM (option D) is an on-device automation tool for event-triggered scripting, not a telemetry collection framework.$patch$, $patch$Automation$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/prog/configuration/1612/b_1612_programmability_cg/model_driven_telemetry.html","label":"Cisco IOS XE Programmability Configuration Guide – Model-Driven Telemetry (gRPC)"},{"url":"https://grpc.io/docs/what-is-grpc/introduction/","label":"gRPC Official Documentation"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network operations team needs a high-performance telemetry solution to stream real-time operational data from Cisco routers to an external collector. The solution must support efficient binary encoding and a remote procedure call framework. Which technology from the source material best satisfies these requirements?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network engineer writes a Python script that uses the Netmiko library to connect to a Cisco IOS-XE switch and push a configuration change. During a code review, a colleague suggests replacing Netmiko with NAPALM. What is the primary architectural advantage of NAPALM over Netmiko for this use case?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"NAPALM provides raw SSH socket access, offering lower latency than Netmiko's abstraction layer."},{"id":"b","text":"NAPALM is a multi-vendor abstraction library, allowing the same API calls to work across different network operating systems without rewriting device-specific logic."},{"id":"c","text":"NAPALM eliminates the need for Python entirely by compiling scripts to native machine code."},{"id":"d","text":"NAPALM integrates directly with Cisco DNA Center's northbound REST API, making it ideal for SD-Access environments."}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$The source material describes the Python libraries as follows: 'Netmiko (SSH)' and 'NAPALM (multi-vendor abstraction).' Netmiko is a library focused on SSH connectivity, often requiring device-specific command syntax. NAPALM's defining characteristic is multi-vendor abstraction — it provides a unified API that works across Arista EOS, Cisco IOS/NX-OS/IOS-XR, Juniper JunOS, and others, so engineers do not need to rewrite logic per platform. Option A is incorrect — NAPALM adds an abstraction layer, it does not provide lower-level raw socket access (Paramiko, also listed in the source, is the raw SSH library). Option C is false; NAPALM is a Python library. Option D incorrectly conflates NAPALM with Cisco DNA Center APIs, which are separate REST-based integrations mentioned independently in the source.$patch$, $patch$Automation$patch$,
         4, $json$[{"url":"https://napalm.readthedocs.io/en/latest/support/index.html","label":"NAPALM Official Documentation – Supported Drivers"},{"url":"https://developer.cisco.com/learning/tracks/devnet-express-network-fund/network-automation-with-python/dnav3-301/step/1","label":"Cisco DevNet – Python Libraries for Network Automation"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P1'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network engineer writes a Python script that uses the Netmiko library to connect to a Cisco IOS-XE switch and push a configuration change. During a code review, a colleague suggests replacing Netmiko with NAPALM. What is the primary architectural advantage of NAPALM over Netmiko for this use case?$patch$);

-- 350-401-P2: 11 new questions
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network architect is designing a large enterprise campus network that must support thousands of endpoints across multiple buildings. The design requires a dedicated layer for high-speed packet switching between distribution blocks, with no routing policy decisions made at that layer. Which campus network architecture model BEST satisfies this requirement, and which layer is being described?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"Two-tier (collapsed core) model; the collapsed core/distribution layer handles both high-speed switching and policy decisions."},{"id":"b","text":"Three-tier (campus) model; the core layer is dedicated to high-speed packet switching between distribution blocks with minimal policy enforcement."},{"id":"c","text":"Three-tier (campus) model; the distribution layer is responsible for high-speed switching between access blocks and applies all routing policy."},{"id":"d","text":"SD-Access fabric model; the underlay IS-IS layer performs high-speed switching and replaces the need for a discrete core tier."}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$The source material states that the three-tier (campus) architecture consists of access → distribution → core layers and is designed for large enterprises. The core layer's role is high-speed packet switching between distribution blocks — it is intentionally kept lean and free of complex policy decisions (such as ACLs or QoS classification) so that forwarding performance is maximized. Option A is incorrect because the two-tier collapsed core model merges the core and distribution layers, making it suitable for small networks and inherently combining policy and switching functions. Option C is incorrect because it misidentifies the distribution layer as the high-speed transit layer; distribution is where policy (routing, filtering, summarization) is applied, not where raw switching speed is the sole objective. Option D is incorrect because SD-Access uses a routed IS-IS underlay, but this does not eliminate discrete architectural tiers in a large campus — and the question's requirement maps precisely to the classical three-tier core definition provided in the source material.$patch$, $patch$Architecture$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/solutions/CVD/Campus/cisco-campus-lan-wlan-design-guide.html","label":"Cisco - Campus LAN and Wireless LAN Design Guide (Three-Tier Architecture)"},{"url":"https://www.ciscopress.com/store/ccnp-and-ccie-enterprise-core-encor-350-401-official-9780138216764","label":"Cisco ENCOR 350-401 Official Cert Guide – Architecture Domain"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P2'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network architect is designing a large enterprise campus network that must support thousands of endpoints across multiple buildings. The design requires a dedicated layer for high-speed packet switching between distribution blocks, with no routing policy decisions made at that layer. Which campus network architecture model BEST satisfies this requirement, and which layer is being described?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network engineer is evaluating first-hop redundancy protocols (FHRPs) for a new enterprise distribution layer. The primary requirements are: (1) the solution must be an open standard supported across multi-vendor devices, and (2) the active gateway must be elected using the highest priority, with ties broken by the highest IP address. Which FHRP meets BOTH requirements, and what multicast address does it use for router communications?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"HSRP version 2; it uses multicast address 224.0.0.102 and is an IEEE open standard."},{"id":"b","text":"GLBP; it uses multicast address 224.0.0.102, supports multi-vendor environments, and elects an Active Virtual Gateway by highest priority."},{"id":"c","text":"VRRP; it uses multicast address 224.0.0.18, is an open standard (RFC-based), and elects the Master router by highest priority with highest IP address as tiebreaker."},{"id":"d","text":"HSRP version 1; it uses multicast address 224.0.0.2, is an open standard, and elects an active router by highest priority then highest IP address."}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$The source material explicitly identifies VRRP as the 'open standard' FHRP (compared to HSRP and GLBP, which are described as 'Cisco proprietary'), and states it uses multicast address 224.0.0.18 for router communications. VRRP (defined in RFC 3768/5798) elects a Master router based on the highest priority value, with the highest IP address serving as a tiebreaker — satisfying both stated requirements. Option A is incorrect on two counts: HSRPv2 uses multicast 224.0.0.102 correctly per the source, but HSRP is explicitly called out as 'Cisco proprietary,' not an open standard. Option B is incorrect because GLBP is also identified in the source as 'Cisco proprietary' and its primary differentiator is load balancing across Active Virtual Forwarders (AVFs), not multi-vendor support. Option D is incorrect because HSRPv1 uses multicast 224.0.0.2 (correct per source), but HSRP is Cisco proprietary — directly contradicting the multi-vendor open-standard requirement.$patch$, $patch$Architecture$patch$,
         4, $json$[{"url":"https://www.rfc-editor.org/rfc/rfc5798","label":"RFC 5798 – Virtual Router Redundancy Protocol (VRRP) Version 3"},{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipapp_fhrp/configuration/xe-16/fhp-xe-16-book/fhp-vrrp.html","label":"Cisco – Configuring VRRP (First Hop Redundancy Protocols)"},{"url":"https://www.ciscopress.com/store/ccnp-and-ccie-enterprise-core-encor-350-401-official-9780138216764","label":"Cisco ENCOR 350-401 Official Cert Guide – Architecture Domain"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P2'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network engineer is evaluating first-hop redundancy protocols (FHRPs) for a new enterprise distribution layer. The primary requirements are: (1) the solution must be an open standard supported across multi-vendor devices, and (2) the active gateway must be elected using the highest priority, with ties broken by the highest IP address. Which FHRP meets BOTH requirements, and what multicast address does it use for router communications?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network engineer is designing a multi-tenant enterprise WAN solution on a single physical Cisco router. The requirement is that each tenant must have completely isolated routing tables, with the ability to selectively share specific routes between tenants when needed. Which technology directly satisfies both requirements on a single device?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"VXLAN with a unique 24-bit VNI per tenant"},{"id":"b","text":"VRF with route-target import/export for route leaking"},{"id":"c","text":"GRE tunnels with per-tenant tunnel interfaces"},{"id":"d","text":"DMVPN Phase 2 with per-tenant NHRP mappings"}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$The source material states explicitly: 'VRF (Virtual Routing and Forwarding): Multiple routing tables on the same device; route leaking via route-target import/export. Used for multi-tenancy on a single physical router.' VRF directly provides isolated routing table instances per tenant on a single device, while the route-target import/export mechanism enables controlled, selective route leaking between VRFs — satisfying both stated requirements. Option A (VXLAN/VNI) is a Layer 2 overlay technology primarily used for data-center fabric segmentation and does not itself provide per-tenant routing table isolation on a router. Option C (GRE tunnels) creates point-to-point logical links but does not inherently maintain separate routing tables or enforce tenant isolation at the routing level. Option D (DMVPN Phase 2) is a WAN overlay technology for spoke-to-spoke communication and relies on NHRP for next-hop resolution, but does not address multi-tenant routing table separation on a single device.$patch$, $patch$Virtualization$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/mp_l3_vpns/configuration/xe-17/mp-l3-vpns-xe-17-book/mp-bgp-mpls-vpn.html","label":"Cisco - Configuring Virtual Routing and Forwarding (VRF)"},{"url":"https://learningnetwork.cisco.com/s/encor-exam-topics","label":"Cisco ENCOR (350-401) Exam Topics"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P2'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network engineer is designing a multi-tenant enterprise WAN solution on a single physical Cisco router. The requirement is that each tenant must have completely isolated routing tables, with the ability to selectively share specific routes between tenants when needed. Which technology directly satisfies both requirements on a single device?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network architect is evaluating tunneling protocols for a new overlay deployment. The solution must support dynamic spoke-to-spoke tunnel establishment without requiring pre-configured static tunnel endpoints between every spoke pair, and it must use next-hop resolution to map overlay addresses to underlay transport addresses. Which combination of technologies, as described in the ENCOR Virtualization domain, fulfills both requirements?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"IPsec in tunnel mode with IKEv2 for every spoke-to-spoke pair"},{"id":"b","text":"DMVPN using mGRE tunnels with NHRP for next-hop resolution"},{"id":"c","text":"VXLAN with a 24-bit VNI providing MAC-in-UDP encapsulation"},{"id":"d","text":"LISP separating EID from RLOC for endpoint mobility"}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$The source material states: 'GRE: simple IP-in-IP tunneling; multipoint GRE (mGRE) used by DMVPN' and 'DMVPN: NHRP for next-hop resolution; phase 1 (hub-spoke), phase 2 (spoke-to-spoke), phase 3 (NHRP redirect).' DMVPN leverages mGRE, which allows a single tunnel interface to accept connections from multiple dynamic peers without pre-configured point-to-point tunnel entries. NHRP (Next Hop Resolution Protocol) dynamically resolves the underlay (physical) IP address of spoke routers, enabling on-demand spoke-to-spoke tunnels — precisely the two requirements stated. Option A (IPsec tunnel mode with IKEv2) provides encryption and authentication but requires static or pre-negotiated peer definitions for every spoke-to-spoke pair; it does not inherently provide dynamic next-hop resolution. Option C (VXLAN) is a MAC-in-UDP data-center overlay technology with a 24-bit VNI for segmentation; it is not designed for WAN spoke-to-spoke dynamic tunneling with next-hop resolution. Option D (LISP) separates the Endpoint Identifier (EID) from the Routing Locator (RLOC) and is used in SD-Access fabric overlays for endpoint mobility, not for dynamic WAN spoke-to-spoke tunnel establishment.$patch$, $patch$Virtualization$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/sec_conn_dmvpn/configuration/xe-17/sec-conn-dmvpn-xe-17-book/sec-conn-dmvpn-dmvpn.html","label":"Cisco - DMVPN Configuration Guide"},{"url":"https://www.cisco.com/c/en/us/support/docs/security-vpn/dynamic-multipoint-vpn-dmvpn/111976-dmvpn-config-guide-00.html","label":"Cisco - NHRP for DMVPN"},{"url":"https://learningnetwork.cisco.com/s/encor-exam-topics","label":"Cisco ENCOR (350-401) Exam Topics"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P2'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network architect is evaluating tunneling protocols for a new overlay deployment. The solution must support dynamic spoke-to-spoke tunnel establishment without requiring pre-configured static tunnel endpoints between every spoke pair, and it must use next-hop resolution to map overlay addresses to underlay transport addresses. Which combination of technologies, as described in the ENCOR Virtualization domain, fulfills both requirements?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network engineer needs to mirror traffic from a distribution-layer switch to an analysis workstation connected to a different switch across the campus network, but the two devices are separated by multiple Layer 2 hops. Which port mirroring technology should the engineer implement to accomplish this without requiring a routed path between the source and destination?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"SPAN (Switched Port Analyzer) configured locally on the distribution switch"},{"id":"b","text":"RSPAN (Remote SPAN) using a dedicated VLAN to carry mirrored traffic across the Layer 2 domain"},{"id":"c","text":"ERSPAN (Encapsulated Remote SPAN) encapsulating mirrored traffic in GRE tunnels across a Layer 3 network"},{"id":"d","text":"EPC (Embedded Packet Capture) exporting pcap files to a TFTP server reachable via the management network"}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$The source material states: 'SPAN (Switched Port Analyzer): local mirror; RSPAN: remote across VLAN; ERSPAN: across L3 via GRE.' Because the source and destination switches are separated by multiple Layer 2 hops but there is no mention of a routed (Layer 3) path, RSPAN is the correct choice — it uses a dedicated transport VLAN to carry mirrored frames across the Layer 2 domain to a remote destination switch. SPAN (option a) is ruled out because it only works locally on a single switch. ERSPAN (option c) is incorrect here because ERSPAN requires a Layer 3 routed path and uses GRE encapsulation — the scenario explicitly describes a Layer 2 multi-hop topology with no routed path. EPC (option d) is an on-device capture mechanism that writes to local memory or a file server; it does not mirror live traffic to an analysis workstation in real time.$patch$, $patch$Network Assurance$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/lanswitch/configuration/xe-16/lanswitch-xe-16-book/lsw-span-rspan-erspan.html","label":"Cisco IOS XE Embedded Packet Capture and SPAN/RSPAN/ERSPAN Configuration Guide"},{"url":"https://www.ciscopress.com/store/ccnp-enterprise-core-encor-350-401-official-cert-guide-9780135768624","label":"Cisco CCNP Enterprise Core ENCOR 350-401 Official Cert Guide — Network Assurance Chapter"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P2'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network engineer needs to mirror traffic from a distribution-layer switch to an analysis workstation connected to a different switch across the campus network, but the two devices are separated by multiple Layer 2 hops. Which port mirroring technology should the engineer implement to accomplish this without requiring a routed path between the source and destination?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$An engineer is configuring SNMPv3 on a Cisco IOS XE router and requires both message integrity verification and encryption of the SNMP payload to protect sensitive MIB data in transit. The engineer also wants the managed device to send unsolicited notifications to the NMS, but does NOT require the NMS to acknowledge receipt of those notifications. Which combination of SNMPv3 security level and notification type satisfies these requirements?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"Security level: authNoPriv; Notification type: Informs"},{"id":"b","text":"Security level: authPriv; Notification type: Traps"},{"id":"c","text":"Security level: authPriv; Notification type: Informs"},{"id":"d","text":"Security level: noAuthNoPriv; Notification type: Traps"},{"id":"e","text":"Security level: authNoPriv; Notification type: Traps"}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$The source material provides two directly applicable passages: (1) 'SNMPv2c (community string, plaintext) vs SNMPv3 (auth+priv, USM)' — SNMPv3 supports three security levels: noAuthNoPriv (neither authentication nor privacy), authNoPriv (authentication only, no encryption), and authPriv (authentication + encryption/privacy). Because the requirement is for both integrity AND encryption, authPriv is mandatory. (2) 'Traps (unsolicited) vs informs (acknowledged)' — The requirement is for unsolicited notifications WITHOUT requiring acknowledgement from the NMS. Traps are unsolicited and unacknowledged; Informs are acknowledged by the NMS. Therefore the correct combination is authPriv + Traps (option b). Option a is wrong because authNoPriv provides no encryption and Informs require NMS acknowledgement. Option c is wrong because Informs require acknowledgement, violating the stated requirement. Option d is wrong because noAuthNoPriv provides neither integrity nor encryption. Option e is wrong because authNoPriv lacks payload encryption.$patch$, $patch$Network Assurance$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/snmp/configuration/xe-16/snmp-xe-16-book/nm-snmp-cfg-snmp-support.html","label":"Cisco IOS XE SNMP Configuration Guide — Configuring SNMP Support"},{"url":"https://www.rfc-editor.org/rfc/rfc3411","label":"RFC 3411 — An Architecture for Describing SNMP Management Frameworks (SNMPv3 Security Models)"},{"url":"https://www.ciscopress.com/store/ccnp-enterprise-core-encor-350-401-official-cert-guide-9780135768624","label":"Cisco CCNP Enterprise Core ENCOR 350-401 Official Cert Guide — Network Assurance Chapter"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P2'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$An engineer is configuring SNMPv3 on a Cisco IOS XE router and requires both message integrity verification and encryption of the SNMP payload to protect sensitive MIB data in transit. The engineer also wants the managed device to send unsolicited notifications to the NMS, but does NOT require the NMS to acknowledge receipt of those notifications. Which combination of SNMPv3 security level and notification type satisfies these requirements?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network engineer needs to implement a solution that encrypts the entire payload of AAA packets, supports per-command authorization, and uses TCP as its transport protocol. Which AAA protocol best satisfies all three requirements?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"RADIUS (UDP/1812)"},{"id":"b","text":"TACACS+ (TCP/49)"},{"id":"c","text":"RADIUS (UDP/1813)"},{"id":"d","text":"Diameter (TCP/3868)"}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$According to the source material: 'TACACS+ (TCP/49, encrypts whole payload, command authorization) vs RADIUS (UDP/1812/1813, encrypts only password).' TACACS+ is the only protocol listed that satisfies all three requirements: it uses TCP port 49 for reliable transport, encrypts the entire AAA payload (not just the password), and supports granular per-command authorization — a critical feature for privileged access control. RADIUS uses UDP and only encrypts the password field in Access-Request packets, making it unsuitable when full payload encryption and command-level authorization are required. Diameter is a RADIUS evolution used in service-provider and mobile networks but is not a standard Cisco enterprise device AAA protocol for command authorization.$patch$, $patch$Security$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/support/docs/security-vpn/remote-authentication-dial-in-user-service-radius/13838-10.html","label":"Cisco: TACACS+ and RADIUS Comparison"},{"url":"https://www.ciscopress.com/store/ccnp-and-ccie-enterprise-core-encor-350-401-official-9780138216764","label":"Cisco ENCOR 350-401 Official Cert Guide – AAA Protocols"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P2'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network engineer needs to implement a solution that encrypts the entire payload of AAA packets, supports per-command authorization, and uses TCP as its transport protocol. Which AAA protocol best satisfies all three requirements?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$An enterprise is deploying 802.1X port-based authentication on its access layer switches. During the authentication exchange, which device acts as the authenticator, relaying EAP messages between the supplicant and the authentication server?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"The end-user host (supplicant)"},{"id":"b","text":"The Cisco Identity Services Engine (ISE)"},{"id":"c","text":"The access layer switch or wireless access point"},{"id":"d","text":"The RADIUS proxy server upstream of ISE"}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$The source material explicitly defines the 802.1X three-party model: 'supplicant (host) – authenticator (switch/AP) – auth server (ISE/RADIUS).' The access layer switch (or wireless AP) is the authenticator. It enforces port access control and acts as the EAP relay — encapsulating EAP frames from the supplicant into RADIUS packets destined for the authentication server (ISE). The supplicant is the end-user device seeking access; ISE is the authentication server that makes the pass/fail decision; a RADIUS proxy is an optional intermediary and is not the authenticator. Confusing the authenticator with the authentication server is a common misconception on this exam domain.$patch$, $patch$Security$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/17-9/configuration_guide/sec/b_179_sec_9300_cg/configuring_ieee_802_1x_port_based_authentication.html","label":"Cisco: 802.1X Port-Based Authentication Configuration Guide"},{"url":"https://www.cisco.com/c/en/us/td/docs/security/ise/3-2/admin_guide/b_ise_admin_3_2/b_ISE_admin_32_secure_wired_access.html","label":"Cisco ISE – 802.1X Overview"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P2'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$An enterprise is deploying 802.1X port-based authentication on its access layer switches. During the authentication exchange, which device acts as the authenticator, relaying EAP messages between the supplicant and the authentication server?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A large financial institution needs to extend encrypted group communications across its existing private MPLS WAN. The solution must preserve IP multicast traffic without requiring spoke-to-spoke tunnels and must use a group keying model rather than pairwise SA negotiations. Which Cisco VPN technology best meets these requirements?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"DMVPN Phase 3 with IPsec profiles"},{"id":"b","text":"AnyConnect SSL VPN with split tunneling"},{"id":"c","text":"GETVPN (Group Encrypted Transport VPN)"},{"id":"d","text":"IKEv2 FlexVPN with virtual tunnel interfaces"}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$The source material states: 'GETVPN (Group Encrypted Transport): for private MPLS, preserves multicast.' GETVPN is uniquely designed for private WAN environments (such as MPLS) where a full-mesh overlay tunnel model is unnecessary. It uses a group key management model — a Key Server distributes a common Group Security Association (GSA) to all Group Members — so any site can decrypt traffic from any other site without pairwise SA negotiation. Critically, GETVPN performs tunnel-less encryption that preserves the original IP header, allowing native multicast routing to function end-to-end. DMVPN is appropriate for hub-and-spoke or dynamic mesh topologies over public internet but requires GRE tunnels and does not natively preserve multicast across the WAN fabric in the same way. AnyConnect is a remote-access solution and is irrelevant to site-to-site WAN encryption. IKEv2 FlexVPN is a flexible point-to-point or hub-and-spoke IPsec solution but still requires tunnel interfaces and pairwise SAs, and does not offer the group key model of GETVPN.$patch$, $patch$Security$patch$,
         4, $json$[{"url":"https://www.cisco.com/c/en/us/td/docs/solutions/Enterprise/WAN_and_MAN/GETVPN/GETVPN_DIG.html","label":"Cisco: Group Encrypted Transport VPN (GETVPN) Design and Implementation Guide"},{"url":"https://www.cisco.com/c/en/us/support/docs/security-vpn/ipsec-negotiation-ike-protocols/116091-technote-getvpn-00.html","label":"Cisco: GETVPN vs DMVPN Technology Comparison"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P2'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A large financial institution needs to extend encrypted group communications across its existing private MPLS WAN. The solution must preserve IP multicast traffic without requiring spoke-to-spoke tunnels and must use a group keying model rather than pairwise SA negotiations. Which Cisco VPN technology best meets these requirements?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network engineer is writing a Python script to retrieve interface statistics from a Cisco IOS XE device using NETCONF. The script successfully establishes a session but must target the correct TCP port and transport protocol. Which port and transport does NETCONF use according to RFC 6241?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"TCP port 443 over HTTPS"},{"id":"b","text":"TCP port 830 over SSH"},{"id":"c","text":"TCP port 161 over UDP"},{"id":"d","text":"TCP port 8080 over HTTP"}]$json$::jsonb, $json$["b"]$json$::jsonb, $patch$According to the source material: 'NETCONF (RFC 6241): XML-based, runs over SSH (port 830), uses YANG models.' NETCONF mandates SSH as its mandatory-to-implement transport and IANA has assigned port 830 for this purpose. Option (a) describes RESTCONF, which uses HTTPS (port 443). Option (c) describes SNMP's transport, which uses UDP port 161. Option (d) describes a generic HTTP alternate port not associated with NETCONF.$patch$, $patch$Automation$patch$,
         4, $json$[{"url":"https://www.rfc-editor.org/rfc/rfc6241","label":"RFC 6241 – Network Configuration Protocol (NETCONF)"},{"url":"https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/prog/configuration/1612/b_1612_programmability_cg/netconf_protocol.html","label":"Cisco IOS XE Programmability Configuration Guide – NETCONF Protocol"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P2'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network engineer is writing a Python script to retrieve interface statistics from a Cisco IOS XE device using NETCONF. The script successfully establishes a session but must target the correct TCP port and transport protocol. Which port and transport does NETCONF use according to RFC 6241?$patch$);
INSERT INTO "Question" (id, "examId", stem, type, options, correct, explanation, domain, difficulty, "references", status, "generatedBy", "isTeaser", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, e.id, $patch$A network automation engineer must choose a configuration management tool that is agentless and uses YAML-based playbooks to push configuration changes to Cisco IOS devices via SSH. The engineer also requires a module specifically designed for IOS device configuration. Which tool and module combination best satisfies these requirements?$patch$, 'SINGLE'::"QType",
         $json$[{"id":"a","text":"Puppet using a Ruby DSL manifest with the cisco_ios resource type"},{"id":"b","text":"Chef using a Ruby DSL cookbook with the ios_template recipe"},{"id":"c","text":"Ansible using YAML playbooks with the ios_config module"},{"id":"d","text":"Terraform using a declarative HCL file with a Cisco provider resource"}]$json$::jsonb, $json$["c"]$json$::jsonb, $patch$The source material states: 'Ansible: agentless, YAML playbooks, SSH/NETCONF. Modules like ios_config, nxos_config.' Ansible requires no agent on managed devices and communicates over SSH, making it the only option that is both agentless and YAML-based. Option (a) Puppet and option (b) Chef are described in the source as 'agent-based, Ruby DSL,' disqualifying them on both the agentless and YAML requirements. Option (d) Terraform is a declarative infrastructure-as-code tool using HCL (HashiCorp Configuration Language) and maintains a state file; it is not a YAML-playbook-driven, SSH-native IOS configuration tool. The ios_config Ansible module sends IOS CLI commands or configuration blocks directly to Cisco devices over SSH, fulfilling the stated requirements.$patch$, $patch$Automation$patch$,
         4, $json$[{"url":"https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_config_module.html","label":"Ansible Documentation – cisco.ios.ios_config module"},{"url":"https://developer.cisco.com/automation-ansible/","label":"Cisco DevNet – Network Automation with Ansible"}]$json$::jsonb, 'DRAFT'::"QStatus", 'claude-sonnet-4-6', false, NOW(), NOW()
  FROM "Exam" e WHERE e.code = '350-401-P2'
  AND NOT EXISTS (SELECT 1 FROM "Question" q2 WHERE q2."examId" = e.id AND q2.stem = $patch$A network automation engineer must choose a configuration management tool that is agentless and uses YAML-based playbooks to push configuration changes to Cisco IOS devices via SSH. The engineer also requires a module specifically designed for IOS device configuration. Which tool and module combination best satisfies these requirements?$patch$);

