// ISO 3166-1 alpha-2 codes with English country names. Keep alphabetized.
export const NATIONALITIES: { code: string; name: string }[] = [
  { code: 'AF', name: 'Afghan' },
  { code: 'AL', name: 'Albanian' },
  { code: 'DZ', name: 'Algerian' },
  { code: 'AR', name: 'Argentine' },
  { code: 'AU', name: 'Australian' },
  { code: 'AT', name: 'Austrian' },
  { code: 'BD', name: 'Bangladeshi' },
  { code: 'BE', name: 'Belgian' },
  { code: 'BR', name: 'Brazilian' },
  { code: 'BN', name: 'Bruneian' },
  { code: 'BG', name: 'Bulgarian' },
  { code: 'KH', name: 'Cambodian' },
  { code: 'CA', name: 'Canadian' },
  { code: 'CL', name: 'Chilean' },
  { code: 'CN', name: 'Chinese' },
  { code: 'CO', name: 'Colombian' },
  { code: 'HR', name: 'Croatian' },
  { code: 'CZ', name: 'Czech' },
  { code: 'DK', name: 'Danish' },
  { code: 'EG', name: 'Egyptian' },
  { code: 'PH', name: 'Filipino' },
  { code: 'FI', name: 'Finnish' },
  { code: 'FR', name: 'French' },
  { code: 'DE', name: 'German' },
  { code: 'GR', name: 'Greek' },
  { code: 'HK', name: 'Hong Konger' },
  { code: 'HU', name: 'Hungarian' },
  { code: 'IS', name: 'Icelandic' },
  { code: 'IN', name: 'Indian' },
  { code: 'ID', name: 'Indonesian' },
  { code: 'IR', name: 'Iranian' },
  { code: 'IQ', name: 'Iraqi' },
  { code: 'IE', name: 'Irish' },
  { code: 'IL', name: 'Israeli' },
  { code: 'IT', name: 'Italian' },
  { code: 'JP', name: 'Japanese' },
  { code: 'JO', name: 'Jordanian' },
  { code: 'KZ', name: 'Kazakh' },
  { code: 'KE', name: 'Kenyan' },
  { code: 'KW', name: 'Kuwaiti' },
  { code: 'LA', name: 'Lao' },
  { code: 'LB', name: 'Lebanese' },
  { code: 'MY', name: 'Malaysian' },
  { code: 'MX', name: 'Mexican' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'NP', name: 'Nepali' },
  { code: 'NL', name: 'Dutch' },
  { code: 'NZ', name: 'New Zealander' },
  { code: 'NG', name: 'Nigerian' },
  { code: 'NO', name: 'Norwegian' },
  { code: 'OM', name: 'Omani' },
  { code: 'PK', name: 'Pakistani' },
  { code: 'PE', name: 'Peruvian' },
  { code: 'PL', name: 'Polish' },
  { code: 'PT', name: 'Portuguese' },
  { code: 'QA', name: 'Qatari' },
  { code: 'RO', name: 'Romanian' },
  { code: 'RU', name: 'Russian' },
  { code: 'SA', name: 'Saudi' },
  { code: 'SG', name: 'Singaporean' },
  { code: 'SK', name: 'Slovak' },
  { code: 'ZA', name: 'South African' },
  { code: 'KR', name: 'South Korean' },
  { code: 'ES', name: 'Spanish' },
  { code: 'LK', name: 'Sri Lankan' },
  { code: 'SE', name: 'Swedish' },
  { code: 'CH', name: 'Swiss' },
  { code: 'TW', name: 'Taiwanese' },
  { code: 'TH', name: 'Thai' },
  { code: 'TR', name: 'Turkish' },
  { code: 'AE', name: 'Emirati' },
  { code: 'GB', name: 'British' },
  { code: 'US', name: 'American' },
  { code: 'UA', name: 'Ukrainian' },
  { code: 'UY', name: 'Uruguayan' },
  { code: 'UZ', name: 'Uzbek' },
  { code: 'VE', name: 'Venezuelan' },
  { code: 'VN', name: 'Vietnamese' },
  { code: 'YE', name: 'Yemeni' }
];

export const NATIONALITY_CODES = new Set(NATIONALITIES.map((n) => n.code));
