import { QType } from '@prisma/client';
import { Q, opts4, opts5, SECURE, RESILIENT, PERF, COST, REF } from './types';

/**
 * SAA-C03 practice variant p2 — service emphasis: Databases & Caching.
 * 65 original scenario questions.
 * Domain split: SECURE 20, RESILIENT 17, PERF 16, COST 12.
 */
export const P2: Q[] = [
  // ---------------- SECURE (20) ----------------
  {
    domain: SECURE,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A company runs an Amazon RDS for PostgreSQL database that stores customer financial records. Compliance requires that all data be encrypted at rest, including automated backups, read replicas, and snapshots. The database is currently unencrypted and in production. Which approach meets the requirement?',
    options: opts4(
      'Enable encryption on the existing DB instance from the RDS console with a single click',
      'Take a snapshot, copy the snapshot with a KMS key to enable encryption, and restore a new encrypted DB instance from the encrypted copy',
      'Attach an encrypted EBS volume to the existing RDS instance',
      'Enable SSL/TLS on the database connection to satisfy the encryption-at-rest requirement'
    ),
    correct: ['b'],
    explanation: 'You cannot enable encryption on an existing unencrypted RDS instance in place. The supported path is to snapshot the instance, copy the snapshot while specifying a KMS key (the copy operation is where encryption is applied), then restore a new encrypted instance. Encryption then propagates to backups, replicas, and snapshots. SSL/TLS only protects data in transit, not at rest.',
    references: [REF.RDS_MULTI_AZ, REF.KMS],
    isTeaser: true
  },
  {
    domain: SECURE,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A microservice running on Amazon ECS needs to read a password to connect to an Amazon Aurora MySQL cluster. The security team mandates automatic credential rotation every 30 days and prohibits hardcoded credentials in task definitions. Which solution is the MOST secure and operationally efficient?',
    options: opts4(
      'Store the password as a plaintext environment variable in the ECS task definition',
      'Store the credentials in AWS Secrets Manager with rotation enabled, and grant the ECS task role permission to retrieve the secret',
      'Store the password in an encrypted S3 object and download it at container startup',
      'Embed the password in the container image and rebuild the image every 30 days'
    ),
    correct: ['b'],
    explanation: 'AWS Secrets Manager natively supports scheduled automatic rotation for RDS/Aurora credentials and integrates with the ECS task IAM role for fine-grained retrieval. Environment variables and baked-in images expose secrets and require manual rotation. An encrypted S3 object lacks built-in rotation.',
    references: [REF.SECRETS_MANAGER, REF.AURORA],
    isTeaser: true
  },
  {
    domain: SECURE,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'An application server in a private subnet must connect to an Amazon DynamoDB table without sending traffic over the public internet or through a NAT gateway. The security team wants table access restricted so that only requests from the VPC are permitted. Which combination achieves this?',
    options: opts4(
      'Create an interface VPC endpoint for DynamoDB and open a public IP on the application server',
      'Create a gateway VPC endpoint for DynamoDB and attach an endpoint policy plus a table resource policy that restricts access to the endpoint',
      'Route DynamoDB traffic through an internet gateway with a restrictive security group',
      'Use a NAT gateway and an IAM policy that allows all DynamoDB actions'
    ),
    correct: ['b'],
    explanation: 'DynamoDB (and S3) use gateway VPC endpoints, which keep traffic on the AWS network and avoid NAT charges. An endpoint policy plus a condition restricting access to the VPC endpoint (aws:sourceVpce) enforces that only in-VPC requests reach the table. Interface endpoints are for most other services, not the classic gateway-endpoint pattern here.',
    references: [REF.GATEWAY_ENDPOINT, REF.DYNAMODB],
    isTeaser: true
  },
  {
    domain: SECURE,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A company uses Amazon Aurora MySQL and wants application code to authenticate to the database without storing any long-lived database password. Engineers should obtain short-lived credentials tied to their IAM identity. Which feature meets this requirement?',
    options: opts4(
      'Aurora IAM database authentication with tokens generated by the IAM credentials',
      'A static MySQL user with a complex password stored in Parameter Store',
      'Kerberos authentication using a self-managed Active Directory',
      'SSL client certificates issued by AWS Certificate Manager Private CA'
    ),
    correct: ['a'],
    explanation: 'Aurora/RDS IAM database authentication lets clients generate a 15-minute auth token from their IAM credentials instead of a stored password, eliminating long-lived secrets. Parameter Store still stores a static password. Kerberos uses AWS Managed Microsoft AD, not arbitrary self-managed AD here, and is for Windows-domain auth, not token-based passwordless auth.',
    references: [{ label: 'Amazon RDS — IAM database authentication', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html' }, REF.AURORA],
    isTeaser: true
  },
  {
    domain: SECURE,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A regulated workload requires that the KMS key used to encrypt an Amazon RDS database be managed by the customer, with the ability to audit every cryptographic operation and to disable the key independently. Which option satisfies these requirements?',
    options: opts4(
      'Use the AWS-owned key for RDS',
      'Use the AWS managed key aws/rds',
      'Use a customer managed KMS key and review AWS CloudTrail logs of key usage',
      'Use client-side encryption with a key stored in the application'
    ),
    correct: ['c'],
    explanation: 'A customer managed KMS key gives the customer control over rotation, key policy, enable/disable, and full CloudTrail auditing of every encrypt/decrypt call. The AWS managed key (aws/rds) cannot be disabled or have its policy edited, and AWS-owned keys are not visible at all.',
    references: [REF.KMS, REF.RDS_MULTI_AZ]
  },
  {
    domain: SECURE,
    difficulty: 3,
    type: QType.MULTI,
    stem: 'A company is hardening access to an Amazon RDS for SQL Server instance in a private subnet. The database must only accept connections from an application Auto Scaling group and must never be reachable from the internet. Which two configurations enforce this? (Choose two.)',
    options: opts5(
      'Place the RDS instance in private subnets with no route to an internet gateway',
      'Set the RDS security group inbound rule to allow port 1433 only from the application tier security group',
      'Assign a public IP address to the RDS instance and restrict it with a NACL',
      'Create an internet-facing endpoint and protect it with AWS WAF',
      'Open the RDS security group to 0.0.0.0/0 on port 1433 and rely on IAM authentication'
    ),
    correct: ['a', 'b'],
    explanation: 'Keeping RDS in private subnets without an internet gateway route prevents internet exposure, and referencing the application tier security group as the source (security group chaining) restricts inbound 1433 to only those instances. Public IPs, internet-facing endpoints, and 0.0.0.0/0 rules all break the isolation requirement.',
    references: [REF.RDS_MULTI_AZ, { label: 'Amazon VPC — Security groups', url: 'https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-groups.html' }],
    isTeaser: true
  },
  {
    domain: SECURE,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'An analytics team needs read-only query access to a subset of tables in an Amazon Redshift cluster. The security team wants the access governed by IAM and temporary credentials rather than permanent Redshift user passwords. Which approach is best?',
    options: opts4(
      'Share the cluster master credentials with the analytics team',
      'Use the Redshift GetClusterCredentials API (or Redshift Data API with IAM) to issue temporary database credentials mapped to a least-privilege database role',
      'Create one permanent superuser per analyst',
      'Disable encryption so analysts can query faster'
    ),
    correct: ['b'],
    explanation: 'GetClusterCredentials (and the Redshift Data API) issues short-lived credentials tied to an IAM principal and can auto-create/join a database group with grants limited to specific tables, enforcing least privilege without permanent passwords. Sharing master credentials or creating superusers violates least privilege; encryption is irrelevant to access control.',
    references: [{ label: 'Amazon Redshift — Using IAM authentication to generate database credentials', url: 'https://docs.aws.amazon.com/redshift/latest/mgmt/generating-iam-credentials-overview.html' }],
    isTeaser: true
  },
  {
    domain: SECURE,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A company runs Amazon ElastiCache for Redis to cache session data that includes personally identifiable information. Auditors require encryption in transit and at rest, plus authentication for clients connecting to the cluster. Which configuration meets all three requirements?',
    options: opts4(
      'Enable cluster mode only',
      'Enable in-transit encryption, at-rest encryption, and Redis AUTH (or RBAC) on the replication group',
      'Place the cluster in a public subnet and use a security group',
      'Use Memcached with TLS termination at an Application Load Balancer'
    ),
    correct: ['b'],
    explanation: 'ElastiCache for Redis supports in-transit (TLS) encryption, at-rest encryption with KMS, and access control via Redis AUTH token or RBAC users. Memcached does not support encryption or AUTH and is not fronted by an ALB. Subnet placement and security groups alone do not satisfy encryption/auth requirements.',
    references: [{ label: 'Amazon ElastiCache for Redis — Data security', url: 'https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/encryption.html' }]
  },
  {
    domain: SECURE,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'An application uses an IAM role on EC2 instances to write to an Amazon DynamoDB table. Security requires that the instances be able to put and query items in one specific table only, and nothing else. Which IAM policy design follows least privilege?',
    options: opts4(
      'Attach the AmazonDynamoDBFullAccess managed policy to the role',
      'Create a customer-managed policy allowing only dynamodb:PutItem and dynamodb:Query on the specific table ARN',
      'Use the root account access keys on the instances',
      'Grant dynamodb:* on Resource "*"'
    ),
    correct: ['b'],
    explanation: 'Least privilege means scoping both actions (PutItem, Query) and the resource (the exact table ARN). The full-access managed policy and dynamodb:* on all resources are over-permissive. Root access keys must never be placed on instances.',
    references: [REF.IAM_ROLES, REF.DYNAMODB]
  },
  {
    domain: SECURE,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A multi-account organization stores production databases in a dedicated account. Security wants to guarantee that no IAM principal in any member account can ever delete RDS instances or disable encryption, regardless of their attached IAM policies. Which control enforces this organization-wide?',
    options: opts4(
      'A permission boundary on each IAM user',
      'A service control policy (SCP) that denies rds:DeleteDBInstance and related actions, applied to the organizational unit',
      'A resource-based policy on the RDS instance',
      'An IAM group with a deny policy in each account'
    ),
    correct: ['b'],
    explanation: 'An SCP sets the maximum available permissions for accounts in an OU and a Deny in an SCP cannot be overridden by any IAM policy in the member account, making it the only org-wide guardrail listed. Permission boundaries and group deny policies must be applied per principal and can be missed; RDS has no resource policy for this.',
    references: [REF.ORGANIZATIONS_SCP, REF.IAM_POLICY_EVAL]
  },
  {
    domain: SECURE,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A web application is experiencing SQL injection attempts that are reaching an Amazon RDS backend through an Application Load Balancer. The team wants to block malicious requests before they hit the application without changing application code. Which service should be added?',
    options: opts4(
      'AWS Shield Standard only',
      'AWS WAF with managed rule groups (including SQL database rules) associated with the ALB',
      'A NAT gateway in front of the ALB',
      'Amazon GuardDuty in monitor-only mode'
    ),
    correct: ['b'],
    explanation: 'AWS WAF can be associated with an ALB and its AWS managed rule groups include SQL injection protections that inspect and block malicious requests at the edge of the application, requiring no code changes. Shield Standard handles DDoS, not injection; GuardDuty detects but does not block requests; a NAT gateway is unrelated.',
    references: [REF.WAF, REF.ALB],
    isTeaser: true
  },
  {
    domain: SECURE,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A company must ensure that Amazon RDS automated snapshots stored cross-region for disaster recovery remain encrypted, and that the destination region uses a different KMS key than the source. Which approach is correct?',
    options: opts4(
      'Cross-region snapshot copies cannot be encrypted',
      'Copy the snapshot to the destination region and specify a KMS key that exists in the destination region during the copy',
      'Encryption keys are automatically shared across all regions by KMS',
      'Disable encryption before copying, then re-enable it after'
    ),
    correct: ['b'],
    explanation: 'KMS keys are region-scoped. When copying an encrypted snapshot to another region you must specify a KMS key in the destination region; the copy is re-encrypted with that key. Keys are never shared across regions automatically, and you should never disable encryption to copy.',
    references: [REF.KMS, REF.RDS_MULTI_AZ]
  },
  {
    domain: SECURE,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'An application connects to an Amazon Aurora PostgreSQL cluster. The security team requires that all client connections to the database be encrypted in transit and that connections without TLS be rejected. Which actions accomplish this?',
    options: opts4(
      'Enable at-rest encryption with a customer managed key',
      'Set the cluster parameter rds.force_ssl to 1 and have clients connect using the AWS-provided certificate bundle',
      'Place the cluster behind a Network Load Balancer with TLS listeners',
      'Use a security group rule that only allows port 443'
    ),
    correct: ['b'],
    explanation: 'Setting rds.force_ssl=1 in the Aurora PostgreSQL DB cluster parameter group forces every connection to use TLS and rejects non-TLS connections; clients verify with the AWS RDS CA bundle. At-rest encryption is unrelated to in-transit. Aurora is not fronted by an NLB, and a port-443 security group rule does not change the database wire protocol.',
    references: [{ label: 'Amazon RDS — Using SSL/TLS to encrypt connections', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html' }, REF.AURORA]
  },
  {
    domain: SECURE,
    difficulty: 3,
    type: QType.MULTI,
    stem: 'A SaaS provider stores tenant data in Amazon DynamoDB and must prevent any single tenant application credential from reading another tenant\'s items. Which two mechanisms enforce per-tenant isolation? (Choose two.)',
    options: opts5(
      'Use IAM policy conditions with dynamodb:LeadingKeys to restrict access to items whose partition key matches the tenant',
      'Store all tenants in one item and filter in the application',
      'Issue per-tenant scoped IAM roles assumed via STS with fine-grained access policies',
      'Disable encryption to simplify cross-tenant queries',
      'Allow dynamodb:* on the whole table for every tenant role'
    ),
    correct: ['a', 'c'],
    explanation: 'DynamoDB fine-grained access control with the dynamodb:LeadingKeys condition limits a principal to items whose partition key equals their tenant ID, and issuing per-tenant STS-assumed roles scopes credentials to a single tenant. Application-side filtering after a broad table-wide grant still allows credential misuse; disabling encryption is irrelevant and harmful.',
    references: [{ label: 'DynamoDB — Using IAM policy conditions for fine-grained access control', url: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/specifying-conditions.html' }, REF.IAM_ROLES],
    isTeaser: true
  },
  {
    domain: SECURE,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A company wants its Lambda functions to retrieve Amazon RDS credentials securely. The credentials must be cached briefly to reduce calls and rotated automatically without redeploying functions. Which solution is best?',
    options: opts4(
      'Hardcode credentials in Lambda environment variables encrypted with a default key',
      'Store credentials in AWS Secrets Manager with rotation, and use the Secrets Manager Lambda extension/SDK caching to fetch them at runtime',
      'Store credentials in a public S3 bucket with a long random key',
      'Pass the credentials as a query string parameter to the function'
    ),
    correct: ['b'],
    explanation: 'Secrets Manager provides managed rotation for RDS credentials, and the Secrets Manager caching client/Lambda extension caches the value for a short TTL so functions pick up rotated secrets automatically without redeploys. Environment variables require redeploy on rotation and a public bucket is a severe exposure.',
    references: [REF.SECRETS_MANAGER, REF.LAMBDA],
    isTeaser: true
  },
  {
    domain: SECURE,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A financial application must restrict which networks can connect to an Amazon RDS Proxy endpoint and ensure database credentials are never exposed to the application. The application authenticates to the proxy using IAM. Which configuration is correct?',
    options: opts4(
      'RDS Proxy with IAM authentication enabled and the proxy retrieving the database secret from AWS Secrets Manager, placed in private subnets with a restrictive security group',
      'RDS Proxy in a public subnet with the master password embedded in the connection string',
      'A direct connection to RDS with the password in plaintext, no proxy',
      'RDS Proxy with anonymous access enabled'
    ),
    correct: ['a'],
    explanation: 'RDS Proxy can require IAM authentication from clients while it retrieves the actual database credentials from Secrets Manager, so the application never sees the password. Placing the proxy in private subnets with a tight security group restricts which networks can reach it. Public subnets, plaintext passwords, and anonymous access all violate the requirements.',
    references: [{ label: 'Amazon RDS Proxy', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html' }, REF.SECRETS_MANAGER]
  },
  {
    domain: SECURE,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'An organization wants to detect, without agents, when an Amazon RDS database is publicly accessible or has unencrypted storage, and be alerted automatically. Which service provides continuous configuration compliance checks for this?',
    options: opts4(
      'AWS Config with managed rules such as rds-instance-public-access-check and rds-storage-encrypted',
      'Amazon Inspector network reachability for RDS',
      'AWS Trusted Advisor only in the free tier',
      'Amazon Macie data classification'
    ),
    correct: ['a'],
    explanation: 'AWS Config continuously evaluates resource configurations against managed rules like rds-instance-public-access-check and rds-storage-encrypted and can trigger notifications/remediation on noncompliance. Inspector focuses on EC2/container vulnerabilities, Macie classifies S3 data, and free-tier Trusted Advisor lacks these specific continuous RDS checks.',
    references: [{ label: 'AWS Config — Managed rules', url: 'https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_use-managed-rules.html' }]
  },
  {
    domain: SECURE,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A company runs Amazon Redshift and must ensure that data is encrypted at rest using keys managed in AWS CloudHSM under the company\'s exclusive control for regulatory reasons. Which Redshift encryption option meets this requirement?',
    options: opts4(
      'Default Redshift encryption with an AWS owned key',
      'Redshift encryption integrated with AWS KMS using a customer managed key',
      'Redshift encryption using an AWS CloudHSM key (HSM-based key management)',
      'No encryption, relying on VPC isolation'
    ),
    correct: ['c'],
    explanation: 'Amazon Redshift supports key management through AWS CloudHSM, where the cluster encryption keys are stored in and controlled by the customer\'s dedicated HSM, satisfying strict regulatory custody requirements. KMS customer managed keys are valid encryption but do not provide dedicated single-tenant HSM custody; VPC isolation is not encryption.',
    references: [{ label: 'Amazon Redshift — Database encryption', url: 'https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-db-encryption.html' }]
  },
  {
    domain: SECURE,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'An application database password stored in AWS Secrets Manager must be rotated, but the database is an Amazon RDS for Oracle instance not in the supported single-user rotation list of the default template behavior. The team wants rotation that also tests the new password before promoting it. Which rotation strategy applies?',
    options: opts4(
      'Disable rotation entirely',
      'Use the Secrets Manager alternating users rotation strategy with two database users so the active credential is always validated before switchover',
      'Rotate only the username, never the password',
      'Store the password in plaintext to avoid rotation complexity'
    ),
    correct: ['b'],
    explanation: 'The alternating users rotation strategy maintains two database users and rotates by updating the inactive one, testing it, then switching the secret to point at it — minimizing downtime and validating credentials before promotion. Disabling rotation or storing plaintext defeats the security goal.',
    references: [{ label: 'Secrets Manager — Rotation strategies', url: 'https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets.html' }]
  },
  {
    domain: SECURE,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A company needs cross-account access so a data science account can read an Amazon DynamoDB table owned by a data lake account, without sharing long-term keys. Which mechanism is the recommended pattern?',
    options: opts4(
      'Create an IAM role in the data lake account with a trust policy for the data science account, granting scoped DynamoDB read permissions, and have the data science principals assume it via STS',
      'Email an IAM user access key from the data lake account to the data science team',
      'Make the DynamoDB table public',
      'Share the data lake account root credentials'
    ),
    correct: ['a'],
    explanation: 'Cross-account access is achieved with an IAM role in the resource-owning account whose trust policy permits the other account, granting only the needed DynamoDB read actions; principals assume the role through STS for temporary credentials. Sharing access keys or root credentials and making tables public are insecure anti-patterns.',
    references: [REF.IAM_ROLES, REF.DYNAMODB]
  },

  // ---------------- RESILIENT (17) ----------------
  {
    domain: RESILIENT,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'An e-commerce platform runs on Amazon RDS for MySQL. The business requires automatic failover to a standby in another Availability Zone within about a minute if the primary instance fails, with no application-managed replication. Which deployment satisfies this with the LEAST operational effort?',
    options: opts4(
      'A single-AZ RDS instance with manual snapshots',
      'An RDS Multi-AZ instance deployment with a synchronous standby in a second AZ',
      'A read replica in the same AZ promoted manually on failure',
      'Two independent RDS instances with application-level dual writes'
    ),
    correct: ['b'],
    explanation: 'RDS Multi-AZ maintains a synchronous standby in another AZ and automatically fails over (typically within 60–120 seconds) by flipping the DNS endpoint, with no application replication logic. Read replicas are asynchronous and require manual promotion; application-level dual writes are complex and error-prone.',
    references: [REF.RDS_MULTI_AZ],
    isTeaser: true
  },
  {
    domain: RESILIENT,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A workload uses Amazon RDS Multi-AZ but experiences read-heavy reporting that occasionally saturates the primary. The team also wants faster failover (under 35 seconds) and the ability to serve reads from the standby instances. Which RDS deployment best fits?',
    options: opts4(
      'RDS Multi-AZ instance deployment (one standby, standby not readable)',
      'RDS Multi-AZ DB cluster deployment with two readable standby instances',
      'A single-AZ instance with a larger instance class',
      'RDS with storage autoscaling only'
    ),
    correct: ['b'],
    explanation: 'The RDS Multi-AZ DB cluster deployment uses one writer and two readable standby instances, offers typically sub-35-second failover, and lets reporting traffic hit the reader endpoint, offloading the writer. The classic Multi-AZ instance deployment keeps the standby non-readable. Vertical scaling or storage autoscaling alone do not add read capacity or faster failover.',
    references: [{ label: 'Amazon RDS — Multi-AZ DB cluster deployments', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZDBClusters.html' }],
    isTeaser: true
  },
  {
    domain: RESILIENT,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A global application needs an Amazon Aurora MySQL database with a primary Region for writes and a secondary Region that can be promoted for disaster recovery with a typical recovery time of under a minute and cross-Region replication lag usually under one second. Which solution meets this?',
    options: opts4(
      'A cross-Region Aurora read replica created manually',
      'Amazon Aurora Global Database with a secondary Region',
      'RDS for MySQL with cross-Region snapshot copies every hour',
      'Aurora Serverless v2 in a single Region'
    ),
    correct: ['b'],
    explanation: 'Aurora Global Database replicates to secondary Regions with typically sub-second lag using dedicated infrastructure and supports cross-Region failover (managed planned failover and unplanned promotion) generally within a minute. A single cross-Region read replica and hourly snapshot copies have higher RTO/RPO; Aurora Serverless v2 in one Region offers no cross-Region DR.',
    references: [{ label: 'Amazon Aurora — Global databases', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database.html' }, REF.AURORA],
    isTeaser: true
  },
  {
    domain: RESILIENT,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A company must be able to restore its Amazon RDS for PostgreSQL database to any second within the last 7 days after an accidental bulk delete. Which capability provides this, and what must be enabled?',
    options: opts4(
      'Manual snapshots taken once per week',
      'Automated backups with a retention period configured, enabling point-in-time recovery (PITR)',
      'Read replicas in another AZ',
      'Multi-AZ deployment alone'
    ),
    correct: ['b'],
    explanation: 'RDS point-in-time recovery relies on automated backups plus transaction logs and lets you restore to any second within the backup retention window (1–35 days). Manual weekly snapshots only restore to snapshot points; replicas and Multi-AZ provide availability, not granular point-in-time restore.',
    references: [{ label: 'Amazon RDS — Point-in-time recovery', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PIT.html' }],
    isTeaser: true
  },
  {
    domain: RESILIENT,
    difficulty: 3,
    type: QType.MULTI,
    stem: 'A team wants to perform a major-version upgrade of a production Amazon RDS for MySQL database with minimal downtime and the ability to quickly roll back if validation fails. Which two characteristics describe the RDS Blue/Green Deployments approach? (Choose two.)',
    options: opts5(
      'It creates a synchronized green (staging) environment that you can test before switching',
      'It permanently deletes the old database immediately at creation',
      'Switchover is typically completed in about a minute with safeguards, and the old (blue) environment remains for rollback',
      'It requires application code changes to handle dual writes',
      'It only works for DynamoDB tables'
    ),
    correct: ['a', 'c'],
    explanation: 'RDS Blue/Green Deployments create a green environment kept in sync via replication so you can test upgrades/changes; switchover is fast (about a minute) with safety checks, and the blue environment is retained afterward so you can revert. It does not delete the old environment at creation, needs no app dual-write logic, and is an RDS/Aurora feature, not DynamoDB.',
    references: [{ label: 'Amazon RDS — Blue/Green Deployments', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/blue-green-deployments-overview.html' }],
    isTeaser: true
  },
  {
    domain: RESILIENT,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'An application stores user profiles in Amazon DynamoDB and must remain fully readable and writable in two AWS Regions, with changes in either Region replicated to the other for active-active resilience. Which feature provides this?',
    options: opts4(
      'DynamoDB Streams with a Lambda copying items manually',
      'DynamoDB global tables (multi-Region, multi-active replication)',
      'A cross-Region read replica of the table',
      'DynamoDB Accelerator (DAX)'
    ),
    correct: ['b'],
    explanation: 'DynamoDB global tables provide fully managed multi-Region, multi-active replication so both Regions accept reads and writes with automatic conflict resolution. A custom Stream+Lambda copy is operationally fragile; DynamoDB has no "read replica" concept; DAX is an in-Region caching layer, not cross-Region replication.',
    references: [{ label: 'DynamoDB — Global tables', url: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GlobalTables.html' }, REF.DYNAMODB],
    isTeaser: true
  },
  {
    domain: RESILIENT,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A company runs Amazon ElastiCache for Redis as a primary store for leaderboard data. It must survive an Availability Zone failure with automatic promotion of a replica and minimal data loss. Which configuration should be used?',
    options: opts4(
      'A single-node Redis cluster',
      'A Redis replication group with Multi-AZ enabled and automatic failover, with replicas in different AZs',
      'Memcached with multiple nodes',
      'Redis with cluster mode disabled and no replicas'
    ),
    correct: ['b'],
    explanation: 'A Redis replication group with replicas spread across AZs and Multi-AZ with automatic failover enabled will detect a primary failure and promote a replica automatically, surviving an AZ outage. Single-node Redis and replica-less configurations have no failover target; Memcached has no replication or persistence.',
    references: [{ label: 'ElastiCache for Redis — Minimizing downtime with Multi-AZ', url: 'https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/AutoFailover.html' }],
    isTeaser: true
  },
  {
    domain: RESILIENT,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A reporting application puts heavy read load on an Amazon RDS for PostgreSQL primary, occasionally affecting transactional performance and risking availability. The team wants to isolate reporting reads while keeping the primary healthy. Which approach is appropriate?',
    options: opts4(
      'Create one or more RDS read replicas and point reporting queries at the read replica endpoint',
      'Increase the backup retention period',
      'Enable Multi-AZ instance deployment so the standby serves reporting reads',
      'Disable automated backups to free up resources'
    ),
    correct: ['a'],
    explanation: 'RDS read replicas asynchronously replicate the primary and can serve read-only reporting traffic, isolating that load from the transactional primary. The Multi-AZ instance standby is not readable; backup retention and disabling backups do not offload read traffic and disabling backups harms resilience.',
    references: [REF.RDS_READ_REPLICA]
  },
  {
    domain: RESILIENT,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'An application using Amazon RDS opens and closes thousands of short-lived database connections during traffic spikes, exhausting the database\'s max connections and causing failures. The team wants improved resilience to connection storms and faster failover handling without re-architecting the app. Which managed solution helps MOST?',
    options: opts4(
      'Add more read replicas',
      'Place Amazon RDS Proxy between the application and the database to pool and share connections',
      'Increase the instance storage size',
      'Switch to a single-AZ deployment'
    ),
    correct: ['b'],
    explanation: 'RDS Proxy pools and multiplexes database connections, absorbing connection storms and reducing failover times by preserving client connections while the database fails over. Read replicas help reads, not connection exhaustion on writes; storage size and single-AZ do not address connection limits or resilience.',
    references: [{ label: 'Amazon RDS Proxy', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html' }, REF.RDS_MULTI_AZ]
  },
  {
    domain: RESILIENT,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A company needs a centralized, policy-driven way to back up Amazon RDS, Amazon DynamoDB, Amazon EFS, and Amazon EBS resources on a schedule with cross-Region copy for disaster recovery. Which service provides this with minimal custom scripting?',
    options: opts4(
      'AWS Backup with backup plans and cross-Region copy rules',
      'Custom cron jobs on an EC2 instance calling each service API',
      'S3 Lifecycle policies',
      'RDS automated backups only'
    ),
    correct: ['a'],
    explanation: 'AWS Backup centrally manages backup plans, schedules, retention, and cross-Region/-account copy across RDS, DynamoDB, EFS, EBS, and more without per-service scripting. Custom cron jobs are fragile and unmanaged; S3 Lifecycle and RDS-only backups do not cover the other services.',
    references: [REF.BACKUP]
  },
  {
    domain: RESILIENT,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'An Aurora MySQL cluster serves a read-heavy application whose read traffic varies widely throughout the day. The team wants the number of Aurora Replicas to scale automatically with load to maintain read availability and performance. Which feature should be configured?',
    options: opts4(
      'Aurora Replica Auto Scaling based on average CPU or connections of the replicas',
      'EC2 Auto Scaling on the database instances',
      'Manual addition of replicas during peak hours by an operator',
      'DynamoDB auto scaling'
    ),
    correct: ['a'],
    explanation: 'Aurora Replica Auto Scaling adds or removes Aurora Replicas automatically based on a target metric such as average CPU utilization or connections, keeping read capacity and availability aligned with demand. EC2 Auto Scaling does not manage Aurora replicas; manual scaling is slow and error-prone; DynamoDB auto scaling is for a different service.',
    references: [{ label: 'Aurora — Using Amazon Aurora Auto Scaling with Aurora Replicas', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Integrating.AutoScaling.html' }, REF.AURORA]
  },
  {
    domain: RESILIENT,
    difficulty: 2,
    type: QType.MULTI,
    stem: 'A company wants to protect against accidental deletion of critical Amazon DynamoDB tables and be able to restore a table to any point in the last 35 days. Which two settings should be enabled? (Choose two.)',
    options: opts5(
      'DynamoDB point-in-time recovery (PITR) on the table',
      'Deletion protection on the table',
      'DynamoDB DAX in front of the table',
      'A global secondary index on every attribute',
      'TTL on all items'
    ),
    correct: ['a', 'b'],
    explanation: 'Point-in-time recovery enables continuous backups allowing restore to any second in the trailing 35 days, and deletion protection prevents the table from being deleted accidentally. DAX is a cache, GSIs are for query patterns, and TTL deletes items — none of these protect against accidental deletion or provide point-in-time restore.',
    references: [{ label: 'DynamoDB — Point-in-time recovery', url: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/PointInTimeRecovery.html' }, REF.DYNAMODB]
  },
  {
    domain: RESILIENT,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A company is migrating a 4 TB on-premises Oracle database to Amazon Aurora PostgreSQL. The schema differs between engines and the business requires near-zero downtime during cutover. Which combination of AWS services should be used?',
    options: opts4(
      'AWS Schema Conversion Tool (SCT) to convert the schema and AWS Database Migration Service (DMS) with ongoing replication (CDC) for near-zero-downtime cutover',
      'Manual mysqldump export and import',
      'Amazon S3 cross-Region replication',
      'Snowball Edge only, with no schema changes'
    ),
    correct: ['a'],
    explanation: 'Because the source and target engines differ, AWS SCT converts the Oracle schema/code to PostgreSQL, and AWS DMS performs the bulk load plus ongoing change data capture so cutover happens with minimal downtime. mysqldump targets MySQL, S3 replication does not migrate databases, and Snowball alone does not handle heterogeneous schema conversion or continuous replication.',
    references: [{ label: 'AWS Database Migration Service — User Guide', url: 'https://docs.aws.amazon.com/dms/latest/userguide/Welcome.html' }, { label: 'AWS Schema Conversion Tool', url: 'https://docs.aws.amazon.com/SchemaConversionTool/latest/userguide/CHAP_Welcome.html' }],
    isTeaser: true
  },
  {
    domain: RESILIENT,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'An Amazon RDS for MySQL database periodically runs out of storage during unpredictable data growth, causing the instance to enter a storage-full state. The team wants storage to grow automatically without downtime. Which feature addresses this?',
    options: opts4(
      'RDS storage autoscaling (Storage Autoscaling) with a maximum storage threshold',
      'Manually resizing the volume each time it fills',
      'Switching to magnetic storage',
      'Creating a read replica to add storage'
    ),
    correct: ['a'],
    explanation: 'RDS Storage Autoscaling automatically increases allocated storage when free space falls below a threshold, up to a configured maximum, preventing storage-full outages without manual intervention or downtime. Manual resizing is reactive; magnetic storage and read replicas do not solve capacity growth.',
    references: [{ label: 'Amazon RDS — Managing capacity with storage autoscaling', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PIOPS.StorageTypes.html#USER_PIOPS.Autoscaling' }]
  },
  {
    domain: RESILIENT,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A development team frequently needs full-size copies of a 2 TB production Aurora MySQL cluster for testing. Creating restores from snapshots takes hours and consumes storage. Which Aurora feature creates a writable copy quickly and cost-efficiently?',
    options: opts4(
      'Aurora database cloning (copy-on-write clones)',
      'Restoring from an automated snapshot each time',
      'Creating a cross-Region read replica',
      'Exporting to S3 and importing into a new cluster'
    ),
    correct: ['a'],
    explanation: 'Aurora cloning uses a copy-on-write protocol to create a new writable cluster almost instantly, sharing underlying storage until pages diverge, which is far faster and cheaper than snapshot restores for test environments. Snapshot restore, cross-Region replica, and S3 export/import are slower and use more storage.',
    references: [{ label: 'Aurora — Cloning a volume', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Managing.Clone.html' }, REF.AURORA]
  },
  {
    domain: RESILIENT,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A company wants its Amazon Aurora cluster to automatically tolerate disk failures and continue serving traffic without administrator action. Which statement about Aurora storage resilience is correct?',
    options: opts4(
      'Aurora stores a single copy of data in one AZ and requires manual recovery on disk failure',
      'Aurora replicates data six ways across three Availability Zones and self-heals storage automatically',
      'Aurora has no built-in storage redundancy; you must configure RAID',
      'Aurora requires a Multi-AZ instance deployment to have any storage redundancy'
    ),
    correct: ['b'],
    explanation: 'Aurora\'s storage layer automatically maintains six copies of data across three AZs and continuously self-heals, tolerating the loss of disk segments transparently without administrator intervention. The other statements misdescribe Aurora\'s inherently distributed, fault-tolerant storage.',
    references: [{ label: 'Aurora — Storage and reliability', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.StorageReliability.html' }]
  },

  {
    domain: RESILIENT,
    difficulty: 2,
    type: QType.MULTI,
    stem: 'A critical Amazon RDS for MySQL database must have its automated backups retained for disaster recovery and protected so that an accidental console action cannot immediately delete the database. Which two settings improve recoverability and protection? (Choose two.)',
    options: opts5(
      'Set the automated backup retention period to a value greater than zero (for example, 14 days)',
      'Enable deletion protection on the DB instance',
      'Disable Multi-AZ to simplify recovery',
      'Set the backup retention period to 0 to save storage',
      'Store the master password in the connection string'
    ),
    correct: ['a', 'b'],
    explanation: 'A non-zero backup retention period keeps automated backups and enables point-in-time recovery, and deletion protection blocks accidental deletion of the instance. Setting retention to 0 disables automated backups, disabling Multi-AZ reduces availability, and placing the password in the connection string is a security anti-pattern unrelated to recoverability.',
    references: [{ label: 'Amazon RDS — Working with backups', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html' }, REF.RDS_MULTI_AZ]
  },

  // ---------------- PERF (16) ----------------
  {
    domain: PERF,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A read-intensive product catalog backed by Amazon RDS for MySQL is hitting CPU limits because the same popular items are queried repeatedly. The team wants to dramatically reduce read latency and database load with minimal code changes. Which solution is MOST effective?',
    options: opts4(
      'Add Amazon ElastiCache (Redis) as a cache-aside layer in front of RDS for hot reads',
      'Increase the RDS backup retention period',
      'Move the database to a single-AZ deployment',
      'Enable Multi-AZ to add read capacity'
    ),
    correct: ['a'],
    explanation: 'A cache-aside pattern with ElastiCache for Redis serves repeated hot reads from in-memory cache, sharply lowering latency and offloading the database. Backup retention is unrelated; single-AZ reduces resilience without adding read capacity; Multi-AZ instance deployment does not add a readable endpoint.',
    references: [{ label: 'Caching strategies — ElastiCache', url: 'https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Strategies.html' }],
    isTeaser: true
  },
  {
    domain: PERF,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A DynamoDB-backed application requires single-digit microsecond read latency for an extremely read-heavy workload of repeated key lookups, an order of magnitude faster than DynamoDB\'s single-digit millisecond reads. Which solution achieves this?',
    options: opts4(
      'Increase provisioned read capacity units significantly',
      'Add Amazon DynamoDB Accelerator (DAX) as an in-memory cache for the table',
      'Enable DynamoDB Streams',
      'Add a global secondary index'
    ),
    correct: ['b'],
    explanation: 'DynamoDB Accelerator (DAX) is a managed in-memory cache for DynamoDB that delivers microsecond read latency for cached items, far faster than DynamoDB\'s millisecond reads. Raising RCUs improves throughput but not the latency floor; Streams and GSIs serve different purposes (change capture, alternate query patterns).',
    references: [{ label: 'DynamoDB Accelerator (DAX)', url: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.html' }, REF.DYNAMODB],
    isTeaser: true
  },
  {
    domain: PERF,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A new application has unpredictable, spiky DynamoDB traffic and the team cannot accurately forecast capacity. They want to avoid throttling during spikes and avoid paying for idle provisioned capacity, with no capacity management. Which capacity mode should they choose?',
    options: opts4(
      'Provisioned capacity with fixed RCUs/WCUs',
      'On-demand capacity mode',
      'Provisioned capacity with auto scaling and a low maximum',
      'Reserved capacity purchased for one year'
    ),
    correct: ['b'],
    explanation: 'On-demand capacity mode automatically accommodates traffic without capacity planning and bills per request, ideal for unpredictable, spiky workloads. Fixed provisioned capacity risks throttling on spikes; auto scaling with a low max can still throttle and reacts with delay; reserved capacity requires committed forecasting.',
    references: [{ label: 'DynamoDB — Read/write capacity mode', url: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadWriteCapacityMode.html' }],
    isTeaser: true
  },
  {
    domain: PERF,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'An Aurora MySQL workload has steady baseline traffic with frequent, sharp, unpredictable spikes. The team wants compute that scales granularly and quickly with load and scales down during idle periods, without managing instance classes. Which Aurora option fits best?',
    options: opts4(
      'Aurora provisioned instances sized for peak load 24/7',
      'Aurora Serverless v2, which scales capacity in fine-grained increments based on demand',
      'Aurora Serverless v1 with a single fixed capacity unit',
      'A db.t3.micro provisioned instance'
    ),
    correct: ['b'],
    explanation: 'Aurora Serverless v2 scales compute in fine-grained ACU increments rapidly to match fluctuating demand and scales down when idle, removing instance-class management. Provisioning for peak 24/7 wastes money; Serverless v1 scales more coarsely/slowly; a fixed t3.micro cannot absorb sharp spikes.',
    references: [{ label: 'Aurora Serverless v2', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.html' }, REF.AURORA],
    isTeaser: true
  },
  {
    domain: PERF,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A reporting application sends complex analytical queries that scan billions of rows; it currently runs on an Amazon RDS for PostgreSQL OLTP database and is too slow. The team needs a columnar, massively parallel data warehouse for these queries. Which service should they use?',
    options: opts4(
      'Amazon Redshift',
      'Amazon ElastiCache for Memcached',
      'A larger RDS for PostgreSQL instance',
      'Amazon DynamoDB'
    ),
    correct: ['a'],
    explanation: 'Amazon Redshift is a columnar, massively parallel processing data warehouse purpose-built for large-scale analytical (OLAP) queries scanning huge datasets. ElastiCache is a cache, scaling the OLTP RDS instance still uses a row store ill-suited to large scans, and DynamoDB is a NoSQL key-value store, not an analytical warehouse.',
    references: [{ label: 'Amazon Redshift — System overview', url: 'https://docs.aws.amazon.com/redshift/latest/dg/welcome.html' }],
    isTeaser: true
  },
  {
    domain: PERF,
    difficulty: 3,
    type: QType.MULTI,
    stem: 'A globally distributed read-mostly application uses Amazon Aurora MySQL with users in North America, Europe, and Asia complaining about read latency from the single primary Region. Which two approaches reduce read latency for distant users? (Choose two.)',
    options: opts5(
      'Deploy an Aurora Global Database and direct local read traffic to read-only secondary Region endpoints',
      'Add an in-Region ElastiCache layer to serve hot reads close to users in each Region',
      'Increase the primary instance size only',
      'Disable encryption to speed up replication',
      'Move the entire database to a single AZ'
    ),
    correct: ['a', 'b'],
    explanation: 'Aurora Global Database places low-latency read replicas in secondary Regions so users read locally, and adding a regional ElastiCache cache further reduces latency for hot reads near users. Enlarging only the primary does not help distant users, disabling encryption is unsafe and not the bottleneck, and a single AZ does not address geographic latency.',
    references: [{ label: 'Amazon Aurora — Global databases', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database.html' }, { label: 'Caching strategies — ElastiCache', url: 'https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Strategies.html' }]
  },
  {
    domain: PERF,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'An application stores user session state and needs a fast, in-memory data store. It also requires data structures such as sorted sets and pub/sub, plus replication and persistence. Which ElastiCache engine should be selected?',
    options: opts4(
      'ElastiCache for Memcached',
      'ElastiCache for Redis',
      'Amazon RDS for MySQL',
      'Amazon DynamoDB without DAX'
    ),
    correct: ['b'],
    explanation: 'ElastiCache for Redis supports rich data structures (sorted sets, lists), pub/sub, replication, and optional persistence/backup. Memcached is a simple multi-threaded key-value cache without replication, persistence, or advanced data structures. RDS and plain DynamoDB are not in-memory caches.',
    references: [{ label: 'ElastiCache — Comparing Memcached and Redis', url: 'https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/SelectEngine.html' }]
  },
  {
    domain: PERF,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'An Aurora PostgreSQL writer is bottlenecked by an OLTP workload that mixes heavy writes with frequent analytical read queries. The team wants to route analytics to replicas while always sending writes to the current writer, with automatic endpoint management. Which Aurora capability should the application use?',
    options: opts4(
      'Hardcode each replica instance endpoint in the application',
      'Use the Aurora cluster reader endpoint for read traffic and the cluster writer endpoint for writes',
      'Send all traffic to a single instance endpoint',
      'Use a Network Load Balancer to distribute database traffic'
    ),
    correct: ['b'],
    explanation: 'The Aurora reader endpoint automatically load-balances connections across available Aurora Replicas while the writer endpoint always points to the current primary, so analytics use the reader endpoint and writes use the writer endpoint with no manual endpoint tracking. Hardcoding instance endpoints breaks on failover; an NLB is not how Aurora routing works.',
    references: [{ label: 'Aurora — Connection management endpoints', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.Endpoints.html' }, REF.AURORA]
  },
  {
    domain: PERF,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A streaming analytics pipeline must ingest hundreds of thousands of clickstream events per second and write aggregated results to Amazon DynamoDB with consistent low-latency writes that scale automatically as traffic grows steadily. Which DynamoDB capacity setting is appropriate for steadily growing, predictable load?',
    options: opts4(
      'Provisioned capacity with auto scaling configured on write capacity',
      'A fixed small provisioned WCU value with no scaling',
      'On-demand mode is the only option that can ever handle high writes',
      'Disable auto scaling and manually adjust WCUs hourly'
    ),
    correct: ['a'],
    explanation: 'For predictable, steadily growing traffic, provisioned capacity with write auto scaling tracks utilization and adjusts WCUs automatically, providing cost-effective scaling. A fixed small WCU throttles; on-demand also works but is not the only option for high writes; manual hourly adjustment is operationally poor and lags demand.',
    references: [{ label: 'DynamoDB — Managing throughput with auto scaling', url: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/AutoScaling.html' }]
  },
  {
    domain: PERF,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A team observes that their Amazon RDS for MySQL gp2 volume is throttling I/O during nightly batch jobs that need sustained high IOPS and consistent throughput, while normal daytime load is light. Which storage choice provides predictable high performance for the batch window?',
    options: opts4(
      'Switch to Provisioned IOPS SSD (io1/io2) storage with the required IOPS provisioned',
      'Reduce the allocated storage size',
      'Move to magnetic (standard) storage',
      'Disable automated backups during the batch window'
    ),
    correct: ['a'],
    explanation: 'Provisioned IOPS SSD storage lets you provision a guaranteed, consistent IOPS level required for I/O-intensive, latency-sensitive workloads like nightly batch jobs. Shrinking storage can reduce gp2 baseline performance, magnetic is slower, and disabling backups harms resilience without solving IOPS throttling.',
    references: [{ label: 'Amazon RDS — Provisioned IOPS SSD storage', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html' }]
  },
  {
    domain: PERF,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A leaderboard service performs millions of increment operations and range queries on ranked scores with sub-millisecond latency requirements. A relational database cannot keep up. Which data store and structure best fits this access pattern?',
    options: opts4(
      'Amazon ElastiCache for Redis using sorted sets',
      'Amazon S3 with object versioning',
      'Amazon RDS for PostgreSQL with a B-tree index',
      'Amazon Athena over JSON files'
    ),
    correct: ['a'],
    explanation: 'Redis sorted sets are purpose-built for leaderboards: O(log N) ranked inserts and range queries with in-memory sub-millisecond latency. S3 and Athena are object/analytics stores unsuited to high-frequency ranked updates, and an RDS B-tree cannot match in-memory leaderboard performance at this scale.',
    references: [{ label: 'ElastiCache for Redis — Sorted sets / use cases', url: 'https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/elasticache-use-cases.html' }]
  },
  {
    domain: PERF,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'An application reads from an Amazon RDS for MySQL read replica but sometimes shows stale data because of replication lag during write bursts. The business can tolerate eventual consistency for most reads but needs a way to monitor and react to excessive lag. Which metric should be alarmed?',
    options: opts4(
      'CloudWatch ReplicaLag metric for the read replica',
      'FreeStorageSpace on the primary',
      'DatabaseConnections on the replica',
      'CPUCreditBalance on a gp2 volume'
    ),
    correct: ['a'],
    explanation: 'The CloudWatch ReplicaLag metric reports how far a read replica is behind the primary; alarming on it lets the team detect and respond to excessive staleness (for example by routing critical reads to the primary). Storage space, connection count, and CPU credits do not measure replication lag.',
    references: [REF.RDS_READ_REPLICA, { label: 'Amazon RDS — Monitoring with CloudWatch metrics', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/monitoring-cloudwatch.html' }]
  },
  {
    domain: PERF,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'An application frequently writes large volumes of time-series sensor data to DynamoDB but only the most recent 30 days are ever queried. Older data wastes storage and slows scans. Which DynamoDB feature automatically removes expired items at scale with no extra cost?',
    options: opts4(
      'DynamoDB Time to Live (TTL) using an expiry timestamp attribute',
      'A scheduled Lambda that scans and deletes old items',
      'DynamoDB Streams',
      'Manual BatchWriteItem deletes nightly'
    ),
    correct: ['a'],
    explanation: 'DynamoDB TTL automatically deletes items shortly after a per-item expiry timestamp at no additional cost and without consuming write throughput for the deletions, ideal for rolling time-series retention. Scheduled scans/deletes and manual batch deletes consume capacity and are operationally heavier; Streams only captures changes.',
    references: [{ label: 'DynamoDB — Time to Live (TTL)', url: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html' }],
    isTeaser: true
  },
  {
    domain: PERF,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A team needs to react in near real time to every change made to items in a DynamoDB table — for example, to update a search index and trigger downstream processing — without polling the table. Which approach is most appropriate?',
    options: opts4(
      'Enable DynamoDB Streams and process change records with an AWS Lambda trigger',
      'Run a full table Scan every minute and diff the results',
      'Use DAX to detect changes',
      'Enable point-in-time recovery and compare snapshots'
    ),
    correct: ['a'],
    explanation: 'DynamoDB Streams captures an ordered, time-windowed log of item-level changes, and a Lambda trigger can process each change in near real time for indexing or downstream workflows. Periodic Scans are costly and laggy, DAX is a read cache, and PITR is for restore, not change notification.',
    references: [{ label: 'DynamoDB — Change data capture with Streams', url: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html' }, REF.LAMBDA],
    isTeaser: true
  },
  {
    domain: PERF,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A specialized legacy application requires operating-system and database-engine access on Amazon RDS for Oracle to install vendor agents and apply custom patches that standard RDS does not allow. The team still wants AWS-managed backups and high availability where possible. Which RDS option fits?',
    options: opts4(
      'Amazon RDS Custom for Oracle',
      'Standard Amazon RDS for Oracle',
      'Self-managed Oracle on EC2 with no automation',
      'Amazon Aurora PostgreSQL'
    ),
    correct: ['a'],
    explanation: 'RDS Custom for Oracle gives privileged OS and database access for legacy/customization requirements while still providing managed automation like backups. Standard RDS for Oracle blocks OS-level access; self-managed EC2 loses managed automation; Aurora PostgreSQL is a different engine and cannot run the Oracle-specific application.',
    references: [{ label: 'Amazon RDS Custom', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-custom.html' }]
  },
  {
    domain: PERF,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A web application connects directly to an Amazon RDS for PostgreSQL database from a fleet of Lambda functions. During traffic surges, the database hits its connection limit because each concurrent Lambda opens its own connection. Which managed solution improves performance under high concurrency?',
    options: opts4(
      'Amazon RDS Proxy to pool and reuse database connections for the Lambda fleet',
      'Increasing the Lambda memory size',
      'Adding a CloudFront distribution in front of the database',
      'Switching the database to magnetic storage'
    ),
    correct: ['a'],
    explanation: 'RDS Proxy maintains a shared pool of database connections that many concurrent Lambda invocations can reuse, preventing connection exhaustion and improving performance under spiky serverless concurrency. Lambda memory, CloudFront, and storage type do not address the database connection limit.',
    references: [{ label: 'Amazon RDS Proxy', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html' }, REF.LAMBDA]
  },

  // ---------------- COST (12) ----------------
  {
    domain: COST,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A company runs a production Amazon RDS for MySQL database 24/7 with steady, predictable utilization for at least the next year. They want to minimize database cost without changing the architecture. Which purchasing option provides the largest savings?',
    options: opts4(
      'On-Demand DB instances',
      'Reserved DB Instances for a 1-year (or 3-year) term matching the instance class',
      'Spot Instances for the database',
      'Provisioned IOPS storage'
    ),
    correct: ['b'],
    explanation: 'RDS Reserved DB Instances offer substantial discounts versus On-Demand for steady, long-running databases with a 1- or 3-year commitment. On-Demand is the baseline price; Spot is not available for RDS instances; Provisioned IOPS is a storage performance choice, not a cost-saving purchase option.',
    references: [{ label: 'Amazon RDS — Reserved DB Instances', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithReservedDBInstances.html' }],
    isTeaser: true
  },
  {
    domain: COST,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A development and test Amazon RDS for PostgreSQL instance is only used during business hours, about 10 hours on weekdays, but currently runs continuously, wasting money on nights and weekends. Which approach reduces cost with minimal effort?',
    options: opts4(
      'Use the RDS stop/start capability on a schedule (e.g., via EventBridge + automation) to stop the instance outside business hours',
      'Delete and recreate the database every morning by hand',
      'Switch the instance to Provisioned IOPS storage',
      'Buy a 3-year Reserved Instance for the dev database'
    ),
    correct: ['a'],
    explanation: 'RDS supports stopping an instance for up to 7 days; scheduling stop/start around business hours stops compute billing during idle nights and weekends with minimal effort. Manual delete/recreate is error-prone and risks data loss; Provisioned IOPS adds cost; a 3-year reservation is wrong for an intermittently used dev database.',
    references: [{ label: 'Amazon RDS — Stopping and starting a DB instance', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_StopInstance.html' }],
    isTeaser: true
  },
  {
    domain: COST,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A serverless application uses an Amazon DynamoDB table provisioned at high RCU/WCU to handle rare daily spikes, but average utilization is under 10%, wasting money. Traffic is sporadic and hard to predict. Which change reduces cost while still handling spikes?',
    options: opts4(
      'Switch the table to on-demand capacity mode so you pay per request instead of for idle provisioned capacity',
      'Increase the provisioned capacity further',
      'Buy DynamoDB reserved capacity for the current high provisioned values',
      'Add a global secondary index to spread the load'
    ),
    correct: ['a'],
    explanation: 'For sporadic, unpredictable, low-average-utilization traffic, on-demand mode bills only for actual requests, eliminating payment for largely idle provisioned capacity while still absorbing spikes. Increasing capacity or reserving the high values increases cost; a GSI adds cost and does not fix over-provisioning.',
    references: [{ label: 'DynamoDB — Read/write capacity mode', url: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadWriteCapacityMode.html' }]
  },
  {
    domain: COST,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A company wants automatic alerts when the projected monthly spend on its Amazon RDS and Amazon Redshift resources is forecast to exceed a defined threshold, so finance can act before the bill arrives. Which service should be configured?',
    options: opts4(
      'AWS Budgets with a cost budget and forecasted-spend alerts filtered to the database services',
      'AWS CloudTrail event history',
      'Amazon CloudWatch billing dashboards only',
      'AWS Config rules'
    ),
    correct: ['a'],
    explanation: 'AWS Budgets lets you define cost budgets (optionally filtered by service) and notify on actual or forecasted spend exceeding thresholds, enabling proactive financial action. CloudTrail logs API activity, Config checks configuration compliance, and a CloudWatch billing dashboard alone does not provide forecasted budget alerting like Budgets.',
    references: [REF.BUDGETS],
    isTeaser: true
  },
  {
    domain: COST,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A company over-provisioned several Amazon RDS instances and wants data-driven recommendations on right-sizing or switching instance classes to reduce cost without performance loss. Which AWS tool provides these specific recommendations?',
    options: opts4(
      'AWS Compute Optimizer (RDS recommendations)',
      'AWS Trusted Advisor cost checks only in the basic support tier',
      'AWS Pricing Calculator',
      'Amazon CloudWatch alarms alone'
    ),
    correct: ['a'],
    explanation: 'AWS Compute Optimizer analyzes utilization metrics and provides right-sizing recommendations for RDS DB instances (and other resources) to cut cost while preserving performance. The Pricing Calculator only estimates hypothetical costs, CloudWatch alarms just notify on thresholds, and basic-tier Trusted Advisor lacks detailed RDS right-sizing analysis.',
    references: [{ label: 'AWS Compute Optimizer — User Guide', url: 'https://docs.aws.amazon.com/compute-optimizer/latest/ug/what-is-compute-optimizer.html' }]
  },
  {
    domain: COST,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'An analytics team queries an Amazon Redshift cluster heavily for 4 hours each business day and the cluster sits idle the rest of the time, but it is provisioned and billed continuously. They want a cost model that charges primarily for the queries they run. Which option fits best?',
    options: opts4(
      'Amazon Redshift Serverless, which scales and bills based on usage rather than a always-on provisioned cluster',
      'A larger provisioned RA3 cluster running 24/7',
      'Adding more reserved nodes to the existing cluster',
      'Switching the cluster to dense storage nodes only'
    ),
    correct: ['a'],
    explanation: 'Amazon Redshift Serverless automatically provisions and scales capacity and bills for the compute used by workloads, which suits intermittent, bursty analytics far better than an always-on provisioned cluster. A larger or reserved 24/7 cluster increases the idle cost; node type alone does not change the always-on billing model.',
    references: [{ label: 'Amazon Redshift Serverless', url: 'https://docs.aws.amazon.com/redshift/latest/mgmt/serverless-whatis.html' }],
    isTeaser: true
  },
  {
    domain: COST,
    difficulty: 3,
    type: QType.MULTI,
    stem: 'A company wants to lower the cost of its production Aurora MySQL environment, which has a steady writer plus several read replicas. Which two cost-optimization actions are appropriate without harming the steady workload? (Choose two.)',
    options: opts5(
      'Purchase Aurora Reserved Instances for the steady writer and baseline replicas',
      'Use Aurora Replica Auto Scaling to remove replicas during sustained low-read periods',
      'Delete all automated backups to reduce storage cost',
      'Run the production writer on Spot capacity',
      'Disable Multi-AZ on the production writer to save money'
    ),
    correct: ['a', 'b'],
    explanation: 'Reserved Instances cut the cost of the always-on writer and baseline replicas, and Aurora Replica Auto Scaling removes excess replicas when read demand drops, reducing spend without hurting steady traffic. Deleting backups and disabling Multi-AZ sacrifice resilience, and Aurora does not run on Spot.',
    references: [{ label: 'Amazon RDS — Reserved DB Instances', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithReservedDBInstances.html' }, { label: 'Aurora — Auto Scaling with Aurora Replicas', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Integrating.AutoScaling.html' }],
    isTeaser: true
  },
  {
    domain: COST,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A company keeps years of Amazon RDS manual snapshots for compliance, and snapshot storage cost is growing. Most old snapshots are rarely needed but must be retained for 7 years cheaply. Which approach reduces long-term retention cost?',
    options: opts4(
      'Export older RDS snapshots to Amazon S3 (Parquet) and apply S3 lifecycle policies to transition to lower-cost storage classes such as Glacier',
      'Keep every snapshot as a standard RDS snapshot indefinitely',
      'Convert snapshots to Provisioned IOPS volumes',
      'Store snapshots on an always-running EC2 instance'
    ),
    correct: ['a'],
    explanation: 'Exporting RDS snapshot data to Amazon S3 lets you apply lifecycle rules transitioning to inexpensive archival classes (e.g., Glacier) for long, rarely accessed retention, far cheaper than retaining many standard RDS snapshots. The other options keep or increase cost.',
    references: [{ label: 'Amazon RDS — Exporting DB snapshot data to Amazon S3', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ExportSnapshot.html' }, REF.S3_LIFECYCLE]
  },
  {
    domain: COST,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A startup runs a small but always-on Amazon DynamoDB workload with steady, well-understood throughput. They currently use on-demand mode and the bill is higher than expected for this predictable traffic. Which change is likely to reduce cost?',
    options: opts4(
      'Switch to provisioned capacity mode sized to the steady throughput (optionally with reserved capacity)',
      'Increase on-demand request limits',
      'Add DAX to lower the DynamoDB bill',
      'Enable global tables in three Regions'
    ),
    correct: ['a'],
    explanation: 'For steady, predictable throughput, provisioned capacity (optionally with reserved capacity) is typically cheaper than on-demand, which carries a premium for elasticity. DAX adds cost (it improves latency), and enabling global tables in extra Regions multiplies cost rather than reducing it.',
    references: [{ label: 'DynamoDB — Read/write capacity mode', url: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadWriteCapacityMode.html' }]
  },
  {
    domain: COST,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A company runs a relational database on a large Amazon EC2 instance with self-managed MySQL, paying for the instance plus significant operational labor for patching, backups, and HA. They want to cut both infrastructure and operational cost while keeping MySQL compatibility. Which migration is MOST cost-effective long term?',
    options: opts4(
      'Migrate to Amazon RDS for MySQL (or Aurora MySQL) to offload patching, backups, and HA to AWS',
      'Move to a larger EC2 instance with the same self-managed setup',
      'Run MySQL in a single container on the same instance',
      'Keep the EC2 database but buy Provisioned IOPS'
    ),
    correct: ['a'],
    explanation: 'Moving self-managed MySQL to RDS or Aurora MySQL removes the undifferentiated operational burden (patching, backups, HA), reducing total cost of ownership while preserving MySQL compatibility. Bigger EC2, containerizing on the same host, or adding Provisioned IOPS keep the operational labor and may add cost.',
    references: [{ label: 'Amazon RDS — User Guide', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Welcome.html' }, REF.AURORA]
  },
  {
    domain: COST,
    difficulty: 2,
    type: QType.SINGLE,
    stem: 'A company wants visibility into which database services (RDS, DynamoDB, ElastiCache) and which teams drive cost, broken down by tags, so they can charge back departments. Which capability provides this analysis?',
    options: opts4(
      'AWS Cost Explorer with cost allocation tags grouped by service and tag',
      'AWS CloudTrail Insights',
      'Amazon CloudWatch Logs Insights',
      'AWS Config aggregators'
    ),
    correct: ['a'],
    explanation: 'AWS Cost Explorer, combined with activated cost allocation tags, lets you analyze and group spend by service and by tag (team/department) for chargeback. CloudTrail Insights detects unusual API activity, CloudWatch Logs Insights queries logs, and Config aggregators track configuration, not cost breakdowns.',
    references: [REF.COST_EXPLORER, { label: 'AWS Billing — Using cost allocation tags', url: 'https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html' }],
    isTeaser: true
  },
  {
    domain: COST,
    difficulty: 3,
    type: QType.SINGLE,
    stem: 'A data platform runs frequent ad hoc SQL analytics over large datasets stored in Amazon S3. Maintaining an always-on Amazon Redshift cluster purely for occasional queries is expensive. Which approach minimizes cost for infrequent querying of S3 data?',
    options: opts4(
      'Use Amazon Athena to run serverless SQL queries directly against S3, paying per query',
      'Keep a large Redshift cluster running 24/7',
      'Load all S3 data into an always-on RDS instance',
      'Provision a fleet of EC2 instances running a SQL engine continuously'
    ),
    correct: ['a'],
    explanation: 'Amazon Athena is serverless and charges per amount of data scanned per query, making it cost-effective for infrequent ad hoc analytics directly on S3 with no cluster to keep running. An always-on Redshift cluster, an always-on RDS load target, or a continuous EC2 fleet all incur idle cost for occasional queries.',
    references: [REF.ATHENA]
  }
];
