/**
 * One-shot seed: CompTIA Data+ (Practice Exam 2) (70 questions).
 *
 *   npx tsx scripts/seed-comptia-data-plus-p2.ts
 *
 * Idempotent: skips Question seeding if any questions tagged "manual:comptia-data-plus-p2"
 * already exist for this exam. Source: practice PDF (parsed via
 * pdftotext + scripts/_pdf-to-seed.ts).
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';

const db = new PrismaClient();

const VENDOR_SLUG = 'comptia';
const EXAM_SLUG = 'comptia-data-plus-p2';
const TAG = 'manual:comptia-data-plus-p2';

const DOMAINS = [
  { name: 'Data Concepts and Environments', weight: 15 },
  { name: 'Data Mining', weight: 25 },
  { name: 'Data Analysis', weight: 23 },
  { name: 'Visualization', weight: 23 },
  { name: 'Data Governance, Quality, and Controls', weight: 14 }
];

const REF = {
  label: 'CompTIA Data+ exam objectives',
  url: 'https://www.comptia.org/certifications/data'
};

type Q = {
  domain: string;
  type: QType;
  stem: string;
  options: { id: string; text: string }[];
  correct: string[];
  explanation: string;
};

const QUESTIONS: Q[] = [
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'When working with a data set, unnecessary data fields that have no value to the analysis are known as:',
    options: [
      { id: 'A', text: 'Invalid Data' },
      { id: 'B', text: 'Noise' },
      { id: 'C', text: 'Non-parametric Data' },
      { id: 'D', text: 'Null Data' }
    ],
    correct: ['A'],
    explanation: 'OBJ 2.2 - Unnecessary data fields that have no value to the analysis are known as noise. Null data has no value in the field and can be identified with NULL, N/A, or a blank field. Invalid data is data that is incorrect. Non-parametric data exists when the data is not within the rules of normal distribution, with values that frequently deviate from the mean.'
  },
  {
    domain: 'Data Analysis',
    type: QType.MULTI,
    stem: 'Jet is working with boolean field data and must identify the following as boolean values. Please select all examples of boolean values:',
    options: [
      { id: 'A', text: '1/0' },
      { id: 'B', text: 'True/False' },
      { id: 'C', text: 'On/Off' },
      { id: 'D', text: 'Yes/No' },
      { id: 'E', text: '500 F. 9/20/1984' }
    ],
    correct: ['A', 'E'],
    explanation: 'OBJ 1.2 - 1/0, True/False, On/Off, and Yes/No are examples of boolean values. 500 is a number value and 9/20/1984 is a date value.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Which of the following is an example of adjusting the outline of a project and its measurable tasks for the desired end state?',
    options: [
      { id: 'A', text: 'Regression analysis' },
      { id: 'B', text: 'Simple linear regression' },
      { id: 'C', text: 'Key Performance Indicators (KPIs)' },
      { id: 'D', text: 'Scope creep' }
    ],
    correct: ['D'],
    explanation: 'OBJ 3.2, 3.3 - This is an example of scope creep. Scope creep is the adjustment of the outline of a project and its measurable tasks that are needed to meet the desired end state. These adjustments can cause issues in meeting deadlines or cause a gap in reaching the desired state on time and within budget. KPIs are measurements or goals used to identify if a business is achieving its objectives. KPIs can be used to monitor the status of products, processes, or sales goals for example. Simple linear regression is used to study the relationship between one dependent variable and one predictor, or independent variable. This analysis informs an analyst on which predictor may have the largest impact. Regression analysis is a statistical method used to estimate relationships between a dependent variable and one or more independent variables.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Which of the following is automatically generated by a computer process, application, or other mechanisms without the intervention of a human?',
    options: [
      { id: 'A', text: 'A Web Service' },
      { id: 'B', text: 'Machine Data' },
      { id: 'C', text: 'An API' },
      { id: 'D', text: 'Web Scraping' }
    ],
    correct: ['B'],
    explanation: 'OBJ 2.1 - Machine data is produced by a machine rather than a human. For example, time stamps for computer logins are automatically generated. Web scraping is the act of pulling information from a website and can be done with automation or by hand. Not all websites allow web scraping. A web service is a type of API that allows a hosted computer on a network to share data back and forth with a computer in the same hosted environment. An API is a set of protocols within a computer system that allows two unrelated systems to communicate.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Tommy is a data analyst that is preparing a presentation to his coworkers on their team\'s cloud service usage. He needs to break down, summarize, and display information in a compelling way. Which of the following should he use to accomplish this?',
    options: [
      { id: 'A', text: 'Table' },
      { id: 'B', text: 'Matrix' },
      { id: 'C', text: 'Graphical visuals' },
      { id: 'D', text: 'Cards' }
    ],
    correct: ['C'],
    explanation: 'OBJ 4.1 - Tommy should use graphical visuals. Graphical visuals are used to break down, summarize, and display information, usually in a dashboard. Cards are a simple way to display critical information on a dashboard. A matrix displays values at the cross-section of a row and column and is great for showing multiple dimensions and aggregated values. A table displays columns and rows of data and can also include aggregate information. Tables are valuable for information that needs to be subtotaled or for the purpose of showing potential values of any dimension in a list format.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Carl is preparing for his Data+ exam that he\'ll take in three weeks at a local testing center. He\'s currently studying domain 4, visualization, and forgot which report reflects a specific period for a data set. Please assist him and select the correct answer below.',
    options: [
      { id: 'A', text: 'Static report' },
      { id: 'B', text: 'Dynamic report' },
      { id: 'C', text: 'Point-in-time report' },
      { id: 'D', text: 'Self-service report' }
    ],
    correct: ['C'],
    explanation: 'OBJ 4.5 - A dynamic report, also known as a real-time report, is connected to the data and can be refreshed on-demand or regularly updated automatically. A point-in-time report reflects on a specific point in time and can cover a day, week, month, year, or more. The timing is flexible and based on the needs of the analysis. A self-service report, also known as an on-demand report, is one that is run directly by the consumer. When consumers can leverage dashboards, or run their own reports from the systems the organization has purchased, they are doing self-service. A static report is a report that does not update automatically.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Susan is a data analyst assigned to the Department of Defense Advanced Research Agency. She is profiling a new database and identifies that it has a relational structure. After examining a customer ID in a table, she realizes that the ID is a unique identifier for a record. This is an example of what data relationship?',
    options: [
      { id: 'A', text: 'A Foreign Key' },
      { id: 'B', text: 'Classified Data' },
      { id: 'C', text: 'Transactional Data' },
      { id: 'D', text: 'A Primary Key' }
    ],
    correct: ['D'],
    explanation: 'OBJ 1.1 - This is an example of a primary key because it serves as a unique identifier for a record. When a primary key is used in another table to refer to your record, it\'s known as a foreign key. Although Susan is working for the DoD, the classification of the data she is working with is not tied to the question. Transactional data is information recorded from transactions, for example when a customer purchases a product.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Bhavna is a data analyst working at Dion automotive. She has been tasked with identifying if the sales team met the dealership goal of selling one hundred vehicles in the second quarter. This goal represents which of the following?',
    options: [
      { id: 'A', text: 'Regression analysis' },
      { id: 'B', text: 'Simple linear regression' },
      { id: 'C', text: 'Key Performance Indicators (KPIs)' },
      { id: 'D', text: 'Scope creep' }
    ],
    correct: ['C'],
    explanation: 'OBJ 3.2, 3.3 - This represents a Key Performance Indicator (KPI). KPIs are measurements or goals used to identify if a business is achieving its objectives. KPIs can be used to monitor the status of products, processes, or sales goals for example. Scope creep is the adjustment of the outline of a project and its measurable tasks that are needed to meet the desired end state. These adjustments can cause issues in meeting deadlines or cause a gap in reaching the desired state on time and within budget. Simple linear regression is used to study the relationship between one dependent variable and one predictor, or independent variable. This analysis informs an analyst on which predictor may have the largest impact. Regression analysis is a statistical method used to estimate relationships between a dependent variable and one or more independent variables.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Sahra is a new data analyst that was recently hired by a textile company. Her manager has tasked her with familiarizing herself with the team database and observes that it uses a tabular schema of storage. What type of database will Sahra be working with?',
    options: [
      { id: 'A', text: 'RDMS' },
      { id: 'B', text: 'Non-Relational' },
      { id: 'C', text: 'Categorical' },
      { id: 'D', text: 'Relational' }
    ],
    correct: ['D'],
    explanation: 'OBJ 1.1 - Sahra will be working with a relational database. A relational database is often called a tabular schema due to the rows and columns it employs. An RMDS, Relational Database Management System, is software that maintains a relational database but is not a type of database itself. Non-Relational databases do not use tabular schemas and are often called No-SQL databases. Categorical refers to a type of data that is qualitative and is not a type of database.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Shawn is a data custodian at Dion Cloud Computing Corporation. He must ensure all data policies are followed within the organization. This is known as which of the following?',
    options: [
      { id: 'A', text: 'Data governance' },
      { id: 'B', text: 'Transparency' },
      { id: 'C', text: 'Accountability' },
      { id: 'D', text: 'Standardization' }
    ],
    correct: ['C'],
    explanation: 'OBJ 5.1, 5.2 - This is known as accountability. Accountability establishes measures to ensure governance policies are followed. Standardization means data is consistently labeled, categorized, and described for use within an organization. Data governance is a framework that covers the technology, people, and processes that help control data within an organization during its different life cycles. This framework is most effective when all departments in an organization are involved and have a stake in proper management. Transparency ensures all members of an organization have access to data governance policies and understand their function.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Charlie is an economist for the state of Florida that specializes in housing prices. He has gathered a data set of 1,000 homes in Orlando and must calculate the middle value of real estate prices in the set. Which of the following is he calculating?',
    options: [
      { id: 'A', text: 'Frequency' },
      { id: 'B', text: 'Mean' },
      { id: 'C', text: 'Median' },
      { id: 'D', text: 'Mode' }
    ],
    correct: ['C'],
    explanation: 'OBJ 3.1 - Charlie is calculating the median of housing values in the set. The median is the middle number within a group of sorted numbers. Frequency is the number of times that a data point occurs in a data set. The mean is the average of a set of numbers. The mode is the number that shows up the highest amount of times in the data set.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Akando is a data steward at Dion Coffee and Tea International. He is responsible for accurate data entry and ensuring data meet applicable laws and regulations. Which of the following data entry rules would be defined by business rules that are not covered by other data integrity settings?',
    options: [
      { id: 'A', text: 'Data constraints' },
      { id: 'B', text: 'Domain integrity' },
      { id: 'C', text: 'Entity integrity' },
      { id: 'D', text: 'User-defined integrity' }
    ],
    correct: ['D'],
    explanation: 'OBJ 5.1, 5.2 - User-defined integrity is defined by business rules that are not covered by other data integrity settings. This goes beyond solely setting constraints based solely on data type or format. Data constraints are integrity rules that limit the types of data that can go into a column or table within a database system. These constraints maintain the existence of accurate and consistent data in the database. Domain integrity is the acceptable value for a field. For example, If the data type is defined as numbers, the field will not allow text. Entity integrity is the unique identifier of a record as defined using a primary key field.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Chucky needs to switch data from rows to columns and columns to rows. This is known as which of the following?',
    options: [
      { id: 'A', text: 'An Index Field' },
      { id: 'B', text: 'Masking' },
      { id: 'C', text: 'Transposing' },
      { id: 'D', text: 'Appending' }
    ],
    correct: ['C'],
    explanation: 'OBJ 2.3 - This is an example of transposing data. Transposing data reverses its direction, so columns become rows and rows become columns. Data masking hides the value of a field to protect sensitive data. An index field creates a unique ID for a record to not disclose its value. Appending combines data from separate data sets.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Tyler wants to combine a first name text field with a last name text field to create a display name for a customer database. Which of the following functions should Tyler use?',
    options: [
      { id: 'A', text: 'Text Functions' },
      { id: 'B', text: 'Merge Fields Functions' },
      { id: 'C', text: 'Logical Functions' },
      { id: 'D', text: 'System Functions' }
    ],
    correct: ['B'],
    explanation: 'OBJ 2.4 - Tyler should use a merge fields function. Merge fields functions combine multiple fields into a single field. Text functions manipulate data in text- based fields. Logical functions will check if a condition is met and return an answer based on the result. System functions track report-related information which can remove the need for an analyst to manually add information on page numbers, refresh dates, report names, etc.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Harshit was recently hired for the IT department at a produce distributor on the west coast of the United States. He now ensures data is labeled, identified with appropriate metadata, and collected and stored in a format that complies with applicable laws and regulations. What is his new role?',
    options: [
      { id: 'A', text: 'Lifecycle of data' },
      { id: 'B', text: 'Data owner' },
      { id: 'C', text: 'Data steward' },
      { id: 'D', text: 'Data custodian' }
    ],
    correct: ['C'],
    explanation: 'OBJ 5.1, 5.2 - He is a data steward. A data steward is fundamentally responsible for data quality. A data steward ensures data is labeled, identified with appropriate metadata, and collected and stored in a format that complies with applicable laws and regulations. A data owner is a management role. The data owner holds ultimate responsibility for maintaining the confidentiality, integrity, and availability of the data. The owner also normally selects a steward and custodian, delegates their actions, sets a budget and allocates resources for sufficient controls. Data has a lifecycle. It\'s created, stored, used, archived, and deleted. Each stage in the lifecycle of data has different rules and requirements for the data an organization will work with related to the regulations and compliance requirements for the industry. A data custodian manages the system where data assets are stored. This includes the responsibilities of enforcing access control, encryption, and backup/ recovery measures.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'The framing and tone of a survey question are particularly important for which of the following?',
    options: [
      { id: 'A', text: 'A Single Choice Question' },
      { id: 'B', text: 'A Multiple Choice Question' },
      { id: 'C', text: 'A Likert Scale Question' },
      { id: 'D', text: 'All of the above' }
    ],
    correct: ['D'],
    explanation: 'OBJ 2.1 - The framing and tone of all questions matter. Survey questions must be written carefully to not create leading questions that will lead to biased answers.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Rupert is a data custodian at Kane and Dion regional automotive. He has worked his way up through the data analysis team and is now responsible for ensuring data can be sent and received between the company\'s many locations. What is he now responsible for?',
    options: [
      { id: 'A', text: 'Data retention' },
      { id: 'B', text: 'Data destruction' },
      { id: 'C', text: 'Transaction processing' },
      { id: 'D', text: 'Data transmission' }
    ],
    correct: ['D'],
    explanation: 'OBJ 5.1, 5.2 - He is now responsible for data transmission. Data transmission is the process of sending and receiving data. Data retention defines the duration that data must be kept. This includes both the minimum and maximum times it can remain in storage before it is destroyed. Data destruction describes the legally compliant means through which data must be removed and made inaccessible. The required level of destruction is directly related to the data\'s classification and sensitivity. Transaction processing is used for transactional data that is mission-critical to an organization. These processes are captured and processed in real-time.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Rupert is a data custodian at Kane and Dion regional automotive. He has worked his way up through the data analysis team and is now responsible for ensuring data is removed in a legally compliant manner after it exceeds a defined threshold. What is he now responsible for?',
    options: [
      { id: 'A', text: 'Data rentention' },
      { id: 'B', text: 'Data destruction' },
      { id: 'C', text: 'Transaction processing' },
      { id: 'D', text: 'Data transmission' }
    ],
    correct: ['B'],
    explanation: 'OBJ 5.1, 5.2 - He is now responsible for data destruction. Data destruction describes the legally compliant means through which data must be removed and made inaccessible. The required level of destruction is directly related to the data\'s classification and sensitivity. Transaction processing is used for transactional data that is mission-critical to an organization. These processes are captured and processed in real-time. Data transmission is the process of sending and receiving data. Data retention defines the duration that data must be kept. This includes both the minimum and maximum times it can remain in storage before it is destroyed.'
  },
  {
    domain: 'Data Analysis',
    type: QType.MULTI,
    stem: 'Which of the following are examples of text functions?',
    options: [
      { id: 'A', text: 'TRIM()' },
      { id: 'B', text: 'CLEAN()' },
      { id: 'C', text: 'SUM()' },
      { id: 'D', text: 'COUNT()' },
      { id: 'E', text: 'NOW() F. TODAY()' }
    ],
    correct: ['B'],
    explanation: 'OBJ 2.4 - TRIM() and CLEAN() are examples of text functions. NOW() and TODAY() are examples of date functions. SUM() and COUNT() are examples of aggregate functions.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Chuck is a data analyst that works for Dion Training. He has been tasked with determining the average time a student spends preparing for CompTIA exams on the Dion Training portal. Which of the following should Chuck use in the team database to derive this information?',
    options: [
      { id: 'A', text: 'Parsing' },
      { id: 'B', text: 'Indexing' },
      { id: 'C', text: 'Aggregate Functions' },
      { id: 'D', text: 'Date Functions' }
    ],
    correct: ['C'],
    explanation: 'OBJ 2.4 - Chuck should use aggregate functions. Aggregate functions perform calculations such as averages. Date functions use data from the date fields but wouldn\'t provide an average. Indexing is a field property setting that improves query speed and performance for fields that are commonly queried, sorted, or filtered. Parsing breaks and extracts data out of a field for use.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'April is studying for her Data+ exam that she\'ll be taking in 2 weeks. In order to prepare, she is reviewing key terms that she might be tested on. Which of the following includes measurable tasks that are needed to meet the desired end state of a project?',
    options: [
      { id: 'A', text: 'Research Question' },
      { id: 'B', text: 'Scope' },
      { id: 'C', text: 'Alternative Hypothesis' },
      { id: 'D', text: 'Null Hypothesis' }
    ],
    correct: ['B'],
    explanation: 'OBJ 3.2, 3.3 - This is an example of a scope. A scope includes measurable tasks that are needed to meet the desired end state of a project. An alternative hypothesis assumes that a relationship between two variables does exist. A null hypothesis assumes that a relationship between two variables does not exist. Research questions are the first step in preparing to research a topic. Research questions should be specific and answerable by a true or false statement.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Commas and spaces are characters intended to support the conversion data into a structured file format when exporting said data from a database. Before exporting the file out of the database, this type of file is known as what?',
    options: [
      { id: 'A', text: 'Flat File' },
      { id: 'B', text: 'JSON File' },
      { id: 'C', text: 'Delimited File' },
      { id: 'D', text: 'XML File' }
    ],
    correct: ['C'],
    explanation: 'OBJ 1.3 - This is known as a delimited file. These files have some form of character that separates each field of data from the other data fields, usually a comma, pipe, or tab. Flat files are delimited files that have been exported out of the database and no longer have a connection to them. Javascript Object Notation (JSON) is used for making web pages interactive. Extensible Markup Language (XML) is used for data transfers.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Veronica is a data analyst team lead for a consulting firm. One of her primary responsibilities is to train junior analysts on analysis and reporting. She recently gave a presentation on something that would allow a consumer to receive information on-demand. What did she teach?',
    options: [
      { id: 'A', text: 'Tactical dashboard' },
      { id: 'B', text: 'Root cause analysis' },
      { id: 'C', text: 'Self-service report' },
      { id: 'D', text: 'Compliance report' }
    ],
    correct: ['C'],
    explanation: 'OBJ 4.5 - She taught a lesson on self-service reports. A self- service report, also known as an on-demand report, is one that is run directly by the consumer. When consumers can leverage dashboards, or run their own reports from the systems the organization has purchased, they are doing self-service. Root cause analysis attempts to identify the cause of a problem that has occurred and can be a useful component of research- driven reports that seek to improve business processes. A tactical dashboard is centered on the operational details of a process or operation. These dashboards can monitor strategic business initiatives that cover long periods of time and must be monitored and measured to be effective. A compliance report is a report that must be run for compliance or regulatory reasons and includes safety reports, financial reports, and health reports.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Microsoft Excel is a very common example of which of the following?',
    options: [
      { id: 'A', text: 'Recurring report' },
      { id: 'B', text: 'Dashboard' },
      { id: 'C', text: 'Paginated report' },
      { id: 'D', text: 'Spreadsheet' }
    ],
    correct: ['D'],
    explanation: 'OBJ 3.4, 4.1 - Microsoft Excel is an example of a spreadsheet. A spreadsheet is a worksheet of data in tabular form. Spreadsheets are an ideal tool for people in an organization that need to export and work with data as part of their roles. A recurring report is set to repeatedly run on certain dates or at specific times, just like how many teams and organizations have daily, weekly, or monthly meetings. A dashboard is an interactive, visual display of information. Dashboards can be designed for mobile devices, tablets, or monitors and should be created in a way that is easily understandable. A paginated report is a multi-page report that is not suitable for display on a dashboard.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Chuck is a data analyst that works for Dion Training. He has been tasked with determining the average time a student spends preparing for CompTIA exams on the Dion Training portal. Which of the following should Chuck use in the team database to derive this information?',
    options: [
      { id: 'A', text: 'Parsing' },
      { id: 'B', text: 'Indexing' },
      { id: 'C', text: 'Aggregate Functions' },
      { id: 'D', text: 'Date Functions' }
    ],
    correct: ['D'],
    explanation: 'OBJ 2.4 - Chuck should use a date function. Date functions derive attributes from date fields, like determining the day of the week, month, or a year from a single date. Aggregate functions are written for a group of records, not just for a single record, and work with a column of data. Indexing is a field property setting that improves query speed and performance for fields that are commonly queried, sorted, or filtered. Parsing breaks and extracts data out of a field for use.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Jean is preparing a monthly report on student satisfaction at the Dion Institute of Technology. Student reviews are tied to student ID numbers, phone numbers, and email addresses which are considered Personally Identifiable Information (PII). Employees must have a demonstrated need for this data before receiving it. This is known as what?',
    options: [
      { id: 'A', text: 'Audience' },
      { id: 'B', text: 'Distribution list' },
      { id: 'C', text: 'Approval' },
      { id: 'D', text: 'Access considerations' }
    ],
    correct: ['D'],
    explanation: 'OBJ 4.1 - This is an access consideration. The approval process varies between organizations, and occasionally between departments. An analyst must also be aware of varied access permissions for the audience. It may be necessary to develop a way to provide reports for individuals who don\'t have access to raw data or other considerations. The audience is the people who will be using the data within your reports and dashboards. It is critical to understand what data the audience needs and what access they require to support the reporting process. A distribution list can also be described as an audience, the people who receive the report or dashboard. Before an analyst begins reporting on data, it is important for them to first gain approval to design the dashboard or report.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Jose is preparing a presentation for his supervisor on last quarter\'s sales. Which visual would allow him to display the distribution of data with categories of information on the x-axis and discrete numerical measurements on the y-axis?',
    options: [
      { id: 'A', text: 'Pie chart' },
      { id: 'B', text: 'Tree map' },
      { id: 'C', text: 'Bar chart' },
      { id: 'D', text: 'Column chart' }
    ],
    correct: ['D'],
    explanation: 'OBJ 4.4 - A column chart would accomplish this. When an analyst wants to display the distribution of data, it is best to choose a column chart or bar chart. These types of visualization show the total values of categories of data. A bar chart lists categories of information on the y-axis and discrete number values on the x-axis in set distances. A column chart displays the information as a bar chart but swaps axes. The x-axis lists categories of information and the y-axis represents numerical values. A tree map is a rectangle that shows the proportion of values using smaller rectangles within the larger one. A Pie chart is the most basic of all visuals and is very easy to use and understand. It is a circle broken into slices to represent percentages of information.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Which of the following are invisible characters at the end of a field of information?',
    options: [
      { id: 'A', text: 'Non-printable Characters' },
      { id: 'B', text: 'Leading Spaces' },
      { id: 'C', text: 'Trailing Spaces' },
      { id: 'D', text: 'Masking' }
    ],
    correct: ['C'],
    explanation: 'OBJ 2.2 - Trailing spaces are invisible characters at the front of a field of information. Leading spaces are invisible characters at the front of a field of information. Non-printable characters are characters that do not produce a written symbol such as a tab or space. ASCII is the acronym for the American Standard Code Information Exchange, a modern standard for electronic communication. Masking is the act of hiding the original value of data by showing something else in its place.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Which markup language is primarily used for data transfers and uses custom tags?',
    options: [
      { id: 'A', text: 'Javascript Object Notation (JSON)' },
      { id: 'B', text: 'Hypertext Markup Language (HTML)' },
      { id: 'C', text: 'Extensible Markup Language (XML)' },
      { id: 'D', text: 'Standard Generalized Markup Language (SGML)' }
    ],
    correct: ['C'],
    explanation: 'OBJ 1.3 - XML is used primarily for data transfers and uses custom tags to make tags and keys more relevant to the data the programmer is working with. SGML is considered the parent of all markup languages and defines the standard of all child markup languages such as HTML and XML. JSON is an object-oriented, event-driven programming language that allows users to interact with websites. HTML displays text to a web browser when an end-user is browsing the internet.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Bhavna is a data analyst working at Dion automotive. She has been tasked with adjusting the timeline for cloud service adoption because of budget constraints in the dealership. This is an example of which of the following?',
    options: [
      { id: 'A', text: 'Regression analysis' },
      { id: 'B', text: 'Simple linear regression' },
      { id: 'C', text: 'Key Performance Indicators (KPIs)' },
      { id: 'D', text: 'Scope creep' }
    ],
    correct: ['D'],
    explanation: 'OBJ 3.2, 3.3 - This is an example of scope creep. Scope creep is the adjustment of the outline of a project and its measurable tasks that are needed to meet a desired end state. These adjustments can cause issues in meeting deadlines or cause a gap in reaching the desired state on time and within budget. KPIs are measurements or goals used to identify if a business is achieving its objectives. KPIs can be used to monitor the status of products, processes, or sales goals for example. Simple linear regression is used to study the relationship between one dependent variable and one predictor, or independent variable. This analysis informs an analyst on which predictor may have the largest impact. Regression analysis is a statistical method used to estimate relationships between a dependent variable and one or more independent variables.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'What term defines the process of ensuring that data used in the analysis is high quality and can provide accurate results?',
    options: [
      { id: 'A', text: 'Data validation' },
      { id: 'B', text: 'Data verification' },
      { id: 'C', text: 'Quality Assurance (QA)' },
      { id: 'D', text: 'Master data management' }
    ],
    correct: ['C'],
    explanation: 'OBJ 5.3 - Quality assurance (QA), also known as data cleaning, is the process of ensuring that data used in the analysis is high quality and can provide accurate results. Master data management is the administration of an organization\'s single source of truth for its records and databases. This is likely a part of a data governance initiative for data that is critical to the organization\'s mission. Data validation is the process of confirming the type, structure, and accurate representation of data. Data verification is the process of confirming that data is accurate or true.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Dante has just created a dashboard for the Dion Shipping and Logistics Company. He wants to ensure that anyone who uses the dashboard can gain additional information about the visual they\'re looking at by hovering over a particular field with their mouse. Which of the following should he employ to enable this capability?',
    options: [
      { id: 'A', text: 'Appendix' },
      { id: 'B', text: 'Visual filters' },
      { id: 'C', text: 'Drill-through capability' },
      { id: 'D', text: 'Tooltips' }
    ],
    correct: ['D'],
    explanation: 'OBJ 4.2, 4.3 - He should use tooltips. Tooltips provide additional information to a user after hovering over a value in a visual. An appendix is used to provide additional details and information related to a report or process. Visual filters allow an analyst to provide additional row values, which can be expanded or collapsed, to provide more detail to the audience without having to create more pages or more visuals. The drill-through capability allows someone to select a value and drill down to a deeper visualization of the information that was selected. This prevents the user from needing to switch between multiple pages and filter the visual.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Jordan needs to optimize a query by reducing the total data set that is being processed. Which of the following accomplishes this?',
    options: [
      { id: 'A', text: 'Query Execution Plan' },
      { id: 'B', text: 'Subquery' },
      { id: 'C', text: 'Estimated Execution Plan' },
      { id: 'D', text: 'Actual Execution Plan' }
    ],
    correct: ['B'],
    explanation: 'OBJ 2.4 - A subquery, also known as a nested query, nests a query within another query to reduce data and improve processing performance. This accesses a smaller set of data rather than querying the whole table. A query execution plan is the order of steps in which a query is processed. An estimated execution plan is a list of possible requirements for executing a query. An actual execution plan confirms the requirements used for a query.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Marin is a recently hired data analyst at the Dion Fruit Co-op. Her supervisor, Patricia, has asked her to find out how the longer blueberry season has affected prices. What has Patricia asked Marin to do?',
    options: [
      { id: 'A', text: 'Exploratory analysis' },
      { id: 'B', text: 'Performance analysis' },
      { id: 'C', text: 'Gap analysis' },
      { id: 'D', text: 'Link analysis' }
    ],
    correct: ['D'],
    explanation: 'OBJ 3.2, 3.3 - Patricia has asked Marin to conduct a link analysis. Link analysis determines how a single data point links to other data points and focuses on relationships and connections in a database. Exploratory analysis should be done on each data set that an analyst encounters. This analysis determines the main characteristics of a data set and identifies what data should be cleaned or transformed for use. Performance analysis uses both qualitative and quantitative data to measure a particular product, outcome, or scenario against a defined objective. Gap analysis is the study of developing projects to move from a present state to the desired state.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'The data analysis team at Dion Home Appliance Company is outlining a new marketing campaign for their latest refrigerator. Which of the following would provide data from a specific period to a data analyst during the campaign?',
    options: [
      { id: 'A', text: 'Static report' },
      { id: 'B', text: 'Dynamic report' },
      { id: 'C', text: 'Point-in-time report' },
      { id: 'D', text: 'Self-service report' }
    ],
    correct: ['C'],
    explanation: 'OBJ 4.5 - A point-in-time report reflects on a specific point in time and can cover a day, week, month, year, or more. The timing is flexible and based on the needs of the analysis. A self-service report, also known as an on-demand report, is one that is run directly by the consumer. When consumers can leverage dashboards, or run their own reports from the systems the organization has purchased, they are doing self-service. A static report is a report that does not update automatically. A dynamic report, also known as a real- time report, is connected to the data and can be refreshed on-demand or regularly updated automatically.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'An author, movie studio, or musician would be most concerned about which of the following?',
    options: [
      { id: 'A', text: 'Protected Health Information (PHI)' },
      { id: 'B', text: 'Personally Identifiable Financial information (PIFI)' },
      { id: 'C', text: 'Intellectual Property (IP)' },
      { id: 'D', text: 'Data breach' }
    ],
    correct: ['C'],
    explanation: 'OBJ 5.1, 5.2 - An author, movie studio, or musician would be most concerned with Intellectual Property (IP). Intellectual property (IP) is an intangible product of human thought and creativity. Intellectual property is legally protected by copyrights, patents, trademarks, and trade secrets. Personally identifiable financial information (PIFI) is information about a consumer provided to a financial institution. PIFI includes information such as account number, credit/debit card number, personal information (such as name and contact information), and social security number. Protected health information (PHI). This is health- related data that can be used to identify an individual. PHI includes information about a person\'s past, present, or future health, and payments and data used in the operation of a healthcare business. A data breach is the loss or disclosure of private or sensitive information. This occurs when data is read, modified, or deleted without authorization.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Ramon is a senior data analyst at the Dion Textile Company. The CEO has directed her to create a business intelligence report on the most popular fabrics for men\'s athletic wear. After researching the subject, she identifies several measurable tasks which must be accomplished to enter the market. Which of the following is this an example of?',
    options: [
      { id: 'A', text: 'Research Question' },
      { id: 'B', text: 'Scope' },
      { id: 'C', text: 'Alternative Hypothesis' },
      { id: 'D', text: 'Null Hypothesis' }
    ],
    correct: ['B'],
    explanation: 'OBJ 3.2, 3.3 - This is an example of a scope. A scope includes measurable tasks that are needed to meet the desired end state of a project. Research questions are the first step in preparing to research a topic. Research questions should be specific and answerable by a true or false statement. An alternative hypothesis assumes that a relationship between two variables does exist. A null hypothesis assumes that a relationship between two variables does not exist.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Reed is a newly hired data steward at the Kane and Dion Center of Analytical Advancement. What could he consult as an authority on all informational definitions that have been agreed upon for the organization?',
    options: [
      { id: 'A', text: 'Data loss' },
      { id: 'B', text: 'Data audit' },
      { id: 'C', text: 'Master data' },
      { id: 'D', text: 'Data dictionary' }
    ],
    correct: ['D'],
    explanation: 'OBJ 5.3 - The data dictionary is a critical part of master data management and an important resource for a data analyst. This document serves as an authority on all informational definitions that have been agreed upon for the organization, as well as key metrics. This will likely contain data elements and their field attributes as well as the relationships and structure of the data. Data loss is the intentional or accidental loss of information by human error or an ineffective process. Data loss occurs when records are lost, incomplete, poorly named, or have accidentally dropped out. A data audit is a process of assessing data quality to identify whether the data can achieve its objective. Master data serves as the single source of truth for all records in an organization and is used by people across the organization for critical business decisions. This data changes less frequently and is intended for dimension data, not transactional data.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Ximena is learning about invalid data at Dion Data Science Co. Please help her select the answer which is not an example of invisible characters:',
    options: [
      { id: 'A', text: 'Non-printable Characters' },
      { id: 'B', text: 'Leading Spaces' },
      { id: 'C', text: 'Trailing Spaces' },
      { id: 'D', text: 'Masking' }
    ],
    correct: ['D'],
    explanation: 'OBJ 2.2 - Masking is the act of hiding the original value of data by showing something else in its place.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Dekwon is a database administrator for a state government tax office. He works with large volumes of records on a daily basis. His supervisor has asked that he implement a processing system that can handle vast amounts of data very accurately. The system must also save resource costs if possible. What should Dekwon implement?',
    options: [
      { id: 'A', text: 'Distributed processing' },
      { id: 'B', text: 'Real-time processing' },
      { id: 'C', text: 'Batch processing' },
      { id: 'D', text: 'Multiprocessing' }
    ],
    correct: ['C'],
    explanation: 'OBJ 5.1, 5.2 - Batch processing is used when processing a large amount of data when accuracy is more important than speed. Batch processing will process the data in batches, saving on the resource costs that are allocated for processing. Multiprocessing uses two or more processors to work on a single data set. This allows faster processing for exceptionally large data sets. This is more expensive than other processing options because of the machine expenses and overall volume or memory needed for it to function properly. Distributed processing takes large-volume data sets and distributes them across multiple servers. This is done to build redundancy into the system so that if a server fails, another server can continue its processes. Real-time processing is used for instantaneous results that are approximate. A common example of this is GPS turn-by-turn directions. This is similar to transaction processing but does not need the same level of accuracy in its results.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Which of the following optimizes data processing?',
    options: [
      { id: 'A', text: 'Query Execution Plan' },
      { id: 'B', text: 'Subquery' },
      { id: 'C', text: 'Estimated Execution Plan' },
      { id: 'D', text: 'Actual Execution Plan' }
    ],
    correct: ['B'],
    explanation: 'OBJ 2.4 - A subquery, also known as a nested query, nests a query within another query to reduce data and improve processing performance. An actual execution plan confirms the requirements used for a query. The estimated execution plan is a list of possible requirements for executing a query. This accesses a smaller set of data rather than querying the whole table. A query execution plan is the order of steps in which a query is processed.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Mateo is updating Dion University student records and must remove student IDs for individuals who have disenrolled from their programs. Which of the following can Mateo do to remove the student ID records from multiple tables simultaneously?',
    options: [
      { id: 'A', text: 'Update ID' },
      { id: 'B', text: 'Cascade Update' },
      { id: 'C', text: 'Cascade ID' },
      { id: 'D', text: 'Cascade Delete' }
    ],
    correct: ['D'],
    explanation: 'OBJ 1.1 - Mateo can use cascade delete to remove the student ID records. When a cascade delete is enforced, all records that are related to the record through that key will be automatically deleted. Update ID and cascade update are not recognized terms on the Data+ exam. Cascade update changes primary keys in related tables and does not delete them.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Tia is a PhD student working on her doctorate in molecular biology. She is graduating in less than 4 months and has already defended her dissertation. Occasionally, she reminisces about her time in graduate school, college, and high school. Her education followed a set progression. What would this progression be considered?',
    options: [
      { id: 'A', text: 'Qualitative Data' },
      { id: 'B', text: 'Educational' },
      { id: 'C', text: 'Nominal' },
      { id: 'D', text: 'Ordinal' }
    ],
    correct: ['D'],
    explanation: 'OBJ 1.2 - Tia\'s education followed an ordinal path because it had a set progression. She had to graduate high school before going to college and then finished college before getting accepted to a PhD program. Though this is a qualitative description of her education, qualitative is not the most accurate description. Educational progression is not a recognized term on the Data+ exam.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Chelsea is preparing an annual report on employee satisfaction at the Dion Institute of Technology. Data for this report is collected from an anonymous poll which is sent to every employee and then results are reviewed by executive management. The poll sent out to every employee would be considered which of the following?',
    options: [
      { id: 'A', text: 'Audience' },
      { id: 'B', text: 'Distribution list' },
      { id: 'C', text: 'Approval' },
      { id: 'D', text: 'Access considerations' }
    ],
    correct: ['B'],
    explanation: 'OBJ 4.1 - The poll sent to every employee would be considered the distribution list. The audience is the people who will be using the data within your reports and dashboards. It is critical to understand what data the audience needs and what access they require to support the reporting process. A distribution list can also be described as an audience, the people who receive the report or dashboard. Before an analyst begins reporting on data, it is important for them to first gain approval to design the dashboard or report. The approval process for data varies between organizations, and occasionally between departments. An analyst must also be aware of varied access permissions for the audience. It may be necessary to develop a way to provide reports for individuals who don\'t have access to raw data or other considerations.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Tamera is conducting a customer satisfaction survey for Dion Training and wants as much detail as possible from student responses. She is most likely going to use which of the following question types?',
    options: [
      { id: 'A', text: 'A Single Choice Question' },
      { id: 'B', text: 'A Multiple Choice Question' },
      { id: 'C', text: 'A Likert Scale Question' },
      { id: 'D', text: 'Correct answer' },
      { id: 'E', text: 'A Text Based Question' }
    ],
    correct: ['E'],
    explanation: 'OBJ 2.1 - Tamera is most likely going to use a text-based question. Text-based questions provide written feedback to a question. These questions are used when more detailed responses are needed. With a single choice question, someone could only respond with a single answer, such as yes or no. Multiple choice questions provide the opportunity to select multiple answers from a given list. A Likert scale provides someone a range of answers, such as a scale from 1 to 10.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Jerome would like to know the z-score for his height compared to other men in his geographic area. He is 73 inches tall and the average for the area is 70 inches. The standard deviation of the area is 1.5. Please calculate the z-score and select the correct answer below.',
    options: [
      { id: 'A', text: '1' },
      { id: 'B', text: '1.5' },
      { id: 'C', text: '2' },
      { id: 'D', text: '3' }
    ],
    correct: ['C'],
    explanation: 'OBJ 3.1 - The z-score is 2. Jerome\'s height is 73 inches, represented by the X value. X bar represents the average height, mean, of the area which is 70 inches. 73-70 = 3. The S value represents the standard deviation. 3/1.5=2. Thus the z-score is 2.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Estaban, a senior data analyst at Dion Electronic Superstore, is mentoring a junior data analyst during her onboarding. During the training, he describes something that is useful for comparing the size difference between an expected result and actual result of multiple variables. What is he describing?',
    options: [
      { id: 'A', text: 'Chi square test' },
      { id: 'B', text: 'Chi square statistic' },
      { id: 'C', text: 'Test of Independence' },
      { id: 'D', text: 'Goodness of fit' }
    ],
    correct: ['C'],
    explanation: 'OBJ 3.2, 3.3 - Estaban is describing a test of independence. Both goodnesses of fit and a test of independence are chi-square tests. A goodness of fit tests a single variable and the test of independence is used to test multiple variables. A chi-square test produces the chi-square statistic and is useful when analyzing data from a random sample and working with a categorical variable, like race or gender. A chi-square statistic compares the size of the difference between an expected result and the actual result. This measures how a model compares to the actual data.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'The U.S. Census is a popular example of which kind of data?',
    options: [
      { id: 'A', text: 'Publicly Available Information (PAI)' },
      { id: 'B', text: 'Aggregated Data' },
      { id: 'C', text: 'Relational Data' },
      { id: 'D', text: 'Public Data' }
    ],
    correct: ['D'],
    explanation: 'OBJ 2.1 - The U.S. census is a popular example of public data. Public data is information that has been made available to the public through legal requirements. Publicly Available Information (PAI) is information available to the public even though there is no legal requirement. An example of PAI is research from nonprofits for the benefit of the public. Aggregated data is data that has already been gathered and analyzed for analysis and reporting. An example of this could be a nonprofit polling of citizens in their country on tobacco use and then making the data available to the public after it is analyzed.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Which type of visual is the following image an example of?',
    options: [
      { id: 'A', text: 'Pie chart' },
      { id: 'B', text: 'Tree map' },
      { id: 'C', text: 'Bar chart' },
      { id: 'D', text: 'Column chart' }
    ],
    correct: ['B'],
    explanation: 'OBJ 4.4 - The image is a tree map. A tree map is a rectangle that shows the proportion of values using smaller rectangles within the larger one. A Pie chart is the most basic of all visuals and is very easy to use and understand. It is a circle broken into slices to represent percentages of information. A column chart would accomplish this. When an analyst wants to display the distribution of data, it is best to choose a column chart or bar chart. These types of visualization show the total values of categories of data. A bar chart lists categories of information on the y-axis and discrete number values on the x-axis in set distances. A column chart displays the information as a bar chart but swaps axes. The x-axis lists categories of information and the y-axis represents numerical values.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Which type of visual is the following image an example of?',
    options: [
      { id: 'A', text: 'Heat map' },
      { id: 'B', text: 'Word cloud' },
      { id: 'C', text: 'Stop word' },
      { id: 'D', text: 'Infographic' }
    ],
    correct: ['D'],
    explanation: 'OBJ 4.4 - This is an infographic. An infographic is any combination of visuals, artwork, photos, and language that tells a story about data in a compelling and appealing way. A word cloud is a visual representation of the words used in a particular body of text. Within this data, stop words appear frequently but do not need to be counted. Removing stop words leaves room for more relevant words to be counted and visualized. A heat map is any visual that uses color to draw attention to a spot, or a part of a visual that needs attention. A heat map can use color scales to draw attention to points on a geographic map.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Molly works for a regional spice and tea distributor out of a port city on the east coast of the United States. She has compiled the following dataset of the most popular teas in the state of Delaware. The names of the following teas are considered what kind of data?',
    options: [
      { id: 'A', text: 'Ordinal Data' },
      { id: 'B', text: 'Nominal Data' },
      { id: 'C', text: 'Discrete Data' },
      { id: 'D', text: 'Continuous Data' }
    ],
    correct: ['B'],
    explanation: 'OBJ 1.2 - The names of the teas are considered nominal data because they follow no natural order. Ordinal data follows a natural order, such as the progression of grades for a child\'s education. Both discrete and continuous data are numerically measurable and thus not possible answers.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Demitry is a data scientist at a regional university who is assigned to the administrative faculty of the school. He has been tasked with creating a yearly safety report for students on campus. Which of the following would he use to deliver his findings to his supervisor?',
    options: [
      { id: 'A', text: 'Operational report' },
      { id: 'B', text: 'Compliance report' },
      { id: 'C', text: 'Ad hoc report' },
      { id: 'D', text: 'Research-driven report' }
    ],
    correct: ['B'],
    explanation: 'OBJ 4.5 - He would use a compliance report. A compliance report is a report that must be run for compliance or regulatory reasons and includes safety reports, financial reports, and health reports. Ad hoc reports are generated to fulfill one-time requests and are typically time-sensitive. A research-driven report relies on research to inform and change business practices, usually to support reaching organizational goals. An operational report is used to inform on the status of a project, product, or organization. These reports can be used to measure key performance indicators (KPIs) for the organization.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Dane was just hired by a new data analytics company and a large portion of his onboarding time will be spent learning his new employer\'s tools. Which of the following would help Dane create a paginated report?',
    options: [
      { id: 'A', text: 'Tableau Prep' },
      { id: 'B', text: 'Qlik' },
      { id: 'C', text: 'IBM SPSS' },
      { id: 'D', text: 'Crystal Reports' }
    ],
    correct: ['D'],
    explanation: 'OBJ 3.4 - Although many of these tools are multifunctional, the Data+ exam defines their roles as the following: Tableau Prep is a data transformation tool. Qlik is a visualization tool. IBM SPSS is a statistical tool. Crystal Reports is a paginated reporting tool.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'The Dion Institute for Public Wellbeing has just released a publicly available report onto the web. While reading the report, a student reads a high level reminder on the page header that says "authorized for public release". This is an example of which of the following?',
    options: [
      { id: 'A', text: 'References' },
      { id: 'B', text: 'Watermark' },
      { id: 'C', text: 'Version number' },
      { id: 'D', text: 'Narrative' }
    ],
    correct: ['B'],
    explanation: 'OBJ 4.2, 4.3 - This is an example of a watermark. A watermark marks information as required for any given report. It provides a high-level reminder about the information contained in a report. Version numbers are used to document a series of reports so that a reader understands which iteration of a report they are reading. This can identify if the analysis is the most current version. A narrative is a summary of the report\'s contents and key findings. References provide information on the source of data and are normally attached to both page footers and a reference page at the end of the report.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Guillermo is an analyst at Reed and Dion Investments LLC. He will deliver a presentation on his most recent report to his team tomorrow. Which of the following would keep his presentation on track and help convey key takeaways to his audience?',
    options: [
      { id: 'A', text: 'Refresh date' },
      { id: 'B', text: 'Print Date' },
      { id: 'C', text: 'Talking points' },
      { id: 'D', text: 'Frequently Asked Questions (FAQs)' }
    ],
    correct: ['C'],
    explanation: 'OBJ 4.2, 4.3 - Talking points are useful to communicate key takeaways to an audience while delivering a presentation. Frequently Asked Questions (FAQs) address anticipated questions about the report, dashboard, or data such as refresh date and source of the information. The refresh date is the date and time that the data was last updated (if applicable). This data informs the audience that they are only seeing data that was available up to that day and time, and not anything since then. The print date of the report informs the audience when the report was printed. It\'s important to remember that the refresh date and print date for a report are not always the same.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'The Dion Institute for Public Wellbeing has just released a publicly available report. Before reading the report, a student glosses over a summary of the key findings from the institute. The student found this summary in which of the following?',
    options: [
      { id: 'A', text: 'References' },
      { id: 'B', text: 'Watermark' },
      { id: 'C', text: 'Version number' },
      { id: 'D', text: 'Narrative' }
    ],
    correct: ['D'],
    explanation: 'OBJ 4.2, 4.3 - The student found this summary in the report narrative. A narrative is a summary of the report\'s contents and key findings. Version numbers are used to document a series of reports so that a reader understands which iteration of a report they are reading. This can identify if the analysis is the most current version. A watermark marks information as required for any given report. It provides a high-level reminder about the information contained in a report. References provide information on the source of data and are normally attached to both page footers and a reference page at the end of the report.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Walter works as a data analyst at Jason Dion Fruit & Co. and must combine two data sets into a single data set. Which of the following actions should he do to accomplish this?',
    options: [
      { id: 'A', text: 'An Intermediate Append' },
      { id: 'B', text: 'Transpose Data' },
      { id: 'C', text: 'An Inline Append' },
      { id: 'D', text: 'Reduce Data' }
    ],
    correct: ['C'],
    explanation: 'OBJ 2.3 - Walter should do an inline append. An inline append will combine all selected data sets, leaving just the combined set. An intermediate append will retain the separate data sets and also create a new data set with all the combined data. Transposing data reverses its direction, so columns become rows and rows become columns. Data reduction reduces the overall volume of data in a data set.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Sasha is preparing an ad hoc report for her IT Director which will focus heavily on the quality of service for their company. The director has requested that Sasha include page numbers and the refresh date to make the report easier to read. Which function should she use to do this?',
    options: [
      { id: 'A', text: 'Text Functions' },
      { id: 'B', text: 'Merge Fields Functions' },
      { id: 'C', text: 'Logical Functions' },
      { id: 'D', text: 'System Functions' }
    ],
    correct: ['D'],
    explanation: 'OBJ 2.4 - Sasha should use a system function to automate page numbers and the refresh date. System functions track report-related information which removes the need for an analyst to manually add information on page numbers, refresh dates, report names, etc. Logical functions will check if a condition is met and return an answer based on the result. Merge fields functions combine multiple fields into a single field. Text functions manipulate data in text-based fields and can remove non-printable characters.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Which of the following confirms the resources that were used while processing a query?',
    options: [
      { id: 'A', text: 'Query Execution Plan' },
      { id: 'B', text: 'Subquery' },
      { id: 'C', text: 'Estimated Execution Plan' },
      { id: 'D', text: 'Actual Execution Plan' }
    ],
    correct: ['D'],
    explanation: 'OBJ 2.4 - An actual execution plan confirms the requirements used for a query. A subquery, also known as a nested query, nests a query within another query to reduce data and improve processing performance. The estimated execution plan is a list of possible requirements for executing a query. This accesses a smaller set of data rather than querying the whole table. A query execution plan is the order of steps in which a query is processed.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Elias is a data analyst working for a social media company. He has been given the following data on a few recent uploads from a celebrity and how many times each post was shared: 10, 20, 30, 30, 40, and 50. What is the mode of this data set?',
    options: [
      { id: 'A', text: '10' },
      { id: 'B', text: '20' },
      { id: 'C', text: '30' },
      { id: 'D', text: '50' }
    ],
    correct: ['C'],
    explanation: 'OBJ 3.1 - The mode is 30. The mode is the number that shows up the highest amount of times in the data set. The mean is the average of a set of numbers. The median is the middle number within a group of sorted numbers. Frequency is the number of times that a data point occurs in a data set.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Reed is a newly hired data steward at the Kane and Dion Center of Analytical Advancement. What could he consult as the single source of truth for all records in the organization if he needed to confirm an entry into a database?',
    options: [
      { id: 'A', text: 'Data loss' },
      { id: 'B', text: 'Data audit' },
      { id: 'C', text: 'Master data' },
      { id: 'D', text: 'Data dictionary' }
    ],
    correct: ['C'],
    explanation: 'OBJ 5.3 - Master data serves as the single source of truth for all records in an organization and is used by people across the organization for critical business decisions. This data changes less frequently and is intended for dimension data, not transactional data. The data dictionary is a critical part of master data management and an important resource for a data analyst. This document serves as an authority on all informational definitions that have been agreed upon for the organization, as well as key metrics. This will likely contain data elements and their field attributes as well as the relationships and structure of the data. Data loss is the intentional or accidental loss of information by human error or an ineffective process. Data loss occurs when records are lost, incomplete, poorly named, or have accidentally dropped out. A data audit is a process of assessing data quality to identify whether the data can achieve its objective.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'A Zoology professor named Christle is conducting a poll of her student\'s favorite animals. Zebras were selected as the class favorite because of their unique pattern. The pattern of a zebra would be considered what kind of data?',
    options: [
      { id: 'A', text: 'Ordinal Data' },
      { id: 'B', text: 'Nominal Data' },
      { id: 'C', text: 'Qualitative Dat' },
      { id: 'D', text: 'Quantitative Data' }
    ],
    correct: ['C'],
    explanation: 'OBJ 1.2 - This is an example of qualitative data because it does not have a numerical value associated with it. Nominal and ordinal data are both subcategories of qualitative data, but this question does not specifically ask about ordering animals or their patterns.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Carl is unsure which term is useful for comparing the size difference between an expected result and actual result. Please assist him and select the best answer that matches this description.',
    options: [
      { id: 'A', text: 'Chi square test' },
      { id: 'B', text: 'Chi square statistic' },
      { id: 'C', text: 'Test of Independence' },
      { id: 'D', text: 'Goodness of fit' }
    ],
    correct: ['B'],
    explanation: 'OBJ 3.2, 3.3 - The best answer is a chi-square statistic. A chi-square statistic compares the size of the difference between an expected result and the actual result. This measures how a model compares to the actual data. A chi-square test produces the chi-square statistic and is useful when analyzing data from a random sample and working with a categorical variable, like race or gender. Both a goodness of fit and a test of independence are chi-square tests. A goodness of fit tests a single variable and the test of independence is used to test multiple variables.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'A restaurant is hosting a band next weekend and expects many people to attend the concert. Which of the following is a quantitative value?',
    options: [
      { id: 'A', text: 'The band\'s name: Dion and the Jets' },
      { id: 'B', text: 'The food specials that night' },
      { id: 'C', text: 'The building\'s maximum capacity' },
      { id: 'D', text: 'The location of the restaurant' }
    ],
    correct: ['C'],
    explanation: 'OBJ 1.2 - The capacity of a building is a quantitative value with a discrete measurement. Quantitative data is defined by the fact that it is portrayed through numbers, meaning it can have a numerical value (like price) or be measured (like weight, distance, or height). Qualitative data is defined by the qualities of the data. Food specials, the band\'s name, and the location of the restaurant are all examples of qualitative data.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Harshit is a data analyst team leader who works closely with data architects and the IT director of his company. During a meeting, he is asked whether or not his team would benefit from an additional database that uses columns and rows to store data. What type of database is Harshit being asked about?',
    options: [
      { id: 'A', text: 'Perpendicular' },
      { id: 'B', text: 'Relational' },
      { id: 'C', text: 'Non-Relational' },
      { id: 'D', text: 'Nominal' }
    ],
    correct: ['B'],
    explanation: 'OBJ 1.1 - Harshit has been asked about an additional relational database because it uses columns and rows to store data. Perpendicular is not a type of database. Non-Relational databases do not use the same tabular schema of rows and columns to store data. Nominal refers to data that has no natural order, not a database structure.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Tony has been asked to identify measures of dispersion for his company\'s data set, but he\'s not confident about the following measurement: Which of the following is the difference between the highest and lowest values of a data set?',
    options: [
      { id: 'A', text: 'Variance' },
      { id: 'B', text: 'Range' },
      { id: 'C', text: 'Z-score' },
      { id: 'D', text: 'Standard deviation' }
    ],
    correct: ['B'],
    explanation: 'OBJ 3.1 - The range is the difference between the highest and lowest values of the data set. Standard deviation identifies the dispersion of data in relation to the mean of all data. A Z-score identifies how many standard deviations a data point is from the mean. Variance is the average squared distance from the mean of the data for a single data point.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Which of the following is often collected incidentally when a system is designed to capture everywhere?',
    options: [
      { id: 'A', text: 'Duplicated Data' },
      { id: 'B', text: 'Null Values' },
      { id: 'C', text: 'Invalid Data' },
      { id: 'D', text: 'Redundant Data' }
    ],
    correct: ['D'],
    explanation: 'OBJ 2.2 - Redundant data is often collected incidentally. The primary challenge an analyst will encounter when working with this is determining which record represents the absolute truth and is the most accurate.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Jake is learning about data science and comes across the following definition: Data that exists outside the rules of normal distribution. What is Jake learning about?',
    options: [
      { id: 'A', text: 'Normal distribution' },
      { id: 'B', text: 'The empirical rule' },
      { id: 'C', text: 'Parametric data' },
      { id: 'D', text: 'Non-parametric data' }
    ],
    correct: ['D'],
    explanation: 'OBJ 3.1 - Jake is learning about non-parametric data. Non- parametric data exists when the data is not within the rules of normal distribution, with values that frequently deviate from the mean. Parametric data exists when the data set is within the rules of normal distribution. A normal distribution of data follows a bell-shaped curve with the mean being the middle and all other data following three points to the left or three points to the right of the mean. The empirical rule refers to the tendency of most data points falling within three points of the mean either on the positive side or the negative side of the curve.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Cody is an entry level data analyst who just passed his certification exam. He is tremendously excited and has already been hired for a new analyst position. His boss has asked him to familiarize himself with a free to use general purpose programming language. What is he likely referring to?',
    options: [
      { id: 'A', text: 'Open source software' },
      { id: 'B', text: 'Proprietary software' },
      { id: 'C', text: 'Middleware' },
      { id: 'D', text: 'Python' }
    ],
    correct: ['D'],
    explanation: 'OBJ 3.4 - Python is an open-source, interpreted, general- purpose programming language. Middleware allows open source languages to communicate with an end system. Proprietary software is custom to the vendor. Open-source software is freely open for people to use. For example, Linux is an open source operating system and has a robust ecosystem of contributors.'
  },
  {
    domain: 'Data Analysis',
    type: QType.SINGLE,
    stem: 'Veronica is a data analyst team lead for a consulting firm. One of her primary responsibilities is to train junior analysts on analysis and reporting. She recently gave a presentation on something that must be run to adhere to government regulations. What did she teach?',
    options: [
      { id: 'A', text: 'Tactical dashboard' },
      { id: 'B', text: 'Root cause analysis' },
      { id: 'C', text: 'Self-service report' },
      { id: 'D', text: 'Compliance report' }
    ],
    correct: ['D'],
    explanation: 'OBJ 4.5 - She taught a lesson on compliance reports. A compliance report is a report that must be run for compliance or regulatory reasons and includes safety reports, financial reports, and health reports. A self-service report, also known as an on-demand report, is one that is run directly by the consumer. When consumers can leverage dashboards, or run their own reports from the systems the organization has purchased, they are doing self-service. Root cause analysis attempts to identify the cause of a problem that has occurred and can be a useful component of research-driven reports that seek to improve business processes. A tactical dashboard is centered on the operational details of a process or operation. These dashboards can monitor strategic business initiatives that cover long periods of time and must be monitored and measured to be effective.'
  }
];

async function main() {
  const vendor = await db.vendor.findUnique({ where: { slug: VENDOR_SLUG } });
  if (!vendor) throw new Error(`Vendor "${VENDOR_SLUG}" not found — run prisma seed first.`);

  const exam = await db.exam.upsert({
    where: { slug: EXAM_SLUG },
    update: {
      title: 'CompTIA Data+ (Practice Exam 2)',
      description: 'CompTIA Data+ practice set covering data concepts, mining, analysis, visualization, and governance. Sourced from a third-party practice exam PDF. Not real exam questions.',
      level: 'Associate',
      durationMinutes: 90,
      passingScore: 70,
      questionCount: 70,
      domains: DOMAINS,
      published: false
    },
    create: {
      vendorId: vendor.id,
      code: 'DA0-001-P2',
      slug: EXAM_SLUG,
      title: 'CompTIA Data+ (Practice Exam 2)',
      description: 'CompTIA Data+ practice set covering data concepts, mining, analysis, visualization, and governance. Sourced from a third-party practice exam PDF. Not real exam questions.',
      level: 'Associate',
      durationMinutes: 90,
      passingScore: 70,
      questionCount: 70,
      domains: DOMAINS,
      published: false
    }
  });

  const alreadySeeded = await db.question.count({
    where: { examId: exam.id, generatedBy: TAG }
  });
  if (alreadySeeded > 0) {
    console.log(`Already have ${alreadySeeded} questions tagged "${TAG}" — skipping.`);
    return;
  }

  let i = 0;
  for (const q of QUESTIONS) {
    await db.question.create({
      data: {
        examId: exam.id,
        domain: q.domain,
        difficulty: 3,
        type: q.type,
        stem: q.stem,
        options: q.options,
        correct: q.correct,
        explanation: q.explanation,
        references: [REF],
        status: QStatus.PUBLISHED,
        generatedBy: TAG,
        isTeaser: i < 10
      }
    });
    i++;
  }

  const total = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  console.log(`✓ ${EXAM_SLUG} — inserted ${QUESTIONS.length} questions (${total} total published)`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => db.$disconnect());
