/**
 * Top-up: PL-300 (P1-P5) to 60 questions.
 *   npx tsx scripts/seed-microsoft-pl-300-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();
const TARGET = 60;
const TAG_PREFIX = 'topup:microsoft-pl-300';
const REF = { label: 'Microsoft PL-300 exam page', url: 'https://learn.microsoft.com/en-us/credentials/certifications/exams/pl-300/' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  { domain: 'Prepare the data', type: QType.SINGLE, stem: 'Which Power BI feature transforms data during loading using the M language?', options: [{ id: 'A', text: 'Power Query Editor' }, { id: 'B', text: 'DAX' }, { id: 'C', text: 'Visualizations pane' }, { id: 'D', text: 'Bookmarks' }], correct: ['A'], explanation: 'Power Query (M) defines transformation steps applied as part of refresh. DAX is for calculations in the model.' },
  { domain: 'Prepare the data', type: QType.SINGLE, stem: 'Which Power BI feature combines multiple files into a single table by stacking rows?', options: [{ id: 'A', text: 'Append queries (Union)' }, { id: 'B', text: 'Merge queries' }, { id: 'C', text: 'Pivot' }, { id: 'D', text: 'Group by' }], correct: ['A'], explanation: 'Append (Union) stacks rows. Merge (Join) combines columns by key.' },
  { domain: 'Prepare the data', type: QType.SINGLE, stem: 'Which feature joins tables on a key column?', options: [{ id: 'A', text: 'Merge queries' }, { id: 'B', text: 'Append queries' }, { id: 'C', text: 'Pivot' }, { id: 'D', text: 'Group by' }], correct: ['A'], explanation: 'Merge produces SQL-style joins with all join types: inner, left/right outer, full outer, anti.' },
  { domain: 'Prepare the data', type: QType.SINGLE, stem: 'Which feature transposes columns into rows (wide to long)?', options: [{ id: 'A', text: 'Unpivot' }, { id: 'B', text: 'Pivot' }, { id: 'C', text: 'Group by' }, { id: 'D', text: 'Aggregate' }], correct: ['A'], explanation: 'Unpivot reshapes wide data to long. Pivot does the opposite.' },
  { domain: 'Prepare the data', type: QType.SINGLE, stem: 'Which Power Query feature splits a column with delimiter into multiple columns?', options: [{ id: 'A', text: 'Split Column by Delimiter' }, { id: 'B', text: 'Merge column' }, { id: 'C', text: 'Pivot' }, { id: 'D', text: 'Group by' }], correct: ['A'], explanation: 'Split Column by Delimiter (or by number of characters / position) breaks one column into many.' },
  { domain: 'Prepare the data', type: QType.SINGLE, stem: 'Which feature lets you parameterize a connection string or filter so it can be changed without editing the file?', options: [{ id: 'A', text: 'Parameters' }, { id: 'B', text: 'DAX measures' }, { id: 'C', text: 'Bookmarks' }, { id: 'D', text: 'Slicers' }], correct: ['A'], explanation: 'Parameters externalize connection strings, file paths, and filter values for reuse and templating.' },
  { domain: 'Prepare the data', type: QType.SINGLE, stem: 'Which feature lets you apply data prep logic created once and reused across many datasets?', options: [{ id: 'A', text: 'Dataflows' }, { id: 'B', text: 'Bookmarks' }, { id: 'C', text: 'Tooltips' }, { id: 'D', text: 'Visualizations' }], correct: ['A'], explanation: 'Dataflows store reusable Power Query logic in the service, output to Azure Data Lake Storage Gen2.' },
  { domain: 'Prepare the data', type: QType.SINGLE, stem: 'Which feature speeds up subsequent refreshes by retrieving only NEW data based on a date column?', options: [{ id: 'A', text: 'Incremental refresh' }, { id: 'B', text: 'Live connection' }, { id: 'C', text: 'Direct query' }, { id: 'D', text: 'Composite model' }], correct: ['A'], explanation: 'Incremental refresh partitions large tables and only refreshes recent partitions, reducing refresh time and memory.' },
  { domain: 'Model the data', type: QType.SINGLE, stem: 'Which schema is preferred for Power BI models for performance reasons?', options: [{ id: 'A', text: 'Star schema (fact + dimension tables)' }, { id: 'B', text: '3NF' }, { id: 'C', text: 'Snowflake (deeply normalized)' }, { id: 'D', text: 'Document model' }], correct: ['A'], explanation: 'Star schema with conformed dimensions and a single fact table works best with the VertiPaq engine.' },
  { domain: 'Model the data', type: QType.SINGLE, stem: 'What language do you use to write calculated columns and measures in Power BI?', options: [{ id: 'A', text: 'DAX (Data Analysis Expressions)' }, { id: 'B', text: 'M (Power Query)' }, { id: 'C', text: 'T-SQL' }, { id: 'D', text: 'Python' }], correct: ['A'], explanation: 'DAX is for in-model calculations. M is for ETL in Power Query.' },
  { domain: 'Model the data', type: QType.SINGLE, stem: 'Which DAX function counts distinct values of a column?', options: [{ id: 'A', text: 'DISTINCTCOUNT' }, { id: 'B', text: 'COUNT' }, { id: 'C', text: 'SUMX' }, { id: 'D', text: 'CALCULATE' }], correct: ['A'], explanation: 'DISTINCTCOUNT returns count of distinct values. COUNT counts non-blank values; SUMX iterates; CALCULATE modifies context.' },
  { domain: 'Model the data', type: QType.SINGLE, stem: 'Which DAX function modifies the filter context of a calculation?', options: [{ id: 'A', text: 'CALCULATE' }, { id: 'B', text: 'SUMX' }, { id: 'C', text: 'DIVIDE' }, { id: 'D', text: 'IF' }], correct: ['A'], explanation: 'CALCULATE evaluates an expression with modified filter context — the cornerstone of DAX.' },
  { domain: 'Model the data', type: QType.SINGLE, stem: 'Which DAX function safely divides two numbers, returning blank or alternate value on divide-by-zero?', options: [{ id: 'A', text: 'DIVIDE(numerator, denominator, [alternateResult])' }, { id: 'B', text: '/' }, { id: 'C', text: 'CALCULATE' }, { id: 'D', text: 'SUMX' }], correct: ['A'], explanation: 'DIVIDE handles divide-by-zero gracefully. The / operator throws an error.' },
  { domain: 'Model the data', type: QType.SINGLE, stem: 'Which DAX function iterates row-by-row and aggregates an expression?', options: [{ id: 'A', text: 'Iterator functions like SUMX, AVERAGEX, MAXX' }, { id: 'B', text: 'COUNTROWS only' }, { id: 'C', text: 'CALCULATE only' }, { id: 'D', text: 'BLANK' }], correct: ['A'], explanation: 'Iterators (SUMX/AVERAGEX/MAXX/MINX/COUNTX) walk a table row-by-row, evaluating the expression in row context.' },
  { domain: 'Model the data', type: QType.SINGLE, stem: 'Which Power BI relationship cardinality requires a unique key on each side?', options: [{ id: 'A', text: 'One-to-one' }, { id: 'B', text: 'One-to-many' }, { id: 'C', text: 'Many-to-many' }, { id: 'D', text: 'Many-to-one' }], correct: ['A'], explanation: '1:1 requires unique values on both sides. Most fact↔dim are 1:many. Many-to-many uses a bridge or new model relationships.' },
  { domain: 'Model the data', type: QType.SINGLE, stem: 'Which Power BI feature lets two tables relate without a unique key on either side using composite keys?', options: [{ id: 'A', text: 'Many-to-many relationships (with bidirectional filter or model relationship)' }, { id: 'B', text: 'Cross-filter direction' }, { id: 'C', text: 'DAX SUMX' }, { id: 'D', text: 'Calculated tables' }], correct: ['A'], explanation: 'Power BI supports M:M relationships directly without bridge tables when needed.' },
  { domain: 'Model the data', type: QType.SINGLE, stem: 'Which DAX time-intelligence function returns "same period last year" of a measure?', options: [{ id: 'A', text: 'SAMEPERIODLASTYEAR' }, { id: 'B', text: 'NEXTYEAR' }, { id: 'C', text: 'PARALLELPERIOD' }, { id: 'D', text: 'YEAR' }], correct: ['A'], explanation: 'SAMEPERIODLASTYEAR returns dates shifted back one year. PARALLELPERIOD is more general.' },
  { domain: 'Model the data', type: QType.SINGLE, stem: 'Which model setting is required for time-intelligence DAX functions to work correctly?', options: [{ id: 'A', text: 'A Date table marked as the date table with a contiguous date range' }, { id: 'B', text: 'No date table' }, { id: 'C', text: 'Star schema' }, { id: 'D', text: 'Composite model' }], correct: ['A'], explanation: 'Time-intelligence requires a contiguous date table with no gaps, marked as the date table.' },
  { domain: 'Visualize and analyze the data', type: QType.SINGLE, stem: 'Which Power BI visualization is best for showing the part-to-whole relationship of a few categories?', options: [{ id: 'A', text: 'Pie / Donut chart' }, { id: 'B', text: 'Line chart' }, { id: 'C', text: 'Scatter plot' }, { id: 'D', text: 'Funnel' }], correct: ['A'], explanation: 'Pie/donut charts show part-to-whole; best for ≤5 categories. Avoid for many small slices.' },
  { domain: 'Visualize and analyze the data', type: QType.SINGLE, stem: 'Which visualization is best for showing the relationship between TWO numeric variables?', options: [{ id: 'A', text: 'Scatter plot' }, { id: 'B', text: 'Pie chart' }, { id: 'C', text: 'Card' }, { id: 'D', text: 'Slicer' }], correct: ['A'], explanation: 'Scatter plots show numeric correlations.' },
  { domain: 'Visualize and analyze the data', type: QType.SINGLE, stem: 'Which Power BI feature lets users filter by clicking a UI control?', options: [{ id: 'A', text: 'Slicer' }, { id: 'B', text: 'Card' }, { id: 'C', text: 'Tooltip' }, { id: 'D', text: 'Bookmark' }], correct: ['A'], explanation: 'Slicers are interactive filters. Cards display KPIs; tooltips show hover info; bookmarks save state.' },
  { domain: 'Visualize and analyze the data', type: QType.SINGLE, stem: 'Which feature creates a snapshot of the report\'s state (filters, selections) for navigation?', options: [{ id: 'A', text: 'Bookmarks' }, { id: 'B', text: 'Slicer' }, { id: 'C', text: 'Tooltip' }, { id: 'D', text: 'Card' }], correct: ['A'], explanation: 'Bookmarks save filter/selection state and can be wired to buttons for guided navigation.' },
  { domain: 'Visualize and analyze the data', type: QType.SINGLE, stem: 'Which Power BI analytics feature decomposes a measure to show key drivers contributing to a result?', options: [{ id: 'A', text: 'Decomposition tree' }, { id: 'B', text: 'Card' }, { id: 'C', text: 'Slicer' }, { id: 'D', text: 'Q&A' }], correct: ['A'], explanation: 'Decomposition tree breaks down a measure by dimensions iteratively for root-cause analysis.' },
  { domain: 'Visualize and analyze the data', type: QType.SINGLE, stem: 'Which feature lets users ask natural-language questions and Power BI generates a viz answer?', options: [{ id: 'A', text: 'Q&A' }, { id: 'B', text: 'Slicer' }, { id: 'C', text: 'Drill-through' }, { id: 'D', text: 'Tooltip' }], correct: ['A'], explanation: 'Q&A interprets natural-language questions about the model.' },
  { domain: 'Visualize and analyze the data', type: QType.SINGLE, stem: 'Which feature lets you click a data point and navigate to a detail page filtered by that point?', options: [{ id: 'A', text: 'Drill-through' }, { id: 'B', text: 'Drill-down' }, { id: 'C', text: 'Slicer' }, { id: 'D', text: 'Tooltip' }], correct: ['A'], explanation: 'Drill-through navigates to a different page filtered to the clicked context.' },
  { domain: 'Visualize and analyze the data', type: QType.SINGLE, stem: 'Which feature controls how visuals interact when you click a value (cross-filter / cross-highlight / none)?', options: [{ id: 'A', text: 'Edit interactions' }, { id: 'B', text: 'Bookmarks' }, { id: 'C', text: 'Drill-through' }, { id: 'D', text: 'Tooltip' }], correct: ['A'], explanation: 'Edit interactions configures per-visual filtering behavior on click.' },
  { domain: 'Visualize and analyze the data', type: QType.SINGLE, stem: 'Which Power BI feature highlights significant changes in a measure over time using ML?', options: [{ id: 'A', text: 'Anomaly detection / Smart Narrative / Insights' }, { id: 'B', text: 'Slicer' }, { id: 'C', text: 'Card' }, { id: 'D', text: 'Bookmark' }], correct: ['A'], explanation: 'Power BI built-in AI surfaces anomalies, narratives, and key influencers.' },
  { domain: 'Deploy and maintain assets', type: QType.SINGLE, stem: 'Which Power BI artifact is the top-level container for related content (datasets, reports, dashboards)?', options: [{ id: 'A', text: 'Workspace' }, { id: 'B', text: 'Tile' }, { id: 'C', text: 'Slicer' }, { id: 'D', text: 'Visualization' }], correct: ['A'], explanation: 'Workspaces store related artifacts and define collaboration permissions.' },
  { domain: 'Deploy and maintain assets', type: QType.SINGLE, stem: 'Which Power BI artifact is a packaged, distributable view of workspace content for end users?', options: [{ id: 'A', text: 'App' }, { id: 'B', text: 'Dataset' }, { id: 'C', text: 'Tile' }, { id: 'D', text: 'Slicer' }], correct: ['A'], explanation: 'Apps are curated read-only experiences for consumers.' },
  { domain: 'Deploy and maintain assets', type: QType.SINGLE, stem: 'Which feature secures rows in a dataset based on user identity?', options: [{ id: 'A', text: 'Row-Level Security (RLS)' }, { id: 'B', text: 'Workspace permissions only' }, { id: 'C', text: 'Bookmarks' }, { id: 'D', text: 'Slicers' }], correct: ['A'], explanation: 'RLS uses DAX filters mapped to roles to limit which rows users see.' },
  { domain: 'Deploy and maintain assets', type: QType.SINGLE, stem: 'Which feature in Power BI Service refreshes datasets on a schedule?', options: [{ id: 'A', text: 'Scheduled refresh' }, { id: 'B', text: 'Workspace permissions' }, { id: 'C', text: 'Bookmarks' }, { id: 'D', text: 'Slicers' }], correct: ['A'], explanation: 'Scheduled refresh is configured per dataset in the service. Up to 8/day on Pro; 48/day on Premium.' },
  { domain: 'Deploy and maintain assets', type: QType.SINGLE, stem: 'Which feature lets on-prem data sources be refreshed in Power BI Service?', options: [{ id: 'A', text: 'On-premises data gateway' }, { id: 'B', text: 'Conditional Access' }, { id: 'C', text: 'Slicer' }, { id: 'D', text: 'BitLocker' }], correct: ['A'], explanation: 'The on-prem data gateway proxies queries from the cloud service to on-prem sources.' },
  { domain: 'Deploy and maintain assets', type: QType.SINGLE, stem: 'Which Power BI mode keeps data in the source and queries it on each interaction?', options: [{ id: 'A', text: 'DirectQuery' }, { id: 'B', text: 'Import' }, { id: 'C', text: 'Live connection' }, { id: 'D', text: 'Composite' }], correct: ['A'], explanation: 'DirectQuery sends queries to the source on every interaction. Import caches in VertiPaq. Live connection is for SSAS/Power BI datasets.' },
  { domain: 'Deploy and maintain assets', type: QType.SINGLE, stem: 'Which Power BI feature compares dataset performance and identifies slow visuals?', options: [{ id: 'A', text: 'Performance analyzer (in Power BI Desktop)' }, { id: 'B', text: 'Slicer' }, { id: 'C', text: 'Bookmarks' }, { id: 'D', text: 'BitLocker' }], correct: ['A'], explanation: 'Performance analyzer logs query/render times per visual to identify bottlenecks.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'microsoft-pl-300-p1', offset: 0 },
  { slug: 'microsoft-pl-300-p2', offset: 7 },
  { slug: 'microsoft-pl-300-p3', offset: 14 },
  { slug: 'microsoft-pl-300-p4', offset: 21 },
  { slug: 'microsoft-pl-300-p5', offset: 28 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: { examId: exam.id, domain: q.domain, difficulty: 3, type: q.type, stem: q.stem, options: q.options, correct: q.correct, explanation: q.explanation, references: [REF], status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up PL-300 to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
