/**
 * Top-up: DP-300 (P1-P4) to 60 questions.
 *   npx tsx scripts/seed-microsoft-dp-300-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();
const TARGET = 60;
const TAG_PREFIX = 'topup:microsoft-dp-300';
const REF = { label: 'Microsoft DP-300 exam page', url: 'https://learn.microsoft.com/en-us/credentials/certifications/exams/dp-300/' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  { domain: 'Plan and implement data platform resources', type: QType.SINGLE, stem: 'Which Azure SQL deployment provides near-100% SQL Server compatibility for lift-and-shift migrations?', options: [{ id: 'A', text: 'Azure SQL Managed Instance' }, { id: 'B', text: 'Azure SQL Database' }, { id: 'C', text: 'SQL Server on Azure VM' }, { id: 'D', text: 'Azure Synapse SQL pool' }], correct: ['A'], explanation: 'MI offers near-full surface-area parity with SQL Server, including SQL Agent and cross-DB queries.' },
  { domain: 'Plan and implement data platform resources', type: QType.SINGLE, stem: 'Which Azure SQL purchasing model lets you choose vCores and storage independently?', options: [{ id: 'A', text: 'vCore-based' }, { id: 'B', text: 'DTU-based' }, { id: 'C', text: 'BACPAC' }, { id: 'D', text: 'Express' }], correct: ['A'], explanation: 'vCore separates compute and storage. DTU bundles them as a single unit.' },
  { domain: 'Plan and implement data platform resources', type: QType.SINGLE, stem: 'Which Azure SQL service tier is best for HA with read-scale replicas and built-in elasticity?', options: [{ id: 'A', text: 'Business Critical' }, { id: 'B', text: 'Basic' }, { id: 'C', text: 'Standard' }, { id: 'D', text: 'Hyperscale (read scale-out)' }], correct: ['A'], explanation: 'Business Critical uses Always On AGs with read replicas. Hyperscale also offers read replicas + petabyte storage.' },
  { domain: 'Plan and implement data platform resources', type: QType.SINGLE, stem: 'Which Azure SQL feature scales storage to 100+ TB with rapid backup/restore via storage snapshots?', options: [{ id: 'A', text: 'Hyperscale service tier' }, { id: 'B', text: 'Basic' }, { id: 'C', text: 'Standard' }, { id: 'D', text: 'BACPAC export' }], correct: ['A'], explanation: 'Hyperscale separates compute from storage and uses snapshot-based backups.' },
  { domain: 'Plan and implement data platform resources', type: QType.SINGLE, stem: 'Which feature lets a single Azure SQL DB run on a pool of resources shared across many DBs to optimize cost?', options: [{ id: 'A', text: 'Elastic pool' }, { id: 'B', text: 'BACPAC export' }, { id: 'C', text: 'Linked server' }, { id: 'D', text: 'Failover group' }], correct: ['A'], explanation: 'Elastic pools share DTU/vCore resources across DBs with variable usage.' },
  { domain: 'Plan and implement data platform resources', type: QType.SINGLE, stem: 'Which migration path lets you move on-prem SQL Server to Azure with online migration tooling?', options: [{ id: 'A', text: 'Azure Database Migration Service / Azure SQL Migration extension' }, { id: 'B', text: 'Manual BACPAC export' }, { id: 'C', text: 'Storage account replication' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'DMS / SQL Migration extension supports online + offline migration with assessment and minimal downtime.' },
  { domain: 'Plan and implement data platform resources', type: QType.SINGLE, stem: 'Which Azure resource lets you point on-prem applications to Azure SQL via a hybrid migration without changing connection strings?', options: [{ id: 'A', text: 'Azure SQL MI link feature (or aliasing)' }, { id: 'B', text: 'Azure DNS only' }, { id: 'C', text: 'Storage account' }, { id: 'D', text: 'Bastion' }], correct: ['A'], explanation: 'MI Link replicates SQL Server to MI and supports failover scenarios.' },
  { domain: 'Implement a secure environment', type: QType.SINGLE, stem: 'Which feature encrypts a database at rest by default in Azure SQL?', options: [{ id: 'A', text: 'Transparent Data Encryption (TDE)' }, { id: 'B', text: 'Always Encrypted' }, { id: 'C', text: 'Row-Level Security' }, { id: 'D', text: 'Dynamic Data Masking' }], correct: ['A'], explanation: 'TDE is on by default for Azure SQL DB / MI, encrypting data and log files at rest.' },
  { domain: 'Implement a secure environment', type: QType.SINGLE, stem: 'Which Azure SQL feature encrypts SPECIFIC columns so DBAs cannot see plaintext?', options: [{ id: 'A', text: 'Always Encrypted' }, { id: 'B', text: 'TDE' }, { id: 'C', text: 'Row-Level Security' }, { id: 'D', text: 'Dynamic Data Masking' }], correct: ['A'], explanation: 'Always Encrypted protects sensitive columns from privileged DB users by performing crypto in the client driver.' },
  { domain: 'Implement a secure environment', type: QType.SINGLE, stem: 'Which feature filters rows users see based on a security predicate function?', options: [{ id: 'A', text: 'Row-Level Security' }, { id: 'B', text: 'Always Encrypted' }, { id: 'C', text: 'TDE' }, { id: 'D', text: 'Auditing' }], correct: ['A'], explanation: 'RLS uses inline TVFs to filter rows automatically per session/user.' },
  { domain: 'Implement a secure environment', type: QType.SINGLE, stem: 'Which feature obscures sensitive columns in query output without changing data at rest?', options: [{ id: 'A', text: 'Dynamic Data Masking' }, { id: 'B', text: 'Always Encrypted' }, { id: 'C', text: 'TDE' }, { id: 'D', text: 'Row-Level Security' }], correct: ['A'], explanation: 'DDM masks columns at query time for non-privileged users.' },
  { domain: 'Implement a secure environment', type: QType.SINGLE, stem: 'Which Azure SQL feature lets you authenticate to the database using Microsoft Entra accounts?', options: [{ id: 'A', text: 'Microsoft Entra (Azure AD) authentication' }, { id: 'B', text: 'Local SQL logins only' }, { id: 'C', text: 'Anonymous' }, { id: 'D', text: 'NTLM' }], correct: ['A'], explanation: 'Entra auth is recommended over SQL logins; supports MFA, conditional access, and groups.' },
  { domain: 'Implement a secure environment', type: QType.SINGLE, stem: 'Which feature lets Azure SQL DB log T-SQL events for audit?', options: [{ id: 'A', text: 'SQL Auditing (to Storage / Log Analytics / Event Hubs)' }, { id: 'B', text: 'Activity Log only' }, { id: 'C', text: 'NSG flow logs' }, { id: 'D', text: 'Network Watcher' }], correct: ['A'], explanation: 'SQL Audit captures DB events; outputs to Storage (immutable) / Log Analytics (KQL queries) / Event Hubs (downstream SIEM).' },
  { domain: 'Implement a secure environment', type: QType.SINGLE, stem: 'Which Defender plan protects Azure SQL/MI/SQL Server on machines from threats?', options: [{ id: 'A', text: 'Microsoft Defender for SQL' }, { id: 'B', text: 'Defender for Storage' }, { id: 'C', text: 'Defender for Endpoint' }, { id: 'D', text: 'Defender for Container' }], correct: ['A'], explanation: 'Defender for SQL detects suspicious queries, vulnerabilities, and surfaces recommendations.' },
  { domain: 'Implement a secure environment', type: QType.SINGLE, stem: 'Which Azure SQL feature provides VNet-restricted access via Private Endpoints?', options: [{ id: 'A', text: 'Private Endpoint with public network access disabled' }, { id: 'B', text: 'Default public access' }, { id: 'C', text: 'NSG flow logs' }, { id: 'D', text: 'Bastion' }], correct: ['A'], explanation: 'Private Endpoints expose SQL DB on a private IP in your VNet; combined with disabling public access for full isolation.' },
  { domain: 'Monitor, configure, and optimize database resources', type: QType.SINGLE, stem: 'Which DMV shows currently executing queries and their wait stats?', options: [{ id: 'A', text: 'sys.dm_exec_requests + sys.dm_os_waiting_tasks' }, { id: 'B', text: 'sys.objects' }, { id: 'C', text: 'sys.databases' }, { id: 'D', text: 'sys.indexes' }], correct: ['A'], explanation: 'Those DMVs show active sessions, waits, and resource usage.' },
  { domain: 'Monitor, configure, and optimize database resources', type: QType.SINGLE, stem: 'Which feature in Azure SQL captures query plans and runtime stats automatically?', options: [{ id: 'A', text: 'Query Store' }, { id: 'B', text: 'Profiler' }, { id: 'C', text: 'BACPAC' }, { id: 'D', text: 'Resource Governor' }], correct: ['A'], explanation: 'Query Store records plan history and runtime metrics, enabling regression detection and forced plans.' },
  { domain: 'Monitor, configure, and optimize database resources', type: QType.SINGLE, stem: 'Which Azure SQL feature automatically tunes performance by recommending indexes and forcing plans?', options: [{ id: 'A', text: 'Automatic Tuning' }, { id: 'B', text: 'Resource Governor' }, { id: 'C', text: 'Linked servers' }, { id: 'D', text: 'BACPAC' }], correct: ['A'], explanation: 'Automatic tuning can create/drop indexes and force last-good-plan when regressions are detected.' },
  { domain: 'Monitor, configure, and optimize database resources', type: QType.SINGLE, stem: 'Which feature provides a recommendations dashboard for index, query, and schema improvements?', options: [{ id: 'A', text: 'Performance Recommendations / Intelligent Insights' }, { id: 'B', text: 'Service Health' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'Performance Insights surface tuning suggestions; Intelligent Insights uses AI to detect anomalies.' },
  { domain: 'Monitor, configure, and optimize database resources', type: QType.SINGLE, stem: 'Which T-SQL command updates statistics on a table?', options: [{ id: 'A', text: 'UPDATE STATISTICS <table> WITH FULLSCAN' }, { id: 'B', text: 'EXEC sp_help' }, { id: 'C', text: 'BACKUP DATABASE' }, { id: 'D', text: 'ALTER TABLE' }], correct: ['A'], explanation: 'UPDATE STATISTICS refreshes column distribution histograms used by the query optimizer.' },
  { domain: 'Monitor, configure, and optimize database resources', type: QType.SINGLE, stem: 'Which index is best for OLAP-style queries scanning large fact tables?', options: [{ id: 'A', text: 'Clustered columnstore index (CCI)' }, { id: 'B', text: 'Clustered B-tree' }, { id: 'C', text: 'Hash index' }, { id: 'D', text: 'Spatial index' }], correct: ['A'], explanation: 'CCI compresses columnar data and is ideal for analytic workloads.' },
  { domain: 'Monitor, configure, and optimize database resources', type: QType.SINGLE, stem: 'Which T-SQL feature creates a temporary in-memory snapshot of data, useful for debugging slow queries?', options: [{ id: 'A', text: 'EXPLAIN / Live Query Statistics + Estimated/Actual Plan' }, { id: 'B', text: 'BACPAC' }, { id: 'C', text: 'Resource Governor' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'Use SET STATISTICS TIME/IO ON, Actual Execution Plan, or Live Query Statistics to diagnose queries.' },
  { domain: 'Configure and manage automation of tasks', type: QType.SINGLE, stem: 'Which Azure feature schedules T-SQL or maintenance jobs in Azure SQL Managed Instance?', options: [{ id: 'A', text: 'SQL Agent (built into MI)' }, { id: 'B', text: 'BACPAC' }, { id: 'C', text: 'Cron in Azure Functions' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'MI ships with SQL Agent. Azure SQL DB doesn\'t have SQL Agent; use Elastic Jobs or Azure Functions instead.' },
  { domain: 'Configure and manage automation of tasks', type: QType.SINGLE, stem: 'Which Azure feature schedules T-SQL across many Azure SQL DBs (e.g., for index maintenance)?', options: [{ id: 'A', text: 'Elastic Jobs (Azure SQL DB)' }, { id: 'B', text: 'SQL Agent (Azure SQL DB)' }, { id: 'C', text: 'BACPAC' }, { id: 'D', text: 'Storage replication' }], correct: ['A'], explanation: 'Elastic Jobs run T-SQL across pools/servers/groups of Azure SQL DBs.' },
  { domain: 'Configure and manage automation of tasks', type: QType.SINGLE, stem: 'Which Azure DevOps feature can deploy database schema changes via DACPAC during CI/CD?', options: [{ id: 'A', text: 'Azure SQL Database Deployment task / SQL Server Database project (DACPAC)' }, { id: 'B', text: 'BACPAC export only' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'DACPAC compiled from SSDT projects deploys schema diffs to target DBs.' },
  { domain: 'Configure and manage automation of tasks', type: QType.SINGLE, stem: 'Which feature lets you parameterize database deployments across environments via templates?', options: [{ id: 'A', text: 'ARM/Bicep templates or Terraform with parameters' }, { id: 'B', text: 'Manual creation' }, { id: 'C', text: 'NSG' }, { id: 'D', text: 'BACPAC' }], correct: ['A'], explanation: 'Bicep/ARM/Terraform define infrastructure declaratively with environment-specific parameters.' },
  { domain: 'Plan and configure a high availability and disaster recovery (HADR) environment', type: QType.SINGLE, stem: 'Which Azure SQL feature replicates a primary database to up to 4 readable secondaries in different regions?', options: [{ id: 'A', text: 'Active geo-replication / Failover groups' }, { id: 'B', text: 'BACPAC' }, { id: 'C', text: 'Storage replication only' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'Active geo-replication maintains async replicas; Failover Groups bundle databases for unified failover with listener endpoints.' },
  { domain: 'Plan and configure a high availability and disaster recovery (HADR) environment', type: QType.SINGLE, stem: 'Which RTO would Failover Groups in Azure SQL DB provide for outages in primary region?', options: [{ id: 'A', text: 'Less than 1 hour with manual or auto failover' }, { id: 'B', text: 'Days' }, { id: 'C', text: 'Weeks' }, { id: 'D', text: 'Months' }], correct: ['A'], explanation: 'Failover Groups provide RTO of <1 hour with automated failover policies (graceful or unplanned).' },
  { domain: 'Plan and configure a high availability and disaster recovery (HADR) environment', type: QType.SINGLE, stem: 'Which Azure SQL backup feature retains backups beyond the standard short-term retention for compliance?', options: [{ id: 'A', text: 'Long-term retention (LTR)' }, { id: 'B', text: 'Geo-replication only' }, { id: 'C', text: 'BACPAC export' }, { id: 'D', text: 'Storage soft-delete' }], correct: ['A'], explanation: 'LTR keeps weekly/monthly/yearly backups for up to 10 years.' },
  { domain: 'Plan and configure a high availability and disaster recovery (HADR) environment', type: QType.SINGLE, stem: 'Which restore option lets you recover a deleted Azure SQL database within the retention window?', options: [{ id: 'A', text: 'Point-in-Time Restore (PITR) from automated backups' }, { id: 'B', text: 'BACPAC import' }, { id: 'C', text: 'Storage account replication' }, { id: 'D', text: 'Azure Backup vault' }], correct: ['A'], explanation: 'PITR uses retained transaction-log backups. Default retention is 7 days, configurable up to 35.' },
  { domain: 'Plan and configure a high availability and disaster recovery (HADR) environment', type: QType.SINGLE, stem: 'Which approach is best for HA in Azure SQL Managed Instance?', options: [{ id: 'A', text: 'Business Critical tier with built-in Always On + zone redundancy' }, { id: 'B', text: 'Single VM' }, { id: 'C', text: 'NSG' }, { id: 'D', text: 'BACPAC export' }], correct: ['A'], explanation: 'BC tier uses Always On AGs across multiple replicas; zone redundancy spreads them across availability zones.' },
  { domain: 'Plan and configure a high availability and disaster recovery (HADR) environment', type: QType.SINGLE, stem: 'Which T-SQL command initiates a manual full backup in SQL Server on Azure VM (not in Azure SQL DB)?', options: [{ id: 'A', text: 'BACKUP DATABASE <name> TO DISK = ...' }, { id: 'B', text: 'EXEC sp_help' }, { id: 'C', text: 'CREATE DATABASE' }, { id: 'D', text: 'BCP' }], correct: ['A'], explanation: 'In SQL Server (IaaS), BACKUP DATABASE creates a backup file. In Azure SQL DB / MI, backups are automatic.' },
  { domain: 'Plan and configure a high availability and disaster recovery (HADR) environment', type: QType.SINGLE, stem: 'Which Azure feature backs up SQL Server on Azure VM to a Recovery Services vault?', options: [{ id: 'A', text: 'Azure Backup for SQL Server in Azure VM' }, { id: 'B', text: 'BACPAC export' }, { id: 'C', text: 'NSG' }, { id: 'D', text: 'Conditional Access' }], correct: ['A'], explanation: 'Azure Backup integrates with SQL Server in VMs for managed, scheduled backups.' },
  { domain: 'Plan and configure a high availability and disaster recovery (HADR) environment', type: QType.SINGLE, stem: 'Which Azure feature is recommended for cross-region DR of Azure SQL Hyperscale databases?', options: [{ id: 'A', text: 'Active geo-replication (Hyperscale supports geo-replication for DR)' }, { id: 'B', text: 'Manual BACPAC' }, { id: 'C', text: 'Storage account redundancy alone' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'Hyperscale supports active geo-replication for cross-region DR.' },
  { domain: 'Plan and configure a high availability and disaster recovery (HADR) environment', type: QType.SINGLE, stem: 'Which Azure SQL feature creates a copy of a database in another server / region for testing?', options: [{ id: 'A', text: 'Database copy (CREATE DATABASE ... AS COPY OF / Copy-AzSqlDatabase)' }, { id: 'B', text: 'NSG' }, { id: 'C', text: 'BACPAC import only' }, { id: 'D', text: 'Storage replication' }], correct: ['A'], explanation: 'Database COPY creates a transactionally consistent copy; faster than BACPAC for large DBs.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'microsoft-dp-300-p1', offset: 0 },
  { slug: 'microsoft-dp-300-p2', offset: 12 },
  { slug: 'microsoft-dp-300-p3', offset: 24 },
  { slug: 'microsoft-dp-300-p4', offset: 0 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: { examId: exam.id, domain: q.domain, difficulty: 3, type: q.type, stem: q.stem, options: q.options, correct: q.correct, explanation: q.explanation, references: [REF], status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up DP-300 to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
