/**
 * Top-up: AWS DOP-C02 (P1-P7) to 60 questions.
 *   npx tsx scripts/seed-aws-dop-c02-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();
const TARGET = 60;
const TAG_PREFIX = 'topup:aws-dop-c02';
const REF = { label: 'AWS Certified DevOps Engineer - Professional (DOP-C02) exam guide', url: 'https://aws.amazon.com/certification/certified-devops-engineer-professional/' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  { domain: 'SDLC Automation', type: QType.SINGLE, stem: 'Which AWS service is the managed CI/CD pipeline orchestrator that integrates with CodeCommit/Build/Deploy?', options: [{ id: 'A', text: 'AWS CodePipeline' }, { id: 'B', text: 'AWS CodeStar only' }, { id: 'C', text: 'AWS CloudFormation' }, { id: 'D', text: 'AWS Step Functions' }], correct: ['A'], explanation: 'CodePipeline orchestrates source/build/test/deploy stages with parallelism and approvals.' },
  { domain: 'SDLC Automation', type: QType.SINGLE, stem: 'Which AWS service runs build jobs in containers with on-demand compute?', options: [{ id: 'A', text: 'AWS CodeBuild' }, { id: 'B', text: 'AWS CodeDeploy' }, { id: 'C', text: 'AWS CodeArtifact' }, { id: 'D', text: 'AWS X-Ray' }], correct: ['A'], explanation: 'CodeBuild runs builds in managed containers via buildspec.yml. Per-minute pricing.' },
  { domain: 'SDLC Automation', type: QType.SINGLE, stem: 'Which AWS service deploys application code to EC2/Lambda/ECS with rolling and blue-green strategies?', options: [{ id: 'A', text: 'AWS CodeDeploy' }, { id: 'B', text: 'AWS CodeBuild' }, { id: 'C', text: 'AWS CloudFormation' }, { id: 'D', text: 'AWS CodeCommit' }], correct: ['A'], explanation: 'CodeDeploy handles deployment to EC2 (rolling, in-place), Lambda (canary, linear), and ECS (blue/green via CodeDeploy hooks).' },
  { domain: 'SDLC Automation', type: QType.SINGLE, stem: 'Which deployment strategy in CodeDeploy gradually shifts traffic to the new version of a Lambda function?', options: [{ id: 'A', text: 'Linear or Canary deployment' }, { id: 'B', text: 'AllAtOnce only' }, { id: 'C', text: 'Snapshot' }, { id: 'D', text: 'Replicate' }], correct: ['A'], explanation: 'CodeDeploy provides Linear (n%/X minutes) and Canary (small initial slice, then 100%) for Lambda traffic shifting.' },
  { domain: 'SDLC Automation', type: QType.SINGLE, stem: 'Which AWS feature lets you run pipelines triggered by Git events using a managed service?', options: [{ id: 'A', text: 'CodePipeline source action with CodeCommit / GitHub / Bitbucket' }, { id: 'B', text: 'Manual triggers only' }, { id: 'C', text: 'CloudFront' }, { id: 'D', text: 'X-Ray' }], correct: ['A'], explanation: 'Source actions trigger pipelines on push events from various Git providers.' },
  { domain: 'SDLC Automation', type: QType.SINGLE, stem: 'Which AWS service stores private package artifacts (npm, Maven, NuGet, PyPI)?', options: [{ id: 'A', text: 'AWS CodeArtifact' }, { id: 'B', text: 'AWS S3 alone' }, { id: 'C', text: 'CodeCommit' }, { id: 'D', text: 'CodeDeploy' }], correct: ['A'], explanation: 'CodeArtifact provides managed package repositories with upstream proxy support.' },
  { domain: 'SDLC Automation', type: QType.SINGLE, stem: 'Which mechanism enforces a manual approval before a pipeline stage proceeds?', options: [{ id: 'A', text: 'CodePipeline manual approval action' }, { id: 'B', text: 'CodeCommit branch protection' }, { id: 'C', text: 'CloudWatch Logs' }, { id: 'D', text: 'X-Ray' }], correct: ['A'], explanation: 'Approval actions in CodePipeline pause execution until a designated user approves via console/SDK.' },
  { domain: 'Configuration Management and IaC', type: QType.SINGLE, stem: 'Which AWS service provides declarative IaC using JSON/YAML templates?', options: [{ id: 'A', text: 'AWS CloudFormation' }, { id: 'B', text: 'AWS CodeDeploy' }, { id: 'C', text: 'AWS Config' }, { id: 'D', text: 'AWS Backup' }], correct: ['A'], explanation: 'CloudFormation deploys stacks declaratively from templates. CDK is the typed-language layer atop CloudFormation.' },
  { domain: 'Configuration Management and IaC', type: QType.SINGLE, stem: 'Which CloudFormation feature deploys a single stack into multiple accounts and regions?', options: [{ id: 'A', text: 'StackSets' }, { id: 'B', text: 'Change sets' }, { id: 'C', text: 'Drift detection' }, { id: 'D', text: 'Nested stacks only' }], correct: ['A'], explanation: 'StackSets centrally manage stack instances across multiple accounts/regions, integrated with AWS Organizations.' },
  { domain: 'Configuration Management and IaC', type: QType.SINGLE, stem: 'Which CloudFormation feature lets you preview changes before applying?', options: [{ id: 'A', text: 'Change sets' }, { id: 'B', text: 'StackSets' }, { id: 'C', text: 'Drift detection' }, { id: 'D', text: 'Custom resources' }], correct: ['A'], explanation: 'Change sets show planned modifications before execute, similar to Terraform plan.' },
  { domain: 'Configuration Management and IaC', type: QType.SINGLE, stem: 'Which CloudFormation feature detects when resources are modified outside of CFN?', options: [{ id: 'A', text: 'Drift detection' }, { id: 'B', text: 'Change sets' }, { id: 'C', text: 'Nested stacks' }, { id: 'D', text: 'Stack policies' }], correct: ['A'], explanation: 'Drift detection identifies resources whose actual config differs from the template.' },
  { domain: 'Configuration Management and IaC', type: QType.SINGLE, stem: 'Which AWS service enforces compliance and configuration rules across resources?', options: [{ id: 'A', text: 'AWS Config' }, { id: 'B', text: 'AWS CloudFormation' }, { id: 'C', text: 'AWS Backup' }, { id: 'D', text: 'AWS X-Ray' }], correct: ['A'], explanation: 'AWS Config records resource state and evaluates rules; non-compliant findings can trigger automated remediation via SSM.' },
  { domain: 'Configuration Management and IaC', type: QType.SINGLE, stem: 'Which AWS service provides typed, OO IaC compiling to CloudFormation?', options: [{ id: 'A', text: 'AWS CDK (Cloud Development Kit)' }, { id: 'B', text: 'AWS Backup' }, { id: 'C', text: 'AWS X-Ray' }, { id: 'D', text: 'AWS Compute Optimizer' }], correct: ['A'], explanation: 'CDK lets you author infrastructure in TypeScript/Python/Java/C#/Go and synthesizes CloudFormation templates.' },
  { domain: 'Configuration Management and IaC', type: QType.SINGLE, stem: 'Which AWS service provides patching, run command, parameter store, and OpsCenter for managed instances?', options: [{ id: 'A', text: 'AWS Systems Manager (SSM)' }, { id: 'B', text: 'AWS CloudFormation' }, { id: 'C', text: 'AWS Lambda' }, { id: 'D', text: 'AWS CodeDeploy' }], correct: ['A'], explanation: 'SSM is the operations hub: Run Command, State Manager, Patch Manager, Parameter Store, OpsCenter, Session Manager.' },
  { domain: 'Resilient Cloud Solutions', type: QType.SINGLE, stem: 'Which AWS feature replicates DynamoDB tables across regions for low-latency reads/writes globally?', options: [{ id: 'A', text: 'DynamoDB Global Tables' }, { id: 'B', text: 'Cross-region snapshot' }, { id: 'C', text: 'DAX' }, { id: 'D', text: 'Backup vaults' }], correct: ['A'], explanation: 'Global Tables replicate DynamoDB across regions with multi-master writes and last-writer-wins.' },
  { domain: 'Resilient Cloud Solutions', type: QType.SINGLE, stem: 'Which AWS feature recovers an EC2 workload to another region using continuous block-level replication?', options: [{ id: 'A', text: 'AWS Elastic Disaster Recovery (DRS)' }, { id: 'B', text: 'EBS snapshots manual copy' }, { id: 'C', text: 'AWS Backup vaults' }, { id: 'D', text: 'Lambda deployments' }], correct: ['A'], explanation: 'DRS replicates source servers to AWS for fast failover with sub-second RPO.' },
  { domain: 'Resilient Cloud Solutions', type: QType.SINGLE, stem: 'Which Aurora feature offers a globally-distributed cluster with cross-region reads and DR?', options: [{ id: 'A', text: 'Aurora Global Database' }, { id: 'B', text: 'Multi-AZ' }, { id: 'C', text: 'Read replicas (single region)' }, { id: 'D', text: 'Backup vault' }], correct: ['A'], explanation: 'Aurora Global Database replicates a primary cluster to up to 5 secondary regions with sub-second lag.' },
  { domain: 'Resilient Cloud Solutions', type: QType.SINGLE, stem: 'Which AWS feature scales an application across AZs automatically when CPU rises?', options: [{ id: 'A', text: 'EC2 Auto Scaling group with target-tracking scaling policy' }, { id: 'B', text: 'Lambda concurrency limit' }, { id: 'C', text: 'NSG' }, { id: 'D', text: 'BitLocker' }], correct: ['A'], explanation: 'ASGs scale instances based on CloudWatch metrics; target-tracking adjusts capacity to keep a metric near a target.' },
  { domain: 'Resilient Cloud Solutions', type: QType.SINGLE, stem: 'Which AWS deployment pattern minimizes risk by maintaining two identical environments and switching traffic?', options: [{ id: 'A', text: 'Blue/Green deployment' }, { id: 'B', text: 'In-place rolling' }, { id: 'C', text: 'AllAtOnce' }, { id: 'D', text: 'Snapshot rollback' }], correct: ['A'], explanation: 'Blue/Green keeps the old env until cutover; rollback is fast by switching back.' },
  { domain: 'Monitoring and Logging', type: QType.SINGLE, stem: 'Which AWS service collects metrics, logs, and dashboards across AWS resources?', options: [{ id: 'A', text: 'Amazon CloudWatch' }, { id: 'B', text: 'AWS Config' }, { id: 'C', text: 'AWS Trusted Advisor' }, { id: 'D', text: 'AWS X-Ray (separate)' }], correct: ['A'], explanation: 'CloudWatch ingests metrics/logs/events with dashboards, alarms, and Insights queries.' },
  { domain: 'Monitoring and Logging', type: QType.SINGLE, stem: 'Which AWS service traces requests through distributed services for latency analysis?', options: [{ id: 'A', text: 'AWS X-Ray' }, { id: 'B', text: 'AWS Config' }, { id: 'C', text: 'CloudFormation' }, { id: 'D', text: 'CloudWatch alarms' }], correct: ['A'], explanation: 'X-Ray collects distributed traces and produces service maps and latency analysis.' },
  { domain: 'Monitoring and Logging', type: QType.SINGLE, stem: 'Which CloudWatch feature lets you query logs with SQL-like syntax?', options: [{ id: 'A', text: 'CloudWatch Logs Insights' }, { id: 'B', text: 'Athena' }, { id: 'C', text: 'CloudWatch Metrics' }, { id: 'D', text: 'CloudWatch Alarms' }], correct: ['A'], explanation: 'Logs Insights provides ad-hoc queries with a SQL-like syntax over log groups.' },
  { domain: 'Monitoring and Logging', type: QType.SINGLE, stem: 'Which AWS service centralizes audit logs of API calls (who did what) for compliance review?', options: [{ id: 'A', text: 'AWS CloudTrail' }, { id: 'B', text: 'AWS Config' }, { id: 'C', text: 'CloudWatch Logs' }, { id: 'D', text: 'X-Ray' }], correct: ['A'], explanation: 'CloudTrail records all account API calls (data and management events) for governance and forensics.' },
  { domain: 'Monitoring and Logging', type: QType.SINGLE, stem: 'Which AWS service provides anomaly detection on CloudWatch metrics using ML?', options: [{ id: 'A', text: 'CloudWatch Anomaly Detection' }, { id: 'B', text: 'AWS Comprehend' }, { id: 'C', text: 'AWS Macie' }, { id: 'D', text: 'X-Ray' }], correct: ['A'], explanation: 'CloudWatch Anomaly Detection learns baselines and flags deviations.' },
  { domain: 'Monitoring and Logging', type: QType.SINGLE, stem: 'Which AWS service provides synthetic monitoring (canaries) of HTTP endpoints?', options: [{ id: 'A', text: 'CloudWatch Synthetics (canaries)' }, { id: 'B', text: 'AWS Backup' }, { id: 'C', text: 'CodeBuild' }, { id: 'D', text: 'X-Ray' }], correct: ['A'], explanation: 'Canaries are scheduled scripts (Node/Python) that probe URLs and emit metrics/alerts.' },
  { domain: 'Incident and Event Response', type: QType.SINGLE, stem: 'Which AWS service triggers automation in response to events on a schedule or via patterns?', options: [{ id: 'A', text: 'Amazon EventBridge' }, { id: 'B', text: 'CloudFormation' }, { id: 'C', text: 'CloudFront' }, { id: 'D', text: 'AWS Direct Connect' }], correct: ['A'], explanation: 'EventBridge routes events from AWS services and SaaS partners to targets; CloudWatch Events is its predecessor.' },
  { domain: 'Incident and Event Response', type: QType.SINGLE, stem: 'Which AWS service provides notification fan-out via topics (email, SMS, Lambda)?', options: [{ id: 'A', text: 'Amazon SNS' }, { id: 'B', text: 'Amazon SQS' }, { id: 'C', text: 'Amazon Kinesis' }, { id: 'D', text: 'Amazon EventBridge' }], correct: ['A'], explanation: 'SNS is pub/sub. SQS is queueing; Kinesis is streaming; EventBridge is event routing.' },
  { domain: 'Incident and Event Response', type: QType.SINGLE, stem: 'Which AWS feature lets you remediate non-compliant resources automatically?', options: [{ id: 'A', text: 'AWS Config rule + SSM Automation document' }, { id: 'B', text: 'CloudFormation drift only' }, { id: 'C', text: 'CodeDeploy' }, { id: 'D', text: 'CodeArtifact' }], correct: ['A'], explanation: 'Config rules detect; SSM Automation runs corrective runbooks; combined for closed-loop remediation.' },
  { domain: 'Incident and Event Response', type: QType.SINGLE, stem: 'Which AWS service detects threats based on VPC Flow Logs, DNS logs, and CloudTrail?', options: [{ id: 'A', text: 'Amazon GuardDuty' }, { id: 'B', text: 'AWS Macie' }, { id: 'C', text: 'AWS Inspector' }, { id: 'D', text: 'AWS Backup' }], correct: ['A'], explanation: 'GuardDuty continuously analyzes flow/DNS/CloudTrail to detect compromise indicators.' },
  { domain: 'Security and Compliance', type: QType.SINGLE, stem: 'Which AWS service centrally manages secrets like database passwords and API keys with rotation?', options: [{ id: 'A', text: 'AWS Secrets Manager' }, { id: 'B', text: 'SSM Parameter Store SecureString' }, { id: 'C', text: 'KMS' }, { id: 'D', text: 'IAM Access Keys' }], correct: ['A'], explanation: 'Secrets Manager stores secrets with built-in rotation. SSM SecureString is similar but lacks built-in rotation.' },
  { domain: 'Security and Compliance', type: QType.SINGLE, stem: 'Which AWS service scans EC2 / ECR for vulnerabilities continuously?', options: [{ id: 'A', text: 'Amazon Inspector' }, { id: 'B', text: 'GuardDuty' }, { id: 'C', text: 'Macie' }, { id: 'D', text: 'WAF' }], correct: ['A'], explanation: 'Inspector v2 continuously scans EC2 and ECR images for CVEs.' },
  { domain: 'Security and Compliance', type: QType.SINGLE, stem: 'Which AWS service classifies and protects S3 data containing PII?', options: [{ id: 'A', text: 'Amazon Macie' }, { id: 'B', text: 'GuardDuty' }, { id: 'C', text: 'Inspector' }, { id: 'D', text: 'AWS Backup' }], correct: ['A'], explanation: 'Macie uses ML to detect sensitive data in S3 buckets and report findings.' },
  { domain: 'Security and Compliance', type: QType.SINGLE, stem: 'Which AWS service provides centralized security dashboard aggregating findings from GuardDuty, Inspector, Macie, etc.?', options: [{ id: 'A', text: 'AWS Security Hub' }, { id: 'B', text: 'CloudWatch' }, { id: 'C', text: 'CloudTrail' }, { id: 'D', text: 'Trusted Advisor' }], correct: ['A'], explanation: 'Security Hub centralizes findings, runs CIS/PCI checks, and supports automation actions.' },
  { domain: 'Security and Compliance', type: QType.SINGLE, stem: 'Which AWS service issues and manages SSL/TLS certificates for AWS resources?', options: [{ id: 'A', text: 'AWS Certificate Manager (ACM)' }, { id: 'B', text: 'Secrets Manager' }, { id: 'C', text: 'KMS' }, { id: 'D', text: 'IAM' }], correct: ['A'], explanation: 'ACM issues free public certs and manages renewal; ACM Private CA for private trust.' },
  { domain: 'Security and Compliance', type: QType.SINGLE, stem: 'Which AWS feature lets organizations enforce service control policies (SCPs) across multiple accounts?', options: [{ id: 'A', text: 'AWS Organizations + SCPs' }, { id: 'B', text: 'IAM only' }, { id: 'C', text: 'Resource policies' }, { id: 'D', text: 'KMS keys' }], correct: ['A'], explanation: 'Organizations group AWS accounts; SCPs set guardrails (deny-by-default lists) inherited by accounts/OUs.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'aws-dop-c02-p1', offset: 0 },
  { slug: 'aws-dop-c02-p2', offset: 5 },
  { slug: 'aws-dop-c02-p3', offset: 10 },
  { slug: 'aws-dop-c02-p4', offset: 15 },
  { slug: 'aws-dop-c02-p5', offset: 20 },
  { slug: 'aws-dop-c02-p6', offset: 25 },
  { slug: 'aws-dop-c02-p7', offset: 30 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: { examId: exam.id, domain: q.domain, difficulty: 3, type: q.type, stem: q.stem, options: q.options, correct: q.correct, explanation: q.explanation, references: [REF], status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up DOP-C02 to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
