/**
 * Top-up: brings Microsoft AZ-104 practice exams (P1, P3, P4) to 60 questions.
 *
 *   npx tsx scripts/seed-microsoft-az-104-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';

const db = new PrismaClient();

const TARGET = 60;
const TAG_PREFIX = 'topup:microsoft-az-104';
const REF = { label: 'Microsoft AZ-104 exam page', url: 'https://learn.microsoft.com/en-us/credentials/certifications/exams/az-104/' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  // ===== Manage Azure identities and governance (12) =====
  { domain: 'Manage Azure identities and governance', type: QType.SINGLE,
    stem: 'You need to grant a user the ability to manage virtual machines in a single resource group, but nothing else. Which built-in RBAC role assigned at the resource-group scope is most appropriate?',
    options: [{ id: 'A', text: 'Owner' }, { id: 'B', text: 'Contributor' }, { id: 'C', text: 'Virtual Machine Contributor' }, { id: 'D', text: 'Reader' }],
    correct: ['C'],
    explanation: 'Virtual Machine Contributor lets a user manage VMs (without granting access to the VM, network, or storage). Owner/Contributor are too broad; Reader is read-only.' },
  { domain: 'Manage Azure identities and governance', type: QType.SINGLE,
    stem: 'Which Microsoft Entra ID feature lets you require multi-factor authentication only when users sign in from outside trusted networks?',
    options: [{ id: 'A', text: 'Conditional Access policy' }, { id: 'B', text: 'Privileged Identity Management' }, { id: 'C', text: 'Azure Policy' }, { id: 'D', text: 'Self-Service Password Reset' }],
    correct: ['A'],
    explanation: 'Conditional Access evaluates signals (location, device, risk) and applies access controls (require MFA, block, require compliant device). PIM manages just-in-time admin access; Azure Policy enforces resource configuration.' },
  { domain: 'Manage Azure identities and governance', type: QType.SINGLE,
    stem: 'Which Azure governance service applies declarative rules to evaluate resources for compliance — for example, denying VM creation outside allowed regions?',
    options: [{ id: 'A', text: 'Azure Policy' }, { id: 'B', text: 'Microsoft Defender for Cloud' }, { id: 'C', text: 'Azure Monitor' }, { id: 'D', text: 'Azure Blueprints' }],
    correct: ['A'],
    explanation: 'Azure Policy assigns definitions (Audit/Deny/Modify/AppendTags) to scopes and reports compliance. Defender for Cloud surfaces security recommendations; Monitor handles telemetry; Blueprints package multiple artifacts.' },
  { domain: 'Manage Azure identities and governance', type: QType.SINGLE,
    stem: 'You need to organize multiple subscriptions for billing and policy inheritance under a hierarchy. Which Azure construct should you use?',
    options: [{ id: 'A', text: 'Management groups' }, { id: 'B', text: 'Resource groups' }, { id: 'C', text: 'Tags' }, { id: 'D', text: 'Resources' }],
    correct: ['A'],
    explanation: 'Management groups sit above subscriptions in the resource hierarchy: Management Group → Subscription → Resource Group → Resource. Policies and RBAC roles applied to a management group inherit downward.' },
  { domain: 'Manage Azure identities and governance', type: QType.SINGLE,
    stem: 'Which Microsoft Entra ID feature provides "just-in-time" elevation for privileged roles with approval workflows and time-limited access?',
    options: [{ id: 'A', text: 'Privileged Identity Management (PIM)' }, { id: 'B', text: 'Azure Bastion' }, { id: 'C', text: 'Azure AD Connect' }, { id: 'D', text: 'Azure Lighthouse' }],
    correct: ['A'],
    explanation: 'PIM enables eligible (rather than permanent) role assignments, requiring activation with optional approval and time bounds. Bastion is RDP/SSH; AD Connect syncs identities; Lighthouse delegates cross-tenant access.' },
  { domain: 'Manage Azure identities and governance', type: QType.SINGLE,
    stem: 'Which RBAC role at the subscription scope grants ALL permissions including the ability to assign roles to others?',
    options: [{ id: 'A', text: 'Owner' }, { id: 'B', text: 'Contributor' }, { id: 'C', text: 'User Access Administrator' }, { id: 'D', text: 'Reader' }],
    correct: ['A'],
    explanation: 'Owner = all actions including role assignment. Contributor = manage resources but cannot grant access. User Access Admin can manage access but not resources. Reader is read-only.' },
  { domain: 'Manage Azure identities and governance', type: QType.SINGLE,
    stem: 'Which Microsoft Entra ID edition is required to use dynamic group membership rules?',
    options: [{ id: 'A', text: 'Microsoft Entra ID Free' }, { id: 'B', text: 'Microsoft Entra ID P1' }, { id: 'C', text: 'Microsoft 365 Apps for business' }, { id: 'D', text: 'Office 365 Personal' }],
    correct: ['B'],
    explanation: 'Dynamic groups (and Conditional Access) require Entra ID P1 or higher. The Free edition does not include dynamic groups.' },
  { domain: 'Manage Azure identities and governance', type: QType.SINGLE,
    stem: 'You want to apply a tag to enforce cost-center reporting on every new resource. Which approach is most maintainable?',
    options: [{ id: 'A', text: 'Azure Policy with append/modify effect to add the required tag' }, { id: 'B', text: 'Manually tag each resource after creation' }, { id: 'C', text: 'Use Resource Locks' }, { id: 'D', text: 'Set up an alert' }],
    correct: ['A'],
    explanation: 'Azure Policy with append/modify can require/inject tags at create time, ensuring consistency. Manual tagging is unreliable; resource locks prevent deletion; alerts only notify.' },
  { domain: 'Manage Azure identities and governance', type: QType.SINGLE,
    stem: 'Which lock prevents accidental deletion of a resource but still allows modification?',
    options: [{ id: 'A', text: 'CanNotDelete' }, { id: 'B', text: 'ReadOnly' }, { id: 'C', text: 'NoAccess' }, { id: 'D', text: 'Deny' }],
    correct: ['A'],
    explanation: 'CanNotDelete allows reads/writes but blocks delete. ReadOnly blocks all writes including delete. NoAccess/Deny aren\'t lock types; ReadOnly is the most restrictive lock.' },
  { domain: 'Manage Azure identities and governance', type: QType.SINGLE,
    stem: 'Which Microsoft Entra ID feature lets external (B2B) guests authenticate to your tenant using their existing identities?',
    options: [{ id: 'A', text: 'External Identities (B2B collaboration)' }, { id: 'B', text: 'Self-Service Password Reset' }, { id: 'C', text: 'Domain Services' }, { id: 'D', text: 'Active Directory Federation Services' }],
    correct: ['A'],
    explanation: 'B2B collaboration invites guest users to your tenant; they sign in with their own (Entra ID, Microsoft, Google, etc.) identity.' },
  { domain: 'Manage Azure identities and governance', type: QType.SINGLE,
    stem: 'You need to scope RBAC such that a user can read resources at the subscription level but only contribute to resources in a single resource group. Which assignment strategy works?',
    options: [{ id: 'A', text: 'Assign Reader at the subscription scope and Contributor at the resource group scope to the same user' }, { id: 'B', text: 'Assign only Owner globally' }, { id: 'C', text: 'Assign Reader at the resource group only' }, { id: 'D', text: 'Use Microsoft 365 license assignment' }],
    correct: ['A'],
    explanation: 'RBAC assignments are additive: Reader@subscription + Contributor@RG yields read across subscription, contribute in RG. Owner is excessive; Reader-only blocks contribution.' },
  { domain: 'Manage Azure identities and governance', type: QType.SINGLE,
    stem: 'Which Azure Policy effect would you use to AUDIT noncompliant resources without preventing their creation?',
    options: [{ id: 'A', text: 'Audit' }, { id: 'B', text: 'Deny' }, { id: 'C', text: 'Modify' }, { id: 'D', text: 'AppendTags' }],
    correct: ['A'],
    explanation: 'Audit logs noncompliance without blocking. Deny prevents create/update; Modify changes properties; Append adds fields. Audit is for visibility-first rollouts.' },

  // ===== Implement and manage storage (10) =====
  { domain: 'Implement and manage storage', type: QType.SINGLE,
    stem: 'Which Azure Storage redundancy option replicates data synchronously across three availability zones in a region?',
    options: [{ id: 'A', text: 'LRS (Locally-Redundant Storage)' }, { id: 'B', text: 'ZRS (Zone-Redundant Storage)' }, { id: 'C', text: 'GRS (Geo-Redundant Storage)' }, { id: 'D', text: 'GZRS (Geo-Zone-Redundant Storage)' }],
    correct: ['B'],
    explanation: 'ZRS = synchronous across 3 AZs in one region. LRS = three copies in one DC. GRS = LRS + async copy to paired region. GZRS = ZRS + async copy to paired region.' },
  { domain: 'Implement and manage storage', type: QType.SINGLE,
    stem: 'Which Azure Storage redundancy option provides the highest durability AND geographic protection AND zone redundancy?',
    options: [{ id: 'A', text: 'LRS' }, { id: 'B', text: 'ZRS' }, { id: 'C', text: 'GRS' }, { id: 'D', text: 'GZRS' }],
    correct: ['D'],
    explanation: 'GZRS = synchronous ZRS in primary region + async copy to paired region. Highest of the four common options for durability and DR.' },
  { domain: 'Implement and manage storage', type: QType.SINGLE,
    stem: 'You need to provide low-cost archival storage for blobs that are rarely accessed and can tolerate hours of retrieval latency. Which access tier should you choose?',
    options: [{ id: 'A', text: 'Hot' }, { id: 'B', text: 'Cool' }, { id: 'C', text: 'Cold' }, { id: 'D', text: 'Archive' }],
    correct: ['D'],
    explanation: 'Archive tier offers the lowest storage cost but requires rehydration (minutes to hours) before reads. Hot/Cool/Cold are for online access at decreasing access frequencies.' },
  { domain: 'Implement and manage storage', type: QType.SINGLE,
    stem: 'Which Azure storage service is best suited for traditional SMB file shares accessible to multiple VMs and on-prem clients?',
    options: [{ id: 'A', text: 'Azure Files' }, { id: 'B', text: 'Azure Blob Storage' }, { id: 'C', text: 'Azure NetApp Files' }, { id: 'D', text: 'Azure Queue Storage' }],
    correct: ['A'],
    explanation: 'Azure Files provides fully managed SMB and NFS file shares. Blob is object storage; NetApp Files is enterprise high-perf NAS; Queue Storage is messaging.' },
  { domain: 'Implement and manage storage', type: QType.SINGLE,
    stem: 'Which feature lets you generate a time-limited delegated access URL to a single blob without sharing the storage account key?',
    options: [{ id: 'A', text: 'Shared Access Signature (SAS)' }, { id: 'B', text: 'Account key' }, { id: 'C', text: 'Public anonymous access' }, { id: 'D', text: 'Storage firewall' }],
    correct: ['A'],
    explanation: 'SAS tokens grant scoped, time-bounded access to specific resources. Sharing account keys gives full access; anonymous makes data public; firewall is network-layer.' },
  { domain: 'Implement and manage storage', type: QType.SINGLE,
    stem: 'You want blob lifecycle management to move objects older than 30 days to Cool tier and delete after 365 days. What is the most maintainable approach?',
    options: [{ id: 'A', text: 'Configure a blob lifecycle management policy on the storage account' }, { id: 'B', text: 'Write a daily PowerShell script' }, { id: 'C', text: 'Manually move files' }, { id: 'D', text: 'Disable replication' }],
    correct: ['A'],
    explanation: 'Lifecycle management policies (JSON rules) automate tier transitions and deletions based on age, prefix, or tags. Scripts/manual approaches are fragile.' },
  { domain: 'Implement and manage storage', type: QType.SINGLE,
    stem: 'Which Azure managed disk type provides the highest sub-millisecond latency, suitable for SAP HANA and tier-1 OLTP workloads?',
    options: [{ id: 'A', text: 'Standard HDD' }, { id: 'B', text: 'Standard SSD' }, { id: 'C', text: 'Premium SSD' }, { id: 'D', text: 'Ultra Disk' }],
    correct: ['D'],
    explanation: 'Ultra Disks provide sub-ms latency, configurable IOPS/throughput. Premium SSD is enterprise-grade but slightly higher latency. Standard SSD/HDD are lower-tier.' },
  { domain: 'Implement and manage storage', type: QType.SINGLE,
    stem: 'Which Azure feature replicates Storage Account contents from one region to its paired region asynchronously, providing protection against regional outages?',
    options: [{ id: 'A', text: 'GRS' }, { id: 'B', text: 'LRS' }, { id: 'C', text: 'ZRS' }, { id: 'D', text: 'NSG' }],
    correct: ['A'],
    explanation: 'GRS replicates async to a Microsoft-paired region. LRS is single-DC; ZRS is multi-AZ same region; NSG is networking, not storage.' },
  { domain: 'Implement and manage storage', type: QType.SINGLE,
    stem: 'Which tool or service migrates large amounts of data into Azure when network bandwidth is impractical, by shipping a physical device?',
    options: [{ id: 'A', text: 'Azure Data Box' }, { id: 'B', text: 'AzCopy' }, { id: 'C', text: 'Storage Explorer' }, { id: 'D', text: 'Network Watcher' }],
    correct: ['A'],
    explanation: 'Data Box ships physical devices for offline TB-PB ingest. AzCopy is online command-line; Storage Explorer is a GUI; Network Watcher diagnoses networking.' },
  { domain: 'Implement and manage storage', type: QType.SINGLE,
    stem: 'You want to mount an Azure Files share from an on-premises Windows machine over the public internet. Which protocol and port does Azure Files use?',
    options: [{ id: 'A', text: 'SMB over TCP 445' }, { id: 'B', text: 'NFS over TCP 2049' }, { id: 'C', text: 'FTP over TCP 21' }, { id: 'D', text: 'HTTPS over TCP 443' }],
    correct: ['A'],
    explanation: 'Azure Files SMB shares use TCP/445 (which many ISPs block, requiring VPN/Private Endpoint workarounds). NFS shares use TCP/2049.' },

  // ===== Deploy and manage Azure compute resources (12) =====
  { domain: 'Deploy and manage Azure compute resources', type: QType.SINGLE,
    stem: 'Which Azure compute option lets you run containers without managing servers, using a per-second pricing model?',
    options: [{ id: 'A', text: 'Azure Container Instances (ACI)' }, { id: 'B', text: 'Azure Virtual Machines' }, { id: 'C', text: 'Azure App Service' }, { id: 'D', text: 'Azure Functions Premium plan' }],
    correct: ['A'],
    explanation: 'ACI runs single containers or container groups serverlessly, billed per-second. AKS manages clusters; VMs require OS management; App Service is for web apps.' },
  { domain: 'Deploy and manage Azure compute resources', type: QType.SINGLE,
    stem: 'Which feature ensures a Virtual Machine Scale Set automatically adjusts capacity based on CPU utilization?',
    options: [{ id: 'A', text: 'Autoscale rules' }, { id: 'B', text: 'Availability Zones' }, { id: 'C', text: 'Proximity Placement Groups' }, { id: 'D', text: 'Spot pricing' }],
    correct: ['A'],
    explanation: 'Autoscale rules define metric-based or schedule-based scaling actions for VMSS. Availability Zones provide redundancy; PPGs reduce latency; Spot is a pricing model.' },
  { domain: 'Deploy and manage Azure compute resources', type: QType.SINGLE,
    stem: 'You need maximum SLA on an Azure VM workload: which architecture provides the highest stated SLA?',
    options: [{ id: 'A', text: 'Single VM with Standard SSD' }, { id: 'B', text: 'Two or more VMs in an Availability Set' }, { id: 'C', text: 'Two or more VMs across Availability Zones' }, { id: 'D', text: 'A single VM with Premium SSD' }],
    correct: ['C'],
    explanation: 'VMs across AZs offer the highest SLA (99.99%). Availability Sets provide 99.95%. Single Premium SSD VM offers 99.9% (depends on disk type).' },
  { domain: 'Deploy and manage Azure compute resources', type: QType.SINGLE,
    stem: 'Which Azure compute model is best for short event-driven workloads that scale to zero and bill per execution?',
    options: [{ id: 'A', text: 'Azure Functions (Consumption plan)' }, { id: 'B', text: 'Azure VM Scale Set' }, { id: 'C', text: 'Azure Kubernetes Service' }, { id: 'D', text: 'Azure App Service Premium' }],
    correct: ['A'],
    explanation: 'Functions Consumption plan scales 0→N instantly, bills per execution + GB-seconds. Other options have always-on baseline cost.' },
  { domain: 'Deploy and manage Azure compute resources', type: QType.SINGLE,
    stem: 'Which Azure feature lets you save 1- or 3-year commitments for VMs in exchange for substantial discounts vs. pay-as-you-go?',
    options: [{ id: 'A', text: 'Azure Reserved Instances' }, { id: 'B', text: 'Spot VMs' }, { id: 'C', text: 'Hybrid Benefit' }, { id: 'D', text: 'Cost Management' }],
    correct: ['A'],
    explanation: 'Reserved Instances (RIs) offer up to 72% discount for 1- or 3-year terms. Spot trades reliability for steeper discounts. Hybrid Benefit is for using existing licenses. Cost Management is reporting.' },
  { domain: 'Deploy and manage Azure compute resources', type: QType.SINGLE,
    stem: 'Which Azure App Service feature provides language- and framework-specific deployment slots with zero-downtime swapping?',
    options: [{ id: 'A', text: 'Deployment slots' }, { id: 'B', text: 'Service plan scaling' }, { id: 'C', text: 'Custom domains' }, { id: 'D', text: 'Hybrid Connections' }],
    correct: ['A'],
    explanation: 'Deployment slots let you stage versions and swap them with the production slot, providing zero-downtime cutovers and easy rollback.' },
  { domain: 'Deploy and manage Azure compute resources', type: QType.SINGLE,
    stem: 'Which Azure VM disk option is local and ephemeral, useful only for OS or temp data that does not need to persist?',
    options: [{ id: 'A', text: 'Temporary disk (D: drive on Windows)' }, { id: 'B', text: 'Premium SSD' }, { id: 'C', text: 'Standard SSD' }, { id: 'D', text: 'Ultra Disk' }],
    correct: ['A'],
    explanation: 'The temporary disk is local SSD on the host, lost on stop-deallocate or hardware migration. Premium/Standard SSD/Ultra are persistent managed disks.' },
  { domain: 'Deploy and manage Azure compute resources', type: QType.SINGLE,
    stem: 'You want the lowest VM cost for non-critical batch jobs that can be interrupted. Which pricing model is most appropriate?',
    options: [{ id: 'A', text: 'Spot Virtual Machines' }, { id: 'B', text: '3-year Reserved Instances' }, { id: 'C', text: 'Pay-as-you-go' }, { id: 'D', text: 'Azure Hybrid Benefit only' }],
    correct: ['A'],
    explanation: 'Spot VMs use unused capacity at a deep discount but can be evicted. Acceptable for fault-tolerant batch workloads. RIs are for steady workloads.' },
  { domain: 'Deploy and manage Azure compute resources', type: QType.SINGLE,
    stem: 'Which Azure VM extension can apply post-deployment configuration scripts (PowerShell DSC, custom shell)?',
    options: [{ id: 'A', text: 'Custom Script Extension' }, { id: 'B', text: 'NSG Flow Logs extension' }, { id: 'C', text: 'Azure Backup extension' }, { id: 'D', text: 'Antimalware extension' }],
    correct: ['A'],
    explanation: 'Custom Script Extension downloads and runs scripts on a VM after deploy. The other extensions serve specific purposes (logging, backup, AV).' },
  { domain: 'Deploy and manage Azure compute resources', type: QType.SINGLE,
    stem: 'Which Azure Kubernetes Service (AKS) component manages the Kubernetes API server and is fully managed by Azure?',
    options: [{ id: 'A', text: 'Control plane' }, { id: 'B', text: 'Node pool' }, { id: 'C', text: 'Pod' }, { id: 'D', text: 'Ingress controller' }],
    correct: ['A'],
    explanation: 'AKS\'s control plane (API server, scheduler, etcd) is fully managed. You manage node pools (worker VMs) and your workloads.' },
  { domain: 'Deploy and manage Azure compute resources', type: QType.SINGLE,
    stem: 'Which Azure feature provides serverless container execution with vNet integration, scaling, and revisions?',
    options: [{ id: 'A', text: 'Azure Container Apps' }, { id: 'B', text: 'Azure Container Registry' }, { id: 'C', text: 'Azure Functions Premium' }, { id: 'D', text: 'Azure Service Bus' }],
    correct: ['A'],
    explanation: 'Container Apps is serverless containers built on Kubernetes/Dapr/KEDA, with built-in revisions, scale-to-zero, and traffic splitting.' },
  { domain: 'Deploy and manage Azure compute resources', type: QType.SINGLE,
    stem: 'You need to ensure VMs in a Scale Set are spread across update and fault domains. Which type of placement does this automatically?',
    options: [{ id: 'A', text: 'A Virtual Machine Scale Set inherently distributes instances across UDs and FDs' }, { id: 'B', text: 'Default Standard VMs do nothing of the sort' }, { id: 'C', text: 'You must use SQL Server' }, { id: 'D', text: 'Only Spot VMs spread across FDs' }],
    correct: ['A'],
    explanation: 'VMSS spreads instances across multiple update/fault domains by default. Across availability zones for additional resilience if zone-aware.' },

  // ===== Implement and manage virtual networking (13) =====
  { domain: 'Implement and manage virtual networking', type: QType.SINGLE,
    stem: 'Which Azure resource controls inbound/outbound traffic to subnets and NICs through allow/deny rules with priority ordering?',
    options: [{ id: 'A', text: 'Network Security Group (NSG)' }, { id: 'B', text: 'Application Security Group (ASG)' }, { id: 'C', text: 'Azure Firewall' }, { id: 'D', text: 'Bastion' }],
    correct: ['A'],
    explanation: 'NSGs are stateful Layer-3/4 ACLs attached to subnets/NICs. ASGs group NICs for use in NSG rules. Azure Firewall is a managed L4-7 firewall. Bastion provides RDP/SSH via portal.' },
  { domain: 'Implement and manage virtual networking', type: QType.SINGLE,
    stem: 'Which Azure service provides DDoS protection at the platform level for public IP resources, with optional Premium tier for app-aware mitigation?',
    options: [{ id: 'A', text: 'Azure DDoS Protection' }, { id: 'B', text: 'Azure Front Door' }, { id: 'C', text: 'Azure Bastion' }, { id: 'D', text: 'Azure Private Link' }],
    correct: ['A'],
    explanation: 'Azure DDoS Protection (Network/Standard/IP Protection tiers) safeguards public-facing resources. Front Door is L7 ingress; Bastion is admin access; Private Link is private connectivity.' },
  { domain: 'Implement and manage virtual networking', type: QType.SINGLE,
    stem: 'Which Azure feature lets you connect two VNets in different regions at the Microsoft backbone, low latency, no public internet?',
    options: [{ id: 'A', text: 'Global VNet peering' }, { id: 'B', text: 'Site-to-Site VPN' }, { id: 'C', text: 'ExpressRoute' }, { id: 'D', text: 'Hub-and-spoke topology' }],
    correct: ['A'],
    explanation: 'Global VNet peering connects VNets across regions over Microsoft backbone with low latency. S2S VPN/ExpressRoute connect Azure to on-prem. Hub-and-spoke is an architectural pattern.' },
  { domain: 'Implement and manage virtual networking', type: QType.SINGLE,
    stem: 'Which Azure load-balancing service is Layer 4 (TCP/UDP), regional, and built into the platform with no extra app-layer features?',
    options: [{ id: 'A', text: 'Azure Load Balancer' }, { id: 'B', text: 'Application Gateway' }, { id: 'C', text: 'Azure Front Door' }, { id: 'D', text: 'Traffic Manager' }],
    correct: ['A'],
    explanation: 'Azure Load Balancer is L4. Application Gateway is regional L7 with WAF. Front Door is global L7. Traffic Manager is DNS-based global routing.' },
  { domain: 'Implement and manage virtual networking', type: QType.SINGLE,
    stem: 'Which Azure load-balancing service provides global Layer-7 load balancing with WAF, anycast acceleration, and SSL offload?',
    options: [{ id: 'A', text: 'Azure Front Door' }, { id: 'B', text: 'Azure Load Balancer' }, { id: 'C', text: 'Application Gateway' }, { id: 'D', text: 'Traffic Manager' }],
    correct: ['A'],
    explanation: 'Front Door is global anycast L7 with WAF, caching, SSL offload, and routing. App Gateway is regional L7. Load Balancer is L4. Traffic Manager is DNS.' },
  { domain: 'Implement and manage virtual networking', type: QType.SINGLE,
    stem: 'Which DNS service can resolve names within a VNet AND between linked VNets, replacing the need for a custom DNS VM?',
    options: [{ id: 'A', text: 'Azure Private DNS Zones' }, { id: 'B', text: 'Azure DNS public zones' }, { id: 'C', text: 'NSG' }, { id: 'D', text: 'Azure Front Door' }],
    correct: ['A'],
    explanation: 'Private DNS zones are hosted by Azure for use inside VNets, with auto-registration and cross-VNet linking. Public zones are for internet-facing names.' },
  { domain: 'Implement and manage virtual networking', type: QType.SINGLE,
    stem: 'Which Azure feature provides PRIVATE access to a PaaS service (e.g., Storage, Key Vault) over your VNet using a private IP, with no public exposure?',
    options: [{ id: 'A', text: 'Private Endpoint (Private Link)' }, { id: 'B', text: 'Service Endpoint' }, { id: 'C', text: 'NSG' }, { id: 'D', text: 'Bastion' }],
    correct: ['A'],
    explanation: 'Private Endpoint creates a NIC in your VNet with a private IP for the PaaS service. Service Endpoints route over the Microsoft backbone but the service still has a public IP.' },
  { domain: 'Implement and manage virtual networking', type: QType.SINGLE,
    stem: 'Which Azure VPN connection type is used for connecting individual remote workers to a VNet from any device with a VPN client?',
    options: [{ id: 'A', text: 'Point-to-Site VPN' }, { id: 'B', text: 'Site-to-Site VPN' }, { id: 'C', text: 'ExpressRoute' }, { id: 'D', text: 'VNet peering' }],
    correct: ['A'],
    explanation: 'P2S connects individual clients (Win/Mac/Linux) using OpenVPN/IKEv2/SSTP. S2S connects whole networks via IPsec. ExpressRoute is private fiber. VNet peering is intra-Azure.' },
  { domain: 'Implement and manage virtual networking', type: QType.SINGLE,
    stem: 'A subnet uses 10.0.1.0/24. How many usable host addresses remain after Azure reserves the standard addresses?',
    options: [{ id: 'A', text: '256' }, { id: 'B', text: '254' }, { id: 'C', text: '251' }, { id: 'D', text: '250' }],
    correct: ['C'],
    explanation: 'Azure reserves 5 addresses per subnet: network, default gateway, two for DNS, broadcast. /24 has 256 total - 5 = 251 usable.' },
  { domain: 'Implement and manage virtual networking', type: QType.SINGLE,
    stem: 'Which Azure networking feature provides a managed jump host for RDP/SSH to VMs without exposing public IPs?',
    options: [{ id: 'A', text: 'Azure Bastion' }, { id: 'B', text: 'Azure Firewall' }, { id: 'C', text: 'Azure Front Door' }, { id: 'D', text: 'Application Gateway' }],
    correct: ['A'],
    explanation: 'Bastion is a managed PaaS jump host accessed through the Azure Portal — VMs only need private IPs.' },
  { domain: 'Implement and manage virtual networking', type: QType.SINGLE,
    stem: 'Which routing feature lets you override the default Azure system routes — for example, to send all internet-bound traffic through a network virtual appliance?',
    options: [{ id: 'A', text: 'User-Defined Routes (UDRs) on a route table' }, { id: 'B', text: 'NSG' }, { id: 'C', text: 'DNS' }, { id: 'D', text: 'Service Tag' }],
    correct: ['A'],
    explanation: 'UDRs in route tables define custom next-hops (often an NVA/firewall). NSGs filter traffic; DNS resolves names; service tags simplify NSG rules.' },
  { domain: 'Implement and manage virtual networking', type: QType.SINGLE,
    stem: 'A VM has both an NSG on the NIC and an NSG on the subnet. What is the effective rule evaluation behavior?',
    options: [{ id: 'A', text: 'Both NSGs are evaluated; flow must pass both' }, { id: 'B', text: 'Only the NIC-level NSG is evaluated' }, { id: 'C', text: 'Only the subnet-level NSG is evaluated' }, { id: 'D', text: 'NSGs do not stack' }],
    correct: ['A'],
    explanation: 'When both are present, both must allow the flow. Inbound: subnet first, then NIC. Outbound: NIC first, then subnet.' },
  { domain: 'Implement and manage virtual networking', type: QType.SINGLE,
    stem: 'Which Azure resource provides outbound SNAT for VMs in a VNet without requiring public IPs on each VM?',
    options: [{ id: 'A', text: 'NAT Gateway' }, { id: 'B', text: 'Azure Bastion' }, { id: 'C', text: 'NSG' }, { id: 'D', text: 'Front Door' }],
    correct: ['A'],
    explanation: 'NAT Gateway provides scalable outbound connectivity (SNAT) to a subnet via static public IPs/IP prefixes. Bastion is for inbound RDP/SSH; NSG filters; Front Door is L7 ingress.' },

  // ===== Monitor and maintain Azure resources (13) =====
  { domain: 'Monitor and maintain Azure resources', type: QType.SINGLE,
    stem: 'Which Azure Monitor component collects logs and metrics from Azure and on-prem sources, queryable with KQL?',
    options: [{ id: 'A', text: 'Log Analytics workspace' }, { id: 'B', text: 'Application Insights only' }, { id: 'C', text: 'Activity Log' }, { id: 'D', text: 'Service Health' }],
    correct: ['A'],
    explanation: 'Log Analytics workspaces store logs from many sources, queried with KQL. App Insights is APM (built atop Log Analytics). Activity Log records control-plane events. Service Health reports Azure outages.' },
  { domain: 'Monitor and maintain Azure resources', type: QType.SINGLE,
    stem: 'Which Azure Backup feature lets you restore a VM to a prior point in time using snapshots stored in a Recovery Services vault?',
    options: [{ id: 'A', text: 'Azure Backup with VM backup policy' }, { id: 'B', text: 'Storage account replication' }, { id: 'C', text: 'Azure Bastion' }, { id: 'D', text: 'Site-to-Site VPN' }],
    correct: ['A'],
    explanation: 'Azure Backup uses Recovery Services vaults and policy-driven snapshots/recovery points for VMs (and SQL, Files, etc.).' },
  { domain: 'Monitor and maintain Azure resources', type: QType.SINGLE,
    stem: 'Which feature replicates VMs from a primary region to a secondary region for disaster recovery, with orchestrated failover?',
    options: [{ id: 'A', text: 'Azure Site Recovery (ASR)' }, { id: 'B', text: 'Azure Backup' }, { id: 'C', text: 'GRS storage' }, { id: 'D', text: 'NSG' }],
    correct: ['A'],
    explanation: 'ASR provides DR for VMs (Azure-to-Azure, on-prem-to-Azure) with replication, recovery plans, and failover/failback. Azure Backup is point-in-time recovery within a region.' },
  { domain: 'Monitor and maintain Azure resources', type: QType.SINGLE,
    stem: 'Which Azure Monitor feature lets you create alerts based on log queries — e.g., "fire when X errors per minute exceeds 100"?',
    options: [{ id: 'A', text: 'Log alerts (Scheduled Query Rules)' }, { id: 'B', text: 'Service Health alerts' }, { id: 'C', text: 'Activity Log alerts' }, { id: 'D', text: 'Smart Detection' }],
    correct: ['A'],
    explanation: 'Log alerts run KQL on a schedule and fire when threshold conditions are met. Service Health monitors platform issues; Activity Log alerts track control-plane events; Smart Detection is anomaly-based for App Insights.' },
  { domain: 'Monitor and maintain Azure resources', type: QType.SINGLE,
    stem: 'Which Azure Monitor component tracks operational telemetry for code-level performance — request rates, dependencies, exceptions?',
    options: [{ id: 'A', text: 'Application Insights' }, { id: 'B', text: 'Log Analytics agent' }, { id: 'C', text: 'Activity Log' }, { id: 'D', text: 'Network Watcher' }],
    correct: ['A'],
    explanation: 'Application Insights is APM for live applications, surfacing request/response latencies, dependencies, exceptions, custom events.' },
  { domain: 'Monitor and maintain Azure resources', type: QType.SINGLE,
    stem: 'Which language is used to query Log Analytics?',
    options: [{ id: 'A', text: 'Kusto Query Language (KQL)' }, { id: 'B', text: 'T-SQL' }, { id: 'C', text: 'GraphQL' }, { id: 'D', text: 'PromQL' }],
    correct: ['A'],
    explanation: 'KQL is Microsoft\'s read-only query language used in Log Analytics, Sentinel, App Insights, ADX, etc.' },
  { domain: 'Monitor and maintain Azure resources', type: QType.SINGLE,
    stem: 'Which Azure tool diagnoses connectivity issues between resources — e.g., showing exactly where traffic is dropped between two VMs?',
    options: [{ id: 'A', text: 'Network Watcher (Connection Troubleshoot, IP Flow Verify)' }, { id: 'B', text: 'Azure Bastion' }, { id: 'C', text: 'Azure DevOps' }, { id: 'D', text: 'Azure Resource Mover' }],
    correct: ['A'],
    explanation: 'Network Watcher provides Connection Troubleshoot, IP Flow Verify, NSG diagnostics, packet capture, and topology visualizations.' },
  { domain: 'Monitor and maintain Azure resources', type: QType.SINGLE,
    stem: 'Which Azure Monitor feature lets you ingest VM-level metrics like guest OS counters using a managed agent on Linux/Windows?',
    options: [{ id: 'A', text: 'Azure Monitor Agent (AMA)' }, { id: 'B', text: 'NSG flow logs' }, { id: 'C', text: 'Service Map' }, { id: 'D', text: 'Backup vault' }],
    correct: ['A'],
    explanation: 'AMA replaces older MMA/OMS agents; it collects guest OS logs and metrics into Azure Monitor.' },
  { domain: 'Monitor and maintain Azure resources', type: QType.SINGLE,
    stem: 'Which Azure feature lets you enable temporary, time-bounded admin access to subscriptions/resources requiring approval?',
    options: [{ id: 'A', text: 'Privileged Identity Management (PIM)' }, { id: 'B', text: 'Azure Lighthouse' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'Azure Backup' }],
    correct: ['A'],
    explanation: 'PIM provides JIT elevation with approval and time bounds for both Entra ID and Azure resource roles.' },
  { domain: 'Monitor and maintain Azure resources', type: QType.SINGLE,
    stem: 'Which feature in Azure VM diagnostics provides serial-console-like access to VMs whose OS may be unbootable?',
    options: [{ id: 'A', text: 'Boot diagnostics + Serial console' }, { id: 'B', text: 'Backup vault' }, { id: 'C', text: 'Azure Cloud Shell' }, { id: 'D', text: 'Diagnostic settings' }],
    correct: ['A'],
    explanation: 'Boot Diagnostics captures screenshots/console logs; the Serial Console provides text-based, OS-independent terminal access for troubleshooting.' },
  { domain: 'Monitor and maintain Azure resources', type: QType.SINGLE,
    stem: 'A scheduled-query alert keeps firing for 1 minute then resolving. Which configuration controls this "noise"?',
    options: [{ id: 'A', text: 'Aggregation granularity, evaluation frequency, and a threshold over multiple periods' }, { id: 'B', text: 'NSG rules' }, { id: 'C', text: 'BitLocker' }, { id: 'D', text: 'Tags' }],
    correct: ['A'],
    explanation: 'Tuning aggregation/eval frequency and requiring N consecutive periods reduces alert noise.' },
  { domain: 'Monitor and maintain Azure resources', type: QType.SINGLE,
    stem: 'Which Azure service helps you optimize cost and right-size VMs by analyzing usage and recommending changes?',
    options: [{ id: 'A', text: 'Azure Advisor' }, { id: 'B', text: 'Azure Bastion' }, { id: 'C', text: 'Azure Lighthouse' }, { id: 'D', text: 'Azure Bot Service' }],
    correct: ['A'],
    explanation: 'Azure Advisor analyzes telemetry and recommends across cost, security, reliability, performance, and operational excellence.' },
  { domain: 'Monitor and maintain Azure resources', type: QType.SINGLE,
    stem: 'Which Azure Backup option reduces total RTO for large VMs by performing instant restore from snapshot before copying back data?',
    options: [{ id: 'A', text: 'Instant Restore (Snapshot tier)' }, { id: 'B', text: 'Vault-tier-only backup' }, { id: 'C', text: 'Cross-region restore' }, { id: 'D', text: 'Soft-delete' }],
    correct: ['A'],
    explanation: 'Instant Restore keeps recent snapshots in the source storage, providing fast restore. Vault tier protects against source loss; cross-region restore serves DR; soft-delete prevents accidental data loss.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'microsoft-az-104-p1', offset: 0 },
  { slug: 'microsoft-az-104-p3', offset: 20 },
  { slug: 'microsoft-az-104-p4', offset: 40 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: {
        examId: exam.id, domain: q.domain, difficulty: 3, type: q.type,
        stem: q.stem, options: q.options, correct: q.correct,
        explanation: q.explanation, references: [REF],
        status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false
      }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up Microsoft AZ-104 exams to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => db.$disconnect());
