/**
 * Top-up: brings Microsoft DP-900 practice exams (P1-P4) to 60 questions.
 *   npx tsx scripts/seed-microsoft-dp-900-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();

const TARGET = 60;
const TAG_PREFIX = 'topup:microsoft-dp-900';
const REF = { label: 'Microsoft DP-900 exam page', url: 'https://learn.microsoft.com/en-us/credentials/certifications/exams/dp-900/' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  // ===== Core data concepts (16) =====
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'Which of the following is an example of structured data?',
    options: [{ id: 'A', text: 'Rows in a relational database with a fixed schema' }, { id: 'B', text: 'A JPEG image' }, { id: 'C', text: 'A free-text email body' }, { id: 'D', text: 'An MP3 file' }],
    correct: ['A'],
    explanation: 'Structured data conforms to a predefined schema (rows/columns). Images, free text, and audio are unstructured.' },
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'Which best describes semi-structured data?',
    options: [{ id: 'A', text: 'Data with self-describing tags or markers (e.g., JSON, XML) but no fixed schema' }, { id: 'B', text: 'Data stored only in CSV files' }, { id: 'C', text: 'Audio recordings' }, { id: 'D', text: 'Photos and videos' }],
    correct: ['A'],
    explanation: 'JSON/XML/YAML have structure (tags, hierarchy) without enforcing a strict schema — semi-structured.' },
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'Which workload type is characterized by short, frequent reads/writes, often involving single rows — typical of order-entry systems?',
    options: [{ id: 'A', text: 'OLTP (Online Transaction Processing)' }, { id: 'B', text: 'OLAP (Online Analytical Processing)' }, { id: 'C', text: 'ETL' }, { id: 'D', text: 'Stream processing' }],
    correct: ['A'],
    explanation: 'OLTP handles fast operational transactions. OLAP is analytics on large historical sets. ETL moves data; streaming processes real-time data.' },
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'A data warehouse stores historical data optimized for analysis. This is an example of which workload?',
    options: [{ id: 'A', text: 'OLAP' }, { id: 'B', text: 'OLTP' }, { id: 'C', text: 'Embedded database' }, { id: 'D', text: 'Time-series streaming' }],
    correct: ['A'],
    explanation: 'OLAP / data warehousing aggregates large historical datasets for analytics, typically with denormalized schemas (star/snowflake).' },
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'Which role designs models, builds pipelines, and ensures data is clean, integrated, and accessible for analytics?',
    options: [{ id: 'A', text: 'Data engineer' }, { id: 'B', text: 'Database administrator' }, { id: 'C', text: 'Data analyst' }, { id: 'D', text: 'Data scientist' }],
    correct: ['A'],
    explanation: 'Data engineers build pipelines, data lakes, warehouses, and integration. DBAs manage databases; analysts produce reports/visualizations; scientists build ML models.' },
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'Which Azure data role typically explores datasets, builds reports, and creates dashboards in tools like Power BI?',
    options: [{ id: 'A', text: 'Data analyst' }, { id: 'B', text: 'Data engineer' }, { id: 'C', text: 'DBA' }, { id: 'D', text: 'ML engineer' }],
    correct: ['A'],
    explanation: 'Data analysts focus on insights via reports/dashboards. Engineers build pipelines, DBAs operate databases, ML engineers build/deploy models.' },
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'Which is an example of "batch" data processing?',
    options: [{ id: 'A', text: 'Nightly aggregation of the day\'s sales orders into a warehouse' }, { id: 'B', text: 'Per-event fraud detection on live card swipes' }, { id: 'C', text: 'Live stock-tick feed to a trading dashboard' }, { id: 'D', text: 'IoT temperature alerts every second' }],
    correct: ['A'],
    explanation: 'Batch processes accumulated data on a schedule. The other options are streaming/real-time.' },
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'Which is an example of "stream" data processing?',
    options: [{ id: 'A', text: 'IoT sensor readings analyzed continuously for anomalies' }, { id: 'B', text: 'Quarterly financial close' }, { id: 'C', text: 'A monthly billing run' }, { id: 'D', text: 'A weekend data warehouse load' }],
    correct: ['A'],
    explanation: 'Streaming processes events continuously as they arrive (low latency). The others are batch.' },
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'Which Azure service is purpose-built for ingesting and processing high-volume streaming events with low latency?',
    options: [{ id: 'A', text: 'Azure Event Hubs / Stream Analytics' }, { id: 'B', text: 'Azure SQL Database' }, { id: 'C', text: 'Azure Files' }, { id: 'D', text: 'Azure Backup' }],
    correct: ['A'],
    explanation: 'Event Hubs ingests millions of events/sec; Stream Analytics processes them with SQL-like queries. The others are storage/backup services.' },
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'Which ACID property guarantees that committed transactions persist even after a system crash?',
    options: [{ id: 'A', text: 'Atomicity' }, { id: 'B', text: 'Consistency' }, { id: 'C', text: 'Isolation' }, { id: 'D', text: 'Durability' }],
    correct: ['D'],
    explanation: 'Durability = committed data survives crashes. Atomicity = all-or-nothing; Consistency = constraints satisfied; Isolation = concurrent transactions don\'t interfere.' },
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'Which ACID property ensures that a transaction either fully succeeds or has no effect at all?',
    options: [{ id: 'A', text: 'Atomicity' }, { id: 'B', text: 'Consistency' }, { id: 'C', text: 'Isolation' }, { id: 'D', text: 'Durability' }],
    correct: ['A'],
    explanation: 'Atomicity = transactions are indivisible: either fully commit or roll back.' },
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'Which database concept enforces that a foreign-key value must reference an existing primary key in the parent table?',
    options: [{ id: 'A', text: 'Referential integrity' }, { id: 'B', text: 'Normalization' }, { id: 'C', text: 'Indexing' }, { id: 'D', text: 'Materialized views' }],
    correct: ['A'],
    explanation: 'Referential integrity (enforced by FK constraints) prevents orphan rows. Normalization eliminates redundancy; indexes accelerate queries; materialized views cache results.' },
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'Which database object speeds up SELECT queries at the cost of additional storage and slightly slower writes?',
    options: [{ id: 'A', text: 'Index' }, { id: 'B', text: 'Trigger' }, { id: 'C', text: 'View' }, { id: 'D', text: 'Stored procedure' }],
    correct: ['A'],
    explanation: 'Indexes provide fast lookup paths but add overhead on insert/update/delete and consume disk space.' },
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'In a relational database, which key uniquely identifies each row in a table?',
    options: [{ id: 'A', text: 'Primary key' }, { id: 'B', text: 'Foreign key' }, { id: 'C', text: 'Candidate key' }, { id: 'D', text: 'Surrogate alias' }],
    correct: ['A'],
    explanation: 'A primary key uniquely identifies each row. Foreign keys reference primary keys in other tables; candidate keys are columns that COULD serve as primary key.' },
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'Which type of database stores data as collections of JSON-like documents and is best for flexible, schema-less workloads?',
    options: [{ id: 'A', text: 'Document database (e.g., Cosmos DB MongoDB API)' }, { id: 'B', text: 'Key-value store' }, { id: 'C', text: 'Column-family' }, { id: 'D', text: 'Graph database' }],
    correct: ['A'],
    explanation: 'Document DBs store BSON/JSON documents with flexible schemas. Key-value stores keys to opaque values; column-family is wide-column; graph DBs store nodes/edges.' },
  { domain: 'Describe core data concepts', type: QType.SINGLE,
    stem: 'Which of the following data types is a measure of how much data we have, often measured in TB or PB — one of the "Vs" of big data?',
    options: [{ id: 'A', text: 'Volume' }, { id: 'B', text: 'Velocity' }, { id: 'C', text: 'Variety' }, { id: 'D', text: 'Veracity' }],
    correct: ['A'],
    explanation: 'The classic 3 Vs of big data: Volume (size), Velocity (speed), Variety (types). Some add Veracity (quality) and Value.' },

  // ===== Relational data on Azure (12) =====
  { domain: 'Identify considerations for relational data on Azure', type: QType.SINGLE,
    stem: 'Which Azure SQL deployment option provides nearly full SQL Server compatibility (including SQL Agent, cross-DB queries) and is best for migrating on-prem databases with minimal change?',
    options: [{ id: 'A', text: 'Azure SQL Managed Instance' }, { id: 'B', text: 'Azure SQL Database (single)' }, { id: 'C', text: 'SQL Server on Azure VM' }, { id: 'D', text: 'Azure Synapse SQL pool' }],
    correct: ['A'],
    explanation: 'Managed Instance offers near-100% SQL Server compatibility while being a managed PaaS. SQL Database is single-DB without SQL Agent etc.; SQL on VM is IaaS; Synapse is data warehouse.' },
  { domain: 'Identify considerations for relational data on Azure', type: QType.SINGLE,
    stem: 'Which Azure SQL purchasing model lets you choose vCores and storage independently?',
    options: [{ id: 'A', text: 'vCore-based purchasing model' }, { id: 'B', text: 'DTU-based purchasing model' }, { id: 'C', text: 'BACPAC model' }, { id: 'D', text: 'Express model' }],
    correct: ['A'],
    explanation: 'vCore lets you choose CPU and storage independently and supports Hybrid Benefit. DTU bundles compute, memory, IO into a single unit.' },
  { domain: 'Identify considerations for relational data on Azure', type: QType.SINGLE,
    stem: 'Which Azure managed PaaS database is fully compatible with PostgreSQL and offers Flexible Server / Hyperscale (Citus) options?',
    options: [{ id: 'A', text: 'Azure Database for PostgreSQL' }, { id: 'B', text: 'Azure Database for MySQL' }, { id: 'C', text: 'Azure SQL Database' }, { id: 'D', text: 'Cosmos DB for PostgreSQL' }],
    correct: ['A'],
    explanation: 'Azure Database for PostgreSQL (Flexible Server / Single Server / Hyperscale via Cosmos DB for PostgreSQL) is the managed PostgreSQL.' },
  { domain: 'Identify considerations for relational data on Azure', type: QType.SINGLE,
    stem: 'Which T-SQL clause filters groups produced by GROUP BY?',
    options: [{ id: 'A', text: 'HAVING' }, { id: 'B', text: 'WHERE' }, { id: 'C', text: 'ORDER BY' }, { id: 'D', text: 'JOIN' }],
    correct: ['A'],
    explanation: 'HAVING filters AFTER aggregation. WHERE filters rows BEFORE aggregation. ORDER BY sorts; JOIN combines tables.' },
  { domain: 'Identify considerations for relational data on Azure', type: QType.SINGLE,
    stem: 'Which JOIN type returns matching rows from BOTH tables and unmatched rows from the LEFT table only?',
    options: [{ id: 'A', text: 'LEFT OUTER JOIN' }, { id: 'B', text: 'INNER JOIN' }, { id: 'C', text: 'FULL OUTER JOIN' }, { id: 'D', text: 'CROSS JOIN' }],
    correct: ['A'],
    explanation: 'LEFT OUTER returns all left rows + matches; right unmatched columns are NULL. INNER returns only matches; FULL returns all; CROSS returns Cartesian.' },
  { domain: 'Identify considerations for relational data on Azure', type: QType.SINGLE,
    stem: 'Which DDL statement removes a table and all its data permanently?',
    options: [{ id: 'A', text: 'DROP TABLE' }, { id: 'B', text: 'DELETE' }, { id: 'C', text: 'TRUNCATE' }, { id: 'D', text: 'REVOKE' }],
    correct: ['A'],
    explanation: 'DROP TABLE removes the table itself. DELETE/TRUNCATE remove rows but keep the table definition. REVOKE removes permissions.' },
  { domain: 'Identify considerations for relational data on Azure', type: QType.SINGLE,
    stem: 'Which Azure feature replicates an Azure SQL Database to one or more secondary regions for read scale-out and DR?',
    options: [{ id: 'A', text: 'Active geo-replication / Failover groups' }, { id: 'B', text: 'BACPAC export' }, { id: 'C', text: 'Linked servers' }, { id: 'D', text: 'Stored procedures' }],
    correct: ['A'],
    explanation: 'Active geo-replication and Failover Groups maintain readable secondary databases in other regions. BACPACs are export files; linked servers are cross-DB queries.' },
  { domain: 'Identify considerations for relational data on Azure', type: QType.SINGLE,
    stem: 'A column with a UNIQUE constraint and a column that is the PRIMARY KEY differ in what way?',
    options: [{ id: 'A', text: 'Only one PRIMARY KEY can exist per table; multiple UNIQUE constraints can. PK does not allow NULLs; UNIQUE typically allows one NULL' }, { id: 'B', text: 'They are identical' }, { id: 'C', text: 'PK allows duplicates' }, { id: 'D', text: 'UNIQUE allows infinite NULLs' }],
    correct: ['A'],
    explanation: 'A table has at most one PK, which disallows NULLs. UNIQUE constraints allow at most one NULL (in SQL Server) and a table can have many.' },
  { domain: 'Identify considerations for relational data on Azure', type: QType.SINGLE,
    stem: 'Which T-SQL clause limits the number of rows returned in SQL Server / Azure SQL?',
    options: [{ id: 'A', text: 'TOP n' }, { id: 'B', text: 'LIMIT n' }, { id: 'C', text: 'FETCH FIRST n ROWS WITH TIES' }, { id: 'D', text: 'Both A and C are valid' }],
    correct: ['D'],
    explanation: 'SQL Server supports `SELECT TOP n` and `OFFSET ... FETCH NEXT/FIRST n ROWS`. `LIMIT` is MySQL/PostgreSQL syntax.' },
  { domain: 'Identify considerations for relational data on Azure', type: QType.SINGLE,
    stem: 'Which feature in Azure SQL DB ENCRYPTS data at rest by default?',
    options: [{ id: 'A', text: 'Transparent Data Encryption (TDE)' }, { id: 'B', text: 'Always Encrypted' }, { id: 'C', text: 'Row-Level Security' }, { id: 'D', text: 'Dynamic Data Masking' }],
    correct: ['A'],
    explanation: 'TDE is enabled by default for Azure SQL DB / MI, encrypting data and log files at rest. Always Encrypted protects specific columns from the DBA. RLS filters rows; DDM masks display.' },
  { domain: 'Identify considerations for relational data on Azure', type: QType.SINGLE,
    stem: 'Which Azure service is a fully managed enterprise data warehouse for petabyte-scale analytics?',
    options: [{ id: 'A', text: 'Azure Synapse Analytics dedicated SQL pool' }, { id: 'B', text: 'Azure SQL Database' }, { id: 'C', text: 'Azure Database for MySQL' }, { id: 'D', text: 'Cosmos DB' }],
    correct: ['A'],
    explanation: 'Synapse dedicated SQL pool (formerly SQL DW) is MPP for large warehouses. Azure SQL DB is OLTP-style; MySQL is row-oriented PaaS; Cosmos is NoSQL.' },
  { domain: 'Identify considerations for relational data on Azure', type: QType.SINGLE,
    stem: 'Which T-SQL command would you use to RESTORE access for a user removed accidentally?',
    options: [{ id: 'A', text: 'GRANT' }, { id: 'B', text: 'REVOKE' }, { id: 'C', text: 'DENY' }, { id: 'D', text: 'DROP USER' }],
    correct: ['A'],
    explanation: 'GRANT assigns permissions. REVOKE removes; DENY explicitly forbids; DROP USER removes the principal.' },

  // ===== Non-relational data (10) =====
  { domain: 'Describe considerations for non-relational data on Azure', type: QType.SINGLE,
    stem: 'Which Azure Cosmos DB API stores key-value pairs with simple GET/PUT semantics?',
    options: [{ id: 'A', text: 'Cosmos DB for Table' }, { id: 'B', text: 'Cosmos DB for MongoDB' }, { id: 'C', text: 'Cosmos DB for Apache Cassandra' }, { id: 'D', text: 'Cosmos DB for Apache Gremlin' }],
    correct: ['A'],
    explanation: 'Cosmos DB Table API is the key-value option, evolved from Azure Table Storage. MongoDB/Cassandra are document/wide-column; Gremlin is graph.' },
  { domain: 'Describe considerations for non-relational data on Azure', type: QType.SINGLE,
    stem: 'Which Azure Cosmos DB API is best for graph data — nodes, edges, traversals?',
    options: [{ id: 'A', text: 'Cosmos DB for Apache Gremlin' }, { id: 'B', text: 'Cosmos DB for NoSQL' }, { id: 'C', text: 'Cosmos DB for Cassandra' }, { id: 'D', text: 'Cosmos DB for Table' }],
    correct: ['A'],
    explanation: 'Gremlin API stores graphs (nodes/edges) and supports the Gremlin traversal language.' },
  { domain: 'Describe considerations for non-relational data on Azure', type: QType.SINGLE,
    stem: 'Which Cosmos DB consistency level offers the strongest guarantee — reads see the latest write?',
    options: [{ id: 'A', text: 'Strong' }, { id: 'B', text: 'Bounded staleness' }, { id: 'C', text: 'Session' }, { id: 'D', text: 'Eventual' }],
    correct: ['A'],
    explanation: 'Strong = linearizable: reads always see the most recent committed write. Five levels: Strong, Bounded, Session, Consistent Prefix, Eventual.' },
  { domain: 'Describe considerations for non-relational data on Azure', type: QType.SINGLE,
    stem: 'Which Cosmos DB consistency level is the DEFAULT and provides "read your own writes" guarantees within a single client session?',
    options: [{ id: 'A', text: 'Session' }, { id: 'B', text: 'Strong' }, { id: 'C', text: 'Bounded staleness' }, { id: 'D', text: 'Eventual' }],
    correct: ['A'],
    explanation: 'Session is the default, balancing performance and developer expectations. Within the same session, reads see writes.' },
  { domain: 'Describe considerations for non-relational data on Azure', type: QType.SINGLE,
    stem: 'Which Azure Storage service provides object/blob storage with hot, cool, and archive tiers?',
    options: [{ id: 'A', text: 'Azure Blob Storage' }, { id: 'B', text: 'Azure Files' }, { id: 'C', text: 'Azure Table Storage' }, { id: 'D', text: 'Azure Queue Storage' }],
    correct: ['A'],
    explanation: 'Blob Storage is object storage with tiered pricing (Hot/Cool/Cold/Archive). Files = SMB shares; Table = key-value; Queue = messaging.' },
  { domain: 'Describe considerations for non-relational data on Azure', type: QType.SINGLE,
    stem: 'Which Azure service provides large-scale data lake storage built on top of Blob Storage with hierarchical namespace?',
    options: [{ id: 'A', text: 'Azure Data Lake Storage Gen2' }, { id: 'B', text: 'Azure Files' }, { id: 'C', text: 'Cosmos DB' }, { id: 'D', text: 'Azure Backup' }],
    correct: ['A'],
    explanation: 'ADLS Gen2 layers a Hadoop-compatible filesystem (HDFS-style hierarchy and ACLs) on Blob Storage for big-data analytics.' },
  { domain: 'Describe considerations for non-relational data on Azure', type: QType.SINGLE,
    stem: 'Which Azure Cosmos DB feature provides automatic global distribution to multiple regions with multi-master writes?',
    options: [{ id: 'A', text: 'Multi-region writes' }, { id: 'B', text: 'Local read-only replicas' }, { id: 'C', text: 'Backup vault' }, { id: 'D', text: 'NSG' }],
    correct: ['A'],
    explanation: 'Cosmos DB lets you enable multi-region writes for active-active geo-distribution.' },
  { domain: 'Describe considerations for non-relational data on Azure', type: QType.SINGLE,
    stem: 'In Cosmos DB, what is a Request Unit (RU)?',
    options: [{ id: 'A', text: 'A normalized currency for the cost of database operations (CPU, memory, IO)' }, { id: 'B', text: 'A networking metric' }, { id: 'C', text: 'A data type' }, { id: 'D', text: 'A backup tier' }],
    correct: ['A'],
    explanation: 'RUs abstract resource cost. You provision throughput in RU/s (or use serverless / autoscale).' },
  { domain: 'Describe considerations for non-relational data on Azure', type: QType.SINGLE,
    stem: 'Which Azure service is a NoSQL key-value store designed for very high-throughput retrieval, often used as a cache?',
    options: [{ id: 'A', text: 'Azure Cache for Redis' }, { id: 'B', text: 'Azure SQL Database' }, { id: 'C', text: 'Azure Synapse' }, { id: 'D', text: 'Azure Table Storage' }],
    correct: ['A'],
    explanation: 'Azure Cache for Redis is a managed Redis service used as session store or hot cache. Table Storage is key-value but not optimized for caching.' },
  { domain: 'Describe considerations for non-relational data on Azure', type: QType.SINGLE,
    stem: 'Which type of NoSQL database stores data as wide-column families and is good for time-series or IoT-style data?',
    options: [{ id: 'A', text: 'Wide-column store (e.g., Cosmos DB for Cassandra)' }, { id: 'B', text: 'Document database' }, { id: 'C', text: 'Graph database' }, { id: 'D', text: 'Key-value store' }],
    correct: ['A'],
    explanation: 'Wide-column stores (Cassandra, Cosmos for Cassandra) organize data by columns within column families — efficient for sparse, time-stamped data.' },

  // ===== Analytics workloads on Azure (22) =====
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which Azure service is an integrated analytics platform that combines data warehousing, big data, and pipeline orchestration in a single workspace?',
    options: [{ id: 'A', text: 'Azure Synapse Analytics' }, { id: 'B', text: 'Azure Cosmos DB' }, { id: 'C', text: 'Azure Functions' }, { id: 'D', text: 'Azure Bastion' }],
    correct: ['A'],
    explanation: 'Synapse unifies serverless/dedicated SQL pools, Spark pools, and pipelines (Data Factory) under one studio.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which Azure service is a hybrid data integration tool for ETL/ELT pipelines that visually orchestrates dataflows?',
    options: [{ id: 'A', text: 'Azure Data Factory' }, { id: 'B', text: 'Azure Synapse SQL pool' }, { id: 'C', text: 'Power BI Desktop' }, { id: 'D', text: 'Azure Logic Apps' }],
    correct: ['A'],
    explanation: 'Azure Data Factory builds data-movement pipelines with visual mapping and dataflows. Synapse incorporates similar pipelines.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which Microsoft tool is the primary self-service BI platform for building reports and dashboards from many data sources?',
    options: [{ id: 'A', text: 'Power BI' }, { id: 'B', text: 'Excel only' }, { id: 'C', text: 'Visual Studio' }, { id: 'D', text: 'SQL Server Management Studio' }],
    correct: ['A'],
    explanation: 'Power BI Desktop (authoring), Power BI Service (publishing/sharing), and Power BI Mobile are Microsoft\'s BI platform.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which Power BI artifact is the top-level container that holds reports, dashboards, datasets, and dataflows?',
    options: [{ id: 'A', text: 'Workspace' }, { id: 'B', text: 'Tile' }, { id: 'C', text: 'Visualization' }, { id: 'D', text: 'Slicer' }],
    correct: ['A'],
    explanation: 'Workspaces contain related Power BI content. Tiles are dashboard panels; visualizations are charts; slicers are filter controls.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which schema is commonly used in dimensional modeling, with a central fact table linked to dimension tables?',
    options: [{ id: 'A', text: 'Star schema' }, { id: 'B', text: '3NF' }, { id: 'C', text: 'Snowflake (denormalized)' }, { id: 'D', text: 'Document model' }],
    correct: ['A'],
    explanation: 'Star schemas have a fact table at the center, surrounded by denormalized dimensions. Snowflake schemas further normalize the dimensions.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which big-data engine, used in Azure Synapse and Azure Databricks, supports distributed in-memory analytics with Python/Scala/SQL?',
    options: [{ id: 'A', text: 'Apache Spark' }, { id: 'B', text: 'Apache Kafka' }, { id: 'C', text: 'Apache Hadoop MapReduce' }, { id: 'D', text: 'Apache Cassandra' }],
    correct: ['A'],
    explanation: 'Spark is the dominant in-memory analytics engine in Azure. Kafka is messaging; MapReduce is older batch; Cassandra is NoSQL DB.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which Power BI feature defines reusable, shared data preparation logic that produces tables consumed by datasets?',
    options: [{ id: 'A', text: 'Dataflows' }, { id: 'B', text: 'Tiles' }, { id: 'C', text: 'Bookmarks' }, { id: 'D', text: 'Reports' }],
    correct: ['A'],
    explanation: 'Power BI dataflows store reusable Power Query logic, output to a datalake, and are consumed by datasets across workspaces.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which Power BI artifact is an INTERACTIVE multi-page document containing visualizations bound to a dataset?',
    options: [{ id: 'A', text: 'Report' }, { id: 'B', text: 'Dashboard' }, { id: 'C', text: 'Workspace' }, { id: 'D', text: 'Dataflow' }],
    correct: ['A'],
    explanation: 'Reports are interactive multi-page documents. Dashboards are single-page summaries pinned from reports. Workspaces contain content; dataflows are data prep.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which Power BI artifact is a single-page summary that can pin tiles from many reports?',
    options: [{ id: 'A', text: 'Dashboard' }, { id: 'B', text: 'Report' }, { id: 'C', text: 'Tabular model' }, { id: 'D', text: 'Slicer' }],
    correct: ['A'],
    explanation: 'Dashboards aggregate pinned tiles for at-a-glance monitoring.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'In Power BI, which language is used to write expressions for calculated columns and measures?',
    options: [{ id: 'A', text: 'DAX (Data Analysis Expressions)' }, { id: 'B', text: 'M (Power Query)' }, { id: 'C', text: 'T-SQL' }, { id: 'D', text: 'KQL' }],
    correct: ['A'],
    explanation: 'DAX is the formula language in Power BI/SSAS Tabular. M is for Power Query data transformations. KQL is for Log Analytics.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'In Power BI, which language is used in Power Query to transform data during loading?',
    options: [{ id: 'A', text: 'M' }, { id: 'B', text: 'DAX' }, { id: 'C', text: 'T-SQL' }, { id: 'D', text: 'JavaScript' }],
    correct: ['A'],
    explanation: 'M (Power Query Formula Language) is the functional language behind Power Query steps.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which Azure analytics service provides a fully managed, serverless data exploration platform optimized for telemetry and time-series?',
    options: [{ id: 'A', text: 'Azure Data Explorer' }, { id: 'B', text: 'Azure SQL Database' }, { id: 'C', text: 'Azure Backup' }, { id: 'D', text: 'Azure DNS' }],
    correct: ['A'],
    explanation: 'Azure Data Explorer (ADX) is purpose-built for fast queries over time-series/telemetry/log data using KQL.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which Azure service provides Spark + Delta Lake + collaborative notebooks via a partnership with Databricks?',
    options: [{ id: 'A', text: 'Azure Databricks' }, { id: 'B', text: 'Azure Data Factory' }, { id: 'C', text: 'Azure SQL Database' }, { id: 'D', text: 'Azure App Service' }],
    correct: ['A'],
    explanation: 'Azure Databricks is the Microsoft-hosted Databricks offering — Spark, Delta Lake, MLflow, collaborative notebooks.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which Synapse compute option is a serverless SQL endpoint that lets you query files in a data lake without provisioning a SQL pool?',
    options: [{ id: 'A', text: 'Synapse Serverless SQL pool' }, { id: 'B', text: 'Synapse Dedicated SQL pool' }, { id: 'C', text: 'Synapse Spark pool' }, { id: 'D', text: 'Synapse Pipelines' }],
    correct: ['A'],
    explanation: 'Serverless SQL pools provide on-demand SQL queries against ADLS Gen2 (Parquet/CSV/JSON) with pay-per-TB-scanned pricing.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which star-schema concept stores numeric, additive measurements such as sales amount and quantity?',
    options: [{ id: 'A', text: 'Fact table' }, { id: 'B', text: 'Dimension table' }, { id: 'C', text: 'Bridge table' }, { id: 'D', text: 'Junk dimension' }],
    correct: ['A'],
    explanation: 'Fact tables hold numeric measures and FKs to dimensions. Dimensions describe context (date, product, customer).' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which Power BI sharing artifact is a curated, packaged collection of reports/dashboards/datasets used to distribute content to a broad audience?',
    options: [{ id: 'A', text: 'App' }, { id: 'B', text: 'Workspace' }, { id: 'C', text: 'Tile' }, { id: 'D', text: 'Bookmark' }],
    correct: ['A'],
    explanation: 'Power BI Apps are published, packaged content distributed to consumers (typically read-only viewers).' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which Azure service is the modern cloud-based ETL/ELT orchestrator that supports more than 90 data connectors and visual pipelines?',
    options: [{ id: 'A', text: 'Azure Data Factory' }, { id: 'B', text: 'Azure Logic Apps' }, { id: 'C', text: 'Azure Functions' }, { id: 'D', text: 'Azure Service Bus' }],
    correct: ['A'],
    explanation: 'ADF is purpose-built for data movement at scale with many connectors and Mapping/Wrangling Data Flows.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which type of analytics answers "What happened?" by summarizing past data?',
    options: [{ id: 'A', text: 'Descriptive' }, { id: 'B', text: 'Diagnostic' }, { id: 'C', text: 'Predictive' }, { id: 'D', text: 'Prescriptive' }],
    correct: ['A'],
    explanation: 'Descriptive = what happened. Diagnostic = why. Predictive = what will. Prescriptive = what should we do.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which type of analytics answers "Why did this happen?" by drilling into root causes?',
    options: [{ id: 'A', text: 'Diagnostic' }, { id: 'B', text: 'Descriptive' }, { id: 'C', text: 'Predictive' }, { id: 'D', text: 'Cognitive' }],
    correct: ['A'],
    explanation: 'Diagnostic analytics investigates causes via drilling, segmentation, and correlation.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which type of analytics uses ML/statistics to forecast future outcomes — "What will happen?"',
    options: [{ id: 'A', text: 'Predictive' }, { id: 'B', text: 'Descriptive' }, { id: 'C', text: 'Diagnostic' }, { id: 'D', text: 'Prescriptive' }],
    correct: ['A'],
    explanation: 'Predictive analytics models likely future outcomes. Prescriptive recommends actions.' },
  { domain: 'Describe analytics workloads on Azure', type: QType.SINGLE,
    stem: 'Which Azure service provides a managed, real-time stream-processing engine using SQL-like queries over Event Hubs/IoT Hub data?',
    options: [{ id: 'A', text: 'Azure Stream Analytics' }, { id: 'B', text: 'Azure Functions' }, { id: 'C', text: 'Azure Service Bus' }, { id: 'D', text: 'Azure Logic Apps' }],
    correct: ['A'],
    explanation: 'Stream Analytics processes real-time event streams with SQL-like temporal queries; outputs to Power BI, Synapse, blob, etc.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'microsoft-dp-900-p1', offset: 0 },
  { slug: 'microsoft-dp-900-p2', offset: 15 },
  { slug: 'microsoft-dp-900-p3', offset: 30 },
  { slug: 'microsoft-dp-900-p4', offset: 45 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: {
        examId: exam.id, domain: q.domain, difficulty: 3, type: q.type,
        stem: q.stem, options: q.options, correct: q.correct,
        explanation: q.explanation, references: [REF],
        status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false
      }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up Microsoft DP-900 exams to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => db.$disconnect());
