/**
 * Top-up: brings every CompTIA Server+ practice exam (P1-P4) to 60 questions
 * by distributing 60 hand-authored supplemental questions across the 4
 * Server+ domains.
 *
 *   npx tsx scripts/seed-comptia-server-plus-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';

const db = new PrismaClient();

const TARGET = 60;
const TAG_PREFIX = 'topup:comptia-server-plus';
const REF = { label: 'CompTIA Server+ exam objectives', url: 'https://www.comptia.org/certifications/server' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  // ===== Server Hardware Installation and Management (10) =====
  { domain: 'Server Hardware Installation and Management', type: QType.SINGLE,
    stem: 'A server administrator wants to allow a failed power supply to be replaced without shutting down the server. Which feature is required?',
    options: [{ id: 'A', text: 'Hot-swappable power supplies in a redundant (N+1) configuration' }, { id: 'B', text: 'A single 80-PLUS Gold supply' }, { id: 'C', text: 'A UPS' }, { id: 'D', text: 'ECC memory' }],
    correct: ['A'],
    explanation: 'Hot-swappable redundant PSUs (N+1 / 1+1) let one fail or be replaced while the other powers the server. UPS provides battery backup; ECC handles memory errors.' },
  { domain: 'Server Hardware Installation and Management', type: QType.SINGLE,
    stem: 'Which RAID level provides striping with distributed parity, requiring at least 3 disks and tolerating one drive failure?',
    options: [{ id: 'A', text: 'RAID 0' }, { id: 'B', text: 'RAID 1' }, { id: 'C', text: 'RAID 5' }, { id: 'D', text: 'RAID 10' }],
    correct: ['C'],
    explanation: 'RAID 5 = striping + distributed parity, ≥3 disks, survives one disk failure. RAID 0 is striping only (no redundancy); RAID 1 mirrors; RAID 10 is striped mirror.' },
  { domain: 'Server Hardware Installation and Management', type: QType.SINGLE,
    stem: 'Which RAID level combines mirroring and striping for both performance and redundancy, tolerating multiple drive failures (not in the same mirror)?',
    options: [{ id: 'A', text: 'RAID 5' }, { id: 'B', text: 'RAID 6' }, { id: 'C', text: 'RAID 10' }, { id: 'D', text: 'RAID 0' }],
    correct: ['C'],
    explanation: 'RAID 10 (1+0) stripes data across mirrored pairs. Performance is high, and as long as both drives in any single mirror don\'t fail simultaneously, the array survives.' },
  { domain: 'Server Hardware Installation and Management', type: QType.SINGLE,
    stem: 'Which memory technology detects AND corrects single-bit errors, recommended for production servers?',
    options: [{ id: 'A', text: 'ECC (Error-Correcting Code)' }, { id: 'B', text: 'Non-ECC DDR4' }, { id: 'C', text: 'LPDDR' }, { id: 'D', text: 'GDDR' }],
    correct: ['A'],
    explanation: 'ECC memory detects/corrects single-bit errors and detects multi-bit errors. Non-ECC is cheaper but lacks correction; LPDDR/GDDR are mobile/graphics RAM.' },
  { domain: 'Server Hardware Installation and Management', type: QType.SINGLE,
    stem: 'A datacenter cabinet uses standardized vertical units. What is 1U?',
    options: [{ id: 'A', text: '1.75 inches (44.45 mm)' }, { id: 'B', text: '1 cm' }, { id: 'C', text: '1 foot' }, { id: 'D', text: '1 meter' }],
    correct: ['A'],
    explanation: 'A rack unit (1U) is 1.75 inches / 44.45 mm tall. Standard racks are 19 inches wide.' },
  { domain: 'Server Hardware Installation and Management', type: QType.SINGLE,
    stem: 'Which connector is used for SAS hard drives in modern enterprise servers?',
    options: [{ id: 'A', text: 'SATA' }, { id: 'B', text: 'eSATA' }, { id: 'C', text: 'SFF-8482 / SFF-8639 / SFF-8643' }, { id: 'D', text: 'IDE' }],
    correct: ['C'],
    explanation: 'SAS uses connectors like SFF-8482 (single-port), SFF-8643 (mini-SAS HD internal), and SFF-8639/U.2 (dual-port for SAS/NVMe). SATA/IDE connectors are for SATA/legacy drives.' },
  { domain: 'Server Hardware Installation and Management', type: QType.SINGLE,
    stem: 'Which interface is the modern replacement for SATA/SAS for high-speed solid-state drives, attached over PCIe lanes?',
    options: [{ id: 'A', text: 'NVMe' }, { id: 'B', text: 'SCSI' }, { id: 'C', text: 'Fibre Channel' }, { id: 'D', text: 'iSCSI' }],
    correct: ['A'],
    explanation: 'NVMe (Non-Volatile Memory Express) drives connect via PCIe (M.2 or U.2) for much higher throughput and lower latency than SATA/SAS.' },
  { domain: 'Server Hardware Installation and Management', type: QType.SINGLE,
    stem: 'A server uses BIOS/UEFI Secure Boot. What does Secure Boot do?',
    options: [{ id: 'A', text: 'Verifies that bootloader and OS kernel signatures match a trusted database before they execute' }, { id: 'B', text: 'Encrypts the disk' }, { id: 'C', text: 'Enables Wake-on-LAN' }, { id: 'D', text: 'Disables USB ports' }],
    correct: ['A'],
    explanation: 'Secure Boot validates digital signatures of boot components against a UEFI trust store, preventing rootkits/bootkits from loading.' },
  { domain: 'Server Hardware Installation and Management', type: QType.SINGLE,
    stem: 'Which power configuration ensures continuous availability if a single PDU or PSU fails?',
    options: [{ id: 'A', text: 'Dual power feeds with redundant power supplies on separate PDUs' }, { id: 'B', text: 'A single circuit with one PSU' }, { id: 'C', text: 'Daisy-chained surge protectors' }, { id: 'D', text: 'A 12V wall adapter' }],
    correct: ['A'],
    explanation: 'Servers in HA datacenters use two PSUs each on different PDUs/feeds (and ideally different UPSes), so any one failure is non-disruptive.' },
  { domain: 'Server Hardware Installation and Management', type: QType.SINGLE,
    stem: 'What is the purpose of an out-of-band management interface (e.g., iDRAC, iLO, IPMI)?',
    options: [{ id: 'A', text: 'A dedicated network port that lets administrators manage the server even when the main OS is offline' }, { id: 'B', text: 'A redundant data network' }, { id: 'C', text: 'A serial-only console' }, { id: 'D', text: 'A USB-only debugging port' }],
    correct: ['A'],
    explanation: 'Out-of-band management (iDRAC/iLO/IPMI/Redfish) provides remote power control, console redirection, sensor monitoring, and firmware updates independent of the OS state.' },

  // ===== Server Administration (18) =====
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'Which Windows Server role provides centralized authentication, authorization, and Group Policy?',
    options: [{ id: 'A', text: 'Active Directory Domain Services (AD DS)' }, { id: 'B', text: 'IIS' }, { id: 'C', text: 'DHCP Server' }, { id: 'D', text: 'File and Storage Services' }],
    correct: ['A'],
    explanation: 'AD DS hosts the directory database, authenticates users via Kerberos, and enforces Group Policy. IIS hosts web apps; DHCP assigns IPs; File Services serves SMB shares.' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'A Linux administrator needs to schedule a recurring maintenance script every weekday at 2:00 AM. Which tool is most appropriate?',
    options: [{ id: 'A', text: 'cron (with a crontab entry)' }, { id: 'B', text: 'apt-get' }, { id: 'C', text: 'systemctl' }, { id: 'D', text: 'nmcli' }],
    correct: ['A'],
    explanation: 'cron schedules recurring jobs via crontab. systemctl manages services; apt-get installs packages; nmcli configures networking.' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'In Linux, which file lists all currently mounted filesystems with their mount points and types?',
    options: [{ id: 'A', text: '/etc/fstab' }, { id: 'B', text: '/proc/mounts' }, { id: 'C', text: '/etc/hosts' }, { id: 'D', text: '/var/log/auth.log' }],
    correct: ['B'],
    explanation: '/proc/mounts (and `mount` output) shows actively mounted filesystems. /etc/fstab lists what SHOULD be mounted at boot. /etc/hosts is name resolution; auth.log is auth events.' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'Which Windows feature creates a snapshot of files for point-in-time recovery and is used by Volume Shadow Copy Service (VSS)?',
    options: [{ id: 'A', text: 'Shadow Copies / VSS snapshots' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Storage Spaces' }, { id: 'D', text: 'Defender Antivirus' }],
    correct: ['A'],
    explanation: 'Shadow Copies are point-in-time snapshots managed by VSS. BitLocker encrypts disks; Storage Spaces pools storage; Defender is AV.' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'Which Linux package manager is native to Debian/Ubuntu?',
    options: [{ id: 'A', text: 'yum' }, { id: 'B', text: 'dnf' }, { id: 'C', text: 'apt' }, { id: 'D', text: 'pacman' }],
    correct: ['C'],
    explanation: 'apt is Debian/Ubuntu. yum/dnf are RHEL/CentOS/Fedora. pacman is Arch.' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'Which command shows established TCP connections and listening ports on a Linux server?',
    options: [{ id: 'A', text: 'ss -tunap' }, { id: 'B', text: 'curl' }, { id: 'C', text: 'rsync' }, { id: 'D', text: 'mount' }],
    correct: ['A'],
    explanation: '`ss -tunap` (or `netstat -tunap`) shows TCP/UDP sockets, numeric ports/addresses, and processes. curl makes HTTP requests; rsync syncs files; mount manages filesystems.' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'Which Windows Server feature provides high-availability clustering for services like file shares and SQL Server?',
    options: [{ id: 'A', text: 'Failover Clustering' }, { id: 'B', text: 'Hyper-V' }, { id: 'C', text: 'IIS' }, { id: 'D', text: 'Storage Replica' }],
    correct: ['A'],
    explanation: 'Failover Clustering provides HA for clustered roles. Hyper-V is virtualization; IIS hosts web apps; Storage Replica replicates volumes between servers.' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'A Linux user wants their script to run with elevated privileges only for specific commands listed in a config file. Which mechanism should they use?',
    options: [{ id: 'A', text: 'sudo with /etc/sudoers entries' }, { id: 'B', text: 'Logging in as root permanently' }, { id: 'C', text: 'chmod 777 on /etc' }, { id: 'D', text: 'Setting SUID on every binary' }],
    correct: ['A'],
    explanation: 'sudo, configured via /etc/sudoers (or /etc/sudoers.d), grants per-command privilege. The other options are insecure or destructive.' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'Which Linux command displays the system\'s memory usage including total, used, free, buffer/cache, and swap?',
    options: [{ id: 'A', text: 'free -h' }, { id: 'B', text: 'df -h' }, { id: 'C', text: 'du -sh' }, { id: 'D', text: 'top' }],
    correct: ['A'],
    explanation: '`free` shows memory/swap totals. `df` shows disk usage; `du` shows directory size; `top`/`htop` show process-level resource usage.' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'Which protocol allows Windows clients to access shared folders on a server?',
    options: [{ id: 'A', text: 'SMB / CIFS' }, { id: 'B', text: 'NFS' }, { id: 'C', text: 'iSCSI' }, { id: 'D', text: 'FTP' }],
    correct: ['A'],
    explanation: 'SMB (CIFS) is the Windows file-sharing protocol. NFS is Unix/Linux; iSCSI is block storage; FTP is for file transfer (not mounted shares).' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'Which protocol allows Linux/Unix clients to mount remote directories as if they were local filesystems?',
    options: [{ id: 'A', text: 'SMB' }, { id: 'B', text: 'NFS' }, { id: 'C', text: 'SFTP' }, { id: 'D', text: 'HTTP' }],
    correct: ['B'],
    explanation: 'NFS (Network File System) is the canonical Unix file-sharing protocol that mounts remote directories.' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'A virtualization administrator needs to dedicate a physical NIC to a guest VM, bypassing the hypervisor\'s virtual switch for performance. Which feature should they use?',
    options: [{ id: 'A', text: 'PCI passthrough / SR-IOV' }, { id: 'B', text: 'NIC teaming on the host only' }, { id: 'C', text: 'Disable the guest network stack' }, { id: 'D', text: 'Add a second virtual switch' }],
    correct: ['A'],
    explanation: 'PCI passthrough (or SR-IOV with virtual functions) lets a VM directly access a physical NIC, bypassing virtual-switch overhead.' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'Which Linux service manager is the modern replacement for SysV init on most major distributions?',
    options: [{ id: 'A', text: 'systemd' }, { id: 'B', text: 'Upstart' }, { id: 'C', text: 'BSD rc' }, { id: 'D', text: 'launchd' }],
    correct: ['A'],
    explanation: 'systemd is the dominant Linux init/service manager (RHEL 7+, Ubuntu 16.04+, Debian 8+, Fedora). Upstart was used briefly; BSD rc is for FreeBSD; launchd for macOS.' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'Which command lists active systemd services and their states?',
    options: [{ id: 'A', text: 'systemctl list-units --type=service' }, { id: 'B', text: 'service status-all' }, { id: 'C', text: 'init 6' }, { id: 'D', text: 'apt update' }],
    correct: ['A'],
    explanation: '`systemctl list-units --type=service` enumerates services with state. `service status-all` is SysV-era; init 6 reboots; apt is package management.' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'Which file in Linux contains user account information (login name, UID, home directory)?',
    options: [{ id: 'A', text: '/etc/passwd' }, { id: 'B', text: '/etc/shadow' }, { id: 'C', text: '/etc/group' }, { id: 'D', text: '/etc/sudoers' }],
    correct: ['A'],
    explanation: '/etc/passwd holds account metadata. /etc/shadow stores password hashes; /etc/group defines groups; /etc/sudoers configures sudo.' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'Which directory typically contains application-level log files on a Linux server?',
    options: [{ id: 'A', text: '/var/log' }, { id: 'B', text: '/etc' }, { id: 'C', text: '/usr/bin' }, { id: 'D', text: '/dev' }],
    correct: ['A'],
    explanation: '/var/log is the standard location for system and application logs (syslog, auth.log, nginx, etc.). /etc holds configs; /usr/bin holds executables; /dev holds device files.' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'Which configuration management tool uses an agentless, push-based model over SSH and YAML "playbooks"?',
    options: [{ id: 'A', text: 'Ansible' }, { id: 'B', text: 'Puppet' }, { id: 'C', text: 'Chef' }, { id: 'D', text: 'SaltStack (in master/minion mode)' }],
    correct: ['A'],
    explanation: 'Ansible is agentless and SSH-based; playbooks are YAML. Puppet/Chef are agent-pull-based; Salt typically uses an agent (master/minion).' },
  { domain: 'Server Administration', type: QType.SINGLE,
    stem: 'A user reports their data drive is "out of space" but `df -h` shows 50% free. Which command checks for inode exhaustion?',
    options: [{ id: 'A', text: 'df -i' }, { id: 'B', text: 'du -h' }, { id: 'C', text: 'free -h' }, { id: 'D', text: 'top' }],
    correct: ['A'],
    explanation: '`df -i` reports inode usage. A filesystem can run out of inodes (lots of small files) even with free blocks remaining.' },

  // ===== Security and Disaster Recovery (14) =====
  { domain: 'Security and Disaster Recovery', type: QType.SINGLE,
    stem: 'Which backup type captures only data that has changed since the LAST FULL backup?',
    options: [{ id: 'A', text: 'Differential' }, { id: 'B', text: 'Incremental' }, { id: 'C', text: 'Synthetic full' }, { id: 'D', text: 'Snapshot' }],
    correct: ['A'],
    explanation: 'Differential = since last FULL. Incremental = since LAST INCREMENTAL (or full). Differentials grow over time; incrementals stay small.' },
  { domain: 'Security and Disaster Recovery', type: QType.SINGLE,
    stem: 'In disaster recovery, what does the Recovery Point Objective (RPO) measure?',
    options: [{ id: 'A', text: 'The maximum tolerable amount of data loss measured in time' }, { id: 'B', text: 'The total downtime allowed' }, { id: 'C', text: 'The cost of recovery' }, { id: 'D', text: 'The number of staff needed' }],
    correct: ['A'],
    explanation: 'RPO = how far back can we restore (data loss tolerance). RTO = how quickly must we be back online (downtime tolerance).' },
  { domain: 'Security and Disaster Recovery', type: QType.SINGLE,
    stem: 'In disaster recovery, what does the Recovery Time Objective (RTO) measure?',
    options: [{ id: 'A', text: 'Maximum acceptable downtime before service is restored' }, { id: 'B', text: 'How far back data is restored' }, { id: 'C', text: 'Backup retention period' }, { id: 'D', text: 'Encryption key rotation interval' }],
    correct: ['A'],
    explanation: 'RTO is the deadline for restoring service after disruption.' },
  { domain: 'Security and Disaster Recovery', type: QType.SINGLE,
    stem: 'Which hardening practice reduces the attack surface of a server?',
    options: [{ id: 'A', text: 'Disable unused services and uninstall unnecessary packages' }, { id: 'B', text: 'Run all services as root' }, { id: 'C', text: 'Open all firewall ports' }, { id: 'D', text: 'Disable patching' }],
    correct: ['A'],
    explanation: 'Removing unused services/packages eliminates code that could host vulnerabilities. The other options expand the attack surface.' },
  { domain: 'Security and Disaster Recovery', type: QType.SINGLE,
    stem: 'Which Windows feature provides full-volume encryption with TPM-backed key protection?',
    options: [{ id: 'A', text: 'BitLocker' }, { id: 'B', text: 'Defender Antivirus' }, { id: 'C', text: 'Windows Update' }, { id: 'D', text: 'Dynamic Access Control' }],
    correct: ['A'],
    explanation: 'BitLocker encrypts entire volumes; on TPM-equipped systems, the key is sealed to platform measurements. The other features serve different purposes.' },
  { domain: 'Security and Disaster Recovery', type: QType.SINGLE,
    stem: 'A sysadmin needs to encrypt a Linux block device for laptops. Which technology is the standard?',
    options: [{ id: 'A', text: 'LUKS / dm-crypt' }, { id: 'B', text: 'EFS' }, { id: 'C', text: 'BitLocker' }, { id: 'D', text: 'NTFS encryption' }],
    correct: ['A'],
    explanation: 'LUKS (Linux Unified Key Setup) on top of dm-crypt is the standard Linux block encryption. EFS/BitLocker/NTFS-encryption are Windows.' },
  { domain: 'Security and Disaster Recovery', type: QType.SINGLE,
    stem: 'Which alternate-site type contains the necessary hardware but does NOT have current data — that data must be restored before operations resume?',
    options: [{ id: 'A', text: 'Cold site' }, { id: 'B', text: 'Warm site' }, { id: 'C', text: 'Hot site' }, { id: 'D', text: 'Mirrored site' }],
    correct: ['B'],
    explanation: 'Warm site = facility + hardware, but data must be loaded. Cold = facility only. Hot = fully running mirror. Mirrored site is the most expensive HA option.' },
  { domain: 'Security and Disaster Recovery', type: QType.SINGLE,
    stem: 'Which security control physically prevents access to the server room while allowing only one person to enter at a time?',
    options: [{ id: 'A', text: 'Mantrap' }, { id: 'B', text: 'Bollard' }, { id: 'C', text: 'Turnstile' }, { id: 'D', text: 'Fence' }],
    correct: ['A'],
    explanation: 'Mantraps are interlocking double-door vestibules that allow one person at a time after authentication, defeating tailgating.' },
  { domain: 'Security and Disaster Recovery', type: QType.SINGLE,
    stem: 'Which type of fire suppression is preferred for datacenters because it does not damage electronics or leave residue?',
    options: [{ id: 'A', text: 'Wet pipe sprinklers' }, { id: 'B', text: 'Clean agent gas (e.g., FM-200, Novec 1230, inert gases)' }, { id: 'C', text: 'Foam' }, { id: 'D', text: 'Dry chemical powder' }],
    correct: ['B'],
    explanation: 'Clean agent gases extinguish fire by removing heat or oxygen without damaging electronics. Water/foam/powder all damage equipment and require cleanup.' },
  { domain: 'Security and Disaster Recovery', type: QType.SINGLE,
    stem: 'A best-practice backup strategy is the 3-2-1 rule. What does it stand for?',
    options: [{ id: 'A', text: '3 copies of data, on 2 different media types, with 1 copy off-site' }, { id: 'B', text: '3 daily backups in 2 datacenters in 1 country' }, { id: 'C', text: '3 administrators, 2 keys, 1 vault' }, { id: 'D', text: '3 weeks of retention, 2 weeks of differentials, 1 week of incrementals' }],
    correct: ['A'],
    explanation: 'The 3-2-1 rule: 3 copies of data, 2 different media types, 1 stored off-site. Provides resilience to disk failure, site disasters, and ransomware.' },
  { domain: 'Security and Disaster Recovery', type: QType.SINGLE,
    stem: 'Which security mechanism enforces server password rotation, complexity, and lockout policies on Windows domain accounts?',
    options: [{ id: 'A', text: 'Group Policy / Fine-Grained Password Policy' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Windows Defender Firewall' }, { id: 'D', text: 'IIS' }],
    correct: ['A'],
    explanation: 'Group Policy (and Fine-Grained Password Policy via PSO) defines complexity, lockout, and rotation. BitLocker encrypts; Firewall filters traffic; IIS hosts web apps.' },
  { domain: 'Security and Disaster Recovery', type: QType.SINGLE,
    stem: 'A datacenter has hot-aisle/cold-aisle layout. What is the primary purpose?',
    options: [{ id: 'A', text: 'Improve cooling efficiency by separating intake and exhaust airflow' }, { id: 'B', text: 'Reduce dust accumulation' }, { id: 'C', text: 'Discourage tailgating' }, { id: 'D', text: 'Comply with PCI DSS' }],
    correct: ['A'],
    explanation: 'Alternating hot (exhaust) and cold (intake) aisles reduces hot-air recirculation and improves CRAC efficiency.' },
  { domain: 'Security and Disaster Recovery', type: QType.SINGLE,
    stem: 'A backup that stores ONLY the changed blocks since the last backup of any kind, requiring the chain of all incrementals plus the last full to restore, is what type?',
    options: [{ id: 'A', text: 'Incremental' }, { id: 'B', text: 'Differential' }, { id: 'C', text: 'Mirror' }, { id: 'D', text: 'Synthetic full' }],
    correct: ['A'],
    explanation: 'Incremental backs up since the last backup of any kind. Restore needs the full + every incremental in order.' },
  { domain: 'Security and Disaster Recovery', type: QType.SINGLE,
    stem: 'Which authentication mechanism requires two independent factors from different categories (e.g., password + hardware token)?',
    options: [{ id: 'A', text: 'Two-factor authentication (2FA)' }, { id: 'B', text: 'Single sign-on' }, { id: 'C', text: 'Privileged access management' }, { id: 'D', text: 'NTLM' }],
    correct: ['A'],
    explanation: '2FA combines two distinct factor categories — knowledge, possession, inherence. SSO is one-login-many-apps; PAM is privileged-account governance; NTLM is a legacy protocol.' },

  // ===== Troubleshooting (18) =====
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'A server\'s CPU temperature alarm is triggering frequently. What is the FIRST thing to check?',
    options: [{ id: 'A', text: 'Airflow obstruction, dust on heatsinks/fans, and ambient room temperature' }, { id: 'B', text: 'CPU clock speed' }, { id: 'C', text: 'BIOS time' }, { id: 'D', text: 'TLS certificate expiration' }],
    correct: ['A'],
    explanation: 'Thermal alarms typically come from cooling problems: blocked airflow, dust, failed fans, or hot ambient room. Address the physical cause first.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'A user reports that connections to a web server time out intermittently. Which command on the SERVER would help diagnose dropped or queued connections?',
    options: [{ id: 'A', text: '`ss -s` and checking listen-queue overflow counters' }, { id: 'B', text: '`ls -l`' }, { id: 'C', text: '`mkdir`' }, { id: 'D', text: '`chmod 777`' }],
    correct: ['A'],
    explanation: '`ss -s` shows socket statistics; checking listen overflows and accept queue size pinpoints connection-rate problems. The other commands are unrelated.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'A RAID 5 array shows "DEGRADED" with one disk failed. What should the administrator do FIRST?',
    options: [{ id: 'A', text: 'Verify backups are current, replace the failed disk, and let the array rebuild' }, { id: 'B', text: 'Power down the server permanently' }, { id: 'C', text: 'Install a different RAID controller' }, { id: 'D', text: 'Reformat the entire array' }],
    correct: ['A'],
    explanation: 'In RAID 5, one disk failure is survivable. Verify backups (in case a second disk fails during rebuild), replace the failed drive, and rebuild.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'Which Linux command shows the boot/kernel messages and is useful for diagnosing hardware initialization issues?',
    options: [{ id: 'A', text: 'dmesg' }, { id: 'B', text: 'whoami' }, { id: 'C', text: 'uptime' }, { id: 'D', text: 'date' }],
    correct: ['A'],
    explanation: '`dmesg` (and `journalctl -k`) prints kernel ring-buffer messages including hardware probes, driver loads, and errors.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'A Linux server\'s root filesystem is full. Which command finds the largest directories under /var?',
    options: [{ id: 'A', text: 'du -sh /var/* | sort -h' }, { id: 'B', text: 'cat /var' }, { id: 'C', text: 'ping /var' }, { id: 'D', text: 'mv /var /tmp' }],
    correct: ['A'],
    explanation: '`du -sh /var/*` summarizes each subdir; piping to `sort -h` orders by human-readable size to find the worst offenders.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'A Windows server fails to boot, stopping at "INACCESSIBLE_BOOT_DEVICE". What is the most likely cause?',
    options: [{ id: 'A', text: 'Storage controller driver mismatch or disk hardware/configuration change' }, { id: 'B', text: 'Wrong domain controller' }, { id: 'C', text: 'IP conflict' }, { id: 'D', text: 'Expired antivirus license' }],
    correct: ['A'],
    explanation: 'INACCESSIBLE_BOOT_DEVICE usually means the OS cannot read the boot volume — typically driver/firmware/storage controller issues or hardware change after restore.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'A user complains that DNS resolution fails for a particular domain. Which Linux command tests resolution against a specific DNS server?',
    options: [{ id: 'A', text: 'dig @8.8.8.8 example.com' }, { id: 'B', text: 'curl example.com' }, { id: 'C', text: 'tar -xf' }, { id: 'D', text: 'whoami' }],
    correct: ['A'],
    explanation: '`dig @<server> <name>` queries a specific DNS server, isolating client vs. resolver vs. authoritative issues.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'Network packets aren\'t reaching a server. Which Linux tool traces the path packets take to a destination, showing each hop?',
    options: [{ id: 'A', text: 'traceroute (or mtr)' }, { id: 'B', text: 'curl' }, { id: 'C', text: 'rsync' }, { id: 'D', text: 'apt' }],
    correct: ['A'],
    explanation: '`traceroute` and `mtr` trace packet paths and identify where loss/latency occurs.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'A disk shows "PRE-FAIL" SMART warnings. What is the recommended action?',
    options: [{ id: 'A', text: 'Replace the disk preemptively before it fails completely' }, { id: 'B', text: 'Ignore — SMART always reports false positives' }, { id: 'C', text: 'Reformat to clear SMART history' }, { id: 'D', text: 'Run a hash check' }],
    correct: ['A'],
    explanation: 'PRE-FAIL SMART attributes (reallocated sectors, pending sectors) signal imminent failure. Replace and rebuild the array.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'After a Windows update, a domain-joined server cannot log in users. The error mentions "trust relationship between this workstation and the primary domain failed." What action restores the trust?',
    options: [{ id: 'A', text: 'Reset the computer account password (e.g., `Test-ComputerSecureChannel -Repair` or rejoin the domain)' }, { id: 'B', text: 'Reboot indefinitely' }, { id: 'C', text: 'Reformat the domain controller' }, { id: 'D', text: 'Disable Active Directory' }],
    correct: ['A'],
    explanation: 'Trust failure is the computer account password being out of sync. `Test-ComputerSecureChannel -Repair` (or rejoin) restores it.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'A Linux service fails to start. Which command shows the most recent journalctl entries for that service?',
    options: [{ id: 'A', text: 'journalctl -u <service> -n 50 --no-pager' }, { id: 'B', text: 'echo' }, { id: 'C', text: 'mv' }, { id: 'D', text: 'true' }],
    correct: ['A'],
    explanation: '`journalctl -u <service>` filters logs to a specific systemd unit. Adding `-n 50` returns the last 50 lines.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'A virtual machine\'s CPU is constantly pegged at 100% but the application is idle. Which troubleshooting step is most useful FIRST?',
    options: [{ id: 'A', text: 'Identify the runaway process with `top`/`htop` and gather a stack/profile to diagnose the hot loop' }, { id: 'B', text: 'Add more vCPU immediately without diagnosing' }, { id: 'C', text: 'Reboot every hour' }, { id: 'D', text: 'Disable monitoring' }],
    correct: ['A'],
    explanation: 'Diagnose the cause: which process owns the CPU, why is it busy. Adding vCPU without diagnosis just wastes resources.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'A user reports they can ping a server by IP but not by hostname. What is the LIKELY cause?',
    options: [{ id: 'A', text: 'DNS resolution problem' }, { id: 'B', text: 'Switch failure' }, { id: 'C', text: 'Disk full on the server' }, { id: 'D', text: 'Expired certificate' }],
    correct: ['A'],
    explanation: 'IP works → network is fine. Name doesn\'t resolve → DNS issue (resolver, /etc/hosts, network DNS settings).' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'A web server returns "503 Service Unavailable" when load increases. Which is the MOST LIKELY cause?',
    options: [{ id: 'A', text: 'Backend application pool/upstream is exhausted (worker saturation, queue overflow)' }, { id: 'B', text: 'DNS misconfiguration' }, { id: 'C', text: 'BIOS misconfiguration' }, { id: 'D', text: 'Wrong subnet mask' }],
    correct: ['A'],
    explanation: '503 typically means upstream/app pool is full or unavailable. Scale workers/check health checks.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'During troubleshooting methodology, what is the FIRST step?',
    options: [{ id: 'A', text: 'Identify the problem (gather information, scope the issue)' }, { id: 'B', text: 'Implement a fix' }, { id: 'C', text: 'Document the resolution' }, { id: 'D', text: 'Verify functionality' }],
    correct: ['A'],
    explanation: 'CompTIA troubleshooting methodology: 1) Identify, 2) Theory of probable cause, 3) Test theory, 4) Plan, 5) Implement, 6) Verify, 7) Document.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'Which network captures issue is most likely the cause of "duplicate IP" alerts on a server?',
    options: [{ id: 'A', text: 'Two devices statically assigned the same IP, or a DHCP scope overlap' }, { id: 'B', text: 'A bad RAID battery' }, { id: 'C', text: 'CPU thermal throttling' }, { id: 'D', text: 'Filesystem corruption' }],
    correct: ['A'],
    explanation: 'Duplicate IPs come from address conflicts: two static assignments, DHCP scope overlap, or stale DHCP reservations.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'A Linux server logs `Out of memory: Killed process N (process_name)`. What does the kernel OOM killer indicate?',
    options: [{ id: 'A', text: 'The system is exhausted of RAM/swap, so the kernel terminated a process to free memory' }, { id: 'B', text: 'A power supply failure' }, { id: 'C', text: 'A failed disk' }, { id: 'D', text: 'A network outage' }],
    correct: ['A'],
    explanation: 'OOM killer activates when memory is exhausted; selects a victim process based on oom_score. Add memory, lower memory pressure, or tune oom_score.' },
  { domain: 'Troubleshooting', type: QType.SINGLE,
    stem: 'A Windows event log shows "NTP source not reachable" and time has drifted. Which service is most likely affected?',
    options: [{ id: 'A', text: 'Kerberos (which requires synchronized clocks within ~5 minutes)' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Hyper-V' }, { id: 'D', text: 'Storage Replica' }],
    correct: ['A'],
    explanation: 'Kerberos rejects requests when clocks differ by more than the configured tolerance (default 5 min). Time drift breaks domain authentication first.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'comptia-server-plus-p1', offset: 0 },
  { slug: 'comptia-server-plus-p2', offset: 15 },
  { slug: 'comptia-server-plus-p3', offset: 30 },
  { slug: 'comptia-server-plus-p4', offset: 45 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: {
        examId: exam.id, domain: q.domain, difficulty: 3, type: q.type,
        stem: q.stem, options: q.options, correct: q.correct,
        explanation: q.explanation, references: [REF],
        status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false
      }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up CompTIA Server+ exams to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
  console.log(`✓ Server+ topup complete.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => db.$disconnect());
