/**
 * Top-up: DP-203 P1 to 60 questions.
 *   npx tsx scripts/seed-microsoft-dp-203-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();
const TARGET = 60;
const TAG = 'topup:microsoft-dp-203-p1';
const REF = { label: 'Microsoft DP-203 exam page', url: 'https://learn.microsoft.com/en-us/credentials/certifications/exams/dp-203/' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  { domain: 'Design and implement data storage', type: QType.SINGLE, stem: 'Which Azure service is the recommended landing zone for big-data analytics with hierarchical namespace?', options: [{ id: 'A', text: 'Azure Data Lake Storage Gen2' }, { id: 'B', text: 'Azure Files' }, { id: 'C', text: 'Azure Queue Storage' }, { id: 'D', text: 'Azure Table Storage' }], correct: ['A'], explanation: 'ADLS Gen2 layers HDFS-style hierarchical namespace and POSIX ACLs over Blob Storage.' },
  { domain: 'Design and implement data storage', type: QType.SINGLE, stem: 'Which Synapse compute lets you query Parquet/CSV files in ADLS without provisioning clusters?', options: [{ id: 'A', text: 'Serverless SQL pool' }, { id: 'B', text: 'Dedicated SQL pool' }, { id: 'C', text: 'Spark pool' }, { id: 'D', text: 'Pipeline orchestrator' }], correct: ['A'], explanation: 'Serverless SQL pool charges per-TB-scanned and queries data lake files without provisioned compute.' },
  { domain: 'Design and implement data storage', type: QType.SINGLE, stem: 'Which file format is the preferred columnar format for big-data analytics on data lakes?', options: [{ id: 'A', text: 'Apache Parquet' }, { id: 'B', text: 'CSV' }, { id: 'C', text: 'XML' }, { id: 'D', text: 'YAML' }], correct: ['A'], explanation: 'Parquet is columnar, compressed, and schema-aware. CSV is row-based and inefficient for analytics.' },
  { domain: 'Design and implement data storage', type: QType.SINGLE, stem: 'Which feature of Azure Synapse Dedicated SQL pool DISTRIBUTES large fact tables across compute nodes by hashing a key?', options: [{ id: 'A', text: 'HASH distribution' }, { id: 'B', text: 'ROUND_ROBIN distribution' }, { id: 'C', text: 'REPLICATE distribution' }, { id: 'D', text: 'CLUSTERED COLUMNSTORE' }], correct: ['A'], explanation: 'HASH on a join key co-locates rows for fast joins. ROUND_ROBIN evenly spreads (no key); REPLICATE copies dimensions; CCI is a storage format.' },
  { domain: 'Design and implement data storage', type: QType.SINGLE, stem: 'Which storage format extends Parquet with ACID transactions and time travel, used heavily in Databricks/Synapse Spark?', options: [{ id: 'A', text: 'Delta Lake' }, { id: 'B', text: 'Avro' }, { id: 'C', text: 'ORC' }, { id: 'D', text: 'JSON' }], correct: ['A'], explanation: 'Delta Lake adds a transaction log (_delta_log) on top of Parquet for ACID semantics and time travel.' },
  { domain: 'Develop data processing', type: QType.SINGLE, stem: 'Which Azure service is the modern cloud-based ETL/orchestration tool with 90+ connectors?', options: [{ id: 'A', text: 'Azure Data Factory' }, { id: 'B', text: 'Azure Functions' }, { id: 'C', text: 'Azure Logic Apps' }, { id: 'D', text: 'Azure Service Bus' }], correct: ['A'], explanation: 'ADF builds visual pipelines and Mapping/Wrangling Data Flows. Synapse Pipelines reuse the same engine.' },
  { domain: 'Develop data processing', type: QType.SINGLE, stem: 'Which feature lets ADF run a stored procedure or notebook activity within a pipeline?', options: [{ id: 'A', text: 'Activities (Stored Procedure, Notebook, Copy, Lookup, etc.)' }, { id: 'B', text: 'Triggers' }, { id: 'C', text: 'Datasets' }, { id: 'D', text: 'Linked services' }], correct: ['A'], explanation: 'Activities are the units of work in pipelines. Triggers schedule runs; datasets describe data; linked services are connections.' },
  { domain: 'Develop data processing', type: QType.SINGLE, stem: 'Which compute is best for big-data transformations using PySpark, Scala, or Spark SQL in Azure?', options: [{ id: 'A', text: 'Synapse Spark pool / Azure Databricks' }, { id: 'B', text: 'Azure SQL Database' }, { id: 'C', text: 'Azure Functions' }, { id: 'D', text: 'Azure Bastion' }], correct: ['A'], explanation: 'Spark is the dominant big-data engine. Synapse and Databricks both expose Spark.' },
  { domain: 'Develop data processing', type: QType.SINGLE, stem: 'Which Azure service runs SQL-like queries continuously over streaming data from Event Hubs / IoT Hub?', options: [{ id: 'A', text: 'Azure Stream Analytics' }, { id: 'B', text: 'Azure Synapse SQL pool' }, { id: 'C', text: 'Azure Backup' }, { id: 'D', text: 'Azure DNS' }], correct: ['A'], explanation: 'Stream Analytics jobs use SQL-like temporal queries with windows (tumbling, hopping, sliding, session).' },
  { domain: 'Develop data processing', type: QType.SINGLE, stem: 'Which Stream Analytics window aggregates events into FIXED, NON-OVERLAPPING contiguous time slots?', options: [{ id: 'A', text: 'Tumbling window' }, { id: 'B', text: 'Hopping window' }, { id: 'C', text: 'Sliding window' }, { id: 'D', text: 'Session window' }], correct: ['A'], explanation: 'Tumbling = fixed, non-overlapping. Hopping = fixed but overlapping. Sliding = variable. Session = activity-bounded.' },
  { domain: 'Develop data processing', type: QType.SINGLE, stem: 'Which serialization format is row-based, schema-on-read, and Hadoop-native?', options: [{ id: 'A', text: 'Avro' }, { id: 'B', text: 'Parquet' }, { id: 'C', text: 'ORC' }, { id: 'D', text: 'CSV' }], correct: ['A'], explanation: 'Avro stores schema with the data and is row-based; ideal for streaming/RPC. Parquet/ORC are columnar.' },
  { domain: 'Develop data processing', type: QType.SINGLE, stem: 'Which technique reduces the volume of data scanned in Synapse SQL by skipping irrelevant partitions?', options: [{ id: 'A', text: 'Partition pruning (folder partitioning + predicate pushdown)' }, { id: 'B', text: 'Indexes only' }, { id: 'C', text: 'Materialized views always' }, { id: 'D', text: 'Auto-pause' }], correct: ['A'], explanation: 'Partition columns in folder paths (year=/month=/day=) plus predicates allow the engine to skip whole partitions.' },
  { domain: 'Develop data processing', type: QType.SINGLE, stem: 'Which Azure service offers managed Apache Kafka without operational overhead?', options: [{ id: 'A', text: 'Azure Event Hubs (Kafka endpoint)' }, { id: 'B', text: 'Azure SQL DB' }, { id: 'C', text: 'Azure Backup' }, { id: 'D', text: 'Azure Bastion' }], correct: ['A'], explanation: 'Event Hubs offers a Kafka-protocol endpoint, so Kafka clients can produce/consume without running Kafka brokers.' },
  { domain: 'Develop data processing', type: QType.SINGLE, stem: 'Which Synapse feature lets you run T-SQL queries that span tables in dedicated SQL pool, serverless SQL, AND data lake files?', options: [{ id: 'A', text: 'Synapse Studio integrated SQL experience with cross-pool queries (using OPENROWSET)' }, { id: 'B', text: 'Linked servers' }, { id: 'C', text: 'PolyBase only' }, { id: 'D', text: 'Stored procedures' }], correct: ['A'], explanation: 'Synapse can query CSV/Parquet via OPENROWSET in serverless SQL and combine with managed tables in dedicated pools.' },
  { domain: 'Secure, monitor, and optimize data storage and data processing', type: QType.SINGLE, stem: 'Which feature monitors data engineering pipelines and surfaces failures, retries, and latency?', options: [{ id: 'A', text: 'Synapse / ADF Monitor (built-in monitoring hub)' }, { id: 'B', text: 'Azure Bastion' }, { id: 'C', text: 'Azure Backup' }, { id: 'D', text: 'NSG flow logs' }], correct: ['A'], explanation: 'The Monitor hub shows pipeline runs, integration runtimes, triggers, and alerts.' },
  { domain: 'Secure, monitor, and optimize data storage and data processing', type: QType.SINGLE, stem: 'Which Synapse SQL pool feature partitions a fact table for management efficiency and partition switching?', options: [{ id: 'A', text: 'Table partitioning by date' }, { id: 'B', text: 'GZIP compression' }, { id: 'C', text: 'Materialized views' }, { id: 'D', text: 'Clustered columnstore index alone' }], correct: ['A'], explanation: 'Partitioning enables fast load/unload via SWITCH, and faster queries that filter on the partition column.' },
  { domain: 'Secure, monitor, and optimize data storage and data processing', type: QType.SINGLE, stem: 'Which feature in Synapse Dedicated SQL pool collects table column distribution stats to enable better query plans?', options: [{ id: 'A', text: 'CREATE STATISTICS / auto-stats' }, { id: 'B', text: 'BACKUP DATABASE' }, { id: 'C', text: 'Resource locks' }, { id: 'D', text: 'TRUNCATE TABLE' }], correct: ['A'], explanation: 'Statistics drive the cost-based optimizer. Outdated stats cause poor plans on large tables.' },
  { domain: 'Secure, monitor, and optimize data storage and data processing', type: QType.SINGLE, stem: 'Which storage redundancy ensures asynchronous replication to a secondary region?', options: [{ id: 'A', text: 'GRS (or GZRS)' }, { id: 'B', text: 'LRS' }, { id: 'C', text: 'ZRS' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'GRS replicates LRS data async to the paired region; GZRS does the same with primary as ZRS.' },
  { domain: 'Design and implement data security', type: QType.SINGLE, stem: 'Which Azure feature classifies and labels sensitive data at rest across data sources?', options: [{ id: 'A', text: 'Microsoft Purview' }, { id: 'B', text: 'Azure Bastion' }, { id: 'C', text: 'Azure DNS' }, { id: 'D', text: 'Azure Backup' }], correct: ['A'], explanation: 'Purview is the unified data governance service: discovery, classification, lineage, and policies across Azure and beyond.' },
  { domain: 'Design and implement data security', type: QType.SINGLE, stem: 'Which Synapse SQL feature lets you grant access to specific columns of a table?', options: [{ id: 'A', text: 'Column-level security (GRANT SELECT on specific columns)' }, { id: 'B', text: 'Row-Level Security' }, { id: 'C', text: 'Database firewall' }, { id: 'D', text: 'TDE' }], correct: ['A'], explanation: 'Column-level security restricts SELECT to listed columns. RLS filters rows; TDE encrypts at rest; firewall is network-layer.' },
  { domain: 'Design and implement data security', type: QType.SINGLE, stem: 'Which Synapse SQL feature filters rows visible to users based on predicates (e.g., user can only see rows where Region = "EU")?', options: [{ id: 'A', text: 'Row-Level Security' }, { id: 'B', text: 'Column-Level Security' }, { id: 'C', text: 'Dynamic Data Masking' }, { id: 'D', text: 'TDE' }], correct: ['A'], explanation: 'RLS uses security policies + inline table-valued functions to filter rows automatically.' },
  { domain: 'Design and implement data security', type: QType.SINGLE, stem: 'Which Synapse SQL feature obscures PII from query results without changing the underlying data?', options: [{ id: 'A', text: 'Dynamic Data Masking' }, { id: 'B', text: 'Always Encrypted' }, { id: 'C', text: 'TDE' }, { id: 'D', text: 'Backup' }], correct: ['A'], explanation: 'DDM masks specified columns at query time. Always Encrypted protects from DBAs entirely. TDE encrypts at rest.' },
  { domain: 'Design and implement data security', type: QType.SINGLE, stem: 'Which Azure service centralizes encryption keys for storage, SQL, etc., with HSM-backed protection?', options: [{ id: 'A', text: 'Azure Key Vault' }, { id: 'B', text: 'Azure Backup' }, { id: 'C', text: 'Azure Bastion' }, { id: 'D', text: 'Azure Cost Management' }], correct: ['A'], explanation: 'Key Vault stores keys/secrets/certs with RBAC, soft-delete, purge protection, and HSM options.' },
  { domain: 'Design and implement data security', type: QType.SINGLE, stem: 'Which network configuration confines Synapse traffic to a managed VNet without going over the internet?', options: [{ id: 'A', text: 'Synapse Managed Virtual Network with managed private endpoints' }, { id: 'B', text: 'Default public access' }, { id: 'C', text: 'Service endpoints alone' }, { id: 'D', text: 'NSG flow logs' }], correct: ['A'], explanation: 'Synapse Managed VNet provisions a dedicated VNet for Spark/SQL, plus managed private endpoints to data sources.' },
  { domain: 'Design and implement data security', type: QType.SINGLE, stem: 'Which authentication method is recommended for Synapse pipelines to access ADLS Gen2 without storing keys?', options: [{ id: 'A', text: 'Managed Identity' }, { id: 'B', text: 'Storage account keys' }, { id: 'C', text: 'SAS tokens hard-coded' }, { id: 'D', text: 'Anonymous access' }], correct: ['A'], explanation: 'Managed Identities eliminate secret rotation and follow least-privilege via RBAC.' },
  { domain: 'Develop data processing', type: QType.SINGLE, stem: 'Which incremental data loading pattern moves only data changed since the last successful run?', options: [{ id: 'A', text: 'Watermark-based incremental load (track max(updated_at) per run)' }, { id: 'B', text: 'Truncate + reload daily' }, { id: 'C', text: 'Random sampling' }, { id: 'D', text: 'Insert-on-startup' }], correct: ['A'], explanation: 'Tracking a watermark column lets pipelines fetch only delta rows since the last marker, reducing load and cost.' },
  { domain: 'Develop data processing', type: QType.SINGLE, stem: 'Which CDC feature in Azure SQL captures row-level changes for downstream processing?', options: [{ id: 'A', text: 'Change Data Capture (CDC) / Change Tracking (CT)' }, { id: 'B', text: 'Backup vault' }, { id: 'C', text: 'Resource locks' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'CDC captures full before/after images per change; Change Tracking (lighter) only flags rows changed since last sync.' },
  { domain: 'Develop data processing', type: QType.SINGLE, stem: 'Which Synapse feature lets you build a star-schema data warehouse with materialized views and clustered columnstore indexes?', options: [{ id: 'A', text: 'Synapse Dedicated SQL pool' }, { id: 'B', text: 'Synapse Spark pool' }, { id: 'C', text: 'Azure Functions' }, { id: 'D', text: 'Azure Logic Apps' }], correct: ['A'], explanation: 'Dedicated SQL pool is the MPP data warehouse engine, optimized for star schemas and CCI.' },
  { domain: 'Design and implement data security', type: QType.SINGLE, stem: 'Which feature provides AUDIT logging of database queries in Azure SQL / Synapse for compliance review?', options: [{ id: 'A', text: 'SQL audit (sending logs to Log Analytics, Storage, or Event Hubs)' }, { id: 'B', text: 'NSG flow logs' }, { id: 'C', text: 'Azure Backup' }, { id: 'D', text: 'Application Insights' }], correct: ['A'], explanation: 'Azure SQL Audit captures DB events. Output to Log Analytics for queries or to immutable storage for retention.' }
];

const SLUG = 'microsoft-dp-203-p1';
async function main() {
  const exam = await db.exam.findUnique({ where: { slug: SLUG } });
  if (!exam) throw new Error(`Exam ${SLUG} not found`);
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`${SLUG}: already at ${current}`); return; }
  const need = TARGET - current;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: TAG } });
  if (already >= need) { console.log(`${SLUG}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[i % SUPPLEMENTALS.length];
    await db.question.create({
      data: { examId: exam.id, domain: q.domain, difficulty: 3, type: q.type, stem: q.stem, options: q.options, correct: q.correct, explanation: q.explanation, references: [REF], status: QStatus.PUBLISHED, generatedBy: TAG, isTeaser: false }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`✓ ${SLUG}: +${need} → ${newTotal} total`);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
