/**
 * Top-up: brings GitHub Foundations practice exams (P1-P4) to 60 questions.
 *   npx tsx scripts/seed-github-foundations-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();
const TARGET = 60;
const TAG_PREFIX = 'topup:github-foundations';
const REF = { label: 'GitHub Foundations exam page', url: 'https://resources.github.com/learn/certifications/' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  // ===== Introduction to Git and GitHub (15) =====
  { domain: 'Introduction to Git and GitHub', type: QType.SINGLE,
    stem: 'What is the difference between Git and GitHub?',
    options: [{ id: 'A', text: 'Git is a distributed version-control system; GitHub is a hosting service for Git repositories with collaboration features' }, { id: 'B', text: 'They are the same product' }, { id: 'C', text: 'GitHub is owned by GitLab' }, { id: 'D', text: 'Git only works with GitHub' }],
    correct: ['A'],
    explanation: 'Git is the open-source DVCS by Linus Torvalds. GitHub is a Microsoft-owned web platform that hosts Git repos and adds PRs, issues, Actions, etc.' },
  { domain: 'Introduction to Git and GitHub', type: QType.SINGLE,
    stem: 'Which command initializes a new Git repository in the current directory?',
    options: [{ id: 'A', text: 'git init' }, { id: 'B', text: 'git start' }, { id: 'C', text: 'git create' }, { id: 'D', text: 'git new' }],
    correct: ['A'],
    explanation: '`git init` creates a .git directory and starts version control.' },
  { domain: 'Introduction to Git and GitHub', type: QType.SINGLE,
    stem: 'Which command stages a file for the next commit?',
    options: [{ id: 'A', text: 'git add <file>' }, { id: 'B', text: 'git commit <file>' }, { id: 'C', text: 'git stage' }, { id: 'D', text: 'git track <file>' }],
    correct: ['A'],
    explanation: '`git add` moves changes to the staging (index). `git commit` records staged changes into a new commit.' },
  { domain: 'Introduction to Git and GitHub', type: QType.SINGLE,
    stem: 'Which command shows the working tree status — staged, unstaged, untracked?',
    options: [{ id: 'A', text: 'git status' }, { id: 'B', text: 'git log' }, { id: 'C', text: 'git diff' }, { id: 'D', text: 'git show' }],
    correct: ['A'],
    explanation: '`git status` summarizes branch state and file states. `git diff` shows changes; `git log` shows history; `git show` shows a commit.' },
  { domain: 'Introduction to Git and GitHub', type: QType.SINGLE,
    stem: 'Which command commits staged changes with a message?',
    options: [{ id: 'A', text: 'git commit -m "msg"' }, { id: 'B', text: 'git push -m "msg"' }, { id: 'C', text: 'git save "msg"' }, { id: 'D', text: 'git checkout "msg"' }],
    correct: ['A'],
    explanation: '`git commit -m` records staged changes with the given message. Push uploads, save isn\'t a command, checkout switches branches.' },
  { domain: 'Introduction to Git and GitHub', type: QType.SINGLE,
    stem: 'Which command uploads local commits to a remote repository?',
    options: [{ id: 'A', text: 'git push' }, { id: 'B', text: 'git pull' }, { id: 'C', text: 'git fetch' }, { id: 'D', text: 'git clone' }],
    correct: ['A'],
    explanation: '`git push` sends local commits to the remote. Pull fetches+merges remote into local. Fetch only downloads. Clone copies a remote repo locally.' },
  { domain: 'Introduction to Git and GitHub', type: QType.SINGLE,
    stem: 'Which command downloads remote refs and integrates them into the current branch?',
    options: [{ id: 'A', text: 'git pull' }, { id: 'B', text: 'git push' }, { id: 'C', text: 'git fetch' }, { id: 'D', text: 'git clone' }],
    correct: ['A'],
    explanation: '`git pull` = `git fetch` + `git merge` (or rebase). Fetch alone does not merge.' },
  { domain: 'Introduction to Git and GitHub', type: QType.SINGLE,
    stem: 'What is a Git branch?',
    options: [{ id: 'A', text: 'A movable pointer to a commit, allowing parallel lines of development' }, { id: 'B', text: 'A backup of the entire repo' }, { id: 'C', text: 'A subdirectory in your project' }, { id: 'D', text: 'A separate database server' }],
    correct: ['A'],
    explanation: 'Branches are lightweight named pointers to commits. They enable parallel work without affecting the main line.' },
  { domain: 'Introduction to Git and GitHub', type: QType.SINGLE,
    stem: 'Which command creates a new branch and switches to it?',
    options: [{ id: 'A', text: 'git checkout -b <name>  (or git switch -c <name>)' }, { id: 'B', text: 'git branch new <name>' }, { id: 'C', text: 'git fork <name>' }, { id: 'D', text: 'git merge <name>' }],
    correct: ['A'],
    explanation: '`git checkout -b` (legacy) or `git switch -c` (modern) creates and switches in one step.' },
  { domain: 'Introduction to Git and GitHub', type: QType.SINGLE,
    stem: 'Which command shows the commit history?',
    options: [{ id: 'A', text: 'git log' }, { id: 'B', text: 'git blame' }, { id: 'C', text: 'git stash' }, { id: 'D', text: 'git tag' }],
    correct: ['A'],
    explanation: '`git log` displays commit history. Blame shows per-line authorship; stash saves uncommitted work; tag labels commits.' },
  { domain: 'Introduction to Git and GitHub', type: QType.SINGLE,
    stem: 'What does `git clone <url>` do?',
    options: [{ id: 'A', text: 'Downloads a copy of an existing repository, including history, into a new directory' }, { id: 'B', text: 'Creates an empty repo' }, { id: 'C', text: 'Pushes local commits' }, { id: 'D', text: 'Deletes a repo' }],
    correct: ['A'],
    explanation: '`git clone` copies the entire repo, including history, branches, and remote-tracking refs.' },
  { domain: 'Introduction to Git and GitHub', type: QType.SINGLE,
    stem: 'Which file in a repository tells Git which paths to ignore (not track)?',
    options: [{ id: 'A', text: '.gitignore' }, { id: 'B', text: '.gitkeep' }, { id: 'C', text: '.gitattributes' }, { id: 'D', text: 'README.md' }],
    correct: ['A'],
    explanation: '.gitignore lists patterns Git should ignore. .gitattributes sets per-path attributes. .gitkeep is a convention to keep empty dirs. README is documentation.' },
  { domain: 'Introduction to Git and GitHub', type: QType.SINGLE,
    stem: 'What is a fork on GitHub?',
    options: [{ id: 'A', text: 'A personal copy of someone else\'s repository under your account, where you can experiment freely' }, { id: 'B', text: 'A type of merge conflict' }, { id: 'C', text: 'A deleted commit' }, { id: 'D', text: 'A backup branch' }],
    correct: ['A'],
    explanation: 'Forking creates a copy under your namespace, typically used to propose changes via pull requests.' },
  { domain: 'Introduction to Git and GitHub', type: QType.SINGLE,
    stem: 'What is a pull request (PR) on GitHub?',
    options: [{ id: 'A', text: 'A proposal to merge changes from one branch (often a fork) into another, with review and discussion' }, { id: 'B', text: 'A request to delete the repository' }, { id: 'C', text: 'A backup operation' }, { id: 'D', text: 'A way to rename branches' }],
    correct: ['A'],
    explanation: 'PRs propose merging changes, support code review, comments, status checks, and required approvals.' },
  { domain: 'Introduction to Git and GitHub', type: QType.SINGLE,
    stem: 'What is the default name for the primary branch in a new GitHub repository (since 2020)?',
    options: [{ id: 'A', text: 'main' }, { id: 'B', text: 'master' }, { id: 'C', text: 'trunk' }, { id: 'D', text: 'default' }],
    correct: ['A'],
    explanation: 'GitHub changed the default to `main`. Existing repos may still use `master`.' },

  // ===== Working with GitHub Repositories (15) =====
  { domain: 'Working with GitHub Repositories', type: QType.SINGLE,
    stem: 'Which GitHub feature lets you mark a repository as a TEMPLATE so others can create new repos pre-populated with its contents?',
    options: [{ id: 'A', text: 'Template repository' }, { id: 'B', text: 'Repository fork' }, { id: 'C', text: 'Repository archive' }, { id: 'D', text: 'Pinned repository' }],
    correct: ['A'],
    explanation: 'Template repos let users start NEW projects from a snapshot. Forks track the upstream. Archive freezes a repo. Pinned shows in profile.' },
  { domain: 'Working with GitHub Repositories', type: QType.SINGLE,
    stem: 'Which file conventionally describes the project, build instructions, and usage at the repo root?',
    options: [{ id: 'A', text: 'README.md' }, { id: 'B', text: 'CHANGELOG.md' }, { id: 'C', text: 'LICENSE' }, { id: 'D', text: 'CONTRIBUTING.md' }],
    correct: ['A'],
    explanation: 'README is rendered on the repo home page. CHANGELOG documents history; LICENSE governs use; CONTRIBUTING guides contributors.' },
  { domain: 'Working with GitHub Repositories', type: QType.SINGLE,
    stem: 'A repository is currently public. Which is required to make it private later?',
    options: [{ id: 'A', text: 'Change visibility in repository settings (admin permissions required)' }, { id: 'B', text: 'Delete and recreate the repo' }, { id: 'C', text: 'Open a support ticket' }, { id: 'D', text: 'Public repos cannot be made private' }],
    correct: ['A'],
    explanation: 'Repo admins can toggle visibility in Settings → General → Danger Zone. Forks are NOT carried over when going public→private.' },
  { domain: 'Working with GitHub Repositories', type: QType.SINGLE,
    stem: 'Which feature freezes a repository — making it read-only — without deleting it?',
    options: [{ id: 'A', text: 'Archive repository' }, { id: 'B', text: 'Lock repository' }, { id: 'C', text: 'Disable Issues' }, { id: 'D', text: 'Pin to profile' }],
    correct: ['A'],
    explanation: 'Archiving makes a repo read-only (no commits, issues, PRs). It can be unarchived later.' },
  { domain: 'Working with GitHub Repositories', type: QType.SINGLE,
    stem: 'Which file lists the project\'s contributors\' code-of-conduct expectations?',
    options: [{ id: 'A', text: 'CODE_OF_CONDUCT.md' }, { id: 'B', text: 'README.md' }, { id: 'C', text: '.gitignore' }, { id: 'D', text: 'package.json' }],
    correct: ['A'],
    explanation: 'CODE_OF_CONDUCT documents community norms; GitHub recognizes the file in repo "Community" insights.' },
  { domain: 'Working with GitHub Repositories', type: QType.SINGLE,
    stem: 'Which feature designates default reviewers automatically required on PRs that touch certain files?',
    options: [{ id: 'A', text: 'CODEOWNERS file' }, { id: 'B', text: 'README.md' }, { id: 'C', text: 'PR template' }, { id: 'D', text: '.gitignore' }],
    correct: ['A'],
    explanation: 'CODEOWNERS maps file-pattern to reviewers. Combined with branch protection, requires their approval before merge.' },
  { domain: 'Working with GitHub Repositories', type: QType.SINGLE,
    stem: 'Which feature prevents direct pushes to a branch and requires PRs with approvals before merge?',
    options: [{ id: 'A', text: 'Branch protection rules' }, { id: 'B', text: 'Repository archive' }, { id: 'C', text: 'CODEOWNERS only' }, { id: 'D', text: 'Pinned issues' }],
    correct: ['A'],
    explanation: 'Branch protection rules can require status checks, approvals, signed commits, linear history, and disallow force pushes/deletions.' },
  { domain: 'Working with GitHub Repositories', type: QType.SINGLE,
    stem: 'Which GitHub feature is a versioned, named snapshot of the repo, often distributed as a tarball/zip with a CHANGELOG?',
    options: [{ id: 'A', text: 'Releases' }, { id: 'B', text: 'Branches' }, { id: 'C', text: 'Forks' }, { id: 'D', text: 'Issues' }],
    correct: ['A'],
    explanation: 'Releases tie a Git tag to release notes and binary artifacts.' },
  { domain: 'Working with GitHub Repositories', type: QType.SINGLE,
    stem: 'A user wants others to acknowledge they have the right to use the code. Which file should the repo include?',
    options: [{ id: 'A', text: 'LICENSE (e.g., MIT, Apache 2.0)' }, { id: 'B', text: 'README' }, { id: 'C', text: 'CONTRIBUTING' }, { id: 'D', text: 'SUPPORT' }],
    correct: ['A'],
    explanation: 'The LICENSE file determines what others may legally do with the code.' },
  { domain: 'Working with GitHub Repositories', type: QType.SINGLE,
    stem: 'What does the .github directory commonly contain?',
    options: [{ id: 'A', text: 'Workflow files (`.github/workflows/`), issue templates, PR templates, CODEOWNERS, dependabot.yml' }, { id: 'B', text: 'Source code' }, { id: 'C', text: 'Compiled binaries' }, { id: 'D', text: 'User passwords' }],
    correct: ['A'],
    explanation: '.github holds GitHub-specific configuration: Actions workflows, templates, code owners, dependabot config.' },
  { domain: 'Working with GitHub Repositories', type: QType.SINGLE,
    stem: 'Which GitHub feature notifies repository maintainers when a dependency has a known security vulnerability?',
    options: [{ id: 'A', text: 'Dependabot alerts' }, { id: 'B', text: 'Code scanning only' }, { id: 'C', text: 'Pull request' }, { id: 'D', text: 'Pinned issue' }],
    correct: ['A'],
    explanation: 'Dependabot alerts surface vulnerable dependencies. Dependabot security updates can auto-open PRs with fixes.' },
  { domain: 'Working with GitHub Repositories', type: QType.SINGLE,
    stem: 'Which size limit applies to a SINGLE file in a GitHub repository?',
    options: [{ id: 'A', text: '100 MB (warned at 50 MB)' }, { id: 'B', text: '1 GB' }, { id: 'C', text: '10 KB' }, { id: 'D', text: 'No limit' }],
    correct: ['A'],
    explanation: 'GitHub blocks files >100 MB. Use Git LFS for large binaries.' },
  { domain: 'Working with GitHub Repositories', type: QType.SINGLE,
    stem: 'Which feature lets you store large binary assets outside the regular Git history while keeping them versioned?',
    options: [{ id: 'A', text: 'Git LFS (Large File Storage)' }, { id: 'B', text: '.gitattributes only' }, { id: 'C', text: 'README links' }, { id: 'D', text: 'GitHub Releases' }],
    correct: ['A'],
    explanation: 'Git LFS replaces large files with text pointers and stores the actual content elsewhere, keeping clones fast.' },
  { domain: 'Working with GitHub Repositories', type: QType.SINGLE,
    stem: 'Which Git command discards local uncommitted changes to a tracked file?',
    options: [{ id: 'A', text: 'git restore <file>  (or git checkout -- <file>)' }, { id: 'B', text: 'git rm <file>' }, { id: 'C', text: 'git push <file>' }, { id: 'D', text: 'git tag <file>' }],
    correct: ['A'],
    explanation: '`git restore <file>` (modern) or `git checkout -- <file>` (legacy) discards working-tree changes.' },
  { domain: 'Working with GitHub Repositories', type: QType.SINGLE,
    stem: 'Which command temporarily saves uncommitted local changes so you can switch branches without committing?',
    options: [{ id: 'A', text: 'git stash' }, { id: 'B', text: 'git tag' }, { id: 'C', text: 'git revert' }, { id: 'D', text: 'git reset' }],
    correct: ['A'],
    explanation: '`git stash` saves working-tree changes onto a stack. Apply with `git stash pop`.' },

  // ===== Collaboration Features (15) =====
  { domain: 'Collaboration Features', type: QType.SINGLE,
    stem: 'Which GitHub feature lets you track bugs and feature requests with labels, assignees, milestones, and comments?',
    options: [{ id: 'A', text: 'Issues' }, { id: 'B', text: 'Wiki' }, { id: 'C', text: 'Discussions' }, { id: 'D', text: 'Releases' }],
    correct: ['A'],
    explanation: 'Issues track bugs/features with full metadata. Wiki is documentation; Discussions is forum-like Q&A; Releases ship versions.' },
  { domain: 'Collaboration Features', type: QType.SINGLE,
    stem: 'Which GitHub feature is best for community Q&A and announcements — separate from actionable bug tracking?',
    options: [{ id: 'A', text: 'Discussions' }, { id: 'B', text: 'Issues' }, { id: 'C', text: 'Pull Requests' }, { id: 'D', text: 'Wiki' }],
    correct: ['A'],
    explanation: 'Discussions provide threaded forum-style conversations distinct from actionable issues.' },
  { domain: 'Collaboration Features', type: QType.SINGLE,
    stem: 'Which GitHub feature lets you organize Issues and PRs into a kanban-style board with custom columns?',
    options: [{ id: 'A', text: 'Projects (Projects v2)' }, { id: 'B', text: 'Wiki' }, { id: 'C', text: 'Releases' }, { id: 'D', text: 'Pulse' }],
    correct: ['A'],
    explanation: 'Projects (v2) provides flexible boards/tables with custom fields, automated workflows, and cross-repo support.' },
  { domain: 'Collaboration Features', type: QType.SINGLE,
    stem: 'Which feature lets you reference a PR from a commit message to AUTOMATICALLY close an issue when merged?',
    options: [{ id: 'A', text: 'Closing keywords (e.g., "Fixes #42", "Closes #42")' }, { id: 'B', text: 'Reactions' }, { id: 'C', text: 'Project columns' }, { id: 'D', text: 'Status checks' }],
    correct: ['A'],
    explanation: 'PRs (or commits on default branch) using closing keywords auto-close referenced issues on merge.' },
  { domain: 'Collaboration Features', type: QType.SINGLE,
    stem: 'Which GitHub feature lets reviewers leave comments on specific lines of a PR diff?',
    options: [{ id: 'A', text: 'Code review (Files Changed → comment on lines)' }, { id: 'B', text: 'Wiki edits' }, { id: 'C', text: 'Repository description' }, { id: 'D', text: 'Issue reactions' }],
    correct: ['A'],
    explanation: 'PR Files Changed view supports per-line comments, suggested edits, and submit-as-Approve/Request-changes/Comment.' },
  { domain: 'Collaboration Features', type: QType.SINGLE,
    stem: 'Which PR review action means the reviewer wants the author to make changes before merging?',
    options: [{ id: 'A', text: 'Request changes' }, { id: 'B', text: 'Approve' }, { id: 'C', text: 'Comment' }, { id: 'D', text: 'Dismiss' }],
    correct: ['A'],
    explanation: 'Request changes blocks the merge until the reviewer dismisses or re-reviews. Approve allows merge; Comment is informational.' },
  { domain: 'Collaboration Features', type: QType.SINGLE,
    stem: 'Which GitHub feature lets you save a draft of a PR review with multiple comments before submitting them all at once?',
    options: [{ id: 'A', text: 'Pending review (Start a review)' }, { id: 'B', text: 'Wiki draft' }, { id: 'C', text: 'Issue draft' }, { id: 'D', text: 'Notification preferences' }],
    correct: ['A'],
    explanation: 'Pending reviews accumulate comments locally; submit them as one batch to avoid noisy notifications.' },
  { domain: 'Collaboration Features', type: QType.SINGLE,
    stem: 'Which merge strategy creates a single new commit that combines all PR changes onto the target branch?',
    options: [{ id: 'A', text: 'Squash and merge' }, { id: 'B', text: 'Create a merge commit' }, { id: 'C', text: 'Rebase and merge' }, { id: 'D', text: 'Cherry-pick' }],
    correct: ['A'],
    explanation: 'Squash merges combine all PR commits into one. Merge commit preserves history with a merge node. Rebase replays commits without a merge node.' },
  { domain: 'Collaboration Features', type: QType.SINGLE,
    stem: 'Which merge strategy preserves the linear history by replaying PR commits onto target without a merge commit?',
    options: [{ id: 'A', text: 'Rebase and merge' }, { id: 'B', text: 'Squash and merge' }, { id: 'C', text: 'Merge commit' }, { id: 'D', text: 'Force push' }],
    correct: ['A'],
    explanation: 'Rebase-and-merge produces a linear history. Each PR commit is preserved but rewritten to apply on top of the target.' },
  { domain: 'Collaboration Features', type: QType.SINGLE,
    stem: 'Which feature lets PR authors propose specific code changes that reviewers can apply with a single click?',
    options: [{ id: 'A', text: 'Suggested changes (in code review)' }, { id: 'B', text: 'PR template' }, { id: 'C', text: 'Status check' }, { id: 'D', text: 'Branch protection' }],
    correct: ['A'],
    explanation: 'Suggested changes use Markdown ```suggestion blocks; the author can apply them as commits.' },
  { domain: 'Collaboration Features', type: QType.SINGLE,
    stem: 'Which GitHub feature lets you assign organization membership levels and team-based access control?',
    options: [{ id: 'A', text: 'Organizations + teams + role-based access' }, { id: 'B', text: 'Wiki' }, { id: 'C', text: 'Pull request reviews' }, { id: 'D', text: 'GitHub Pages' }],
    correct: ['A'],
    explanation: 'Orgs let you create teams with hierarchical access. Roles (Owner/Member/Maintainer) and team permissions govern repo access.' },
  { domain: 'Collaboration Features', type: QType.SINGLE,
    stem: 'Which keyword in a comment notifies a specific user or team?',
    options: [{ id: 'A', text: '@username or @team-slug' }, { id: 'B', text: '#hashtag' }, { id: 'C', text: '!alert' }, { id: 'D', text: '/notify' }],
    correct: ['A'],
    explanation: '@-mentions notify users/teams. # references issues/PRs.' },
  { domain: 'Collaboration Features', type: QType.SINGLE,
    stem: 'Which feature lets you create RE-USABLE issue creation forms that ensure consistent reporting?',
    options: [{ id: 'A', text: 'Issue templates / Issue forms' }, { id: 'B', text: 'PR drafts' }, { id: 'C', text: 'GitHub Pages' }, { id: 'D', text: 'GitHub CLI' }],
    correct: ['A'],
    explanation: 'Issue templates (Markdown) and Issue forms (YAML) provide structured input and pre-applied labels.' },
  { domain: 'Collaboration Features', type: QType.SINGLE,
    stem: 'Which feature shows a small thumbs-up/thumbs-down etc. on Issues, PRs, and comments?',
    options: [{ id: 'A', text: 'Reactions (emoji)' }, { id: 'B', text: 'Mentions' }, { id: 'C', text: 'Reviews' }, { id: 'D', text: 'Status checks' }],
    correct: ['A'],
    explanation: 'Reactions allow lightweight feedback (👍 ❤️ 🚀 etc.) without comment noise.' },
  { domain: 'Collaboration Features', type: QType.SINGLE,
    stem: 'Which GitHub feature lets contributors sign their commits cryptographically to prove they wrote them?',
    options: [{ id: 'A', text: 'GPG / SSH commit signing (Verified badge)' }, { id: 'B', text: 'Branch protection' }, { id: 'C', text: 'PR review' }, { id: 'D', text: 'Forks' }],
    correct: ['A'],
    explanation: 'Signed commits show a Verified badge. Branch protection can require signed commits.' },

  // ===== GitHub Ecosystem and AI Tools (15) =====
  { domain: 'GitHub Ecosystem and AI Tools', type: QType.SINGLE,
    stem: 'Which GitHub feature provides CI/CD pipelines defined as YAML files in .github/workflows?',
    options: [{ id: 'A', text: 'GitHub Actions' }, { id: 'B', text: 'GitHub Pages' }, { id: 'C', text: 'GitHub Codespaces' }, { id: 'D', text: 'GitHub Packages' }],
    correct: ['A'],
    explanation: 'GitHub Actions provides workflows, jobs, and steps that run on triggers (push, PR, schedule, etc.) using runners.' },
  { domain: 'GitHub Ecosystem and AI Tools', type: QType.SINGLE,
    stem: 'Which GitHub feature hosts static websites directly from a repo branch?',
    options: [{ id: 'A', text: 'GitHub Pages' }, { id: 'B', text: 'GitHub Codespaces' }, { id: 'C', text: 'GitHub Packages' }, { id: 'D', text: 'GitHub Discussions' }],
    correct: ['A'],
    explanation: 'GitHub Pages hosts static sites under https://<user>.github.io/ or custom domains.' },
  { domain: 'GitHub Ecosystem and AI Tools', type: QType.SINGLE,
    stem: 'Which GitHub product provides a cloud-based development environment in the browser, pre-configured with VS Code?',
    options: [{ id: 'A', text: 'GitHub Codespaces' }, { id: 'B', text: 'GitHub Actions' }, { id: 'C', text: 'GitHub Pages' }, { id: 'D', text: 'GitHub Models' }],
    correct: ['A'],
    explanation: 'Codespaces spins up a containerized VS Code in the cloud, configurable via devcontainer.json.' },
  { domain: 'GitHub Ecosystem and AI Tools', type: QType.SINGLE,
    stem: 'Which GitHub product is an AI pair programmer that suggests code completions and chat-based assistance?',
    options: [{ id: 'A', text: 'GitHub Copilot' }, { id: 'B', text: 'GitHub Codespaces' }, { id: 'C', text: 'GitHub Actions' }, { id: 'D', text: 'GitHub Pages' }],
    correct: ['A'],
    explanation: 'Copilot offers in-editor completions, chat (Copilot Chat), CLI assist, and PR summarization.' },
  { domain: 'GitHub Ecosystem and AI Tools', type: QType.SINGLE,
    stem: 'Which file format defines a GitHub Actions workflow?',
    options: [{ id: 'A', text: 'YAML (.yml/.yaml in .github/workflows/)' }, { id: 'B', text: 'JSON only' }, { id: 'C', text: 'XML' }, { id: 'D', text: 'TOML' }],
    correct: ['A'],
    explanation: 'Actions workflows are YAML files in .github/workflows/.' },
  { domain: 'GitHub Ecosystem and AI Tools', type: QType.SINGLE,
    stem: 'Which Actions concept executes the steps in a workflow — for example, on a Linux/Windows/Mac VM or a self-hosted machine?',
    options: [{ id: 'A', text: 'Runner' }, { id: 'B', text: 'Trigger' }, { id: 'C', text: 'Action' }, { id: 'D', text: 'Job' }],
    correct: ['A'],
    explanation: 'Runners execute the jobs. GitHub-hosted runners are managed; self-hosted runners are user-managed.' },
  { domain: 'GitHub Ecosystem and AI Tools', type: QType.SINGLE,
    stem: 'Which GitHub feature provides container, npm, NuGet, Maven, RubyGems, and Docker image hosting?',
    options: [{ id: 'A', text: 'GitHub Packages' }, { id: 'B', text: 'GitHub Releases' }, { id: 'C', text: 'GitHub Pages' }, { id: 'D', text: 'GitHub Codespaces' }],
    correct: ['A'],
    explanation: 'GitHub Packages hosts artifacts across major registries with fine-grained access tied to repo permissions.' },
  { domain: 'GitHub Ecosystem and AI Tools', type: QType.SINGLE,
    stem: 'Which GitHub feature provides centralized SAST that detects security vulnerabilities in your code?',
    options: [{ id: 'A', text: 'CodeQL / Code scanning' }, { id: 'B', text: 'Dependabot' }, { id: 'C', text: 'Issues' }, { id: 'D', text: 'Discussions' }],
    correct: ['A'],
    explanation: 'CodeQL is GitHub\'s SAST engine, run via Code scanning on push/PR. Dependabot focuses on dependency vulnerabilities.' },
  { domain: 'GitHub Ecosystem and AI Tools', type: QType.SINGLE,
    stem: 'Which GitHub feature scans for secrets accidentally pushed to repositories?',
    options: [{ id: 'A', text: 'Secret scanning' }, { id: 'B', text: 'Dependabot' }, { id: 'C', text: 'Code scanning (CodeQL)' }, { id: 'D', text: 'Branch protection' }],
    correct: ['A'],
    explanation: 'Secret scanning detects partner-recognized secret formats (API keys, credentials) and notifies owners. Free for public repos; Advanced Security for private.' },
  { domain: 'GitHub Ecosystem and AI Tools', type: QType.SINGLE,
    stem: 'Which Actions trigger fires when code is pushed to any branch?',
    options: [{ id: 'A', text: 'on: push' }, { id: 'B', text: 'on: schedule' }, { id: 'C', text: 'on: workflow_dispatch' }, { id: 'D', text: 'on: pull_request' }],
    correct: ['A'],
    explanation: '`on: push` triggers on push events. `pull_request` triggers on PR events. `schedule` is cron-based. `workflow_dispatch` is manual.' },
  { domain: 'GitHub Ecosystem and AI Tools', type: QType.SINGLE,
    stem: 'Which Actions trigger lets a user MANUALLY run a workflow from the GitHub UI?',
    options: [{ id: 'A', text: 'on: workflow_dispatch' }, { id: 'B', text: 'on: push' }, { id: 'C', text: 'on: schedule' }, { id: 'D', text: 'on: release' }],
    correct: ['A'],
    explanation: 'workflow_dispatch enables a "Run workflow" button. It can declare inputs that the user supplies.' },
  { domain: 'GitHub Ecosystem and AI Tools', type: QType.SINGLE,
    stem: 'Which Actions feature provides ENCRYPTED storage for credentials accessible by workflows via ${{ secrets.NAME }}?',
    options: [{ id: 'A', text: 'Repository / Environment / Organization secrets' }, { id: 'B', text: 'README files' }, { id: 'C', text: '.gitignore' }, { id: 'D', text: 'PR comments' }],
    correct: ['A'],
    explanation: 'Secrets are encrypted at rest and exposed via the secrets context. Use environment secrets for prod-gated values.' },
  { domain: 'GitHub Ecosystem and AI Tools', type: QType.SINGLE,
    stem: 'Which Copilot feature lets you ask code questions and get explanations or suggestions in a chat panel?',
    options: [{ id: 'A', text: 'Copilot Chat' }, { id: 'B', text: 'GitHub Discussions' }, { id: 'C', text: 'GitHub Codespaces' }, { id: 'D', text: 'GitHub Sponsors' }],
    correct: ['A'],
    explanation: 'Copilot Chat is the conversational interface for code Q&A and refactoring suggestions, available in IDEs and on GitHub.com.' },
  { domain: 'GitHub Ecosystem and AI Tools', type: QType.SINGLE,
    stem: 'Which GitHub feature lets you fund open-source maintainers from your account or organization?',
    options: [{ id: 'A', text: 'GitHub Sponsors' }, { id: 'B', text: 'GitHub Marketplace' }, { id: 'C', text: 'GitHub Releases' }, { id: 'D', text: 'GitHub Education' }],
    correct: ['A'],
    explanation: 'GitHub Sponsors enables monthly or one-time financial support to OSS maintainers.' },
  { domain: 'GitHub Ecosystem and AI Tools', type: QType.SINGLE,
    stem: 'Which marketplace lets you discover and install third-party Apps and Actions?',
    options: [{ id: 'A', text: 'GitHub Marketplace' }, { id: 'B', text: 'GitHub Pages' }, { id: 'C', text: 'GitHub Sponsors' }, { id: 'D', text: 'GitHub Education' }],
    correct: ['A'],
    explanation: 'GitHub Marketplace hosts GitHub Apps (CI/CD, security, project management) and reusable Actions.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'github-foundations-p1', offset: 0 },
  { slug: 'github-foundations-p2', offset: 15 },
  { slug: 'github-foundations-p3', offset: 30 },
  { slug: 'github-foundations-p4', offset: 45 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: {
        examId: exam.id, domain: q.domain, difficulty: 3, type: q.type,
        stem: q.stem, options: q.options, correct: q.correct,
        explanation: q.explanation, references: [REF],
        status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false
      }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up GitHub Foundations exams to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
}

main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
