/**
 * Top-up: Google Professional ML Engineer (P1-P3) to 60 questions.
 * P4-P6 already at 60 from PDF parsing.
 *   npx tsx scripts/seed-google-pro-ml-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();
const TARGET = 60;
const TAG_PREFIX = 'topup:google-pro-ml';
const REF = { label: 'Google Professional ML Engineer exam page', url: 'https://cloud.google.com/learn/certification/machine-learning-engineer' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  { domain: 'Architecting low-code AI solutions', type: QType.SINGLE, stem: 'Which Google Cloud service lets you build ML models without writing code, using AutoML?', options: [{ id: 'A', text: 'Vertex AI AutoML' }, { id: 'B', text: 'Cloud Functions' }, { id: 'C', text: 'BigQuery' }, { id: 'D', text: 'Cloud Run' }], correct: ['A'], explanation: 'Vertex AI AutoML offers no-code training for tabular, vision, text, video.' },
  { domain: 'Architecting low-code AI solutions', type: QType.SINGLE, stem: 'Which Google Cloud service lets you train ML models directly inside the data warehouse using SQL?', options: [{ id: 'A', text: 'BigQuery ML' }, { id: 'B', text: 'Cloud SQL' }, { id: 'C', text: 'Cloud Functions' }, { id: 'D', text: 'Vertex AI Workbench' }], correct: ['A'], explanation: 'BigQuery ML enables training/predicting models with SQL syntax (CREATE MODEL, ML.PREDICT).' },
  { domain: 'Architecting low-code AI solutions', type: QType.SINGLE, stem: 'Which Vertex AI capability provides foundation models (Gemini, PaLM, etc.) via APIs?', options: [{ id: 'A', text: 'Vertex AI Model Garden / Generative AI Studio' }, { id: 'B', text: 'BigQuery ML' }, { id: 'C', text: 'Cloud Functions' }, { id: 'D', text: 'Cloud Run' }], correct: ['A'], explanation: 'Model Garden hosts foundation models; Generative AI Studio is the prompt-design UI.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which Vertex AI feature stores and serves features for both training and online inference?', options: [{ id: 'A', text: 'Vertex AI Feature Store' }, { id: 'B', text: 'Cloud Storage' }, { id: 'C', text: 'BigQuery alone' }, { id: 'D', text: 'Cloud Functions' }], correct: ['A'], explanation: 'Vertex AI Feature Store provides offline + online stores with versioning and time-travel for training/inference parity.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which Vertex AI feature centralizes versioned trained models?', options: [{ id: 'A', text: 'Vertex AI Model Registry' }, { id: 'B', text: 'Cloud Storage' }, { id: 'C', text: 'BigQuery' }, { id: 'D', text: 'Cloud Run' }], correct: ['A'], explanation: 'Model Registry tracks versions, evaluations, and deploys to endpoints.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which Vertex AI feature provides governed datasets for ML?', options: [{ id: 'A', text: 'Vertex AI Datasets' }, { id: 'B', text: 'Cloud Storage' }, { id: 'C', text: 'Cloud Run' }, { id: 'D', text: 'Cloud Functions' }], correct: ['A'], explanation: 'Vertex AI Datasets handle import, schema, labeling, and serve as inputs for training jobs.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which IAM role grants the ability to manage ML resources without project-wide ownership?', options: [{ id: 'A', text: 'Vertex AI Admin / Vertex AI User predefined roles' }, { id: 'B', text: 'Project Owner' }, { id: 'C', text: 'Editor' }, { id: 'D', text: 'Viewer' }], correct: ['A'], explanation: 'Service-specific Vertex AI roles provide scoped access without elevating to Owner/Editor.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which Vertex AI feature provides a managed Jupyter environment for collaborative ML development?', options: [{ id: 'A', text: 'Vertex AI Workbench' }, { id: 'B', text: 'Cloud Run' }, { id: 'C', text: 'Cloud Functions' }, { id: 'D', text: 'Compute Engine alone' }], correct: ['A'], explanation: 'Workbench is the managed JupyterLab IDE on GCP — managed-notebooks (single-user) or user-managed.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'Which Vertex AI capability runs distributed training jobs on managed clusters?', options: [{ id: 'A', text: 'Vertex AI Custom Training jobs (with worker pools, GPU/TPU)' }, { id: 'B', text: 'Cloud Functions' }, { id: 'C', text: 'BigQuery only' }, { id: 'D', text: 'Cloud Run' }], correct: ['A'], explanation: 'Custom training jobs scale across multiple workers/GPUs/TPUs with managed orchestration.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'Which framework is Google\'s open-source ML library used heavily on Vertex AI?', options: [{ id: 'A', text: 'TensorFlow / JAX (with PyTorch also fully supported)' }, { id: 'B', text: 'XGBoost only' }, { id: 'C', text: 'scikit-learn only' }, { id: 'D', text: 'MXNet' }], correct: ['A'], explanation: 'Vertex AI supports TF/JAX (Google), PyTorch, scikit-learn, XGBoost via prebuilt containers.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'Which feature in Vertex AI tunes hyperparameters automatically using Bayesian / random / grid search?', options: [{ id: 'A', text: 'Vertex AI Hyperparameter Tuning (Vizier-based)' }, { id: 'B', text: 'BigQuery ML' }, { id: 'C', text: 'Cloud Run' }, { id: 'D', text: 'Cloud Build' }], correct: ['A'], explanation: 'Vertex AI uses Vizier (Google\'s black-box optimization) for HPO with parallel trials.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'Which Vertex AI feature compiles and optimizes models for the Edge TPU or GPU inference?', options: [{ id: 'A', text: 'Vertex AI Optimized inference (NVIDIA Triton / Edge TPU compiler)' }, { id: 'B', text: 'BigQuery ML' }, { id: 'C', text: 'Cloud Run' }, { id: 'D', text: 'Cloud Functions' }], correct: ['A'], explanation: 'Vertex AI optimizes inference via Triton or Edge TPU compilation for accelerated serving.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'Which Vertex AI deployment serves real-time predictions with autoscaling and traffic splitting?', options: [{ id: 'A', text: 'Vertex AI Online Prediction (Endpoints)' }, { id: 'B', text: 'Vertex AI Batch Prediction' }, { id: 'C', text: 'BigQuery' }, { id: 'D', text: 'Cloud Functions' }], correct: ['A'], explanation: 'Online endpoints provide HTTP inference with autoscaling and traffic split between deployed models.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'Which Vertex AI deployment processes large input files asynchronously in parallel?', options: [{ id: 'A', text: 'Vertex AI Batch Prediction' }, { id: 'B', text: 'Online Endpoints' }, { id: 'C', text: 'Cloud Run' }, { id: 'D', text: 'Cloud Build' }], correct: ['A'], explanation: 'Batch Prediction parallelizes scoring across worker nodes for high-throughput offline jobs.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'Which Vertex AI feature shifts a percentage of traffic to a new model version safely?', options: [{ id: 'A', text: 'Endpoint with multiple deployed models + traffic split' }, { id: 'B', text: 'BigQuery ML alone' }, { id: 'C', text: 'Cloud Run revisions only' }, { id: 'D', text: 'Cloud Build' }], correct: ['A'], explanation: 'A Vertex AI endpoint can host multiple model deployments with percentage-based traffic split.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'Which serving option deploys ML models to edge / mobile devices with TensorFlow Lite?', options: [{ id: 'A', text: 'Vertex AI ML / TensorFlow Lite for edge inference' }, { id: 'B', text: 'BigQuery ML' }, { id: 'C', text: 'Cloud Functions' }, { id: 'D', text: 'Cloud Run' }], correct: ['A'], explanation: 'TF Lite (and Edge TPU) provides edge ML inference; Vertex AI ML can manage and update edge models.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which Vertex AI feature is the managed orchestration platform for ML pipelines using Kubeflow Pipelines or TFX?', options: [{ id: 'A', text: 'Vertex AI Pipelines' }, { id: 'B', text: 'Cloud Build' }, { id: 'C', text: 'Cloud Composer' }, { id: 'D', text: 'Cloud Run' }], correct: ['A'], explanation: 'Vertex AI Pipelines is a serverless orchestrator for KFP/TFX pipelines with lineage tracking.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which language/framework defines components and pipelines for Vertex AI Pipelines?', options: [{ id: 'A', text: 'Kubeflow Pipelines (KFP) v2 SDK in Python' }, { id: 'B', text: 'Bash only' }, { id: 'C', text: 'Java / Maven' }, { id: 'D', text: 'Go' }], correct: ['A'], explanation: 'KFP SDK (Python) defines components (containers) and pipelines; Vertex AI Pipelines runs them serverlessly.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which Vertex AI feature schedules pipeline runs?', options: [{ id: 'A', text: 'Vertex AI Pipelines schedules (Cloud Scheduler / cron)' }, { id: 'B', text: 'Cloud Build trigger only' }, { id: 'C', text: 'Cloud Run scheduler' }, { id: 'D', text: 'BigQuery scheduled queries' }], correct: ['A'], explanation: 'Vertex AI Pipelines integrates with Cloud Scheduler for cron-based scheduling.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which feature triggers pipeline runs based on a CI/CD event (e.g., new commit)?', options: [{ id: 'A', text: 'Cloud Build trigger invoking a pipeline run' }, { id: 'B', text: 'Cloud Run alone' }, { id: 'C', text: 'BigQuery ML' }, { id: 'D', text: 'Cloud Functions only' }], correct: ['A'], explanation: 'CI/CD pipelines (Cloud Build) call the Vertex AI API to launch pipeline runs on commit.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which Vertex AI feature versions and tracks all artifacts (datasets, models, metrics) produced by pipeline runs?', options: [{ id: 'A', text: 'Vertex ML Metadata' }, { id: 'B', text: 'Cloud Storage' }, { id: 'C', text: 'BigQuery' }, { id: 'D', text: 'Cloud Build' }], correct: ['A'], explanation: 'Vertex ML Metadata stores lineage of pipeline executions for reproducibility and audit.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which feature in Vertex AI Pipelines lets you run conditional/branching steps?', options: [{ id: 'A', text: 'KFP control-flow constructs (Condition, ParallelFor, ExitHandler)' }, { id: 'B', text: 'Cloud Run revisions' }, { id: 'C', text: 'BigQuery views' }, { id: 'D', text: 'Cloud Functions' }], correct: ['A'], explanation: 'KFP v2 SDK exposes Condition, ParallelFor, and ExitHandler for control flow.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'Which Vertex AI feature monitors deployed models for data drift?', options: [{ id: 'A', text: 'Vertex AI Model Monitoring (data + prediction drift)' }, { id: 'B', text: 'Cloud Logging only' }, { id: 'C', text: 'Cloud Build' }, { id: 'D', text: 'BigQuery' }], correct: ['A'], explanation: 'Model Monitoring computes drift scores against training baselines and alerts on threshold breach.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'Which GCP service collects per-request prediction logs from Vertex AI Endpoints?', options: [{ id: 'A', text: 'Cloud Logging (Vertex AI request logs)' }, { id: 'B', text: 'Cloud Build' }, { id: 'C', text: 'Cloud Run logs' }, { id: 'D', text: 'BigQuery alone' }], correct: ['A'], explanation: 'Vertex AI emits request/response logs to Cloud Logging when sampling is enabled.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'Which Vertex AI feature explains predictions using feature attributions?', options: [{ id: 'A', text: 'Vertex Explainable AI (Sampled Shapley, integrated gradients, XRAI)' }, { id: 'B', text: 'BigQuery alone' }, { id: 'C', text: 'Cloud Run' }, { id: 'D', text: 'Cloud Build' }], correct: ['A'], explanation: 'Explainable AI provides feature attributions for predictions to support debugging and compliance.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'Which Vertex AI feature evaluates the fairness of a model across protected groups?', options: [{ id: 'A', text: 'Vertex AI Bias / Fairness analysis (with What-If Tool integration)' }, { id: 'B', text: 'Cloud Run' }, { id: 'C', text: 'BigQuery alone' }, { id: 'D', text: 'Cloud Build' }], correct: ['A'], explanation: 'Vertex AI surfaces fairness metrics across protected groups using tools like the What-If tool.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'Which GCP feature stores model artifacts immutably for compliance audit?', options: [{ id: 'A', text: 'Cloud Storage with bucket lock / retention policy' }, { id: 'B', text: 'BigQuery only' }, { id: 'C', text: 'Cloud Run' }, { id: 'D', text: 'Cloud SQL' }], correct: ['A'], explanation: 'GCS bucket lock + retention policy provides WORM (write-once-read-many) for immutable artifact storage.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'google-professional-ml-engineer-p1', offset: 0 },
  { slug: 'google-professional-ml-engineer-p2', offset: 9 },
  { slug: 'google-professional-ml-engineer-p3', offset: 18 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: { examId: exam.id, domain: q.domain, difficulty: 3, type: q.type, stem: q.stem, options: q.options, correct: q.correct, explanation: q.explanation, references: [REF], status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up Pro ML to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
