/**
 * Top-up: Google Professional ML Engineer (P1-P3) to 60 questions.
 * P4-P6 already at 60 from PDF parsing.
 *   npx tsx scripts/seed-google-pro-ml-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();
const TARGET = 60;
const TAG_PREFIX = 'topup:google-pro-ml';
const REF = { label: 'Google Professional ML Engineer exam page', url: 'https://cloud.google.com/learn/certification/machine-learning-engineer' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  { domain: 'Architecting low-code AI solutions', type: QType.SINGLE, stem: 'Which Google Cloud service lets you build ML models without writing code, using AutoML?', options: [{ id: 'A', text: 'Vertex AI AutoML' }, { id: 'B', text: 'Cloud Functions' }, { id: 'C', text: 'BigQuery' }, { id: 'D', text: 'Cloud Run' }], correct: ['A'], explanation: 'Vertex AI AutoML offers no-code training for tabular, vision, text, video.' },
  { domain: 'Architecting low-code AI solutions', type: QType.SINGLE, stem: 'Which Google Cloud service lets you train ML models directly inside the data warehouse using SQL?', options: [{ id: 'A', text: 'BigQuery ML' }, { id: 'B', text: 'Cloud SQL' }, { id: 'C', text: 'Cloud Functions' }, { id: 'D', text: 'Vertex AI Workbench' }], correct: ['A'], explanation: 'BigQuery ML enables training/predicting models with SQL syntax (CREATE MODEL, ML.PREDICT).' },
  { domain: 'Architecting low-code AI solutions', type: QType.SINGLE, stem: 'Which Vertex AI capability provides foundation models (Gemini, PaLM, etc.) via APIs?', options: [{ id: 'A', text: 'Vertex AI Model Garden / Generative AI Studio' }, { id: 'B', text: 'BigQuery ML' }, { id: 'C', text: 'Cloud Functions' }, { id: 'D', text: 'Cloud Run' }], correct: ['A'], explanation: 'Model Garden hosts foundation models; Generative AI Studio is the prompt-design UI.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which Vertex AI feature stores and serves features for both training and online inference?', options: [{ id: 'A', text: 'Vertex AI Feature Store' }, { id: 'B', text: 'Cloud Storage' }, { id: 'C', text: 'BigQuery alone' }, { id: 'D', text: 'Cloud Functions' }], correct: ['A'], explanation: 'Vertex AI Feature Store provides offline + online stores with versioning and time-travel for training/inference parity.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which Vertex AI feature centralizes versioned trained models?', options: [{ id: 'A', text: 'Vertex AI Model Registry' }, { id: 'B', text: 'Cloud Storage' }, { id: 'C', text: 'BigQuery' }, { id: 'D', text: 'Cloud Run' }], correct: ['A'], explanation: 'Model Registry tracks versions, evaluations, and deploys to endpoints.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which Vertex AI feature provides governed datasets for ML?', options: [{ id: 'A', text: 'Vertex AI Datasets' }, { id: 'B', text: 'Cloud Storage' }, { id: 'C', text: 'Cloud Run' }, { id: 'D', text: 'Cloud Functions' }], correct: ['A'], explanation: 'Vertex AI Datasets handle import, schema, labeling, and serve as inputs for training jobs.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which IAM role grants the ability to manage ML resources without project-wide ownership?', options: [{ id: 'A', text: 'Vertex AI Admin / Vertex AI User predefined roles' }, { id: 'B', text: 'Project Owner' }, { id: 'C', text: 'Editor' }, { id: 'D', text: 'Viewer' }], correct: ['A'], explanation: 'Service-specific Vertex AI roles provide scoped access without elevating to Owner/Editor.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which Vertex AI feature provides a managed Jupyter environment for collaborative ML development?', options: [{ id: 'A', text: 'Vertex AI Workbench' }, { id: 'B', text: 'Cloud Run' }, { id: 'C', text: 'Cloud Functions' }, { id: 'D', text: 'Compute Engine alone' }], correct: ['A'], explanation: 'Workbench is the managed JupyterLab IDE on GCP — managed-notebooks (single-user) or user-managed.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'Which Vertex AI capability runs distributed training jobs on managed clusters?', options: [{ id: 'A', text: 'Vertex AI Custom Training jobs (with worker pools, GPU/TPU)' }, { id: 'B', text: 'Cloud Functions' }, { id: 'C', text: 'BigQuery only' }, { id: 'D', text: 'Cloud Run' }], correct: ['A'], explanation: 'Custom training jobs scale across multiple workers/GPUs/TPUs with managed orchestration.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'Which framework is Google\'s open-source ML library used heavily on Vertex AI?', options: [{ id: 'A', text: 'TensorFlow / JAX (with PyTorch also fully supported)' }, { id: 'B', text: 'XGBoost only' }, { id: 'C', text: 'scikit-learn only' }, { id: 'D', text: 'MXNet' }], correct: ['A'], explanation: 'Vertex AI supports TF/JAX (Google), PyTorch, scikit-learn, XGBoost via prebuilt containers.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'Which feature in Vertex AI tunes hyperparameters automatically using Bayesian / random / grid search?', options: [{ id: 'A', text: 'Vertex AI Hyperparameter Tuning (Vizier-based)' }, { id: 'B', text: 'BigQuery ML' }, { id: 'C', text: 'Cloud Run' }, { id: 'D', text: 'Cloud Build' }], correct: ['A'], explanation: 'Vertex AI uses Vizier (Google\'s black-box optimization) for HPO with parallel trials.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'Which Vertex AI feature compiles and optimizes models for the Edge TPU or GPU inference?', options: [{ id: 'A', text: 'Vertex AI Optimized inference (NVIDIA Triton / Edge TPU compiler)' }, { id: 'B', text: 'BigQuery ML' }, { id: 'C', text: 'Cloud Run' }, { id: 'D', text: 'Cloud Functions' }], correct: ['A'], explanation: 'Vertex AI optimizes inference via Triton or Edge TPU compilation for accelerated serving.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'Which Vertex AI deployment serves real-time predictions with autoscaling and traffic splitting?', options: [{ id: 'A', text: 'Vertex AI Online Prediction (Endpoints)' }, { id: 'B', text: 'Vertex AI Batch Prediction' }, { id: 'C', text: 'BigQuery' }, { id: 'D', text: 'Cloud Functions' }], correct: ['A'], explanation: 'Online endpoints provide HTTP inference with autoscaling and traffic split between deployed models.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'Which Vertex AI deployment processes large input files asynchronously in parallel?', options: [{ id: 'A', text: 'Vertex AI Batch Prediction' }, { id: 'B', text: 'Online Endpoints' }, { id: 'C', text: 'Cloud Run' }, { id: 'D', text: 'Cloud Build' }], correct: ['A'], explanation: 'Batch Prediction parallelizes scoring across worker nodes for high-throughput offline jobs.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'Which Vertex AI feature shifts a percentage of traffic to a new model version safely?', options: [{ id: 'A', text: 'Endpoint with multiple deployed models + traffic split' }, { id: 'B', text: 'BigQuery ML alone' }, { id: 'C', text: 'Cloud Run revisions only' }, { id: 'D', text: 'Cloud Build' }], correct: ['A'], explanation: 'A Vertex AI endpoint can host multiple model deployments with percentage-based traffic split.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'Which serving option deploys ML models to edge / mobile devices with TensorFlow Lite?', options: [{ id: 'A', text: 'Vertex AI ML / TensorFlow Lite for edge inference' }, { id: 'B', text: 'BigQuery ML' }, { id: 'C', text: 'Cloud Functions' }, { id: 'D', text: 'Cloud Run' }], correct: ['A'], explanation: 'TF Lite (and Edge TPU) provides edge ML inference; Vertex AI ML can manage and update edge models.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which Vertex AI feature is the managed orchestration platform for ML pipelines using Kubeflow Pipelines or TFX?', options: [{ id: 'A', text: 'Vertex AI Pipelines' }, { id: 'B', text: 'Cloud Build' }, { id: 'C', text: 'Cloud Composer' }, { id: 'D', text: 'Cloud Run' }], correct: ['A'], explanation: 'Vertex AI Pipelines is a serverless orchestrator for KFP/TFX pipelines with lineage tracking.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which language/framework defines components and pipelines for Vertex AI Pipelines?', options: [{ id: 'A', text: 'Kubeflow Pipelines (KFP) v2 SDK in Python' }, { id: 'B', text: 'Bash only' }, { id: 'C', text: 'Java / Maven' }, { id: 'D', text: 'Go' }], correct: ['A'], explanation: 'KFP SDK (Python) defines components (containers) and pipelines; Vertex AI Pipelines runs them serverlessly.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which Vertex AI feature schedules pipeline runs?', options: [{ id: 'A', text: 'Vertex AI Pipelines schedules (Cloud Scheduler / cron)' }, { id: 'B', text: 'Cloud Build trigger only' }, { id: 'C', text: 'Cloud Run scheduler' }, { id: 'D', text: 'BigQuery scheduled queries' }], correct: ['A'], explanation: 'Vertex AI Pipelines integrates with Cloud Scheduler for cron-based scheduling.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which feature triggers pipeline runs based on a CI/CD event (e.g., new commit)?', options: [{ id: 'A', text: 'Cloud Build trigger invoking a pipeline run' }, { id: 'B', text: 'Cloud Run alone' }, { id: 'C', text: 'BigQuery ML' }, { id: 'D', text: 'Cloud Functions only' }], correct: ['A'], explanation: 'CI/CD pipelines (Cloud Build) call the Vertex AI API to launch pipeline runs on commit.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which Vertex AI feature versions and tracks all artifacts (datasets, models, metrics) produced by pipeline runs?', options: [{ id: 'A', text: 'Vertex ML Metadata' }, { id: 'B', text: 'Cloud Storage' }, { id: 'C', text: 'BigQuery' }, { id: 'D', text: 'Cloud Build' }], correct: ['A'], explanation: 'Vertex ML Metadata stores lineage of pipeline executions for reproducibility and audit.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which feature in Vertex AI Pipelines lets you run conditional/branching steps?', options: [{ id: 'A', text: 'KFP control-flow constructs (Condition, ParallelFor, ExitHandler)' }, { id: 'B', text: 'Cloud Run revisions' }, { id: 'C', text: 'BigQuery views' }, { id: 'D', text: 'Cloud Functions' }], correct: ['A'], explanation: 'KFP v2 SDK exposes Condition, ParallelFor, and ExitHandler for control flow.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'Which Vertex AI feature monitors deployed models for data drift?', options: [{ id: 'A', text: 'Vertex AI Model Monitoring (data + prediction drift)' }, { id: 'B', text: 'Cloud Logging only' }, { id: 'C', text: 'Cloud Build' }, { id: 'D', text: 'BigQuery' }], correct: ['A'], explanation: 'Model Monitoring computes drift scores against training baselines and alerts on threshold breach.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'Which GCP service collects per-request prediction logs from Vertex AI Endpoints?', options: [{ id: 'A', text: 'Cloud Logging (Vertex AI request logs)' }, { id: 'B', text: 'Cloud Build' }, { id: 'C', text: 'Cloud Run logs' }, { id: 'D', text: 'BigQuery alone' }], correct: ['A'], explanation: 'Vertex AI emits request/response logs to Cloud Logging when sampling is enabled.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'Which Vertex AI feature explains predictions using feature attributions?', options: [{ id: 'A', text: 'Vertex Explainable AI (Sampled Shapley, integrated gradients, XRAI)' }, { id: 'B', text: 'BigQuery alone' }, { id: 'C', text: 'Cloud Run' }, { id: 'D', text: 'Cloud Build' }], correct: ['A'], explanation: 'Explainable AI provides feature attributions for predictions to support debugging and compliance.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'Which Vertex AI feature evaluates the fairness of a model across protected groups?', options: [{ id: 'A', text: 'Vertex AI Bias / Fairness analysis (with What-If Tool integration)' }, { id: 'B', text: 'Cloud Run' }, { id: 'C', text: 'BigQuery alone' }, { id: 'D', text: 'Cloud Build' }], correct: ['A'], explanation: 'Vertex AI surfaces fairness metrics across protected groups using tools like the What-If tool.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'Which GCP feature stores model artifacts immutably for compliance audit?', options: [{ id: 'A', text: 'Cloud Storage with bucket lock / retention policy' }, { id: 'B', text: 'BigQuery only' }, { id: 'C', text: 'Cloud Run' }, { id: 'D', text: 'Cloud SQL' }], correct: ['A'], explanation: 'GCS bucket lock + retention policy provides WORM (write-once-read-many) for immutable artifact storage.' },
  // ───────── Hand-authored supplementals batch 2 (indices 28+) ─────────
  // These cover the same blueprint domains and are used to fill P4 / P5 / P6.
  // Architecting low-code AI solutions (7)
  { domain: 'Architecting low-code AI solutions', type: QType.SINGLE, stem: 'Which Google Cloud service processes invoices, contracts, and forms to extract structured fields without writing parsing code?', options: [{ id: 'A', text: 'Document AI (specialized + custom processors)' }, { id: 'B', text: 'Cloud Storage' }, { id: 'C', text: 'BigQuery' }, { id: 'D', text: 'Cloud Run' }], correct: ['A'], explanation: 'Document AI provides pre-built and custom processors to extract entities from common business documents.' },
  { domain: 'Architecting low-code AI solutions', type: QType.SINGLE, stem: 'Which Vertex AI AutoML capability trains a tabular regression model with no code, given a CSV in Cloud Storage?', options: [{ id: 'A', text: 'AutoML Tabular (Regression objective)' }, { id: 'B', text: 'Custom training only' }, { id: 'C', text: 'BigQuery ML CREATE MODEL (always required)' }, { id: 'D', text: 'Dataflow' }], correct: ['A'], explanation: 'AutoML Tabular handles classification, regression, and forecasting objectives with a managed UI/SDK and no code.' },
  { domain: 'Architecting low-code AI solutions', type: QType.SINGLE, stem: 'Which pre-trained API is the fastest path to extract printed and handwritten text from scanned images?', options: [{ id: 'A', text: 'Cloud Vision API (DOCUMENT_TEXT_DETECTION)' }, { id: 'B', text: 'Speech-to-Text API' }, { id: 'C', text: 'Translation API' }, { id: 'D', text: 'Natural Language API' }], correct: ['A'], explanation: 'DOCUMENT_TEXT_DETECTION is the OCR feature of the Vision API that handles printed and handwritten text.' },
  { domain: 'Architecting low-code AI solutions', type: QType.SINGLE, stem: 'For real-time call-center captioning over telephony audio, which Speech-to-Text model is most appropriate?', options: [{ id: 'A', text: 'phone_call / telephony model' }, { id: 'B', text: 'video model' }, { id: 'C', text: 'medical_dictation' }, { id: 'D', text: 'default short' }], correct: ['A'], explanation: 'The telephony (phone_call) model is tuned for 8 kHz narrowband audio typical in call-center streams.' },
  { domain: 'Architecting low-code AI solutions', type: QType.SINGLE, stem: 'Which BigQuery ML model type is best for predicting a continuous numerical outcome from tabular features?', options: [{ id: 'A', text: 'LINEAR_REG or BOOSTED_TREE_REGRESSOR' }, { id: 'B', text: 'KMEANS' }, { id: 'C', text: 'MATRIX_FACTORIZATION' }, { id: 'D', text: 'TIME_SERIES (ARIMA_PLUS)' }], correct: ['A'], explanation: 'For supervised regression on tabular data, linear regression or boosted-tree regressors are the canonical BQML choices.' },
  { domain: 'Architecting low-code AI solutions', type: QType.SINGLE, stem: 'A team needs a conversational AI agent that can branch by intent, manage state, and integrate with telephony. Which product fits best?', options: [{ id: 'A', text: 'Dialogflow CX' }, { id: 'B', text: 'Cloud Translation' }, { id: 'C', text: 'Cloud Run' }, { id: 'D', text: 'BigQuery ML' }], correct: ['A'], explanation: 'Dialogflow CX is a state-machine-based conversational platform with first-class telephony integrations.' },
  { domain: 'Architecting low-code AI solutions', type: QType.SINGLE, stem: 'Which Vertex AI capability lets analysts prompt foundation models from a UI without writing any code?', options: [{ id: 'A', text: 'Generative AI Studio (in Vertex AI / Model Garden)' }, { id: 'B', text: 'Cloud Build' }, { id: 'C', text: 'Cloud Composer' }, { id: 'D', text: 'BigQuery DTS' }], correct: ['A'], explanation: 'Generative AI Studio is the prompt-design UI surface for Vertex AI foundation models.' },
  // Collaborating within and across teams (8)
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which Vertex AI feature tracks runs, metrics, and parameters across experiments so teammates can compare model versions?', options: [{ id: 'A', text: 'Vertex AI Experiments' }, { id: 'B', text: 'Cloud Logging only' }, { id: 'C', text: 'Cloud Storage versioning' }, { id: 'D', text: 'BigQuery Information Schema' }], correct: ['A'], explanation: 'Vertex AI Experiments logs runs, metrics, and params and offers run comparison views.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which Vertex AI tool visualizes scalar metrics, distributions, and embeddings produced during model training?', options: [{ id: 'A', text: 'Vertex AI TensorBoard' }, { id: 'B', text: 'Cloud Monitoring dashboards only' }, { id: 'C', text: 'Looker Studio' }, { id: 'D', text: 'BigQuery BI Engine' }], correct: ['A'], explanation: 'Vertex AI TensorBoard is the managed TensorBoard service for visualizing training metrics.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which Vertex AI artifact lets teams publish a human-readable summary of a model\'s intended use, performance, and limitations?', options: [{ id: 'A', text: 'Model Cards (via Model Registry)' }, { id: 'B', text: 'Cloud Storage README' }, { id: 'C', text: 'BigQuery table comments' }, { id: 'D', text: 'Cloud Logging exports' }], correct: ['A'], explanation: 'Model Cards document use cases, fairness, and known limitations — central to responsible ML collaboration.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which Vertex AI feature gives complete provenance — datasets → models → endpoints — for any pipeline run?', options: [{ id: 'A', text: 'Vertex ML Metadata (lineage graph)' }, { id: 'B', text: 'Cloud Audit Logs only' }, { id: 'C', text: 'Cloud Source Repositories' }, { id: 'D', text: 'BigQuery DTS' }], correct: ['A'], explanation: 'Vertex ML Metadata captures the lineage of every artifact produced by pipeline executions.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which Workbench notebook variant is fully managed by Google with built-in security patches and idle-timeout shutdown?', options: [{ id: 'A', text: 'Vertex AI Workbench managed notebooks (now "Instances")' }, { id: 'B', text: 'GCE-only manual notebooks' }, { id: 'C', text: 'Cloud Functions' }, { id: 'D', text: 'Cloud Run jobs' }], correct: ['A'], explanation: 'Managed Workbench Instances handle patching, idle-shutdown, and identity automatically — ideal for shared teams.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which IAM role allows a data scientist to run training jobs and create endpoints WITHOUT granting Project Editor?', options: [{ id: 'A', text: 'roles/aiplatform.user (or aiplatform.admin)' }, { id: 'B', text: 'roles/owner' }, { id: 'C', text: 'roles/viewer' }, { id: 'D', text: 'roles/billing.admin' }], correct: ['A'], explanation: 'Vertex AI predefined roles scope permissions to ML resources without granting project-wide write access.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which integration version-controls notebook code while keeping outputs out of git?', options: [{ id: 'A', text: 'Cloud Source Repositories + nbstripout / Jupytext in Workbench' }, { id: 'B', text: 'BigQuery snapshots' }, { id: 'C', text: 'Cloud Storage object versioning of .ipynb' }, { id: 'D', text: 'Cloud Build artifacts' }], correct: ['A'], explanation: 'Pairing a git remote (CSR or GitHub) with nbstripout/Jupytext keeps notebook history clean of bulky outputs.' },
  { domain: 'Collaborating within and across teams to manage data and models', type: QType.SINGLE, stem: 'Which Vertex AI feature provides offline + online feature serving with consistent training/inference values?', options: [{ id: 'A', text: 'Vertex AI Feature Store' }, { id: 'B', text: 'Cloud Storage' }, { id: 'C', text: 'BigQuery BI Engine' }, { id: 'D', text: 'Cloud SQL' }], correct: ['A'], explanation: 'Feature Store provides parity between offline (training) and online (serving) feature reads to prevent skew.' },
  // Scaling prototypes into ML models (9)
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'When a custom training image embeds a non-standard framework version, which approach is most portable?', options: [{ id: 'A', text: 'Build a custom Docker container and push to Artifact Registry, then run as a Vertex AI custom job' }, { id: 'B', text: 'Submit a Cloud Function with the code inline' }, { id: 'C', text: 'Use Cloud Run only' }, { id: 'D', text: 'Use BigQuery ML' }], correct: ['A'], explanation: 'Custom containers via Artifact Registry are the portable, reproducible way to ship arbitrary frameworks/versions.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'For Bayesian-style hyperparameter search across continuous + discrete params, which Vertex AI feature is correct?', options: [{ id: 'A', text: 'Vertex AI Hyperparameter Tuning (uses Vizier)' }, { id: 'B', text: 'Cloud Composer DAG' }, { id: 'C', text: 'Cloud Functions' }, { id: 'D', text: 'BigQuery scheduled queries' }], correct: ['A'], explanation: 'Vizier-powered hyperparameter tuning explores the search space efficiently with parallel trials.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'Which TensorFlow distribution strategy is appropriate for multi-GPU single-machine training?', options: [{ id: 'A', text: 'MirroredStrategy' }, { id: 'B', text: 'MultiWorkerMirroredStrategy' }, { id: 'C', text: 'ParameterServerStrategy' }, { id: 'D', text: 'TPUStrategy' }], correct: ['A'], explanation: 'MirroredStrategy synchronously trains across multiple GPUs on a single machine.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'A team trains 8-GPU jobs and wants to cut precision-related memory use without large accuracy loss. What helps?', options: [{ id: 'A', text: 'Mixed-precision training (FP16/BF16 with loss scaling)' }, { id: 'B', text: 'Switching to CPU' }, { id: 'C', text: 'Increasing replica count to 100' }, { id: 'D', text: 'Disabling autotuning' }], correct: ['A'], explanation: 'Mixed precision uses 16-bit storage with 32-bit master weights — halves memory and accelerates throughput on modern accelerators.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'For training on terabyte-scale TFRecord data, which storage layout maximizes read throughput?', options: [{ id: 'A', text: 'Sharded TFRecord files on GCS read via tf.data with parallel interleave' }, { id: 'B', text: 'A single 1 TB file on local SSD' }, { id: 'C', text: 'Per-row rows in BigQuery streamed individually' }, { id: 'D', text: 'A NFS share' }], correct: ['A'], explanation: 'Multiple sharded TFRecords on GCS with tf.data parallelism maximize throughput on Vertex AI custom jobs.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'Which Vertex AI feature aggregates gradients from many workers more efficiently than all-reduce alone for large jobs?', options: [{ id: 'A', text: 'Vertex AI Reduction Server' }, { id: 'B', text: 'Cloud Functions' }, { id: 'C', text: 'Cloud SQL' }, { id: 'D', text: 'Cloud Composer' }], correct: ['A'], explanation: 'Reduction Server offloads gradient aggregation to dedicated reducers, improving scaling on multi-worker training.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'To reduce training cost ~70% for fault-tolerant jobs, which compute option fits best?', options: [{ id: 'A', text: 'Spot / preemptible VMs as worker pools' }, { id: 'B', text: 'A2 ultragpu always-on' }, { id: 'C', text: 'On-demand TPU v5p only' }, { id: 'D', text: 'Cloud Functions' }], correct: ['A'], explanation: 'Spot VMs are significantly cheaper and work well when training has checkpoint/restart support.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'A model overfits at epoch 7/20. Which technique most directly addresses overfitting WITHOUT changing model architecture?', options: [{ id: 'A', text: 'Early stopping + data augmentation + regularization (L2, dropout)' }, { id: 'B', text: 'Doubling the learning rate' }, { id: 'C', text: 'Removing the validation split' }, { id: 'D', text: 'Switching from Adam to SGD only' }], correct: ['A'], explanation: 'Early stopping, augmentation, and regularization address overfitting at the data + training-loop level.' },
  { domain: 'Scaling prototypes into ML models', type: QType.SINGLE, stem: 'Which is the best way to detect training-serving skew before deploying a model?', options: [{ id: 'A', text: 'Use the same feature engineering code path (e.g. tf.Transform / Feature Store) in train + serve' }, { id: 'B', text: 'Manually copy-paste preprocessing into a Cloud Function' }, { id: 'C', text: 'Skip preprocessing at serving time' }, { id: 'D', text: 'Train on raw data and preprocess only at serving' }], correct: ['A'], explanation: 'Sharing the feature transformation code path between train and serve is the canonical way to prevent skew.' },
  // Serving and scaling models (9)
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'How do you configure a Vertex AI Endpoint to scale to zero when idle?', options: [{ id: 'A', text: 'Vertex AI Endpoints do NOT scale to zero — set the minimum replica count to 1; use Cloud Run if scale-to-zero is required' }, { id: 'B', text: 'Set min replicas to 0 in the endpoint config' }, { id: 'C', text: 'Use a Cloud Function trigger' }, { id: 'D', text: 'Lower the QPS quota' }], correct: ['A'], explanation: 'Vertex AI Endpoints require at least one replica running; teams that need scale-to-zero typically use Cloud Run for inference.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'A model must be reachable only from inside a VPC with no public IP. What Vertex AI feature fits?', options: [{ id: 'A', text: 'Private Endpoints (Private Service Connect)' }, { id: 'B', text: 'Public Endpoints with IAM only' }, { id: 'C', text: 'Cloud NAT' }, { id: 'D', text: 'Identity-Aware Proxy on the endpoint' }], correct: ['A'], explanation: 'Private endpoints expose the endpoint via PSC inside the VPC with no public IP.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'Which container interface must a custom prediction image expose?', options: [{ id: 'A', text: 'HTTP server with /health and /predict routes on a port set via $AIP_HTTP_PORT' }, { id: 'B', text: 'gRPC server on port 22' }, { id: 'C', text: 'WebSocket on port 8443' }, { id: 'D', text: 'A CLI binary' }], correct: ['A'], explanation: 'Vertex AI custom prediction containers must serve HTTP health and predict endpoints on the AIP_HTTP_PORT.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'Which is the simplest serverless option for a Python ML model with cold start under ~5s and scale-to-zero?', options: [{ id: 'A', text: 'Cloud Run with a container that loads the model on cold start' }, { id: 'B', text: 'Vertex AI Endpoint (no scale-to-zero)' }, { id: 'C', text: 'Cloud SQL' }, { id: 'D', text: 'Cloud Composer' }], correct: ['A'], explanation: 'Cloud Run gives true scale-to-zero with per-request billing for low-traffic inference workloads.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'Which high-performance serving runtime supports concurrent multi-model loading and dynamic batching?', options: [{ id: 'A', text: 'NVIDIA Triton Inference Server' }, { id: 'B', text: 'Cloud Functions' }, { id: 'C', text: 'BigQuery' }, { id: 'D', text: 'Pub/Sub' }], correct: ['A'], explanation: 'Triton supports multi-framework models, GPU sharing, ensemble graphs, and dynamic batching.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'A 5-TB monthly batch scoring job needs to run cheapest. Which approach fits?', options: [{ id: 'A', text: 'Vertex AI Batch Prediction with sharded inputs' }, { id: 'B', text: 'A single Cloud Function over 5 TB' }, { id: 'C', text: 'Calling the online endpoint row-by-row' }, { id: 'D', text: 'Running inference in BigQuery without batching' }], correct: ['A'], explanation: 'Batch Prediction parallelizes scoring across workers and reads sharded inputs — the cost-optimized async path.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'Which Vertex AI feature reduces TF model serving latency via XLA/TensorRT-style optimization?', options: [{ id: 'A', text: 'Vertex AI Optimized TensorFlow Runtime' }, { id: 'B', text: 'Cloud Composer' }, { id: 'C', text: 'Cloud SQL' }, { id: 'D', text: 'BigQuery DTS' }], correct: ['A'], explanation: 'The Optimized TensorFlow Runtime applies graph optimizations for lower serving latency on Vertex AI.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'When migrating from legacy AI Platform Prediction, what is the recommended replacement?', options: [{ id: 'A', text: 'Vertex AI Online Prediction Endpoints' }, { id: 'B', text: 'Cloud Build' }, { id: 'C', text: 'Cloud SQL' }, { id: 'D', text: 'Cloud Spanner' }], correct: ['A'], explanation: 'Vertex AI replaced AI Platform Prediction; online endpoints are the supported successor.' },
  { domain: 'Serving and scaling models', type: QType.SINGLE, stem: 'Which technique safely rolls out a new model version while limiting blast radius?', options: [{ id: 'A', text: 'Traffic split (e.g. 10/90) between two deployed model versions on one Vertex AI Endpoint' }, { id: 'B', text: 'Deploying directly with 100% traffic' }, { id: 'C', text: 'Tearing down the old endpoint first' }, { id: 'D', text: 'Manual DNS swap' }], correct: ['A'], explanation: 'Endpoint traffic splitting lets you canary a percentage of traffic to the new version and watch metrics.' },
  // Automating and orchestrating ML pipelines (10)
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'In KFP v2, how do you define a reusable step bundled with its environment?', options: [{ id: 'A', text: 'A containerized Component (Python or Container) decorated with @component' }, { id: 'B', text: 'A Cloud Function only' }, { id: 'C', text: 'A BigQuery view' }, { id: 'D', text: 'A Cloud Source repo' }], correct: ['A'], explanation: 'KFP v2 components encapsulate code + container image and are the unit of reuse in pipelines.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which KFP feature passes a runtime value (e.g. dataset URI) into a pipeline at submit time?', options: [{ id: 'A', text: 'Pipeline parameters (declared in @pipeline signature)' }, { id: 'B', text: 'Hardcoded constants' }, { id: 'C', text: 'Env vars on the worker only' }, { id: 'D', text: 'Cloud Storage notifications' }], correct: ['A'], explanation: 'Pipeline parameters are declared on the @pipeline function and supplied per run.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'How should pipeline components access secrets like API keys without baking them in?', options: [{ id: 'A', text: 'Mount Secret Manager secrets at runtime via the component\'s service account' }, { id: 'B', text: 'Hardcode them in the container image' }, { id: 'C', text: 'Pass them as plain pipeline parameters' }, { id: 'D', text: 'Store them in Cloud Logging' }], correct: ['A'], explanation: 'Secret Manager + the component\'s service account is the correct, auditable way to inject secrets.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which Vertex AI Pipelines feature avoids re-running an expensive component when its inputs are unchanged?', options: [{ id: 'A', text: 'Execution caching (enabled by default)' }, { id: 'B', text: 'Manual restart of failed runs' }, { id: 'C', text: 'Disabling retries' }, { id: 'D', text: 'Lowering the worker count' }], correct: ['A'], explanation: 'Vertex AI Pipelines caches component outputs by hashed inputs — toggleable per component and per run.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'How do components in a KFP pipeline pass large datasets to each other?', options: [{ id: 'A', text: 'Via Artifact / Dataset I/O backed by GCS — components exchange URIs, not bytes' }, { id: 'B', text: 'By inlining the data in pipeline parameters' }, { id: 'C', text: 'Through Cloud Logging messages' }, { id: 'D', text: 'Through Pub/Sub topics' }], correct: ['A'], explanation: 'Components produce Artifact outputs whose URIs (in GCS or Vertex ML Metadata) are consumed by downstream steps.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'A pipeline\'s third step occasionally fails on a transient network error. What is the best mitigation?', options: [{ id: 'A', text: 'Configure component-level retries with backoff in the pipeline definition' }, { id: 'B', text: 'Disable the step' }, { id: 'C', text: 'Reduce parallelism to 1' }, { id: 'D', text: 'Bake retries into pipeline parameters' }], correct: ['A'], explanation: 'KFP v2 supports per-component retry configuration with backoff, which absorbs transient failures.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'What is produced when you call `compiler.Compiler().compile(pipeline_func, "pipeline.json")` in KFP v2?', options: [{ id: 'A', text: 'A compiled pipeline spec (JSON/YAML) you submit to Vertex AI Pipelines' }, { id: 'B', text: 'A Docker image' }, { id: 'C', text: 'A BigQuery table' }, { id: 'D', text: 'A Cloud Function source bundle' }], correct: ['A'], explanation: 'The KFP compiler emits a portable IR (JSON or YAML) that Vertex AI Pipelines executes.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which Google-recommended SDK should you author Vertex AI Pipelines in today?', options: [{ id: 'A', text: 'KFP v2 SDK (kfp >= 2.x)' }, { id: 'B', text: 'KFP v1 SDK only' }, { id: 'C', text: 'Apache Airflow only' }, { id: 'D', text: 'Cloud Workflows YAML only' }], correct: ['A'], explanation: 'KFP v2 is the current SDK Google recommends for new Vertex AI Pipelines work.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'For a production TFX pipeline, which standard component validates input data schema and statistics?', options: [{ id: 'A', text: 'StatisticsGen + SchemaGen + ExampleValidator' }, { id: 'B', text: 'Trainer alone' }, { id: 'C', text: 'Evaluator only' }, { id: 'D', text: 'Pusher only' }], correct: ['A'], explanation: 'TFX uses StatisticsGen → SchemaGen → ExampleValidator to detect anomalies before training.' },
  { domain: 'Automating and orchestrating ML pipelines', type: QType.SINGLE, stem: 'Which CI/CD pattern lets a new git commit automatically retrain a model and gate deployment on quality?', options: [{ id: 'A', text: 'Cloud Build trigger → Vertex AI Pipeline run → evaluator gate → conditional deploy step' }, { id: 'B', text: 'Manual notebook execution only' }, { id: 'C', text: 'BigQuery scheduled query' }, { id: 'D', text: 'Cloud SQL trigger' }], correct: ['A'], explanation: 'Cloud Build triggers on commit, runs the pipeline, and the pipeline\'s evaluator step gates the conditional deploy.' },
  // Monitoring AI solutions (9)
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'What does training-serving skew detection in Vertex AI Model Monitoring compare?', options: [{ id: 'A', text: 'Live request distributions vs the training baseline distribution' }, { id: 'B', text: 'CPU usage on serving replicas' }, { id: 'C', text: 'Latency p99 vs p50' }, { id: 'D', text: 'Pipeline step durations' }], correct: ['A'], explanation: 'Skew detection compares incoming serving feature distributions against the original training data baseline.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'What distinguishes drift detection from skew detection in Vertex AI Model Monitoring?', options: [{ id: 'A', text: 'Drift compares live requests over time (current window vs earlier window); skew compares live vs training baseline' }, { id: 'B', text: 'They are identical' }, { id: 'C', text: 'Drift only works on tabular data; skew only on images' }, { id: 'D', text: 'Drift needs a TPU; skew uses CPU' }], correct: ['A'], explanation: 'Drift = production distribution changing over time; skew = production vs training distribution mismatch.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'How do you alert on a custom metric (e.g. business KPI) emitted from inference code?', options: [{ id: 'A', text: 'Write a Cloud Monitoring custom metric and create an alerting policy on it' }, { id: 'B', text: 'Email yourself manually after each request' }, { id: 'C', text: 'Use BigQuery alone' }, { id: 'D', text: 'Send logs to GCS with no alert policy' }], correct: ['A'], explanation: 'Custom metrics + Cloud Monitoring alerting policies + notification channels is the standard pattern.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'You want a sample of prediction requests + responses logged for offline analysis. Where do you configure this?', options: [{ id: 'A', text: 'Enable request-response logging on the Vertex AI Endpoint (with a sampling rate)' }, { id: 'B', text: 'Cloud Build trigger' }, { id: 'C', text: 'BigQuery DTS' }, { id: 'D', text: 'Cloud Functions' }], correct: ['A'], explanation: 'Endpoint request-response logging writes a sampled payload of inputs/outputs to BigQuery for later analysis.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'Which SRE concept best describes "99% of prediction requests return in under 250 ms" as a measurable goal?', options: [{ id: 'A', text: 'SLO (Service Level Objective) defined on a latency SLI' }, { id: 'B', text: 'An SLA only' }, { id: 'C', text: 'A retention policy' }, { id: 'D', text: 'A quota' }], correct: ['A'], explanation: 'The 99% target on a latency SLI is an SLO; SLAs are external contracts derived from SLOs.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'Which Vertex AI signal indicates that a feature\'s contribution to predictions has shifted (potential model degradation)?', options: [{ id: 'A', text: 'Feature attribution drift (via Explainable AI in Model Monitoring)' }, { id: 'B', text: 'CPU spike' }, { id: 'C', text: 'Higher network egress' }, { id: 'D', text: 'Increased disk reads' }], correct: ['A'], explanation: 'Feature-attribution drift uses Explainable AI scores to surface shifts in how features drive predictions.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'To track production model quality continuously, you should periodically log:', options: [{ id: 'A', text: 'Ground-truth labels joined with predictions to compute precision/recall/AUC on a rolling window' }, { id: 'B', text: 'Only request count' }, { id: 'C', text: 'Only latency p50' }, { id: 'D', text: 'CPU utilization only' }], correct: ['A'], explanation: 'Computing rolling quality metrics requires logging predictions and matching them with later-arriving labels.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'How can you cap inference cost when traffic is bursty and unpredictable on a Vertex AI Endpoint?', options: [{ id: 'A', text: 'Set autoscaling min and max replicas + per-replica CPU/GPU target utilization' }, { id: 'B', text: 'Disable autoscaling' }, { id: 'C', text: 'Use Cloud SQL' }, { id: 'D', text: 'Increase request payload size' }], correct: ['A'], explanation: 'Bounded autoscaling with utilization targets caps maximum spend while still absorbing bursts.' },
  { domain: 'Monitoring AI solutions', type: QType.SINGLE, stem: 'Which is the right approach for monitoring a Vertex AI Endpoint serving a tabular model with sensitive features?', options: [{ id: 'A', text: 'Enable Model Monitoring (skew + drift) on the endpoint with a sampling rate that satisfies privacy policy' }, { id: 'B', text: 'Disable all logging' }, { id: 'C', text: 'Log full payloads at 100% sampling indefinitely' }, { id: 'D', text: 'Rely solely on uptime monitoring' }], correct: ['A'], explanation: 'Vertex AI Model Monitoring with a tuned sampling rate balances visibility into skew/drift with privacy obligations.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  // P1-P3 use the first batch of supplementals (indices 0-27)
  { slug: 'google-professional-ml-engineer-p1', offset: 0 },
  { slug: 'google-professional-ml-engineer-p2', offset: 9 },
  { slug: 'google-professional-ml-engineer-p3', offset: 18 },
  // P4-P6 use the second batch (indices 28+) so they don't duplicate P1-P3
  { slug: 'google-professional-ml-engineer-p4', offset: 28 }, // needs 10 → 28..37
  { slug: 'google-professional-ml-engineer-p5', offset: 38 }, // needs 13 → 38..50
  { slug: 'google-professional-ml-engineer-p6', offset: 51 }  // needs 29 → 51..79
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: { examId: exam.id, domain: q.domain, difficulty: 3, type: q.type, stem: q.stem, options: q.options, correct: q.correct, explanation: q.explanation, references: [REF], status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up Pro ML to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
