/**
 * Top-up: AI-102 (P1-P4 + official) to 60 questions.
 *   npx tsx scripts/seed-microsoft-ai-102-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();
const TARGET = 60;
const TAG_PREFIX = 'topup:microsoft-ai-102';
const REF = { label: 'Microsoft AI-102 exam page', url: 'https://learn.microsoft.com/en-us/credentials/certifications/exams/ai-102/' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  { domain: 'Plan and manage an Azure AI solution', type: QType.SINGLE, stem: 'Which Azure resource provides a unified endpoint for multiple Azure AI services (Vision, Language, Speech, etc.)?', options: [{ id: 'A', text: 'Azure AI Services multi-service resource' }, { id: 'B', text: 'Single-service resource per service' }, { id: 'C', text: 'Azure Bastion' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'Multi-service Azure AI Services resource centralizes billing and a single key/endpoint across multiple AI services.' },
  { domain: 'Plan and manage an Azure AI solution', type: QType.SINGLE, stem: 'Which authentication mechanism is recommended for Azure AI services to avoid hardcoded keys?', options: [{ id: 'A', text: 'Microsoft Entra ID (Managed Identity)' }, { id: 'B', text: 'Hardcoded subscription keys' }, { id: 'C', text: 'Anonymous' }, { id: 'D', text: 'NTLM' }], correct: ['A'], explanation: 'Managed identities + Entra-based RBAC eliminate secret rotation and follow least-privilege.' },
  { domain: 'Plan and manage an Azure AI solution', type: QType.SINGLE, stem: 'Which feature lets you regenerate and rotate Azure AI service keys without downtime?', options: [{ id: 'A', text: 'Two keys (Key1/Key2) — rotate by switching apps to Key2 then regenerating Key1' }, { id: 'B', text: 'Single key only' }, { id: 'C', text: 'Disable encryption' }, { id: 'D', text: 'Public endpoints' }], correct: ['A'], explanation: 'Each service has 2 keys to support zero-downtime rotation.' },
  { domain: 'Plan and manage an Azure AI solution', type: QType.SINGLE, stem: 'Which feature locks down an Azure AI service to a private VNet?', options: [{ id: 'A', text: 'Private Endpoint with public access disabled' }, { id: 'B', text: 'Default public endpoint' }, { id: 'C', text: 'Multi-region peering' }, { id: 'D', text: 'NSG flow logs' }], correct: ['A'], explanation: 'Private Endpoints expose AI services on private IPs in your VNet; disabling public access ensures no public internet ingress.' },
  { domain: 'Plan and manage an Azure AI solution', type: QType.SINGLE, stem: 'Which feature lets you cap costs on Azure AI services?', options: [{ id: 'A', text: 'Pricing tiers (Free/F0, Standard) + Azure Cost Management budgets/alerts' }, { id: 'B', text: 'Public endpoints' }, { id: 'C', text: 'Compliance Manager' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'Choose F0/Standard tiers and set Azure budgets/alerts to prevent runaway costs.' },
  { domain: 'Implement decision support solutions', type: QType.SINGLE, stem: 'Which Azure AI service provides decision-making capabilities like content moderation and personalization?', options: [{ id: 'A', text: 'Azure AI Content Safety / Personalizer' }, { id: 'B', text: 'Azure Files' }, { id: 'C', text: 'Bastion' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'Content Safety moderates text/image; Personalizer recommends actions; Anomaly Detector finds anomalies.' },
  { domain: 'Implement decision support solutions', type: QType.SINGLE, stem: 'Which Azure AI service detects anomalies in time-series data?', options: [{ id: 'A', text: 'Azure AI Anomaly Detector' }, { id: 'B', text: 'Azure SQL DB' }, { id: 'C', text: 'Bastion' }, { id: 'D', text: 'BitLocker' }], correct: ['A'], explanation: 'Anomaly Detector identifies anomalies in univariate or multivariate time-series.' },
  { domain: 'Implement computer vision solutions', type: QType.SINGLE, stem: 'Which Azure AI service offers prebuilt models for tagging, describing, and reading text in general images?', options: [{ id: 'A', text: 'Azure AI Vision' }, { id: 'B', text: 'Azure AI Custom Vision' }, { id: 'C', text: 'Azure AI Face' }, { id: 'D', text: 'Azure AI Document Intelligence' }], correct: ['A'], explanation: 'Azure AI Vision provides prebuilt image analysis; Custom Vision is for training your own classifiers.' },
  { domain: 'Implement computer vision solutions', type: QType.SINGLE, stem: 'Which Azure AI service trains custom image classifiers and object detectors?', options: [{ id: 'A', text: 'Azure AI Custom Vision' }, { id: 'B', text: 'Azure AI Vision (prebuilt)' }, { id: 'C', text: 'Azure AI Translator' }, { id: 'D', text: 'Azure AI Speech' }], correct: ['A'], explanation: 'Custom Vision lets you upload labeled images and train models without ML expertise.' },
  { domain: 'Implement computer vision solutions', type: QType.SINGLE, stem: 'Which Custom Vision project type both classifies and locates objects with bounding boxes?', options: [{ id: 'A', text: 'Object detection' }, { id: 'B', text: 'Image classification' }, { id: 'C', text: 'Multilabel classification' }, { id: 'D', text: 'OCR' }], correct: ['A'], explanation: 'Object detection produces bounding boxes; classification only labels the whole image.' },
  { domain: 'Implement computer vision solutions', type: QType.SINGLE, stem: 'Which Azure service extracts structured data from receipts, invoices, IDs, and business cards?', options: [{ id: 'A', text: 'Azure AI Document Intelligence' }, { id: 'B', text: 'Azure AI Vision' }, { id: 'C', text: 'Azure AI Translator' }, { id: 'D', text: 'Azure AI Speech' }], correct: ['A'], explanation: 'Document Intelligence (formerly Form Recognizer) provides prebuilt + custom models for forms and documents.' },
  { domain: 'Implement computer vision solutions', type: QType.SINGLE, stem: 'Which Azure AI service identifies and analyzes faces (detection, attributes, verification, identification)?', options: [{ id: 'A', text: 'Azure AI Face' }, { id: 'B', text: 'Azure AI Vision (basic face detection only)' }, { id: 'C', text: 'Azure AI Custom Vision' }, { id: 'D', text: 'Azure AI Speech' }], correct: ['A'], explanation: 'Face is the dedicated face service. Vision can detect faces but Face provides recognition/identification.' },
  { domain: 'Implement natural language processing solutions', type: QType.SINGLE, stem: 'Which Azure AI service detects PII, named entities, sentiment, key phrases, and language in text?', options: [{ id: 'A', text: 'Azure AI Language' }, { id: 'B', text: 'Azure AI Vision' }, { id: 'C', text: 'Azure AI Speech' }, { id: 'D', text: 'Azure AI Translator' }], correct: ['A'], explanation: 'Azure AI Language consolidates text analytics: NER, PII, sentiment, key phrase, summarization, language detection.' },
  { domain: 'Implement natural language processing solutions', type: QType.SINGLE, stem: 'Which Azure AI Language feature builds intent + entity-extraction models for chatbots?', options: [{ id: 'A', text: 'Conversational Language Understanding (CLU)' }, { id: 'B', text: 'Sentiment analysis' }, { id: 'C', text: 'Custom NER' }, { id: 'D', text: 'Translator' }], correct: ['A'], explanation: 'CLU is the successor to LUIS for intent classification + entity extraction in conversational interfaces.' },
  { domain: 'Implement natural language processing solutions', type: QType.SINGLE, stem: 'Which Azure AI Language feature builds question-answering knowledge bases from FAQs?', options: [{ id: 'A', text: 'Question answering' }, { id: 'B', text: 'Sentiment analysis' }, { id: 'C', text: 'Translator' }, { id: 'D', text: 'CLU' }], correct: ['A'], explanation: 'Question Answering (formerly QnA Maker) builds searchable QA over FAQs and documents.' },
  { domain: 'Implement natural language processing solutions', type: QType.SINGLE, stem: 'Which Azure AI service translates text and supports custom-trained domain-specific models?', options: [{ id: 'A', text: 'Azure AI Translator (with Custom Translator)' }, { id: 'B', text: 'Azure AI Language' }, { id: 'C', text: 'Azure AI Speech' }, { id: 'D', text: 'Azure AI Vision' }], correct: ['A'], explanation: 'Translator handles 100+ languages; Custom Translator allows domain customization.' },
  { domain: 'Implement natural language processing solutions', type: QType.SINGLE, stem: 'Which Azure AI service converts speech to text in real time and offline?', options: [{ id: 'A', text: 'Azure AI Speech (Speech-to-Text)' }, { id: 'B', text: 'Azure AI Language' }, { id: 'C', text: 'Azure AI Vision' }, { id: 'D', text: 'Azure OpenAI' }], correct: ['A'], explanation: 'Speech service includes STT, TTS, speech translation, speaker recognition, custom speech, and custom voice.' },
  { domain: 'Implement natural language processing solutions', type: QType.SINGLE, stem: 'Which Azure AI Speech feature trains a custom acoustic/language model for jargon-heavy domains?', options: [{ id: 'A', text: 'Custom Speech' }, { id: 'B', text: 'Custom NER' }, { id: 'C', text: 'Custom Vision' }, { id: 'D', text: 'Translator' }], correct: ['A'], explanation: 'Custom Speech lets you upload audio + transcripts to fine-tune a model for domain accuracy.' },
  { domain: 'Implement knowledge mining and document intelligence solutions', type: QType.SINGLE, stem: 'Which Azure service indexes documents and provides AI-enriched search with vector + keyword?', options: [{ id: 'A', text: 'Azure AI Search (formerly Cognitive Search)' }, { id: 'B', text: 'Azure SQL Database' }, { id: 'C', text: 'Azure Bastion' }, { id: 'D', text: 'Azure Storage' }], correct: ['A'], explanation: 'Azure AI Search indexes content with built-in AI enrichment skillsets and vector search.' },
  { domain: 'Implement knowledge mining and document intelligence solutions', type: QType.SINGLE, stem: 'Which Azure AI Search capability is critical for retrieval-augmented generation (RAG) with LLMs?', options: [{ id: 'A', text: 'Vector search (with embeddings)' }, { id: 'B', text: 'Wildcard search only' }, { id: 'C', text: 'Phonetic matching' }, { id: 'D', text: 'Synonym maps' }], correct: ['A'], explanation: 'Vector search retrieves semantically similar documents using embeddings — the foundation of RAG.' },
  { domain: 'Implement knowledge mining and document intelligence solutions', type: QType.SINGLE, stem: 'Which Azure AI Search component applies enrichments (OCR, key phrase extraction, etc.) during indexing?', options: [{ id: 'A', text: 'Skillset (custom or built-in skills)' }, { id: 'B', text: 'Indexer alone' }, { id: 'C', text: 'Synonym maps' }, { id: 'D', text: 'Suggesters' }], correct: ['A'], explanation: 'Skillsets chain built-in cognitive skills (OCR, language detection, NER, etc.) and custom skills.' },
  { domain: 'Implement knowledge mining and document intelligence solutions', type: QType.SINGLE, stem: 'Which Document Intelligence prebuilt model extracts general layout (lines, tables, selection marks) from arbitrary documents?', options: [{ id: 'A', text: 'Layout model' }, { id: 'B', text: 'Receipt model' }, { id: 'C', text: 'Invoice model' }, { id: 'D', text: 'ID document model' }], correct: ['A'], explanation: 'Layout extracts text, tables, and selection marks from any document. Other models are specialized.' },
  { domain: 'Implement generative AI solutions', type: QType.SINGLE, stem: 'Which Azure service provides REST/SDK access to OpenAI models with enterprise security?', options: [{ id: 'A', text: 'Azure OpenAI Service' }, { id: 'B', text: 'Azure ML' }, { id: 'C', text: 'Azure Functions' }, { id: 'D', text: 'Azure Bastion' }], correct: ['A'], explanation: 'Azure OpenAI hosts GPT-4, GPT-3.5, embeddings, DALL-E, Whisper with Azure SLA, identity, networking.' },
  { domain: 'Implement generative AI solutions', type: QType.SINGLE, stem: 'Which Azure OpenAI parameter controls randomness/creativity of generated text?', options: [{ id: 'A', text: 'Temperature' }, { id: 'B', text: 'Max tokens' }, { id: 'C', text: 'Frequency penalty' }, { id: 'D', text: 'Stop sequences' }], correct: ['A'], explanation: 'Higher temperature → more diverse output; lower → more deterministic.' },
  { domain: 'Implement generative AI solutions', type: QType.SINGLE, stem: 'Which Azure OpenAI feature adds your own data to the LLM context for grounded answers?', options: [{ id: 'A', text: 'Retrieval-Augmented Generation (RAG) using Azure AI Search vector index' }, { id: 'B', text: 'Setting temperature to 0' }, { id: 'C', text: 'Stop sequences' }, { id: 'D', text: 'Frequency penalty' }], correct: ['A'], explanation: 'RAG injects retrieved passages into the prompt as context, grounding responses in your own data.' },
  { domain: 'Implement generative AI solutions', type: QType.SINGLE, stem: 'Which Azure OpenAI parameter constrains the length of the model\'s response?', options: [{ id: 'A', text: 'Max tokens (max_tokens)' }, { id: 'B', text: 'Temperature' }, { id: 'C', text: 'Top-p' }, { id: 'D', text: 'Stop sequences only' }], correct: ['A'], explanation: 'max_tokens caps the output length. Stop sequences end generation when matched but do not bound length.' },
  { domain: 'Implement generative AI solutions', type: QType.SINGLE, stem: 'Which Azure OpenAI message role tells the model how to behave (persona, rules)?', options: [{ id: 'A', text: 'system' }, { id: 'B', text: 'user' }, { id: 'C', text: 'assistant' }, { id: 'D', text: 'function' }], correct: ['A'], explanation: 'The system message sets persona and constraints. user contains the user input; assistant captures previous outputs; function (legacy) was for function-calling responses.' },
  { domain: 'Implement generative AI solutions', type: QType.SINGLE, stem: 'Which Azure OpenAI capability filters harmful content in prompts and completions automatically?', options: [{ id: 'A', text: 'Content safety / content filters' }, { id: 'B', text: 'Temperature' }, { id: 'C', text: 'Token limit' }, { id: 'D', text: 'Stop sequences' }], correct: ['A'], explanation: 'Built-in content filters screen for hate, sexual, violence, and self-harm categories with configurable thresholds.' },
  { domain: 'Implement generative AI solutions', type: QType.SINGLE, stem: 'Which Azure OpenAI feature runs structured tool calls / function calls to integrate external systems?', options: [{ id: 'A', text: 'Function calling / tool calling' }, { id: 'B', text: 'Embeddings only' }, { id: 'C', text: 'DALL-E' }, { id: 'D', text: 'Whisper' }], correct: ['A'], explanation: 'Function/tool calling lets the model invoke developer-defined functions with structured arguments.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'microsoft-ai-102-p1', offset: 0 },
  { slug: 'microsoft-ai-102-p2', offset: 6 },
  { slug: 'microsoft-ai-102-p3', offset: 12 },
  { slug: 'microsoft-ai-102-p4', offset: 18 },
  { slug: 'microsoft-ai-102-official', offset: 24 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: { examId: exam.id, domain: q.domain, difficulty: 3, type: q.type, stem: q.stem, options: q.options, correct: q.correct, explanation: q.explanation, references: [REF], status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up AI-102 to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
