/**
 * Top-up: MS-102 (P1-P4) to 60 questions.
 *   npx tsx scripts/seed-microsoft-ms-102-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();
const TARGET = 60;
const TAG_PREFIX = 'topup:microsoft-ms-102';
const REF = { label: 'Microsoft MS-102 exam page', url: 'https://learn.microsoft.com/en-us/credentials/certifications/exams/ms-102/' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  { domain: 'Deploy and manage a Microsoft 365 tenant', type: QType.SINGLE, stem: 'Which Microsoft 365 admin role provides full control over the tenant?', options: [{ id: 'A', text: 'Global Administrator' }, { id: 'B', text: 'Reports Reader' }, { id: 'C', text: 'Service Support Administrator' }, { id: 'D', text: 'License Administrator' }], correct: ['A'], explanation: 'Global Admin has highest privileges. Use sparingly and protect with PIM/MFA. Microsoft recommends 2-4 break-glass GA accounts max.' },
  { domain: 'Deploy and manage a Microsoft 365 tenant', type: QType.SINGLE, stem: 'Which Microsoft 365 service hub centralizes admin tasks for the whole tenant?', options: [{ id: 'A', text: 'Microsoft 365 admin center (admin.microsoft.com)' }, { id: 'B', text: 'Azure portal' }, { id: 'C', text: 'Defender for Cloud' }, { id: 'D', text: 'Microsoft Edge' }], correct: ['A'], explanation: 'M365 admin center is the primary tenant management portal; specialized tasks deep-link into Exchange/SharePoint/Teams admin centers.' },
  { domain: 'Deploy and manage a Microsoft 365 tenant', type: QType.SINGLE, stem: 'Which feature lets you assign Microsoft 365 licenses to users automatically based on group membership?', options: [{ id: 'A', text: 'Group-based licensing' }, { id: 'B', text: 'Manual per-user assignment only' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'PIM' }], correct: ['A'], explanation: 'Group-based licensing assigns licenses to security groups; new members inherit licenses automatically.' },
  { domain: 'Deploy and manage a Microsoft 365 tenant', type: QType.SINGLE, stem: 'Which DNS record type does Microsoft 365 require to verify ownership of a custom domain during onboarding?', options: [{ id: 'A', text: 'TXT (or MX) record' }, { id: 'B', text: 'A record' }, { id: 'C', text: 'PTR record' }, { id: 'D', text: 'SRV record' }], correct: ['A'], explanation: 'M365 verifies domain ownership using a TXT or MX challenge.' },
  { domain: 'Deploy and manage a Microsoft 365 tenant', type: QType.SINGLE, stem: 'Which feature lets you delegate admin permissions to a partner or MSP?', options: [{ id: 'A', text: 'Delegated Access Permissions / Granular Delegated Admin Privileges (GDAP)' }, { id: 'B', text: 'Conditional Access' }, { id: 'C', text: 'PIM' }, { id: 'D', text: 'Defender for Identity' }], correct: ['A'], explanation: 'GDAP replaces the older DAP and provides time-bound, role-scoped partner access.' },
  { domain: 'Deploy and manage a Microsoft 365 tenant', type: QType.SINGLE, stem: 'Which Microsoft 365 monitoring view shows tenant-level service health?', options: [{ id: 'A', text: 'Service Health' }, { id: 'B', text: 'Compliance Manager' }, { id: 'C', text: 'Microsoft Graph Explorer' }, { id: 'D', text: 'Windows Update' }], correct: ['A'], explanation: 'Service Health in the M365 admin center reports incidents and advisories across services.' },
  { domain: 'Deploy and manage a Microsoft 365 tenant', type: QType.SINGLE, stem: 'Which type of Entra ID group is recommended when assigning licenses and access to Microsoft 365 apps?', options: [{ id: 'A', text: 'Microsoft 365 group (formerly Office 365 group)' }, { id: 'B', text: 'Distribution list' }, { id: 'C', text: 'Mail-enabled security group only' }, { id: 'D', text: 'Dynamic device group' }], correct: ['A'], explanation: 'M365 groups bring together a mailbox, calendar, SharePoint site, OneNote, Teams, etc.' },
  { domain: 'Deploy and manage a Microsoft 365 tenant', type: QType.SINGLE, stem: 'Which feature lets users self-service create groups in Microsoft 365 with optional approval?', options: [{ id: 'A', text: 'Self-service group creation (with naming policy and access reviews)' }, { id: 'B', text: 'Manual ticketing only' }, { id: 'C', text: 'Compliance Manager' }, { id: 'D', text: 'Defender for Identity' }], correct: ['A'], explanation: 'Self-service group creation with naming/blocklist policies and approval flows balances agility and governance.' },

  { domain: 'Implement and manage identity and access in Microsoft Entra ID', type: QType.SINGLE, stem: 'Which Entra ID feature synchronizes on-prem AD users to the cloud?', options: [{ id: 'A', text: 'Entra Cloud Sync (or Microsoft Entra Connect)' }, { id: 'B', text: 'Conditional Access' }, { id: 'C', text: 'PIM' }, { id: 'D', text: 'Defender for Cloud' }], correct: ['A'], explanation: 'Cloud Sync (newer, lightweight) and Connect Sync (full-featured) sync directories from AD to Entra.' },
  { domain: 'Implement and manage identity and access in Microsoft Entra ID', type: QType.SINGLE, stem: 'Which authentication method federates on-prem AD with Entra so users sign in with on-prem credentials?', options: [{ id: 'A', text: 'AD FS (or Pass-through Authentication, or Password Hash Sync)' }, { id: 'B', text: 'NTLM only' }, { id: 'C', text: 'Anonymous' }, { id: 'D', text: 'IPsec' }], correct: ['A'], explanation: 'Federation/PTA/PHS are the three Entra hybrid identity authentication methods. PHS is recommended for most.' },
  { domain: 'Implement and manage identity and access in Microsoft Entra ID', type: QType.SINGLE, stem: 'Which Conditional Access setting requires MFA when sign-in risk is high?', options: [{ id: 'A', text: 'Sign-in risk-based Conditional Access policy with grant control "Require MFA"' }, { id: 'B', text: 'Disable MFA' }, { id: 'C', text: 'Allow anonymous sign-in' }, { id: 'D', text: 'Set password expiry to 30 days' }], correct: ['A'], explanation: 'Risk-based CA dynamically applies MFA when Entra ID Protection signals indicate a risky sign-in.' },
  { domain: 'Implement and manage identity and access in Microsoft Entra ID', type: QType.SINGLE, stem: 'Which Entra ID feature provides time-bounded admin role activation?', options: [{ id: 'A', text: 'Privileged Identity Management (PIM)' }, { id: 'B', text: 'Conditional Access' }, { id: 'C', text: 'Self-Service Password Reset' }, { id: 'D', text: 'Defender for Identity' }], correct: ['A'], explanation: 'PIM activates eligible roles for set durations with optional approval.' },
  { domain: 'Implement and manage identity and access in Microsoft Entra ID', type: QType.SINGLE, stem: 'Which Entra ID feature audits high-privileged role assignments and access patterns periodically?', options: [{ id: 'A', text: 'Access reviews' }, { id: 'B', text: 'PIM only' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'Compliance Manager' }], correct: ['A'], explanation: 'Access reviews periodically have approvers confirm or remove access, reducing standing privilege.' },
  { domain: 'Implement and manage identity and access in Microsoft Entra ID', type: QType.SINGLE, stem: 'Which feature lets B2B guests authenticate with their existing identities?', options: [{ id: 'A', text: 'Microsoft Entra B2B collaboration' }, { id: 'B', text: 'AD FS only' }, { id: 'C', text: 'Self-service password reset' }, { id: 'D', text: 'Defender for Identity' }], correct: ['A'], explanation: 'B2B invites guests using their own Microsoft / Google / SAML identity providers.' },
  { domain: 'Implement and manage identity and access in Microsoft Entra ID', type: QType.SINGLE, stem: 'Which Entra ID feature lets you use FIDO2 security keys as a passwordless authentication method?', options: [{ id: 'A', text: 'Passwordless authentication with FIDO2' }, { id: 'B', text: 'NTLM' }, { id: 'C', text: 'WPA2-PSK' }, { id: 'D', text: 'IPsec' }], correct: ['A'], explanation: 'FIDO2 security keys provide phishing-resistant, passwordless authentication via WebAuthn.' },

  { domain: 'Manage security and threats by using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which service is the unified threat-protection portal across endpoints, identities, email, cloud apps?', options: [{ id: 'A', text: 'Microsoft Defender XDR (security.microsoft.com)' }, { id: 'B', text: 'Azure portal' }, { id: 'C', text: 'M365 admin center' }, { id: 'D', text: 'Compliance portal' }], correct: ['A'], explanation: 'Defender XDR unifies Defender for Endpoint, Identity, Office 365, and Cloud Apps signals.' },
  { domain: 'Manage security and threats by using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender component protects mailboxes from phishing and malware in attachments/links?', options: [{ id: 'A', text: 'Defender for Office 365' }, { id: 'B', text: 'Defender for Endpoint' }, { id: 'C', text: 'Defender for Identity' }, { id: 'D', text: 'Defender for Cloud' }], correct: ['A'], explanation: 'Defender for Office 365 protects email/Teams/SharePoint with Safe Attachments, Safe Links, anti-phishing.' },
  { domain: 'Manage security and threats by using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender component protects Windows/Mac/Linux/mobile endpoints with EDR + ASR + AV?', options: [{ id: 'A', text: 'Defender for Endpoint' }, { id: 'B', text: 'Defender for Cloud' }, { id: 'C', text: 'Defender for Identity' }, { id: 'D', text: 'Defender for Cloud Apps' }], correct: ['A'], explanation: 'MDE provides EDR, AV, ASR, vulnerability management on endpoints.' },
  { domain: 'Manage security and threats by using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender component monitors on-prem AD/AD FS for compromise indicators?', options: [{ id: 'A', text: 'Defender for Identity' }, { id: 'B', text: 'Defender for Endpoint' }, { id: 'C', text: 'Defender for Office 365' }, { id: 'D', text: 'Defender for SQL' }], correct: ['A'], explanation: 'Defender for Identity (formerly ATP / Azure ATP) detects on-prem identity attacks like Pass-the-Hash, Golden Ticket.' },
  { domain: 'Manage security and threats by using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender component is a CASB providing visibility and control over SaaS apps and shadow IT?', options: [{ id: 'A', text: 'Defender for Cloud Apps' }, { id: 'B', text: 'Defender for Endpoint' }, { id: 'C', text: 'Defender for Office 365' }, { id: 'D', text: 'Defender for Cloud' }], correct: ['A'], explanation: 'Defender for Cloud Apps (formerly MCAS) provides CASB capabilities: discovery, governance, threat detection across SaaS.' },
  { domain: 'Manage security and threats by using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender for Endpoint capability isolates a compromised device from the network?', options: [{ id: 'A', text: 'Live response / Isolate machine' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Windows Update' }, { id: 'D', text: 'Group Policy' }], correct: ['A'], explanation: 'MDE supports network isolation while allowing the security team to remediate via Live response.' },
  { domain: 'Manage security and threats by using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender for Office 365 feature opens email attachments in a sandbox to detect zero-day malware?', options: [{ id: 'A', text: 'Safe Attachments' }, { id: 'B', text: 'Safe Links' }, { id: 'C', text: 'Anti-phish policies' }, { id: 'D', text: 'DKIM' }], correct: ['A'], explanation: 'Safe Attachments detonates files in a sandbox before delivery (or uses Dynamic Delivery).' },
  { domain: 'Manage security and threats by using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which feature time-of-click rewrites URLs in emails to detect malicious links?', options: [{ id: 'A', text: 'Safe Links' }, { id: 'B', text: 'Safe Attachments' }, { id: 'C', text: 'DMARC' }, { id: 'D', text: 'Conditional Access' }], correct: ['A'], explanation: 'Safe Links rewrites URLs and checks them against the latest threat intelligence at click time.' },
  { domain: 'Manage security and threats by using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which feature aggregates incidents across Defender products into unified investigations?', options: [{ id: 'A', text: 'Defender XDR Incident view (correlated alerts)' }, { id: 'B', text: 'Compliance Manager' }, { id: 'C', text: 'M365 admin center' }, { id: 'D', text: 'Windows Update' }], correct: ['A'], explanation: 'Defender XDR correlates alerts from Endpoint/Identity/Office/Cloud Apps into incidents to reduce SOC fatigue.' },
  { domain: 'Manage security and threats by using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which DNS feature helps prevent email spoofing by signing outbound mail?', options: [{ id: 'A', text: 'DKIM' }, { id: 'B', text: 'PTR' }, { id: 'C', text: 'A record' }, { id: 'D', text: 'SRV' }], correct: ['A'], explanation: 'DKIM signs outbound mail with a domain key. SPF lists allowed senders. DMARC ties them together.' },
  { domain: 'Manage security and threats by using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which DMARC policy directs receivers to reject unauthenticated mail?', options: [{ id: 'A', text: 'p=reject' }, { id: 'B', text: 'p=none' }, { id: 'C', text: 'p=quarantine' }, { id: 'D', text: 'p=allow' }], correct: ['A'], explanation: 'p=reject enforces strictest action on SPF/DKIM failures. p=quarantine sends to spam; p=none monitors only.' },
  { domain: 'Manage security and threats by using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender for Endpoint setting reduces attack surface (ASR) via predefined rules like blocking Office macros?', options: [{ id: 'A', text: 'Attack Surface Reduction (ASR) rules' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'Network Watcher' }], correct: ['A'], explanation: 'ASR rules block known dangerous behaviors (e.g., child processes from Office, obfuscated scripts, USB execution).' },
  { domain: 'Manage security and threats by using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender for Endpoint feature catalogs known vulnerabilities on managed devices?', options: [{ id: 'A', text: 'Microsoft Defender Vulnerability Management' }, { id: 'B', text: 'Conditional Access' }, { id: 'C', text: 'PIM' }, { id: 'D', text: 'Compliance Manager' }], correct: ['A'], explanation: 'Defender Vulnerability Management surfaces CVEs, software inventory, and configuration weaknesses with prioritization.' },

  { domain: 'Manage compliance by using Microsoft Purview', type: QType.SINGLE, stem: 'Which Purview feature classifies and labels sensitive data so it can be tracked and protected?', options: [{ id: 'A', text: 'Sensitivity labels' }, { id: 'B', text: 'Conditional Access' }, { id: 'C', text: 'BitLocker' }, { id: 'D', text: 'PIM' }], correct: ['A'], explanation: 'Sensitivity labels (formerly AIP labels) classify content and apply protections like encryption and watermarks.' },
  { domain: 'Manage compliance by using Microsoft Purview', type: QType.SINGLE, stem: 'Which Purview feature retains or deletes data based on policies for compliance reasons?', options: [{ id: 'A', text: 'Retention labels and policies' }, { id: 'B', text: 'Service Health' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'Retention policies meet legal/regulatory requirements for data lifecycle (retain X years, then delete).' },
  { domain: 'Manage compliance by using Microsoft Purview', type: QType.SINGLE, stem: 'Which Purview feature scans communications across Teams/Exchange for policy violations like harassment or insider risk?', options: [{ id: 'A', text: 'Communication compliance' }, { id: 'B', text: 'Defender for Endpoint' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'PIM' }], correct: ['A'], explanation: 'Communication compliance flags risky messages and supports remediation workflows.' },
  { domain: 'Manage compliance by using Microsoft Purview', type: QType.SINGLE, stem: 'Which Purview feature finds and exports content for legal eDiscovery?', options: [{ id: 'A', text: 'eDiscovery (Standard / Premium)' }, { id: 'B', text: 'Service Health' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'Defender for Endpoint' }], correct: ['A'], explanation: 'eDiscovery searches across mailboxes/sites/Teams; Premium adds advanced workflows, custodian management, machine-learning prioritization.' },
  { domain: 'Manage compliance by using Microsoft Purview', type: QType.SINGLE, stem: 'Which Purview feature blocks transmission of sensitive data (e.g., credit cards) via email or SharePoint?', options: [{ id: 'A', text: 'Data Loss Prevention (DLP)' }, { id: 'B', text: 'Conditional Access' }, { id: 'C', text: 'Compliance Manager' }, { id: 'D', text: 'PIM' }], correct: ['A'], explanation: 'DLP detects sensitive info (built-in or custom types) and applies block / warn / encrypt actions across M365 services.' },
  { domain: 'Manage compliance by using Microsoft Purview', type: QType.SINGLE, stem: 'Which Purview feature scores tenant compliance against frameworks like NIST, ISO, GDPR?', options: [{ id: 'A', text: 'Compliance Manager' }, { id: 'B', text: 'Service Health' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'Defender for Endpoint' }], correct: ['A'], explanation: 'Compliance Manager calculates a Compliance Score by mapping configured controls to control sets in standards/regulations.' },
  { domain: 'Manage compliance by using Microsoft Purview', type: QType.SINGLE, stem: 'Which feature limits which devices can access Microsoft 365 based on compliance posture?', options: [{ id: 'A', text: 'Conditional Access + Intune device compliance' }, { id: 'B', text: 'Defender for Identity' }, { id: 'C', text: 'PIM' }, { id: 'D', text: 'Compliance Manager' }], correct: ['A'], explanation: 'CA grant control "Require compliant device" combined with Intune compliance policies enforces device hygiene.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'microsoft-ms-102-p1', offset: 0 },
  { slug: 'microsoft-ms-102-p2', offset: 12 },
  { slug: 'microsoft-ms-102-p3', offset: 24 },
  { slug: 'microsoft-ms-102-p4', offset: 36 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: { examId: exam.id, domain: q.domain, difficulty: 3, type: q.type, stem: q.stem, options: q.options, correct: q.correct, explanation: q.explanation, references: [REF], status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up MS-102 to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
