/**
 * Top-up: Google ACE (P1, P2) to 60 questions.
 *   npx tsx scripts/seed-google-ace-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();
const TARGET = 60;
const TAG_PREFIX = 'topup:google-ace';
const REF = { label: 'Google Associate Cloud Engineer exam page', url: 'https://cloud.google.com/learn/certification/cloud-engineer' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  { domain: 'Setting up a cloud solution environment', type: QType.SINGLE, stem: 'Which GCP resource hierarchy level is the highest, containing folders/projects?', options: [{ id: 'A', text: 'Organization' }, { id: 'B', text: 'Folder' }, { id: 'C', text: 'Project' }, { id: 'D', text: 'Resource' }], correct: ['A'], explanation: 'Org → Folder(s) → Project(s) → Resources. Policies set at higher levels inherit downward.' },
  { domain: 'Setting up a cloud solution environment', type: QType.SINGLE, stem: 'Which gcloud command authenticates the CLI as the current user?', options: [{ id: 'A', text: 'gcloud auth login' }, { id: 'B', text: 'gcloud init' }, { id: 'C', text: 'gcloud config' }, { id: 'D', text: 'gcloud projects list' }], correct: ['A'], explanation: '`gcloud auth login` opens a browser to authenticate. `gcloud init` walks through full setup; the others manage config.' },
  { domain: 'Setting up a cloud solution environment', type: QType.SINGLE, stem: 'Which GCP service is the centralized billing and budget management interface?', options: [{ id: 'A', text: 'Cloud Billing' }, { id: 'B', text: 'Cloud Logging' }, { id: 'C', text: 'Cloud Monitoring' }, { id: 'D', text: 'Cloud Functions' }], correct: ['A'], explanation: 'Cloud Billing manages billing accounts, budgets, exports to BigQuery for analysis.' },
  { domain: 'Setting up a cloud solution environment', type: QType.SINGLE, stem: 'Which IAM role lets a user manage all resources of a particular service across a project?', options: [{ id: 'A', text: 'Service-specific Admin role (e.g., roles/compute.admin)' }, { id: 'B', text: 'Owner only' }, { id: 'C', text: 'Viewer only' }, { id: 'D', text: 'Editor only' }], correct: ['A'], explanation: 'Predefined service-specific Admin roles (compute.admin, storage.admin) provide scoped management without project-wide power.' },
  { domain: 'Setting up a cloud solution environment', type: QType.SINGLE, stem: 'Which gcloud command lists all GCP projects you can see?', options: [{ id: 'A', text: 'gcloud projects list' }, { id: 'B', text: 'gcloud orgs list' }, { id: 'C', text: 'gcloud auth list' }, { id: 'D', text: 'gcloud info' }], correct: ['A'], explanation: '`gcloud projects list` enumerates accessible projects.' },
  { domain: 'Setting up a cloud solution environment', type: QType.SINGLE, stem: 'Which feature lets you organize projects under a hierarchy with shared policies for departments / environments?', options: [{ id: 'A', text: 'Folders' }, { id: 'B', text: 'Resource manager labels only' }, { id: 'C', text: 'Service accounts' }, { id: 'D', text: 'Cloud Identity' }], correct: ['A'], explanation: 'Folders nest under the organization to group projects.' },
  { domain: 'Planning and configuring a cloud solution', type: QType.SINGLE, stem: 'Which GCP compute service runs serverless containers with autoscaling, scale-to-zero, and HTTPS endpoints?', options: [{ id: 'A', text: 'Cloud Run' }, { id: 'B', text: 'Compute Engine' }, { id: 'C', text: 'Cloud Functions Gen 1' }, { id: 'D', text: 'GKE Autopilot' }], correct: ['A'], explanation: 'Cloud Run runs container images with HTTP triggers, scales to zero, supports per-request and per-instance billing.' },
  { domain: 'Planning and configuring a cloud solution', type: QType.SINGLE, stem: 'Which compute option is fully managed Kubernetes that abstracts node management?', options: [{ id: 'A', text: 'GKE Autopilot' }, { id: 'B', text: 'GKE Standard' }, { id: 'C', text: 'Compute Engine' }, { id: 'D', text: 'Cloud Run' }], correct: ['A'], explanation: 'GKE Autopilot fully manages nodes (you only manage workloads). Standard exposes node pools.' },
  { domain: 'Planning and configuring a cloud solution', type: QType.SINGLE, stem: 'Which GCS storage class is best for archives accessed less than once a year?', options: [{ id: 'A', text: 'Archive' }, { id: 'B', text: 'Standard' }, { id: 'C', text: 'Nearline' }, { id: 'D', text: 'Coldline' }], correct: ['A'], explanation: 'Archive (least frequent access, lowest storage cost). Coldline is for ~once a quarter; Nearline once a month; Standard frequent.' },
  { domain: 'Planning and configuring a cloud solution', type: QType.SINGLE, stem: 'Which GCP service is the managed relational database for PostgreSQL/MySQL/SQL Server?', options: [{ id: 'A', text: 'Cloud SQL' }, { id: 'B', text: 'Cloud Spanner' }, { id: 'C', text: 'Cloud Bigtable' }, { id: 'D', text: 'BigQuery' }], correct: ['A'], explanation: 'Cloud SQL is managed Postgres/MySQL/SQL Server. Spanner is globally distributed relational; Bigtable is NoSQL wide-column; BigQuery is data warehouse.' },
  { domain: 'Planning and configuring a cloud solution', type: QType.SINGLE, stem: 'Which GCP database is globally distributed, strongly consistent, with horizontal scalability?', options: [{ id: 'A', text: 'Cloud Spanner' }, { id: 'B', text: 'Cloud SQL' }, { id: 'C', text: 'Cloud Bigtable' }, { id: 'D', text: 'Firestore' }], correct: ['A'], explanation: 'Spanner combines relational SQL with horizontal scale-out and external consistency.' },
  { domain: 'Planning and configuring a cloud solution', type: QType.SINGLE, stem: 'Which GCP database is a serverless, scalable NoSQL document database for mobile/web?', options: [{ id: 'A', text: 'Firestore' }, { id: 'B', text: 'Cloud SQL' }, { id: 'C', text: 'BigQuery' }, { id: 'D', text: 'Cloud Spanner' }], correct: ['A'], explanation: 'Firestore is the document NoSQL DB with offline sync and real-time listeners.' },
  { domain: 'Planning and configuring a cloud solution', type: QType.SINGLE, stem: 'Which GCP networking service offers global L7 load balancing with anycast IP?', options: [{ id: 'A', text: 'Global HTTP(S) Load Balancer' }, { id: 'B', text: 'Internal TCP/UDP Load Balancer' }, { id: 'C', text: 'Cloud CDN alone' }, { id: 'D', text: 'Cloud NAT' }], correct: ['A'], explanation: 'Global HTTPS LB uses anycast for low-latency global routing with backend services.' },
  { domain: 'Deploying and implementing a cloud solution', type: QType.SINGLE, stem: 'Which Compute Engine feature lets a VM auto-recover by restarting on healthy hardware?', options: [{ id: 'A', text: 'Live migration / automatic restart on host maintenance' }, { id: 'B', text: 'Manual reboot' }, { id: 'C', text: 'NSG' }, { id: 'D', text: 'Storage migration' }], correct: ['A'], explanation: 'Live migration moves running VMs across hosts during maintenance with no downtime.' },
  { domain: 'Deploying and implementing a cloud solution', type: QType.SINGLE, stem: 'Which Compute Engine instance template feature ensures auto-healing if VMs crash?', options: [{ id: 'A', text: 'Managed Instance Groups (MIGs) with health checks' }, { id: 'B', text: 'Single VM only' }, { id: 'C', text: 'Cloud DNS' }, { id: 'D', text: 'Cloud Functions' }], correct: ['A'], explanation: 'MIGs use templates + health checks to auto-heal/scale and roll updates.' },
  { domain: 'Deploying and implementing a cloud solution', type: QType.SINGLE, stem: 'Which Compute Engine pricing offers the lowest cost for fault-tolerant workloads that can be preempted?', options: [{ id: 'A', text: 'Spot VMs (formerly Preemptible)' }, { id: 'B', text: 'Reserved instances 3-year' }, { id: 'C', text: 'On-demand' }, { id: 'D', text: 'Sole-tenant nodes' }], correct: ['A'], explanation: 'Spot VMs are deeply discounted but can be preempted with 30s notice.' },
  { domain: 'Deploying and implementing a cloud solution', type: QType.SINGLE, stem: 'Which GCP service deploys infrastructure declaratively from YAML/Terraform?', options: [{ id: 'A', text: 'Deployment Manager / Terraform via Cloud Build / Config Connector' }, { id: 'B', text: 'Cloud DNS' }, { id: 'C', text: 'Cloud Scheduler' }, { id: 'D', text: 'Cloud Logging' }], correct: ['A'], explanation: 'Deployment Manager (legacy) and Terraform are the declarative IaC tools for GCP.' },
  { domain: 'Deploying and implementing a cloud solution', type: QType.SINGLE, stem: 'Which kubectl command deploys a manifest from a YAML file?', options: [{ id: 'A', text: 'kubectl apply -f <file>' }, { id: 'B', text: 'kubectl get' }, { id: 'C', text: 'kubectl rollout' }, { id: 'D', text: 'kubectl exec' }], correct: ['A'], explanation: '`kubectl apply -f` creates/updates resources from manifests declaratively.' },
  { domain: 'Deploying and implementing a cloud solution', type: QType.SINGLE, stem: 'Which command creates a new GKE cluster with default settings?', options: [{ id: 'A', text: 'gcloud container clusters create <name>' }, { id: 'B', text: 'gcloud compute instances create' }, { id: 'C', text: 'gcloud functions deploy' }, { id: 'D', text: 'gcloud run deploy' }], correct: ['A'], explanation: '`gcloud container clusters create` provisions a GKE cluster.' },
  { domain: 'Ensuring successful operation of a cloud solution', type: QType.SINGLE, stem: 'Which GCP service collects logs from infrastructure and applications?', options: [{ id: 'A', text: 'Cloud Logging' }, { id: 'B', text: 'Cloud Trace' }, { id: 'C', text: 'Cloud Profiler' }, { id: 'D', text: 'Cloud Build' }], correct: ['A'], explanation: 'Cloud Logging aggregates logs across services; Trace for request latency, Profiler for CPU/memory, Build for CI/CD.' },
  { domain: 'Ensuring successful operation of a cloud solution', type: QType.SINGLE, stem: 'Which service collects time-series metrics with alerting?', options: [{ id: 'A', text: 'Cloud Monitoring' }, { id: 'B', text: 'Cloud Storage' }, { id: 'C', text: 'Cloud DNS' }, { id: 'D', text: 'Cloud Build' }], correct: ['A'], explanation: 'Cloud Monitoring aggregates metrics, dashboards, and alerts (formerly Stackdriver Monitoring).' },
  { domain: 'Ensuring successful operation of a cloud solution', type: QType.SINGLE, stem: 'Which GCP service traces individual request latencies through distributed services?', options: [{ id: 'A', text: 'Cloud Trace' }, { id: 'B', text: 'Cloud Profiler' }, { id: 'C', text: 'Cloud Logging' }, { id: 'D', text: 'Cloud Run' }], correct: ['A'], explanation: 'Cloud Trace produces distributed traces with spans across services (OpenTelemetry compatible).' },
  { domain: 'Ensuring successful operation of a cloud solution', type: QType.SINGLE, stem: 'Which GCP feature lets you provision Kubernetes Workload Identity to map K8s service accounts to IAM service accounts?', options: [{ id: 'A', text: 'GKE Workload Identity' }, { id: 'B', text: 'Service Account Keys' }, { id: 'C', text: 'OAuth' }, { id: 'D', text: 'IAP' }], correct: ['A'], explanation: 'Workload Identity binds K8s SAs to IAM SAs without keys. Service account keys are discouraged.' },
  { domain: 'Configuring access and security', type: QType.SINGLE, stem: 'Which GCP service centrally manages keys for encryption and CMEK?', options: [{ id: 'A', text: 'Cloud KMS' }, { id: 'B', text: 'Secret Manager' }, { id: 'C', text: 'IAM' }, { id: 'D', text: 'Cloud DNS' }], correct: ['A'], explanation: 'Cloud KMS manages cryptographic keys with rotation, IAM, HSM/EKM options. Secret Manager stores secrets like passwords/tokens.' },
  { domain: 'Configuring access and security', type: QType.SINGLE, stem: 'Which GCP service stores secrets like API keys with audit logging and rotation?', options: [{ id: 'A', text: 'Secret Manager' }, { id: 'B', text: 'Cloud KMS' }, { id: 'C', text: 'IAM' }, { id: 'D', text: 'Cloud Storage' }], correct: ['A'], explanation: 'Secret Manager stores secret values with versioning; KMS handles cryptographic keys.' },
  { domain: 'Configuring access and security', type: QType.SINGLE, stem: 'Which GCP feature provides identity-aware access to web apps and SSH/RDP without a VPN?', options: [{ id: 'A', text: 'Identity-Aware Proxy (IAP)' }, { id: 'B', text: 'Cloud VPN' }, { id: 'C', text: 'Cloud NAT' }, { id: 'D', text: 'Cloud DNS' }], correct: ['A'], explanation: 'IAP enforces context-aware authentication and provides BeyondCorp-style access without VPN.' },
  { domain: 'Configuring access and security', type: QType.SINGLE, stem: 'Which GCP feature applies organization-wide policy constraints (e.g., disallow public IPs)?', options: [{ id: 'A', text: 'Organization Policy Service' }, { id: 'B', text: 'Cloud DNS' }, { id: 'C', text: 'IAM only' }, { id: 'D', text: 'Cloud Build triggers' }], correct: ['A'], explanation: 'Org Policies set hard guardrails (deny public IPs, deny external IPs on GCE, restrict regions, etc.).' },
  { domain: 'Configuring access and security', type: QType.SINGLE, stem: 'Which GCP feature enables granular RBAC for IAM with conditions like time-of-day or resource tags?', options: [{ id: 'A', text: 'IAM Conditions' }, { id: 'B', text: 'Org Policy' }, { id: 'C', text: 'Cloud KMS' }, { id: 'D', text: 'Cloud Audit Logs' }], correct: ['A'], explanation: 'IAM Conditions add CEL expressions to bindings (e.g., expires after a date, restricted to specific buckets).' },
  { domain: 'Configuring access and security', type: QType.SINGLE, stem: 'Which logs capture WHO did WHAT in GCP — every API call?', options: [{ id: 'A', text: 'Cloud Audit Logs (Admin Activity, Data Access, System Event)' }, { id: 'B', text: 'Cloud Trace' }, { id: 'C', text: 'Cloud Profiler' }, { id: 'D', text: 'Cloud Storage' }], correct: ['A'], explanation: 'Audit Logs record API calls. Admin Activity is on by default; Data Access requires opt-in.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'google-ace-p1', offset: 0 },
  { slug: 'google-ace-p2', offset: 15 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: { examId: exam.id, domain: q.domain, difficulty: 3, type: q.type, stem: q.stem, options: q.options, correct: q.correct, explanation: q.explanation, references: [REF], status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up Google ACE to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
