/**
 * Top-up: Cisco CCNA (P1-P6) to 60 questions.
 *   npx tsx scripts/seed-cisco-ccna-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();
const TARGET = 60;
const TAG_PREFIX = 'topup:cisco-ccna';
const REF = { label: 'Cisco CCNA (200-301) exam page', url: 'https://www.cisco.com/site/us/en/learn/training-certifications/certifications/enterprise/ccna/index.html' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  { domain: 'Network Fundamentals', type: QType.SINGLE, stem: 'Which OSI layer is responsible for routing packets between networks?', options: [{ id: 'A', text: 'Layer 3 — Network' }, { id: 'B', text: 'Layer 2 — Data Link' }, { id: 'C', text: 'Layer 4 — Transport' }, { id: 'D', text: 'Layer 7 — Application' }], correct: ['A'], explanation: 'Layer 3 (IP) routes packets across networks. Layer 2 frames within one segment.' },
  { domain: 'Network Fundamentals', type: QType.SINGLE, stem: 'What does the subnet mask 255.255.255.0 (/24) provide for IPv4 addressing?', options: [{ id: 'A', text: '256 addresses, 254 usable hosts (excluding network and broadcast)' }, { id: 'B', text: '128 addresses' }, { id: 'C', text: '512 addresses' }, { id: 'D', text: '65536 addresses' }], correct: ['A'], explanation: '/24 has 8 host bits = 256 total. Subtract network (.0) and broadcast (.255) → 254 usable.' },
  { domain: 'Network Fundamentals', type: QType.SINGLE, stem: 'What is the default TTL value for ICMP echo from a typical router?', options: [{ id: 'A', text: '255 (decremented by each hop)' }, { id: 'B', text: '0' }, { id: 'C', text: '1024' }, { id: 'D', text: 'unlimited' }], correct: ['A'], explanation: 'TTL starts at 64, 128, or 255 depending on OS; decremented by each router; packet dropped at 0.' },
  { domain: 'Network Fundamentals', type: QType.SINGLE, stem: 'Which IPv6 address starts with FE80::/10?', options: [{ id: 'A', text: 'Link-local (auto-configured per interface)' }, { id: 'B', text: 'Global unicast' }, { id: 'C', text: 'Multicast' }, { id: 'D', text: 'Loopback' }], correct: ['A'], explanation: 'FE80::/10 is link-local, automatically assigned to each IPv6 interface.' },
  { domain: 'Network Fundamentals', type: QType.SINGLE, stem: 'Which protocol resolves an IPv4 address to a MAC address on a LAN?', options: [{ id: 'A', text: 'ARP' }, { id: 'B', text: 'DNS' }, { id: 'C', text: 'DHCP' }, { id: 'D', text: 'NDP' }], correct: ['A'], explanation: 'ARP resolves IPv4→MAC. NDP (Neighbor Discovery) does this in IPv6. DNS resolves names; DHCP assigns IPs.' },
  { domain: 'Network Fundamentals', type: QType.SINGLE, stem: 'Which RFC1918 range is NOT a valid private IPv4 address space?', options: [{ id: 'A', text: '11.0.0.0/8 (this is public)' }, { id: 'B', text: '10.0.0.0/8' }, { id: 'C', text: '172.16.0.0/12' }, { id: 'D', text: '192.168.0.0/16' }], correct: ['A'], explanation: 'RFC1918 private: 10/8, 172.16/12, 192.168/16. 11/8 is public.' },
  { domain: 'Network Fundamentals', type: QType.SINGLE, stem: 'How many bits are in an IPv6 address?', options: [{ id: 'A', text: '128' }, { id: 'B', text: '32' }, { id: 'C', text: '64' }, { id: 'D', text: '256' }], correct: ['A'], explanation: 'IPv6 = 128 bits = 8 groups of 4 hex digits. IPv4 = 32 bits.' },
  { domain: 'Network Fundamentals', type: QType.SINGLE, stem: 'Which network device operates at OSI Layer 1?', options: [{ id: 'A', text: 'Hub' }, { id: 'B', text: 'Switch' }, { id: 'C', text: 'Router' }, { id: 'D', text: 'Firewall' }], correct: ['A'], explanation: 'Hubs are physical-layer (L1). Switches are L2; routers L3; firewalls L3-7.' },
  { domain: 'Network Access', type: QType.SINGLE, stem: 'Which protocol prevents Layer 2 loops by blocking redundant paths?', options: [{ id: 'A', text: 'STP / RSTP' }, { id: 'B', text: 'OSPF' }, { id: 'C', text: 'BGP' }, { id: 'D', text: 'HSRP' }], correct: ['A'], explanation: 'Spanning Tree Protocol elects a root bridge and blocks redundant paths to prevent loops.' },
  { domain: 'Network Access', type: QType.SINGLE, stem: 'What is a VLAN?', options: [{ id: 'A', text: 'A logical grouping of switch ports into a single broadcast domain, regardless of physical location' }, { id: 'B', text: 'A type of WAN link' }, { id: 'C', text: 'A routing protocol' }, { id: 'D', text: 'A wireless authentication method' }], correct: ['A'], explanation: 'VLANs segment broadcast domains within a switch fabric. 802.1Q tags identify VLAN membership across trunks.' },
  { domain: 'Network Access', type: QType.SINGLE, stem: 'Which 802.1Q field carries the VLAN ID across trunk links?', options: [{ id: 'A', text: 'Tag (4-byte VLAN tag inserted in the Ethernet frame)' }, { id: 'B', text: 'Preamble' }, { id: 'C', text: 'CRC' }, { id: 'D', text: 'EtherType only' }], correct: ['A'], explanation: '802.1Q inserts a 4-byte tag (TPID + TCI) including a 12-bit VLAN ID.' },
  { domain: 'Network Access', type: QType.SINGLE, stem: 'Which Cisco port mode allows traffic from a single VLAN, suitable for end-user devices?', options: [{ id: 'A', text: 'Access port' }, { id: 'B', text: 'Trunk port' }, { id: 'C', text: 'Voice VLAN port' }, { id: 'D', text: 'Hybrid port' }], correct: ['A'], explanation: 'Access ports carry untagged traffic for one VLAN. Trunks carry multiple tagged VLANs.' },
  { domain: 'Network Access', type: QType.SINGLE, stem: 'Which Cisco protocol negotiates trunk encapsulation between two switches?', options: [{ id: 'A', text: 'DTP (Dynamic Trunking Protocol)' }, { id: 'B', text: 'CDP' }, { id: 'C', text: 'LLDP' }, { id: 'D', text: 'STP' }], correct: ['A'], explanation: 'DTP negotiates trunk mode between Cisco switches. Best practice: disable DTP and configure trunks manually.' },
  { domain: 'Network Access', type: QType.SINGLE, stem: 'Which 802.11 wireless security standard introduced AES-CCMP encryption?', options: [{ id: 'A', text: 'WPA2' }, { id: 'B', text: 'WEP' }, { id: 'C', text: 'WPA' }, { id: 'D', text: 'WPS' }], correct: ['A'], explanation: 'WPA2 (IEEE 802.11i) introduced AES-CCMP. WEP/WPA/TKIP are legacy/insecure.' },
  { domain: 'Network Access', type: QType.SINGLE, stem: 'Which port-channel protocol is the IEEE standard for link aggregation?', options: [{ id: 'A', text: 'LACP (802.3ad)' }, { id: 'B', text: 'PAgP' }, { id: 'C', text: 'STP' }, { id: 'D', text: 'CDP' }], correct: ['A'], explanation: 'LACP is the IEEE standard. PAgP is Cisco-proprietary.' },
  { domain: 'IP Connectivity', type: QType.SINGLE, stem: 'Which routing protocol is a link-state protocol used inside a single autonomous system?', options: [{ id: 'A', text: 'OSPF' }, { id: 'B', text: 'BGP' }, { id: 'C', text: 'RIP' }, { id: 'D', text: 'EIGRP (advanced distance vector)' }], correct: ['A'], explanation: 'OSPF (Open Shortest Path First) is link-state IGP. BGP is path-vector EGP. RIP is distance-vector IGP.' },
  { domain: 'IP Connectivity', type: QType.SINGLE, stem: 'Which routing protocol exchanges routing info between autonomous systems on the internet?', options: [{ id: 'A', text: 'BGP' }, { id: 'B', text: 'OSPF' }, { id: 'C', text: 'RIP' }, { id: 'D', text: 'EIGRP' }], correct: ['A'], explanation: 'BGP is the path-vector EGP that runs between AS\'s on the internet.' },
  { domain: 'IP Connectivity', type: QType.SINGLE, stem: 'What does "Administrative Distance" represent in Cisco routing?', options: [{ id: 'A', text: 'A trustworthiness rating used to choose between routing protocols when multiple sources offer the same prefix' }, { id: 'B', text: 'The path length in hops' }, { id: 'C', text: 'A QoS metric' }, { id: 'D', text: 'A bandwidth allocation' }], correct: ['A'], explanation: 'Lower AD = more trusted. Connected = 0, Static = 1, EBGP = 20, OSPF = 110, RIP = 120, IBGP = 200.' },
  { domain: 'IP Connectivity', type: QType.SINGLE, stem: 'What is the purpose of OSPF area 0?', options: [{ id: 'A', text: 'It is the backbone area to which all other areas must connect' }, { id: 'B', text: 'It is the IPv6-only area' }, { id: 'C', text: 'It is reserved for stub networks' }, { id: 'D', text: 'It does not exist' }], correct: ['A'], explanation: 'OSPF requires a backbone (area 0); all non-backbone areas connect through it (or via virtual links).' },
  { domain: 'IP Connectivity', type: QType.SINGLE, stem: 'Which Cisco command shows the IP routing table?', options: [{ id: 'A', text: 'show ip route' }, { id: 'B', text: 'show interfaces' }, { id: 'C', text: 'show running-config' }, { id: 'D', text: 'show vlan' }], correct: ['A'], explanation: '`show ip route` displays the routing table with codes for source protocol.' },
  { domain: 'IP Connectivity', type: QType.SINGLE, stem: 'Which protocol provides first-hop redundancy by allowing two routers to share a virtual IP gateway?', options: [{ id: 'A', text: 'HSRP / VRRP / GLBP' }, { id: 'B', text: 'OSPF' }, { id: 'C', text: 'BGP' }, { id: 'D', text: 'STP' }], correct: ['A'], explanation: 'FHRPs (HSRP Cisco, VRRP standard, GLBP load-balancing) provide redundant default gateways.' },
  { domain: 'IP Connectivity', type: QType.SINGLE, stem: 'What is the destination MAC address used in an ARP reply?', options: [{ id: 'A', text: 'The unicast MAC of the original requester' }, { id: 'B', text: 'FF:FF:FF:FF:FF:FF (broadcast)' }, { id: 'C', text: '00:00:00:00:00:00' }, { id: 'D', text: 'A multicast group' }], correct: ['A'], explanation: 'ARP REQUEST is broadcast; the REPLY is unicast back to the requester.' },
  { domain: 'IP Connectivity', type: QType.SINGLE, stem: 'Which packet field is used to detect loops in routed networks?', options: [{ id: 'A', text: 'TTL (Time-to-Live)' }, { id: 'B', text: 'Checksum' }, { id: 'C', text: 'Source IP' }, { id: 'D', text: 'Destination port' }], correct: ['A'], explanation: 'Each router decrements TTL by 1; at 0 the packet is discarded. Prevents endless loops.' },
  { domain: 'IP Services', type: QType.SINGLE, stem: 'Which protocol assigns IP configuration (IP, mask, gateway, DNS) to clients automatically?', options: [{ id: 'A', text: 'DHCP' }, { id: 'B', text: 'DNS' }, { id: 'C', text: 'ARP' }, { id: 'D', text: 'RIP' }], correct: ['A'], explanation: 'DHCP automates IP config. The DORA process: Discover, Offer, Request, Acknowledge.' },
  { domain: 'IP Services', type: QType.SINGLE, stem: 'Which feature lets internal private hosts share a single public IP for outbound traffic?', options: [{ id: 'A', text: 'NAT (PAT/Overload — Port Address Translation)' }, { id: 'B', text: 'OSPF' }, { id: 'C', text: 'STP' }, { id: 'D', text: 'BGP' }], correct: ['A'], explanation: 'PAT/NAT Overload maps many internal addresses to one public IP via differing source ports.' },
  { domain: 'IP Services', type: QType.SINGLE, stem: 'Which UDP port does DNS use by default?', options: [{ id: 'A', text: '53' }, { id: 'B', text: '67' }, { id: 'C', text: '80' }, { id: 'D', text: '443' }], correct: ['A'], explanation: 'DNS uses UDP/53 (and TCP/53 for large responses or zone transfers). DHCP is UDP/67-68. HTTP is TCP/80; HTTPS is TCP/443.' },
  { domain: 'IP Services', type: QType.SINGLE, stem: 'Which protocol synchronizes time across network devices?', options: [{ id: 'A', text: 'NTP' }, { id: 'B', text: 'SMTP' }, { id: 'C', text: 'SNMP' }, { id: 'D', text: 'FTP' }], correct: ['A'], explanation: 'NTP (UDP/123) synchronizes time. SNMP monitors devices; SMTP is email; FTP is file transfer.' },
  { domain: 'Security Fundamentals', type: QType.SINGLE, stem: 'Which Cisco command enables port security on a switch interface?', options: [{ id: 'A', text: 'switchport port-security' }, { id: 'B', text: 'switchport access vlan' }, { id: 'C', text: 'spanning-tree portfast' }, { id: 'D', text: 'channel-group 1 mode active' }], correct: ['A'], explanation: 'switchport port-security enables MAC address filtering on access ports.' },
  { domain: 'Security Fundamentals', type: QType.SINGLE, stem: 'Which authentication mechanism is most secure for VTY access on a Cisco device?', options: [{ id: 'A', text: 'AAA with RADIUS/TACACS+ + SSH only (telnet disabled)' }, { id: 'B', text: 'Telnet with local password' }, { id: 'C', text: 'Console-only access' }, { id: 'D', text: 'Anonymous SSH' }], correct: ['A'], explanation: 'AAA with central authentication + SSH (no telnet) is best practice.' },
  { domain: 'Security Fundamentals', type: QType.SINGLE, stem: 'Which command applies an access list inbound on an interface?', options: [{ id: 'A', text: 'ip access-group <number> in' }, { id: 'B', text: 'access-class' }, { id: 'C', text: 'ip route' }, { id: 'D', text: 'switchport mode trunk' }], correct: ['A'], explanation: '`ip access-group X in` applies ACL X inbound on the interface.' },
  { domain: 'Security Fundamentals', type: QType.SINGLE, stem: 'Which feature provides encryption of management traffic and is the recommended replacement for telnet?', options: [{ id: 'A', text: 'SSH (port 22)' }, { id: 'B', text: 'Telnet' }, { id: 'C', text: 'HTTP' }, { id: 'D', text: 'TFTP' }], correct: ['A'], explanation: 'SSH provides encrypted management. Telnet is plaintext and deprecated.' },
  { domain: 'Security Fundamentals', type: QType.SINGLE, stem: 'Which feature enforces 802.1X port-based authentication on a switch?', options: [{ id: 'A', text: 'dot1x port-control auto + RADIUS server' }, { id: 'B', text: 'switchport port-security' }, { id: 'C', text: 'spanning-tree portfast' }, { id: 'D', text: 'cdp enable' }], correct: ['A'], explanation: '802.1X uses EAP over LAN with a RADIUS authenticator to authenticate devices/users at port admission.' },
  { domain: 'Automation and Programmability', type: QType.SINGLE, stem: 'Which data format is used by REST APIs and is human-readable text?', options: [{ id: 'A', text: 'JSON' }, { id: 'B', text: 'Binary' }, { id: 'C', text: 'CSV' }, { id: 'D', text: 'TIFF' }], correct: ['A'], explanation: 'JSON is the dominant format for REST APIs. XML is also used; YAML for configs.' },
  { domain: 'Automation and Programmability', type: QType.SINGLE, stem: 'Which Cisco automation platform provides cross-domain orchestration with intent-based networking?', options: [{ id: 'A', text: 'Cisco DNA Center' }, { id: 'B', text: 'Cisco APIC-EM' }, { id: 'C', text: 'Cisco UCS Director' }, { id: 'D', text: 'Cisco Webex' }], correct: ['A'], explanation: 'DNA Center (now Catalyst Center) is the network controller for Cisco SD-Access intent-based networking.' },
  { domain: 'Automation and Programmability', type: QType.SINGLE, stem: 'Which protocol provides a model-driven, structured CLI for network device configuration via YANG models?', options: [{ id: 'A', text: 'NETCONF / RESTCONF (over YANG models)' }, { id: 'B', text: 'SNMP v1' }, { id: 'C', text: 'CDP' }, { id: 'D', text: 'STP' }], correct: ['A'], explanation: 'NETCONF (XML over SSH/TLS) and RESTCONF (HTTP/JSON or XML) use YANG for model-driven device config and telemetry.' },
  { domain: 'Automation and Programmability', type: QType.SINGLE, stem: 'Which configuration-management tool is agentless and uses SSH + YAML playbooks?', options: [{ id: 'A', text: 'Ansible' }, { id: 'B', text: 'Puppet' }, { id: 'C', text: 'Chef' }, { id: 'D', text: 'SaltStack (with master/minion)' }], correct: ['A'], explanation: 'Ansible is agentless and SSH-based. Puppet/Chef use agents; Salt typically does too.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'cisco-ccna-p1', offset: 0 },
  { slug: 'cisco-ccna-p2', offset: 6 },
  { slug: 'cisco-ccna-p3', offset: 12 },
  { slug: 'cisco-ccna-p4', offset: 18 },
  { slug: 'cisco-ccna-p5', offset: 24 },
  { slug: 'cisco-ccna-p6', offset: 30 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: { examId: exam.id, domain: q.domain, difficulty: 3, type: q.type, stem: q.stem, options: q.options, correct: q.correct, explanation: q.explanation, references: [REF], status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up CCNA to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
