/**
 * Top-up: DP-100 (P1, P2) to 60 questions.
 *   npx tsx scripts/seed-microsoft-dp-100-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();
const TARGET = 60;
const TAG_PREFIX = 'topup:microsoft-dp-100';
const REF = { label: 'Microsoft DP-100 exam page', url: 'https://learn.microsoft.com/en-us/credentials/certifications/exams/dp-100/' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  { domain: 'Design and prepare a machine learning solution', type: QType.SINGLE, stem: 'Which Azure ML resource provides a managed cloud workstation pre-installed with Jupyter, VS Code, and the SDK?', options: [{ id: 'A', text: 'Compute instance' }, { id: 'B', text: 'Compute cluster' }, { id: 'C', text: 'Inference cluster' }, { id: 'D', text: 'Endpoint' }], correct: ['A'], explanation: 'Compute instances are personal cloud workstations. Compute clusters are training/scoring nodes; endpoints serve models.' },
  { domain: 'Design and prepare a machine learning solution', type: QType.SINGLE, stem: 'Which Azure ML feature provides a fully isolated workspace per project with its own compute, datastores, and models?', options: [{ id: 'A', text: 'Workspace' }, { id: 'B', text: 'Resource group' }, { id: 'C', text: 'Subscription' }, { id: 'D', text: 'Region' }], correct: ['A'], explanation: 'Workspaces are the top-level Azure ML resource that contains all artifacts, RBAC, and compute.' },
  { domain: 'Design and prepare a machine learning solution', type: QType.SINGLE, stem: 'Which Azure ML data abstraction provides a versioned, named pointer to data in storage that can be reused across experiments?', options: [{ id: 'A', text: 'Data asset (datasets)' }, { id: 'B', text: 'Compute target' }, { id: 'C', text: 'Endpoint' }, { id: 'D', text: 'Job' }], correct: ['A'], explanation: 'Data assets/datasets are the versioned data abstractions referenced by jobs/training scripts.' },
  { domain: 'Design and prepare a machine learning solution', type: QType.SINGLE, stem: 'Which compute is best for distributed training of a deep-learning model across multiple GPUs?', options: [{ id: 'A', text: 'GPU compute cluster (multi-node)' }, { id: 'B', text: 'CPU compute instance' }, { id: 'C', text: 'Endpoint' }, { id: 'D', text: 'Datastore' }], correct: ['A'], explanation: 'Multi-node GPU clusters with NCCL/Horovod scale DL training. Endpoints serve models; datastores reference data.' },
  { domain: 'Design and prepare a machine learning solution', type: QType.SINGLE, stem: 'Which Azure ML feature ensures reproducibility by tracking the exact code, environment, parameters, and metrics for each run?', options: [{ id: 'A', text: 'Experiments and Jobs (with MLflow integration)' }, { id: 'B', text: 'Compute targets' }, { id: 'C', text: 'Endpoints' }, { id: 'D', text: 'Datastores' }], correct: ['A'], explanation: 'Each job tracks code snapshot, environment image, params, metrics, outputs. MLflow integrations are first-class.' },
  { domain: 'Design and prepare a machine learning solution', type: QType.SINGLE, stem: 'Which Azure ML feature provides reusable container definitions for training/inference?', options: [{ id: 'A', text: 'Environments (curated or custom)' }, { id: 'B', text: 'Pipelines' }, { id: 'C', text: 'Datasets' }, { id: 'D', text: 'Datastores' }], correct: ['A'], explanation: 'Environments encapsulate Python deps, system libs, base images, and CUDA, ensuring reproducibility.' },
  { domain: 'Explore data and train models', type: QType.SINGLE, stem: 'Which Azure ML capability automates algorithm selection, hyperparameter tuning, and feature engineering?', options: [{ id: 'A', text: 'Automated ML (AutoML)' }, { id: 'B', text: 'Designer' }, { id: 'C', text: 'Endpoints' }, { id: 'D', text: 'Compute clusters' }], correct: ['A'], explanation: 'AutoML iterates over algorithms/hyperparameters/featurization and surfaces the best run.' },
  { domain: 'Explore data and train models', type: QType.SINGLE, stem: 'Which Azure ML feature is the no-code drag-and-drop pipeline builder for training and inference?', options: [{ id: 'A', text: 'Designer' }, { id: 'B', text: 'AutoML' }, { id: 'C', text: 'Notebook' }, { id: 'D', text: 'CLI v2' }], correct: ['A'], explanation: 'Designer provides a visual canvas with prebuilt components.' },
  { domain: 'Explore data and train models', type: QType.SINGLE, stem: 'Which type of HPO algorithm intelligently selects new hyperparameter values based on previous trial results?', options: [{ id: 'A', text: 'Bayesian sampling' }, { id: 'B', text: 'Random sampling' }, { id: 'C', text: 'Grid sampling' }, { id: 'D', text: 'Linear sampling' }], correct: ['A'], explanation: 'Bayesian uses prior trials to guide future sampling. Grid is exhaustive; random is uninformed.' },
  { domain: 'Explore data and train models', type: QType.SINGLE, stem: 'Which Azure ML HPO feature stops poorly-performing trials early to save cost?', options: [{ id: 'A', text: 'Early termination policies (Bandit, Median, Truncation)' }, { id: 'B', text: 'Compute clusters' }, { id: 'C', text: 'Datasets' }, { id: 'D', text: 'Endpoints' }], correct: ['A'], explanation: 'Early termination kills weak trials based on intermediate metrics, freeing budget for promising ones.' },
  { domain: 'Explore data and train models', type: QType.SINGLE, stem: 'Which Azure ML feature tracks model lineage, metrics, and outputs across runs for the same experiment?', options: [{ id: 'A', text: 'Experiment tracking with MLflow' }, { id: 'B', text: 'Compute targets' }, { id: 'C', text: 'Datastores' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'Azure ML uses MLflow as the experiment tracking standard.' },
  { domain: 'Explore data and train models', type: QType.SINGLE, stem: 'Which Azure ML feature lets you log custom metrics from inside a training script?', options: [{ id: 'A', text: 'mlflow.log_metric() (or run.log() in legacy SDK)' }, { id: 'B', text: 'print() to stdout only' }, { id: 'C', text: 'environment variables' }, { id: 'D', text: 'compute properties' }], correct: ['A'], explanation: 'mlflow.log_metric persists scalar metrics; mlflow.log_artifact persists files; both show in the run UI.' },
  { domain: 'Explore data and train models', type: QType.SINGLE, stem: 'Which evaluation metric is preferred for binary classification with imbalanced classes when both error types matter?', options: [{ id: 'A', text: 'F1 score (or balanced accuracy)' }, { id: 'B', text: 'Plain accuracy' }, { id: 'C', text: 'RMSE' }, { id: 'D', text: 'Log loss only' }], correct: ['A'], explanation: 'F1 (harmonic mean of precision and recall) balances both error types better than accuracy on imbalanced data.' },
  { domain: 'Explore data and train models', type: QType.SINGLE, stem: 'Which Azure ML feature lets you compose multi-step pipelines (data prep → train → register) with dependencies and parallelism?', options: [{ id: 'A', text: 'Azure ML Pipelines' }, { id: 'B', text: 'Designer canvas only' }, { id: 'C', text: 'Endpoints' }, { id: 'D', text: 'Workspaces' }], correct: ['A'], explanation: 'Pipelines orchestrate ML workflows with reusable components, parameterization, and compute targeting per step.' },
  { domain: 'Explore data and train models', type: QType.SINGLE, stem: 'Which technique splits data so that each fold serves as test once, providing a robust generalization estimate?', options: [{ id: 'A', text: 'k-fold cross-validation' }, { id: 'B', text: 'Bootstrap with replacement' }, { id: 'C', text: 'Holdout' }, { id: 'D', text: 'Train-on-test' }], correct: ['A'], explanation: 'k-fold rotates the test fold across k splits and averages metrics. Holdout uses one split; bootstrap samples with replacement.' },
  { domain: 'Explore data and train models', type: QType.SINGLE, stem: 'Which transformation is most appropriate when categorical features have HIGH cardinality (e.g., 10000+ values)?', options: [{ id: 'A', text: 'Target / leave-one-out / hashing encoding' }, { id: 'B', text: 'Plain one-hot' }, { id: 'C', text: 'Standardization' }, { id: 'D', text: 'Min-max scaling' }], correct: ['A'], explanation: 'High-cardinality features explode the dimensionality with one-hot. Target/hashing encodings keep dimensionality manageable.' },
  { domain: 'Explore data and train models', type: QType.SINGLE, stem: 'Which Azure ML feature provides built-in interpretability with feature importance and SHAP-like values?', options: [{ id: 'A', text: 'Responsible AI dashboard / interpretability SDK' }, { id: 'B', text: 'Endpoints' }, { id: 'C', text: 'Compute clusters' }, { id: 'D', text: 'Datastores' }], correct: ['A'], explanation: 'The Responsible AI dashboard exposes interpretability, error analysis, fairness, and counterfactuals.' },
  { domain: 'Explore data and train models', type: QType.SINGLE, stem: 'Which Azure ML feature lets you train a model on data that cannot leave a particular region/tenant?', options: [{ id: 'A', text: 'Workspace + compute provisioned in the required region; data assets pointing to compliant storage' }, { id: 'B', text: 'Use any region' }, { id: 'C', text: 'Public blob with SAS' }, { id: 'D', text: 'Disable encryption' }], correct: ['A'], explanation: 'Region-pinning the workspace, compute, and data ensures data residency and compliance.' },
  { domain: 'Prepare a model for deployment', type: QType.SINGLE, stem: 'Which Azure ML feature lets you register a model for governed deployment with version, tags, and properties?', options: [{ id: 'A', text: 'Model registry' }, { id: 'B', text: 'Compute targets' }, { id: 'C', text: 'Datastores' }, { id: 'D', text: 'Pipelines' }], correct: ['A'], explanation: 'The model registry stores versions, tags, and metadata for reuse and deployment.' },
  { domain: 'Prepare a model for deployment', type: QType.SINGLE, stem: 'Which Azure ML deployment target provides REAL-TIME, low-latency HTTP endpoints for synchronous predictions?', options: [{ id: 'A', text: 'Online endpoint (Managed online endpoint)' }, { id: 'B', text: 'Batch endpoint' }, { id: 'C', text: 'Compute cluster only' }, { id: 'D', text: 'Datastore' }], correct: ['A'], explanation: 'Online endpoints provide sub-second HTTPS inference with autoscale and traffic shifting between deployments.' },
  { domain: 'Prepare a model for deployment', type: QType.SINGLE, stem: 'Which Azure ML deployment target processes large input files asynchronously, queuing jobs for high-throughput offline scoring?', options: [{ id: 'A', text: 'Batch endpoint' }, { id: 'B', text: 'Online endpoint' }, { id: 'C', text: 'Compute instance' }, { id: 'D', text: 'Datastore' }], correct: ['A'], explanation: 'Batch endpoints score large datasets via parallel jobs on compute clusters.' },
  { domain: 'Prepare a model for deployment', type: QType.SINGLE, stem: 'Which feature lets you split traffic between multiple model versions on the SAME online endpoint to enable canary releases?', options: [{ id: 'A', text: 'Deployments under an endpoint with traffic allocation' }, { id: 'B', text: 'Multiple workspaces' }, { id: 'C', text: 'Different regions' }, { id: 'D', text: 'NSG rules' }], correct: ['A'], explanation: 'An endpoint can host multiple deployments and route traffic by percentage (e.g., 90/10 split for canary).' },
  { domain: 'Prepare a model for deployment', type: QType.SINGLE, stem: 'Which artifact does an inference deployment require in addition to the trained model?', options: [{ id: 'A', text: 'A scoring script (init() and run() functions) and an environment' }, { id: 'B', text: 'A new Workspace' }, { id: 'C', text: 'A separate region' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'The scoring script defines how requests map to predictions. The environment provides the runtime libraries.' },
  { domain: 'Prepare a model for deployment', type: QType.SINGLE, stem: 'Which serverless compute option in Azure ML lets you deploy small models with autoscale-to-zero and per-second billing?', options: [{ id: 'A', text: 'Managed online endpoint with consumption autoscale' }, { id: 'B', text: 'Batch endpoint only' }, { id: 'C', text: 'Compute cluster keep-alive' }, { id: 'D', text: 'Compute instance' }], correct: ['A'], explanation: 'Managed online endpoints support autoscale rules and traffic-based scaling for cost-efficient hosting.' },
  { domain: 'Prepare a model for deployment', type: QType.SINGLE, stem: 'Which deployment best PROTECTS production users when rolling out a new model?', options: [{ id: 'A', text: 'Blue-green or canary deployment with gradual traffic shift and automatic rollback on metrics regression' }, { id: 'B', text: 'Replace 100% at once' }, { id: 'C', text: 'Disable monitoring' }, { id: 'D', text: 'Skip testing' }], correct: ['A'], explanation: 'Gradual traffic shift + automated rollback minimizes risk to users.' },
  { domain: 'Deploy and retrain a model', type: QType.SINGLE, stem: 'Which Azure ML feature continuously monitors data and prediction drift in production?', options: [{ id: 'A', text: 'Model monitoring (data drift / prediction drift signals)' }, { id: 'B', text: 'Compute targets' }, { id: 'C', text: 'Datastores' }, { id: 'D', text: 'Endpoints alone' }], correct: ['A'], explanation: 'Azure ML Model Monitoring detects drift and quality regressions and emits alerts.' },
  { domain: 'Deploy and retrain a model', type: QType.SINGLE, stem: 'Which strategy automates retraining when monitoring detects significant drift?', options: [{ id: 'A', text: 'Drift-triggered retraining pipeline (Monitor → trigger → ML Pipeline → register → redeploy)' }, { id: 'B', text: 'Manual retraining once a year' }, { id: 'C', text: 'Disable monitoring after deploy' }, { id: 'D', text: 'Skip retraining' }], correct: ['A'], explanation: 'Drift-triggered retraining keeps the model fresh with minimal cost and human effort.' },
  { domain: 'Deploy and retrain a model', type: QType.SINGLE, stem: 'Which Azure feature centralizes ML lifecycle audit logs for governance?', options: [{ id: 'A', text: 'Activity Log + Diagnostic settings sending to Log Analytics' }, { id: 'B', text: 'Compute clusters' }, { id: 'C', text: 'Datastores' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'Activity Logs and diagnostic settings send control-plane audit events to Log Analytics / Storage / Event Hubs.' },
  { domain: 'Deploy and retrain a model', type: QType.SINGLE, stem: 'Which is a good practice for safe model retraining?', options: [{ id: 'A', text: 'Maintain a holdout set of recent labeled data, evaluate the candidate against the production model, and gate promotion on improvement' }, { id: 'B', text: 'Always promote the new model' }, { id: 'C', text: 'Skip evaluation' }, { id: 'D', text: 'Promote to 100% traffic immediately' }], correct: ['A'], explanation: 'Champion-challenger evaluation with a recent holdout prevents regressions.' },
  { domain: 'Deploy and retrain a model', type: QType.SINGLE, stem: 'Which Azure ML CLI/SDK feature reproduces a job in a different workspace using configuration files?', options: [{ id: 'A', text: 'YAML job definitions with az ml job create' }, { id: 'B', text: 'Manual UI clicks only' }, { id: 'C', text: 'Datastore copy' }, { id: 'D', text: 'NSG settings' }], correct: ['A'], explanation: 'YAML-based v2 CLI defines jobs/components/endpoints in code, enabling DevOps reproducibility.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'microsoft-dp-100-p1', offset: 0 },
  { slug: 'microsoft-dp-100-p2', offset: 15 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: { examId: exam.id, domain: q.domain, difficulty: 3, type: q.type, stem: q.stem, options: q.options, correct: q.correct, explanation: q.explanation, references: [REF], status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up DP-100 to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
