/**
 * Top-up: SC-200 (P1-P5) to 60 questions.
 *   npx tsx scripts/seed-microsoft-sc-200-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();
const TARGET = 60;
const TAG_PREFIX = 'topup:microsoft-sc-200';
const REF = { label: 'Microsoft SC-200 exam page', url: 'https://learn.microsoft.com/en-us/credentials/certifications/exams/sc-200/' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  { domain: 'Mitigate threats using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender XDR component correlates alerts across endpoints, identities, email, and cloud apps into a single incident?', options: [{ id: 'A', text: 'Microsoft Defender XDR (Incidents)' }, { id: 'B', text: 'Sentinel' }, { id: 'C', text: 'Defender for Cloud' }, { id: 'D', text: 'Compliance Manager' }], correct: ['A'], explanation: 'Defender XDR groups related alerts from MDE/MDI/MDO/MCAS into incidents to reduce SOC fatigue.' },
  { domain: 'Mitigate threats using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender for Endpoint feature lets responders run scripts and gather forensic data on a managed device?', options: [{ id: 'A', text: 'Live response' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'Compliance policy' }], correct: ['A'], explanation: 'Live response provides a remote PowerShell-like console for forensic actions on enrolled endpoints.' },
  { domain: 'Mitigate threats using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender for Endpoint capability isolates a compromised host from the network during incident response?', options: [{ id: 'A', text: 'Network isolation (Isolate machine action)' }, { id: 'B', text: 'NSG flow logs' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'Group Policy' }], correct: ['A'], explanation: 'MDE supports network isolation while allowing the security team to remediate via Live response.' },
  { domain: 'Mitigate threats using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which feature in Defender for Office 365 lets users report suspicious emails for analyst triage?', options: [{ id: 'A', text: 'User-reported messages (Submissions)' }, { id: 'B', text: 'Conditional Access' }, { id: 'C', text: 'PIM' }, { id: 'D', text: 'BitLocker' }], correct: ['A'], explanation: 'Submissions in Defender for Office 365 collect user reports and feed them to the security team and to ML training.' },
  { domain: 'Mitigate threats using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender feature scores a tenant\'s overall security posture and recommends improvements?', options: [{ id: 'A', text: 'Microsoft Secure Score' }, { id: 'B', text: 'Compliance Manager' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'PIM' }], correct: ['A'], explanation: 'Secure Score in Defender XDR measures security posture and provides ranked recommendations.' },
  { domain: 'Mitigate threats using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender for Endpoint feature catalogs vulnerabilities on managed devices?', options: [{ id: 'A', text: 'Defender Vulnerability Management (TVM)' }, { id: 'B', text: 'Conditional Access' }, { id: 'C', text: 'Compliance Manager' }, { id: 'D', text: 'PIM' }], correct: ['A'], explanation: 'TVM continuously discovers vulnerabilities, prioritizes them by exploitability, and links to remediation.' },
  { domain: 'Mitigate threats using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which feature blocks dangerous behaviors on Windows endpoints (e.g., Office spawning child processes)?', options: [{ id: 'A', text: 'Attack Surface Reduction (ASR) rules' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Compliance Manager' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'ASR rules block specific dangerous behaviors via policy.' },
  { domain: 'Mitigate threats using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender for Endpoint feature controls executable allow/block lists at the kernel level?', options: [{ id: 'A', text: 'Windows Defender Application Control (WDAC) / AppLocker' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'Defender Antivirus' }], correct: ['A'], explanation: 'WDAC/AppLocker restrict which apps and scripts can run on managed devices.' },
  { domain: 'Mitigate threats using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender for Identity feature alerts on Pass-the-Hash, Golden Ticket, and other AD attacks?', options: [{ id: 'A', text: 'Defender for Identity sensors on domain controllers (Identity threat detections)' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'PIM' }], correct: ['A'], explanation: 'MDI sensors install on DCs and detect suspicious activities like Pass-the-Hash, Golden Ticket, DCSync.' },
  { domain: 'Mitigate threats using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender for Cloud Apps feature shows shadow IT — unsanctioned SaaS in use?', options: [{ id: 'A', text: 'Cloud Discovery (using firewall/SWG logs or Defender for Endpoint integration)' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'PIM' }, { id: 'D', text: 'Compliance Manager' }], correct: ['A'], explanation: 'Cloud Discovery analyzes traffic logs to surface shadow IT SaaS usage and risk scores.' },
  { domain: 'Mitigate threats using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender XDR feature lets analysts run KQL queries to hunt threats proactively?', options: [{ id: 'A', text: 'Advanced Hunting' }, { id: 'B', text: 'Compliance Manager' }, { id: 'C', text: 'PIM' }, { id: 'D', text: 'BitLocker' }], correct: ['A'], explanation: 'Advanced Hunting exposes raw telemetry tables across MDE/MDI/MDO/MCAS for KQL-based threat hunting.' },
  { domain: 'Mitigate threats using Microsoft Defender XDR', type: QType.SINGLE, stem: 'Which Defender XDR feature triggers actions automatically based on rules (e.g., disable user, isolate device)?', options: [{ id: 'A', text: 'Custom detection rules + Automated investigation and response (AIR)' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Compliance Manager' }, { id: 'D', text: 'PIM' }], correct: ['A'], explanation: 'Custom detections can chain into AIR playbooks for automated remediation across XDR.' },
  { domain: 'Mitigate threats using Microsoft Defender for Cloud', type: QType.SINGLE, stem: 'Which Defender for Cloud plan protects Linux/Windows VMs and Arc machines from threats?', options: [{ id: 'A', text: 'Defender for Servers' }, { id: 'B', text: 'Defender for SQL' }, { id: 'C', text: 'Defender for Storage' }, { id: 'D', text: 'Defender for Containers' }], correct: ['A'], explanation: 'Defender for Servers extends MDE to Azure/Arc machines with vulnerability assessment, EDR, and adaptive controls.' },
  { domain: 'Mitigate threats using Microsoft Defender for Cloud', type: QType.SINGLE, stem: 'Which Defender for Cloud plan protects against malware uploads to Azure Storage?', options: [{ id: 'A', text: 'Defender for Storage' }, { id: 'B', text: 'Defender for SQL' }, { id: 'C', text: 'Defender for Servers' }, { id: 'D', text: 'Defender for Containers' }], correct: ['A'], explanation: 'Defender for Storage scans uploaded blobs for malware and detects suspicious access patterns.' },
  { domain: 'Mitigate threats using Microsoft Defender for Cloud', type: QType.SINGLE, stem: 'Which Defender for Cloud capability aggregates compliance posture across multiple clouds (AWS, GCP, Azure)?', options: [{ id: 'A', text: 'Multi-cloud connectors with regulatory compliance dashboard' }, { id: 'B', text: 'NSG flow logs' }, { id: 'C', text: 'Compliance Manager' }, { id: 'D', text: 'PIM' }], correct: ['A'], explanation: 'Defender for Cloud connectors onboard AWS/GCP and assess compliance against benchmarks.' },
  { domain: 'Mitigate threats using Microsoft Defender for Cloud', type: QType.SINGLE, stem: 'Which Defender for Cloud feature provides JIT VM access by opening RDP/SSH only when needed?', options: [{ id: 'A', text: 'Just-in-Time VM access' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'PIM' }], correct: ['A'], explanation: 'JIT VM access uses NSG rules to open management ports for a configured window after request and approval.' },
  { domain: 'Mitigate threats using Microsoft Defender for Cloud', type: QType.SINGLE, stem: 'Which Defender for Cloud capability whitelists known-good app behaviors on VMs to detect anomalies?', options: [{ id: 'A', text: 'Adaptive Application Controls' }, { id: 'B', text: 'Compliance Manager' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'BitLocker' }], correct: ['A'], explanation: 'Adaptive App Controls learn typical application behaviors and alert on deviations.' },
  { domain: 'Mitigate threats using Microsoft Defender for Cloud', type: QType.SINGLE, stem: 'Which Defender for Cloud capability enforces secure configuration on Azure resources?', options: [{ id: 'A', text: 'Recommendations + Azure Policy assignments (Microsoft Cloud Security Benchmark)' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'PIM' }, { id: 'D', text: 'Conditional Access' }], correct: ['A'], explanation: 'Defender for Cloud recommendations map to Azure Policy assignments enforcing the Microsoft Cloud Security Benchmark.' },
  { domain: 'Mitigate threats using Microsoft Defender for Cloud', type: QType.SINGLE, stem: 'Which Defender for Cloud plan protects Azure App Service?', options: [{ id: 'A', text: 'Defender for App Service' }, { id: 'B', text: 'Defender for Storage' }, { id: 'C', text: 'Defender for SQL' }, { id: 'D', text: 'Defender for Endpoint' }], correct: ['A'], explanation: 'Defender for App Service detects suspicious activity, vulnerable runtimes, and exposed admin endpoints.' },
  { domain: 'Mitigate threats using Microsoft Defender for Cloud', type: QType.SINGLE, stem: 'Which feature uses agentless scanning to assess VM software inventory without installing agents?', options: [{ id: 'A', text: 'Agentless scanning for machines' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'Compliance Manager' }], correct: ['A'], explanation: 'Defender for Servers offers agentless scanning that snapshots disks to discover packages and vulnerabilities without on-VM agents.' },
  { domain: 'Mitigate threats using Microsoft Sentinel', type: QType.SINGLE, stem: 'What is Microsoft Sentinel?', options: [{ id: 'A', text: 'A cloud-native SIEM/SOAR built on top of Log Analytics' }, { id: 'B', text: 'A backup service' }, { id: 'C', text: 'A network firewall' }, { id: 'D', text: 'An EDR product' }], correct: ['A'], explanation: 'Sentinel adds analytics rules, hunting queries, workbooks, and SOAR playbooks on top of Log Analytics.' },
  { domain: 'Mitigate threats using Microsoft Sentinel', type: QType.SINGLE, stem: 'Which Sentinel feature lets you run KQL hunting queries proactively to find threats?', options: [{ id: 'A', text: 'Hunting (with bookmarks and notebooks)' }, { id: 'B', text: 'Compliance Manager' }, { id: 'C', text: 'BitLocker' }, { id: 'D', text: 'PIM' }], correct: ['A'], explanation: 'Hunting offers KQL-based queries, bookmarks, and Jupyter notebook integration.' },
  { domain: 'Mitigate threats using Microsoft Sentinel', type: QType.SINGLE, stem: 'Which Sentinel feature automates response (e.g., disable user, post to Teams) when an alert fires?', options: [{ id: 'A', text: 'Playbooks (Logic Apps integration)' }, { id: 'B', text: 'Workbooks' }, { id: 'C', text: 'Hunting queries' }, { id: 'D', text: 'Conditional Access' }], correct: ['A'], explanation: 'Playbooks are Azure Logic Apps that automate response. Workbooks are dashboards; hunting queries are proactive searches.' },
  { domain: 'Mitigate threats using Microsoft Sentinel', type: QType.SINGLE, stem: 'Which Sentinel feature creates analytics rules that detect suspicious activity using KQL?', options: [{ id: 'A', text: 'Scheduled / Microsoft Security / NRT analytics rules' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'PIM' }], correct: ['A'], explanation: 'Sentinel supports Scheduled (cron KQL), Microsoft Security (alert forwarding), Fusion (cross-data-source ML), and NRT rules.' },
  { domain: 'Mitigate threats using Microsoft Sentinel', type: QType.SINGLE, stem: 'Which Sentinel data structure represents an evidence collection during hunting?', options: [{ id: 'A', text: 'Bookmarks' }, { id: 'B', text: 'Workbooks' }, { id: 'C', text: 'Playbooks' }, { id: 'D', text: 'Workspaces' }], correct: ['A'], explanation: 'Bookmarks save query results during hunting and can be added to incidents.' },
  { domain: 'Mitigate threats using Microsoft Sentinel', type: QType.SINGLE, stem: 'Which Sentinel feature ingests data from external sources (Microsoft, AWS, Linux, etc.)?', options: [{ id: 'A', text: 'Data connectors (codeless or via Logic Apps / agents)' }, { id: 'B', text: 'Conditional Access' }, { id: 'C', text: 'BitLocker' }, { id: 'D', text: 'PIM' }], correct: ['A'], explanation: 'Sentinel offers 100+ data connectors for Microsoft and third-party sources.' },
  { domain: 'Mitigate threats using Microsoft Sentinel', type: QType.SINGLE, stem: 'Which Sentinel feature visualizes data from Log Analytics with custom dashboards?', options: [{ id: 'A', text: 'Workbooks' }, { id: 'B', text: 'Hunting' }, { id: 'C', text: 'Playbooks' }, { id: 'D', text: 'Bookmarks' }], correct: ['A'], explanation: 'Workbooks are interactive Azure Monitor dashboards used to visualize SOC analytics.' },
  { domain: 'Mitigate threats using Microsoft Sentinel', type: QType.SINGLE, stem: 'Which Sentinel feature stores curated lists (e.g., known IPs, executive accounts) used in detections?', options: [{ id: 'A', text: 'Watchlists' }, { id: 'B', text: 'Workbooks' }, { id: 'C', text: 'Playbooks' }, { id: 'D', text: 'Conditional Access' }], correct: ['A'], explanation: 'Watchlists provide a controlled lookup table referenced in KQL queries.' },
  { domain: 'Mitigate threats using Microsoft Sentinel', type: QType.SINGLE, stem: 'Which Sentinel feature ingests threat intelligence indicators from feeds for use in detections?', options: [{ id: 'A', text: 'Threat Intelligence (STIX/TAXII import)' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'PIM' }], correct: ['A'], explanation: 'Sentinel ingests TI from Microsoft feeds, partners, or custom STIX/TAXII; indicators are matched to telemetry.' },
  { domain: 'Mitigate threats using Microsoft Sentinel', type: QType.SINGLE, stem: 'Which Sentinel cross-data-source ML feature finds multi-stage attacks correlating different signals?', options: [{ id: 'A', text: 'Fusion analytics' }, { id: 'B', text: 'Workbooks' }, { id: 'C', text: 'Hunting' }, { id: 'D', text: 'BitLocker' }], correct: ['A'], explanation: 'Fusion uses ML to detect multi-stage attacks across products and emit high-fidelity incidents.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'microsoft-sc-200-p1', offset: 0 },
  { slug: 'microsoft-sc-200-p2', offset: 6 },
  { slug: 'microsoft-sc-200-p3', offset: 12 },
  { slug: 'microsoft-sc-200-p4', offset: 18 },
  { slug: 'microsoft-sc-200-p5', offset: 24 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: { examId: exam.id, domain: q.domain, difficulty: 3, type: q.type, stem: q.stem, options: q.options, correct: q.correct, explanation: q.explanation, references: [REF], status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up SC-200 to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
