/**
 * Top-up: AZ-500 P1 to 60 questions.
 *   npx tsx scripts/seed-microsoft-az-500-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();
const TARGET = 60;
const TAG = 'topup:microsoft-az-500-p1';
const REF = { label: 'Microsoft AZ-500 exam page', url: 'https://learn.microsoft.com/en-us/credentials/certifications/exams/az-500/' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  // Identity & Access
  { domain: 'Manage identity and access', type: QType.SINGLE, stem: 'Which Microsoft Entra ID feature provides risk-based conditional access using sign-in and user-risk signals?', options: [{ id: 'A', text: 'Microsoft Entra ID Protection' }, { id: 'B', text: 'Azure Bastion' }, { id: 'C', text: 'Azure Policy' }, { id: 'D', text: 'Azure Firewall' }], correct: ['A'], explanation: 'Entra ID Protection produces user/sign-in risk signals consumable by Conditional Access policies (e.g., require MFA on high risk).' },
  { domain: 'Manage identity and access', type: QType.SINGLE, stem: 'Which feature enforces JIT, time-bounded admin access with approval workflows?', options: [{ id: 'A', text: 'Privileged Identity Management (PIM)' }, { id: 'B', text: 'Azure Arc' }, { id: 'C', text: 'Azure Lighthouse' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'PIM activates eligible roles for limited windows with optional approval.' },
  { domain: 'Manage identity and access', type: QType.SINGLE, stem: 'Which feature lets you classify and tag PII in user attributes and apply access policies based on tags?', options: [{ id: 'A', text: 'Microsoft Purview Information Protection / Entra Custom Security Attributes' }, { id: 'B', text: 'Azure Bastion' }, { id: 'C', text: 'Defender for Endpoint' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'Purview classifies/labels data; Custom Security Attributes tag identities for ABAC-style policy evaluation.' },
  { domain: 'Manage identity and access', type: QType.SINGLE, stem: 'Which mechanism lets Azure VMs/services authenticate to Azure resources WITHOUT storing secrets?', options: [{ id: 'A', text: 'Managed identities (system-assigned or user-assigned)' }, { id: 'B', text: 'Service principals with passwords' }, { id: 'C', text: 'Storage account keys' }, { id: 'D', text: 'NTLM' }], correct: ['A'], explanation: 'Managed identities provision identities for Azure services automatically; the platform handles tokens.' },
  { domain: 'Manage identity and access', type: QType.SINGLE, stem: 'Which Microsoft Entra ID licensing tier is required for Conditional Access?', options: [{ id: 'A', text: 'P1 or higher' }, { id: 'B', text: 'Free' }, { id: 'C', text: 'Office 365 E1' }, { id: 'D', text: 'External Identities only' }], correct: ['A'], explanation: 'Conditional Access requires Entra ID P1 or higher.' },
  { domain: 'Manage identity and access', type: QType.SINGLE, stem: 'Which feature lets administrators configure self-service password reset for cloud users?', options: [{ id: 'A', text: 'Self-Service Password Reset (SSPR)' }, { id: 'B', text: 'PIM' }, { id: 'C', text: 'Conditional Access' }, { id: 'D', text: 'Defender for Identity' }], correct: ['A'], explanation: 'SSPR allows users to reset their own passwords with verified methods (phone, email, MFA app).' },
  { domain: 'Manage identity and access', type: QType.SINGLE, stem: 'Which Conditional Access control would you use to require a compliant or hybrid-joined device for accessing apps?', options: [{ id: 'A', text: 'Grant control: Require device to be marked as compliant / Require hybrid Azure AD joined' }, { id: 'B', text: 'Block legacy auth' }, { id: 'C', text: 'Custom RBAC role' }, { id: 'D', text: 'Network watcher' }], correct: ['A'], explanation: 'Conditional Access grant controls include compliant device, hybrid join, MFA, and approved client app.' },
  { domain: 'Manage identity and access', type: QType.SINGLE, stem: 'Which Entra ID feature helps protect against phishing by requiring number-matching during MFA approvals?', options: [{ id: 'A', text: 'Authenticator app number matching' }, { id: 'B', text: 'Password expiration' }, { id: 'C', text: 'Anonymous IP blocks' }, { id: 'D', text: 'Smart lockout' }], correct: ['A'], explanation: 'Number matching forces the user to enter the displayed number in their app, defeating push-bombing/MFA fatigue.' },

  // Secure networking
  { domain: 'Secure networking', type: QType.SINGLE, stem: 'Which Azure service is a managed, stateful firewall with threat intelligence and L4-7 inspection?', options: [{ id: 'A', text: 'Azure Firewall' }, { id: 'B', text: 'NSG' }, { id: 'C', text: 'WAF on Application Gateway' }, { id: 'D', text: 'Azure Bastion' }], correct: ['A'], explanation: 'Azure Firewall is fully managed PaaS firewall (Standard/Premium tiers). NSG is L3/4 ACL; WAF is L7 web filtering; Bastion is jump host.' },
  { domain: 'Secure networking', type: QType.SINGLE, stem: 'Which Azure service provides L7 web app firewalling against OWASP threats in front of web apps?', options: [{ id: 'A', text: 'Azure Web Application Firewall (WAF) on App Gateway / Front Door' }, { id: 'B', text: 'NSG' }, { id: 'C', text: 'Azure DDoS Protection' }, { id: 'D', text: 'Azure Firewall basic tier' }], correct: ['A'], explanation: 'WAF (on App Gateway or Front Door) blocks SQLi, XSS, and other web attacks based on OWASP CRS.' },
  { domain: 'Secure networking', type: QType.SINGLE, stem: 'Which Azure feature provides per-resource DDoS protection with adaptive tuning and SLA-backed mitigation?', options: [{ id: 'A', text: 'Azure DDoS Protection (Standard/Premium)' }, { id: 'B', text: 'NSG' }, { id: 'C', text: 'Azure Firewall' }, { id: 'D', text: 'Bastion' }], correct: ['A'], explanation: 'Standard DDoS adds per-VNet adaptive tuning, mitigation reports, and rapid response. Basic is included in the platform.' },
  { domain: 'Secure networking', type: QType.SINGLE, stem: 'Which feature lets you connect a PaaS service privately into your VNet using a private IP?', options: [{ id: 'A', text: 'Private Endpoint (Private Link)' }, { id: 'B', text: 'Service Endpoint' }, { id: 'C', text: 'Site-to-Site VPN' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'Private Endpoints assign private IPs to PaaS services in your VNet. Service Endpoints route over the Microsoft backbone but service still has public IP.' },
  { domain: 'Secure networking', type: QType.SINGLE, stem: 'Which Azure feature lets you route ALL outbound traffic through a single firewall using forced tunneling and UDRs?', options: [{ id: 'A', text: 'User-Defined Routes (UDRs) on subnet route tables, pointing to Azure Firewall as next-hop' }, { id: 'B', text: 'NSG' }, { id: 'C', text: 'DNS' }, { id: 'D', text: 'Bastion' }], correct: ['A'], explanation: 'UDRs override default routes and can force all outbound traffic to a hub firewall (egress filtering).' },
  { domain: 'Secure networking', type: QType.SINGLE, stem: 'Which Azure service provides RDP/SSH access to VMs without exposing public IPs?', options: [{ id: 'A', text: 'Azure Bastion' }, { id: 'B', text: 'Azure Firewall' }, { id: 'C', text: 'Front Door' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'Bastion is a managed jump host accessed via Azure Portal over TLS, eliminating per-VM public IPs.' },
  { domain: 'Secure networking', type: QType.SINGLE, stem: 'Which feature prevents an Azure Storage account from being reached via the public internet?', options: [{ id: 'A', text: 'Disable public network access on the storage account; use Private Endpoints' }, { id: 'B', text: 'Set the storage to Cool tier' }, { id: 'C', text: 'Enable soft-delete' }, { id: 'D', text: 'Use a different storage SKU' }], correct: ['A'], explanation: 'Disabling public access + Private Endpoints constrains the data plane to the VNet only.' },

  // Secure compute, storage, databases
  { domain: 'Secure compute, storage, and databases', type: QType.SINGLE, stem: 'Which service provides centralized vulnerability management and security posture for Azure resources?', options: [{ id: 'A', text: 'Microsoft Defender for Cloud' }, { id: 'B', text: 'Azure Monitor' }, { id: 'C', text: 'Azure Backup' }, { id: 'D', text: 'NSG flow logs only' }], correct: ['A'], explanation: 'Defender for Cloud provides Cloud Security Posture Management (CSPM) and workload protection (CWPP) plans.' },
  { domain: 'Secure compute, storage, and databases', type: QType.SINGLE, stem: 'Which Defender for Cloud plan protects SQL databases (Azure SQL, MI, on-prem SQL on machines) against threats?', options: [{ id: 'A', text: 'Defender for SQL' }, { id: 'B', text: 'Defender for Storage' }, { id: 'C', text: 'Defender for Containers' }, { id: 'D', text: 'Defender for App Service' }], correct: ['A'], explanation: 'Defender for SQL detects suspicious queries, vulnerabilities, and surfaces recommendations.' },
  { domain: 'Secure compute, storage, and databases', type: QType.SINGLE, stem: 'Which Azure Storage feature encrypts blobs with KEYS YOU control via Azure Key Vault?', options: [{ id: 'A', text: 'Customer-managed keys (CMK)' }, { id: 'B', text: 'Microsoft-managed keys (default)' }, { id: 'C', text: 'No encryption' }, { id: 'D', text: 'Sas tokens' }], correct: ['A'], explanation: 'CMK lets you control rotation, lifecycle, and revocation of the encryption key in Key Vault.' },
  { domain: 'Secure compute, storage, and databases', type: QType.SINGLE, stem: 'Which Azure SQL feature encrypts SPECIFIC columns so DBAs cannot see plaintext?', options: [{ id: 'A', text: 'Always Encrypted' }, { id: 'B', text: 'TDE' }, { id: 'C', text: 'Row-Level Security' }, { id: 'D', text: 'Dynamic Data Masking' }], correct: ['A'], explanation: 'Always Encrypted protects sensitive columns from privileged users by performing crypto in the client driver.' },
  { domain: 'Secure compute, storage, and databases', type: QType.SINGLE, stem: 'Which Azure feature provides a managed HSM-backed key store for cryptographic keys, secrets, and certificates?', options: [{ id: 'A', text: 'Azure Key Vault' }, { id: 'B', text: 'Azure Storage' }, { id: 'C', text: 'Azure Backup' }, { id: 'D', text: 'Azure App Configuration' }], correct: ['A'], explanation: 'Key Vault stores keys/secrets/certs with RBAC, soft-delete, purge protection, and HSM-backing options.' },
  { domain: 'Secure compute, storage, and databases', type: QType.SINGLE, stem: 'Which Azure VM feature encrypts the OS and data disks at the platform level using DiskEncryption + KeyVault?', options: [{ id: 'A', text: 'Azure Disk Encryption (BitLocker / DM-Crypt + Key Vault)' }, { id: 'B', text: 'Server-Side Encryption only' }, { id: 'C', text: 'NSG flow logs' }, { id: 'D', text: 'Resource locks' }], correct: ['A'], explanation: 'Azure Disk Encryption uses BitLocker (Windows) or dm-crypt (Linux) with keys in Key Vault for in-OS volume encryption (in addition to platform-level SSE).' },

  // Manage security operations
  { domain: 'Manage security operations', type: QType.SINGLE, stem: 'Which Azure service is a cloud-native SIEM/SOAR that ingests logs from Azure, Microsoft 365, and third parties?', options: [{ id: 'A', text: 'Microsoft Sentinel' }, { id: 'B', text: 'Defender for Endpoint' }, { id: 'C', text: 'Azure Monitor Logs only' }, { id: 'D', text: 'Network Watcher' }], correct: ['A'], explanation: 'Sentinel adds analytics rules, hunting queries, workbooks, and SOAR playbooks on top of Log Analytics.' },
  { domain: 'Manage security operations', type: QType.SINGLE, stem: 'Which Sentinel feature automates response actions (e.g., disable user, isolate VM) based on alerts?', options: [{ id: 'A', text: 'Playbooks (Logic Apps integration)' }, { id: 'B', text: 'Hunting queries' }, { id: 'C', text: 'Watchlists' }, { id: 'D', text: 'Threat intelligence' }], correct: ['A'], explanation: 'Playbooks are Logic Apps that automate response. Hunting queries are proactive searches; watchlists curate lookups; TI is indicators.' },
  { domain: 'Manage security operations', type: QType.SINGLE, stem: 'Which feature in Defender for Cloud aggregates security posture across multi-cloud (AWS, GCP, on-prem) workloads?', options: [{ id: 'A', text: 'Multi-cloud connectors' }, { id: 'B', text: 'NSG' }, { id: 'C', text: 'Bastion' }, { id: 'D', text: 'Resource locks' }], correct: ['A'], explanation: 'Defender for Cloud connectors onboard AWS/GCP accounts and surface unified recommendations and alerts.' },
  { domain: 'Manage security operations', type: QType.SINGLE, stem: 'Which Defender for Cloud capability assesses compliance against benchmarks like CIS, PCI DSS, NIST, ISO 27001?', options: [{ id: 'A', text: 'Regulatory Compliance dashboard' }, { id: 'B', text: 'Just-in-Time VM access' }, { id: 'C', text: 'Workload Protection only' }, { id: 'D', text: 'Resource Health' }], correct: ['A'], explanation: 'Regulatory Compliance maps controls in standards to Defender assessments and reports posture.' },
  { domain: 'Manage security operations', type: QType.SINGLE, stem: 'Which Azure feature provides immutable storage for audit logs (cannot be deleted/modified for a retention period)?', options: [{ id: 'A', text: 'Immutable blob storage with time-based retention policies' }, { id: 'B', text: 'Hot tier' }, { id: 'C', text: 'Cool tier' }, { id: 'D', text: 'Premium SSD' }], correct: ['A'], explanation: 'Immutable storage policies (legal hold or time-based) make blobs WORM-compliant — they cannot be deleted/modified during retention.' },
  { domain: 'Manage security operations', type: QType.SINGLE, stem: 'Which feature in Microsoft Sentinel uses MITRE ATT&CK mappings and analytic rules to detect threats?', options: [{ id: 'A', text: 'Analytics rules' }, { id: 'B', text: 'Watchlists' }, { id: 'C', text: 'Workbooks' }, { id: 'D', text: 'Notebooks' }], correct: ['A'], explanation: 'Analytics rules use scheduled or near-real-time queries to detect threats; templates are mapped to MITRE ATT&CK tactics/techniques.' }
];

const SLUG = 'microsoft-az-500-p1';
async function main() {
  const exam = await db.exam.findUnique({ where: { slug: SLUG } });
  if (!exam) throw new Error(`Exam ${SLUG} not found`);
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`${SLUG}: already at ${current}`); return; }
  const need = TARGET - current;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: TAG } });
  if (already >= need) { console.log(`${SLUG}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[i % SUPPLEMENTALS.length];
    await db.question.create({
      data: { examId: exam.id, domain: q.domain, difficulty: 3, type: q.type, stem: q.stem, options: q.options, correct: q.correct, explanation: q.explanation, references: [REF], status: QStatus.PUBLISHED, generatedBy: TAG, isTeaser: false }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`✓ ${SLUG}: +${need} → ${newTotal} total`);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
