/**
 * Top-up: MD-102 (P1-P4) to 60 questions.
 *   npx tsx scripts/seed-microsoft-md-102-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';
const db = new PrismaClient();
const TARGET = 60;
const TAG_PREFIX = 'topup:microsoft-md-102';
const REF = { label: 'Microsoft MD-102 exam page', url: 'https://learn.microsoft.com/en-us/credentials/certifications/exams/md-102/' };

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  { domain: 'Deploy Windows client', type: QType.SINGLE, stem: 'Which Windows deployment method enrolls devices automatically into Intune from the OOBE using Microsoft Entra join?', options: [{ id: 'A', text: 'Windows Autopilot' }, { id: 'B', text: 'WDS PXE boot' }, { id: 'C', text: 'MDT task sequence' }, { id: 'D', text: 'In-place upgrade' }], correct: ['A'], explanation: 'Autopilot configures preinstalled OEM devices via cloud profiles, joining them to Entra and enrolling in Intune at first sign-in.' },
  { domain: 'Deploy Windows client', type: QType.SINGLE, stem: 'Which Autopilot deployment profile is best for shared kiosks where users sign in to a single account?', options: [{ id: 'A', text: 'Self-Deploying mode' }, { id: 'B', text: 'User-Driven Hybrid Entra Join' }, { id: 'C', text: 'Pre-provisioning' }, { id: 'D', text: 'Reset' }], correct: ['A'], explanation: 'Self-Deploying mode runs without user credentials at first boot — ideal for kiosks/digital signage.' },
  { domain: 'Deploy Windows client', type: QType.SINGLE, stem: 'Which feature lets a help-desk technician pre-stage Autopilot devices to apply policies/apps before user sign-in?', options: [{ id: 'A', text: 'Autopilot Pre-provisioning (formerly White Glove)' }, { id: 'B', text: 'Autopilot Self-Deploying' }, { id: 'C', text: 'Reset' }, { id: 'D', text: 'In-place upgrade' }], correct: ['A'], explanation: 'Pre-provisioning lets IT complete the heavy lifting before handing the device to the user.' },
  { domain: 'Deploy Windows client', type: QType.SINGLE, stem: 'Which feature lets you upgrade Windows 10 to Windows 11 over the network with policy compliance?', options: [{ id: 'A', text: 'Intune Feature Updates / Windows Update for Business' }, { id: 'B', text: 'Autopilot Reset' }, { id: 'C', text: 'BitLocker' }, { id: 'D', text: 'NSG' }], correct: ['A'], explanation: 'WUfB and Intune Feature Update profiles deploy major OS upgrades within compliance and ring policies.' },
  { domain: 'Deploy Windows client', type: QType.SINGLE, stem: 'Which Windows imaging tool creates and customizes WIM/ISO images for traditional deployment?', options: [{ id: 'A', text: 'DISM (Deployment Image Servicing and Management)' }, { id: 'B', text: 'Intune' }, { id: 'C', text: 'Defender' }, { id: 'D', text: 'BitLocker' }], correct: ['A'], explanation: 'DISM mounts/services WIM images, integrates updates, and adds drivers/features.' },
  { domain: 'Deploy Windows client', type: QType.SINGLE, stem: 'Which Windows feature lets you reset a device to a clean state remotely while preserving Autopilot enrollment?', options: [{ id: 'A', text: 'Autopilot Reset' }, { id: 'B', text: 'Factory reset (without Autopilot)' }, { id: 'C', text: 'BitLocker recovery' }, { id: 'D', text: 'Defender update' }], correct: ['A'], explanation: 'Autopilot Reset wipes user data and reapplies Autopilot profile + Intune policies.' },
  { domain: 'Deploy Windows client', type: QType.SINGLE, stem: 'Which Entra ID join type is for personally-owned devices accessing corporate apps without joining the directory?', options: [{ id: 'A', text: 'Microsoft Entra registration (workplace join)' }, { id: 'B', text: 'Entra Joined' }, { id: 'C', text: 'Hybrid Entra Joined' }, { id: 'D', text: 'On-prem AD only' }], correct: ['A'], explanation: 'Entra registration registers personal devices for SSO and conditional access without full join.' },
  { domain: 'Deploy Windows client', type: QType.SINGLE, stem: 'Which Entra ID join type is required for cloud-native devices managed only by Intune?', options: [{ id: 'A', text: 'Entra (Azure AD) Joined' }, { id: 'B', text: 'Entra Registered' }, { id: 'C', text: 'Hybrid Entra Joined' }, { id: 'D', text: 'Workgroup' }], correct: ['A'], explanation: 'Entra Joined is for corporate-owned devices fully managed in the cloud.' },
  { domain: 'Manage identity and compliance', type: QType.SINGLE, stem: 'Which Intune policy type evaluates a device against rules (encryption, OS version, etc.) and reports compliance?', options: [{ id: 'A', text: 'Compliance policy' }, { id: 'B', text: 'Configuration profile' }, { id: 'C', text: 'App protection policy' }, { id: 'D', text: 'Update ring' }], correct: ['A'], explanation: 'Compliance policies define minimum requirements; Conditional Access blocks non-compliant devices.' },
  { domain: 'Manage identity and compliance', type: QType.SINGLE, stem: 'Which Intune policy type configures device settings (Wi-Fi, VPN, certificates, OS settings)?', options: [{ id: 'A', text: 'Configuration profile' }, { id: 'B', text: 'Compliance policy' }, { id: 'C', text: 'Update ring' }, { id: 'D', text: 'Endpoint security policy' }], correct: ['A'], explanation: 'Configuration profiles deploy device settings via templates or settings catalog.' },
  { domain: 'Manage identity and compliance', type: QType.SINGLE, stem: 'Which Intune feature deploys app data protection (e.g., prevent copy/paste from work apps to personal apps) on mobile devices WITHOUT enrolling them?', options: [{ id: 'A', text: 'App protection policies (MAM without enrollment)' }, { id: 'B', text: 'Compliance policy' }, { id: 'C', text: 'Configuration profile' }, { id: 'D', text: 'Update ring' }], correct: ['A'], explanation: 'MAM-WE applies data protection at the app level on personal devices, ideal for BYOD.' },
  { domain: 'Manage identity and compliance', type: QType.SINGLE, stem: 'Which Conditional Access integration with Intune blocks access from non-compliant devices?', options: [{ id: 'A', text: 'Require device to be marked as compliant grant control' }, { id: 'B', text: 'Block legacy auth' }, { id: 'C', text: 'Sign-in frequency' }, { id: 'D', text: 'PIM activation' }], correct: ['A'], explanation: 'CA grant control "Require compliant device" enforces Intune compliance status as a prerequisite.' },
  { domain: 'Manage identity and compliance', type: QType.SINGLE, stem: 'Which Microsoft 365 feature reports adoption metrics, productivity insights, and feature usage?', options: [{ id: 'A', text: 'Microsoft 365 admin center reports / Viva Insights' }, { id: 'B', text: 'Defender for Endpoint' }, { id: 'C', text: 'Compliance Manager' }, { id: 'D', text: 'PIM' }], correct: ['A'], explanation: 'Reports show usage; Viva Insights aggregates productivity/adoption analytics for orgs.' },
  { domain: 'Manage, maintain, and protect devices', type: QType.SINGLE, stem: 'Which Defender for Endpoint feature blocks known dangerous behaviors (e.g., child processes from Word) on managed devices?', options: [{ id: 'A', text: 'Attack Surface Reduction (ASR) rules' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Windows Update' }, { id: 'D', text: 'Group Policy' }], correct: ['A'], explanation: 'ASR rules block specific dangerous behaviors via policy.' },
  { domain: 'Manage, maintain, and protect devices', type: QType.SINGLE, stem: 'Which Intune feature deploys Windows Defender Antivirus settings, ASR rules, BitLocker, and disk encryption?', options: [{ id: 'A', text: 'Endpoint security profiles' }, { id: 'B', text: 'Compliance policies only' }, { id: 'C', text: 'App protection' }, { id: 'D', text: 'Update rings' }], correct: ['A'], explanation: 'Endpoint security profiles in Intune cover AV, ASR, disk encryption, firewall, account protection, and EDR.' },
  { domain: 'Manage, maintain, and protect devices', type: QType.SINGLE, stem: 'Which Windows feature provides full-volume encryption with TPM-backed key protection?', options: [{ id: 'A', text: 'BitLocker' }, { id: 'B', text: 'Defender' }, { id: 'C', text: 'Group Policy' }, { id: 'D', text: 'Windows Update' }], correct: ['A'], explanation: 'BitLocker encrypts entire volumes; on TPM-equipped systems, the key is sealed to platform measurements.' },
  { domain: 'Manage, maintain, and protect devices', type: QType.SINGLE, stem: 'Which Intune update strategy organizes devices into rings (e.g., Pilot, Broad, Critical) for staged rollouts?', options: [{ id: 'A', text: 'Update Rings (deferral days, schedule, target groups)' }, { id: 'B', text: 'Compliance policy' }, { id: 'C', text: 'NSG' }, { id: 'D', text: 'BitLocker' }], correct: ['A'], explanation: 'Update Rings target Pilot vs Broad audiences with different deferral schedules.' },
  { domain: 'Manage, maintain, and protect devices', type: QType.SINGLE, stem: 'Which feature lets you delay quality and feature updates separately on managed Windows devices?', options: [{ id: 'A', text: 'Windows Update for Business with deferral periods' }, { id: 'B', text: 'WSUS only' }, { id: 'C', text: 'Group Policy local' }, { id: 'D', text: 'Defender update channels' }], correct: ['A'], explanation: 'WUfB defines deferral days for quality vs feature updates with pause options.' },
  { domain: 'Manage, maintain, and protect devices', type: QType.SINGLE, stem: 'Which Intune feature lets a help-desk admin perform actions like wipe, retire, sync on enrolled devices?', options: [{ id: 'A', text: 'Device actions in Intune (Wipe, Retire, Sync, Restart, Fresh Start, Autopilot Reset)' }, { id: 'B', text: 'Conditional Access' }, { id: 'C', text: 'PIM' }, { id: 'D', text: 'Defender for Endpoint' }], correct: ['A'], explanation: 'Intune\'s device actions include Wipe (factory reset), Retire (remove corporate data), Sync (refresh), and others.' },
  { domain: 'Manage, maintain, and protect devices', type: QType.SINGLE, stem: 'Which Defender for Endpoint feature gives security analysts an interactive shell on managed devices for incident response?', options: [{ id: 'A', text: 'Live response' }, { id: 'B', text: 'Compliance policy' }, { id: 'C', text: 'Update ring' }, { id: 'D', text: 'BitLocker' }], correct: ['A'], explanation: 'Live response is a remote PowerShell-like console for forensic actions on enrolled endpoints.' },
  { domain: 'Manage, maintain, and protect devices', type: QType.SINGLE, stem: 'Which Endpoint Privilege Management feature lets a standard user run a SPECIFIC app with elevated rights without granting admin?', options: [{ id: 'A', text: 'Endpoint Privilege Management (EPM) elevation rules' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Add-as-admin policy' }, { id: 'D', text: 'WSUS' }], correct: ['A'], explanation: 'EPM provides JIT, rule-based elevation for individual apps so users don\'t need persistent admin rights.' },
  { domain: 'Manage applications', type: QType.SINGLE, stem: 'Which Intune capability deploys Win32 apps packaged as .intunewin files?', options: [{ id: 'A', text: 'Win32 app deployment (using IntuneWinAppUtil packaging)' }, { id: 'B', text: 'Microsoft Store apps only' }, { id: 'C', text: 'iOS App Store only' }, { id: 'D', text: 'Anti-malware' }], correct: ['A'], explanation: 'Win32 apps are packaged with IntuneWinAppUtil and deployed with detection rules and dependencies.' },
  { domain: 'Manage applications', type: QType.SINGLE, stem: 'Which Microsoft 365 deployment tool lets you tailor Office Click-to-Run channel and apps?', options: [{ id: 'A', text: 'Office Customization Tool (XML config) + ODT' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Defender' }, { id: 'D', text: 'WSUS' }], correct: ['A'], explanation: 'OCT generates XML config consumed by the Office Deployment Tool to deploy and update Office.' },
  { domain: 'Manage applications', type: QType.SINGLE, stem: 'Which Intune feature ensures iOS apps come from the App Store with managed configuration and app data separation?', options: [{ id: 'A', text: 'Apple Volume Purchase / App and Books in Apple Business Manager + Intune assignment' }, { id: 'B', text: 'Sideloading via TestFlight' }, { id: 'C', text: 'Manual install' }, { id: 'D', text: 'Disable App Store' }], correct: ['A'], explanation: 'Volume-purchased iOS apps are deployed managed via Intune, with optional license assignment per device or user.' },
  { domain: 'Manage applications', type: QType.SINGLE, stem: 'Which Intune feature distributes Microsoft Store apps automatically?', options: [{ id: 'A', text: 'Microsoft Store integration / Microsoft Store apps (new) for Business' }, { id: 'B', text: 'WSUS' }, { id: 'C', text: 'BitLocker' }, { id: 'D', text: 'Conditional Access' }], correct: ['A'], explanation: 'The new Store integration in Intune lets you assign Store apps to users/devices.' },
  { domain: 'Manage applications', type: QType.SINGLE, stem: 'Which Intune feature lets users self-service install approved apps from a portal?', options: [{ id: 'A', text: 'Company Portal app (or web)' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Defender' }, { id: 'D', text: 'WSUS' }], correct: ['A'], explanation: 'Company Portal lists Available apps users can install on demand and shows compliance status.' },
  { domain: 'Manage applications', type: QType.SINGLE, stem: 'Which Win32 app detection method confirms the app is installed correctly?', options: [{ id: 'A', text: 'File / registry / MSI product code detection rule' }, { id: 'B', text: 'Random check' }, { id: 'C', text: 'NSG' }, { id: 'D', text: 'BitLocker' }], correct: ['A'], explanation: 'Detection rules verify install via file path/version, registry value, or MSI ProductCode.' },
  { domain: 'Manage applications', type: QType.SINGLE, stem: 'Which Microsoft 365 service governs configuration of Microsoft 365 Apps for enterprise (Office) at the tenant level?', options: [{ id: 'A', text: 'Office cloud policy service / Microsoft 365 Apps admin center' }, { id: 'B', text: 'Conditional Access' }, { id: 'C', text: 'Compliance Manager' }, { id: 'D', text: 'Defender for Endpoint' }], correct: ['A'], explanation: 'Office cloud policy applies user-level Office settings without GPO; the Apps admin center centralizes update management.' },
  { domain: 'Manage applications', type: QType.SINGLE, stem: 'Which feature ensures managed iOS apps prevent corporate data from being saved to personal cloud storage?', options: [{ id: 'A', text: 'App Protection Policy (MAM) restricting Save-as / Cut-Copy-Paste' }, { id: 'B', text: 'BitLocker' }, { id: 'C', text: 'Conditional Access policy alone' }, { id: 'D', text: 'Defender' }], correct: ['A'], explanation: 'App Protection Policies enforce data-handling restrictions inside MAM-aware apps.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'microsoft-md-102-p1', offset: 0 },
  { slug: 'microsoft-md-102-p2', offset: 8 },
  { slug: 'microsoft-md-102-p3', offset: 16 },
  { slug: 'microsoft-md-102-p4', offset: 24 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: { examId: exam.id, domain: q.domain, difficulty: 3, type: q.type, stem: q.stem, options: q.options, correct: q.correct, explanation: q.explanation, references: [REF], status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up MD-102 to ${TARGET} (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
