/**
 * Top-up: brings every ISC2 CISSP practice exam (P1-P6) to 60 questions
 * by distributing 60 hand-authored supplemental questions across the 8
 * CISSP domains. Each exam pulls a different starting offset.
 *
 *   npx tsx scripts/seed-isc2-cissp-topup.ts
 */
import { PrismaClient, QStatus, QType } from '@prisma/client';

const db = new PrismaClient();

const TARGET = 60;
const TAG_PREFIX = 'topup:isc2-cissp';
const REF = {
  label: 'ISC2 CISSP Common Body of Knowledge',
  url: 'https://www.isc2.org/Certifications/CISSP'
};

type Q = { domain: string; type: QType; stem: string; options: { id: string; text: string }[]; correct: string[]; explanation: string; };

const SUPPLEMENTALS: Q[] = [
  // ===== Security and Risk Management (8) =====
  { domain: 'Security and Risk Management', type: QType.SINGLE,
    stem: 'Which of the following BEST describes the CIA triad?',
    options: [{ id: 'A', text: 'Compliance, Integrity, Availability' }, { id: 'B', text: 'Confidentiality, Integrity, Availability' }, { id: 'C', text: 'Confidentiality, Identity, Authentication' }, { id: 'D', text: 'Continuity, Integrity, Authorization' }],
    correct: ['B'],
    explanation: 'The CIA triad — Confidentiality, Integrity, Availability — is the foundational security model: protect data from unauthorized disclosure, prevent unauthorized modification, and ensure timely access for authorized users.' },
  { domain: 'Security and Risk Management', type: QType.SINGLE,
    stem: 'A company calculates that a flood event causes $2M of damage and is expected once every 25 years. What is the Annualized Loss Expectancy (ALE)?',
    options: [{ id: 'A', text: '$2,000,000' }, { id: 'B', text: '$80,000' }, { id: 'C', text: '$50,000,000' }, { id: 'D', text: '$25,000' }],
    correct: ['B'],
    explanation: 'ALE = SLE × ARO. SLE (Single Loss Expectancy) = $2M; ARO (Annualized Rate of Occurrence) = 1/25 = 0.04. ALE = $2M × 0.04 = $80,000.' },
  { domain: 'Security and Risk Management', type: QType.SINGLE,
    stem: 'Which document describes the FUNCTIONAL behavior of the security program from a high level — what is acceptable, who is responsible, and the consequences of non-compliance?',
    options: [{ id: 'A', text: 'Policy' }, { id: 'B', text: 'Standard' }, { id: 'C', text: 'Procedure' }, { id: 'D', text: 'Guideline' }],
    correct: ['A'],
    explanation: 'Policies are high-level governance documents. Standards mandate specific controls/technologies; procedures describe step-by-step how to do something; guidelines are recommendations.' },
  { domain: 'Security and Risk Management', type: QType.SINGLE,
    stem: 'Which risk treatment option involves accepting the consequence of a risk if it materializes, typically because mitigation cost exceeds the impact?',
    options: [{ id: 'A', text: 'Transfer' }, { id: 'B', text: 'Mitigate' }, { id: 'C', text: 'Avoid' }, { id: 'D', text: 'Accept' }],
    correct: ['D'],
    explanation: 'Risk acceptance is choosing to live with a risk. Transfer shifts to a third party (e.g., insurance); mitigate reduces likelihood/impact; avoid eliminates the activity that creates the risk.' },
  { domain: 'Security and Risk Management', type: QType.SINGLE,
    stem: 'Under GDPR, what is the maximum statutory fine for the most severe categories of violations?',
    options: [{ id: 'A', text: 'Up to 4% of annual global turnover or €20 million, whichever is higher' }, { id: 'B', text: 'Up to 2% of US revenue' }, { id: 'C', text: 'A flat €100,000' }, { id: 'D', text: 'No fines, only injunctions' }],
    correct: ['A'],
    explanation: 'GDPR Article 83 sets the highest tier of fines at up to 4% of annual global turnover or €20M, whichever is greater, for the most severe violations.' },
  { domain: 'Security and Risk Management', type: QType.SINGLE,
    stem: 'In the (ISC)² Code of Ethics, which canon comes FIRST and takes precedence over the others?',
    options: [{ id: 'A', text: 'Protect society, the common good, necessary public trust and confidence, and the infrastructure' }, { id: 'B', text: 'Act honorably, honestly, justly, responsibly, and legally' }, { id: 'C', text: 'Provide diligent and competent service to principals' }, { id: 'D', text: 'Advance and protect the profession' }],
    correct: ['A'],
    explanation: 'The four canons are listed in order of priority. Protecting society and infrastructure is canon #1 and takes precedence when conflicts arise.' },
  { domain: 'Security and Risk Management', type: QType.SINGLE,
    stem: 'Which type of plan focuses on getting critical IT systems back online after a disaster, with defined RTO and RPO targets?',
    options: [{ id: 'A', text: 'Disaster Recovery Plan (DRP)' }, { id: 'B', text: 'Business Continuity Plan (BCP)' }, { id: 'C', text: 'Incident Response Plan' }, { id: 'D', text: 'Information Security Policy' }],
    correct: ['A'],
    explanation: 'A DRP focuses on restoring IT systems after disruption with technical RTO/RPO targets. BCP is broader — keeping the business operating; incident response handles security events; policy is governance.' },
  { domain: 'Security and Risk Management', type: QType.SINGLE,
    stem: 'What is the PRIMARY output of a Business Impact Analysis (BIA)?',
    options: [{ id: 'A', text: 'A prioritized list of critical business functions with RTO and RPO requirements' }, { id: 'B', text: 'A finished disaster recovery script' }, { id: 'C', text: 'A complete penetration-test report' }, { id: 'D', text: 'A signed insurance policy' }],
    correct: ['A'],
    explanation: 'A BIA identifies critical processes, assesses impact of disruption, and produces RTO/RPO requirements that drive BCP/DRP design.' },

  // ===== Asset Security (6) =====
  { domain: 'Asset Security', type: QType.SINGLE,
    stem: 'Which data classification level typically applies to information that, if disclosed, would cause exceptionally grave damage to national security?',
    options: [{ id: 'A', text: 'Confidential' }, { id: 'B', text: 'Secret' }, { id: 'C', text: 'Top Secret' }, { id: 'D', text: 'Unclassified' }],
    correct: ['C'],
    explanation: 'In the U.S. government scheme: Confidential = damage; Secret = serious damage; Top Secret = exceptionally grave damage. Private sector schemes differ but follow similar tiering.' },
  { domain: 'Asset Security', type: QType.SINGLE,
    stem: 'Who has the ultimate accountability for the protection of organizational data?',
    options: [{ id: 'A', text: 'Data owner' }, { id: 'B', text: 'Data custodian' }, { id: 'C', text: 'System administrator' }, { id: 'D', text: 'End user' }],
    correct: ['A'],
    explanation: 'The data owner (typically a business executive) is accountable for classification, access decisions, and risk acceptance. Custodians implement controls; admins operate systems; users follow policies.' },
  { domain: 'Asset Security', type: QType.SINGLE,
    stem: 'Which media-sanitization method renders data unrecoverable by physically destroying the media — the strongest level for highly sensitive data?',
    options: [{ id: 'A', text: 'Clearing' }, { id: 'B', text: 'Purging' }, { id: 'C', text: 'Destruction' }, { id: 'D', text: 'Reformatting' }],
    correct: ['C'],
    explanation: 'NIST 800-88 levels: Clearing (logical/overwrite), Purging (degaussing/firmware wipe), Destruction (shredding, incineration). Destruction is the most thorough.' },
  { domain: 'Asset Security', type: QType.SINGLE,
    stem: 'Which of the following is an example of "data in use"?',
    options: [{ id: 'A', text: 'A file decrypted in memory while being edited' }, { id: 'B', text: 'A backup tape stored in a vault' }, { id: 'C', text: 'A TLS-encrypted HTTP request crossing the internet' }, { id: 'D', text: 'A sealed flash drive in a drawer' }],
    correct: ['A'],
    explanation: 'Data in use = actively being processed in memory. Data at rest = stored (tape/drive). Data in transit = moving across networks (TLS/HTTPS).' },
  { domain: 'Asset Security', type: QType.SINGLE,
    stem: 'Which technique replaces sensitive data with a non-sensitive placeholder (token) that maps back to the original value via a secure vault?',
    options: [{ id: 'A', text: 'Tokenization' }, { id: 'B', text: 'Encryption' }, { id: 'C', text: 'Hashing' }, { id: 'D', text: 'Masking' }],
    correct: ['A'],
    explanation: 'Tokenization substitutes sensitive data with tokens; the original is held in a secure mapping vault. Encryption is reversible with a key; hashing is one-way; masking obscures display values.' },
  { domain: 'Asset Security', type: QType.SINGLE,
    stem: 'A company wants to ensure that PII is handled in accordance with applicable laws across multiple jurisdictions. Which role is PRIMARILY responsible for ensuring the legal/regulatory compliance of data processing?',
    options: [{ id: 'A', text: 'Data Protection Officer (DPO)' }, { id: 'B', text: 'Data custodian' }, { id: 'C', text: 'Database administrator' }, { id: 'D', text: 'CISO' }],
    correct: ['A'],
    explanation: 'A DPO (mandatory under GDPR for many organizations) ensures data-protection compliance and serves as a contact for regulators. The CISO has broader security responsibilities; custodians/DBAs operate.' },

  // ===== Security Architecture and Engineering (8) =====
  { domain: 'Security Architecture and Engineering', type: QType.SINGLE,
    stem: 'Which of the following is an example of "defense in depth"?',
    options: [{ id: 'A', text: 'Layering perimeter firewalls, host firewalls, IDS, EDR, MFA, and least-privilege controls' }, { id: 'B', text: 'Relying on a single, very strong perimeter firewall' }, { id: 'C', text: 'Storing all backups on the same server as production' }, { id: 'D', text: 'Granting administrators unlimited access' }],
    correct: ['A'],
    explanation: 'Defense in depth uses multiple, overlapping controls so that failure of one does not compromise the system. Single-control reliance is the opposite.' },
  { domain: 'Security Architecture and Engineering', type: QType.SINGLE,
    stem: 'Which security model is concerned PRIMARILY with confidentiality and is enforced by the rules "no read up, no write down"?',
    options: [{ id: 'A', text: 'Bell-LaPadula' }, { id: 'B', text: 'Biba' }, { id: 'C', text: 'Clark-Wilson' }, { id: 'D', text: 'Brewer-Nash' }],
    correct: ['A'],
    explanation: 'Bell-LaPadula enforces confidentiality with the simple security property (no read up) and the * (star) property (no write down). Biba is the integrity counterpart with reversed rules.' },
  { domain: 'Security Architecture and Engineering', type: QType.SINGLE,
    stem: 'Which security model is focused on integrity and uses the principles "no read down, no write up"?',
    options: [{ id: 'A', text: 'Bell-LaPadula' }, { id: 'B', text: 'Biba' }, { id: 'C', text: 'Brewer-Nash' }, { id: 'D', text: 'Take-Grant' }],
    correct: ['B'],
    explanation: 'Biba prevents low-integrity sources from corrupting high-integrity data: subjects can\'t read lower-integrity data nor write to higher-integrity data.' },
  { domain: 'Security Architecture and Engineering', type: QType.SINGLE,
    stem: 'Which symmetric encryption algorithm is the U.S. NIST standard, with key sizes of 128, 192, and 256 bits?',
    options: [{ id: 'A', text: 'DES' }, { id: 'B', text: '3DES' }, { id: 'C', text: 'AES' }, { id: 'D', text: 'RSA' }],
    correct: ['C'],
    explanation: 'AES (FIPS 197) replaced DES/3DES as the NIST symmetric standard. RSA is asymmetric.' },
  { domain: 'Security Architecture and Engineering', type: QType.SINGLE,
    stem: 'In a Public Key Infrastructure (PKI), which entity issues digital certificates after verifying the requester\'s identity?',
    options: [{ id: 'A', text: 'Registration Authority (RA)' }, { id: 'B', text: 'Certificate Authority (CA)' }, { id: 'C', text: 'Validation Authority (VA)' }, { id: 'D', text: 'Subscriber' }],
    correct: ['B'],
    explanation: 'The CA issues and signs certificates. The RA verifies identity and forwards requests to the CA. The VA confirms a certificate\'s status (e.g., OCSP). The subscriber is the certificate holder.' },
  { domain: 'Security Architecture and Engineering', type: QType.SINGLE,
    stem: 'Which cryptographic primitive provides INTEGRITY and AUTHENTICATION using a shared secret key?',
    options: [{ id: 'A', text: 'Digital signature (RSA/ECDSA)' }, { id: 'B', text: 'HMAC' }, { id: 'C', text: 'Symmetric encryption (AES)' }, { id: 'D', text: 'One-way hash (SHA-256)' }],
    correct: ['B'],
    explanation: 'HMAC = keyed hash; both parties share a secret key, so it provides integrity AND authentication. Plain hashes provide only integrity. Digital signatures use asymmetric keys (no shared secret).' },
  { domain: 'Security Architecture and Engineering', type: QType.SINGLE,
    stem: 'Which type of attack against a cryptographic system involves observing power consumption, electromagnetic emissions, or timing to extract secrets?',
    options: [{ id: 'A', text: 'Birthday attack' }, { id: 'B', text: 'Side-channel attack' }, { id: 'C', text: 'Replay attack' }, { id: 'D', text: 'Brute-force attack' }],
    correct: ['B'],
    explanation: 'Side-channel attacks exploit physical leakage (timing, power, EM emissions, sound) rather than mathematical weaknesses. Birthday attacks target hash collisions; replay re-sends valid traffic; brute-force tries all keys.' },
  { domain: 'Security Architecture and Engineering', type: QType.SINGLE,
    stem: 'A trusted platform module (TPM) provides which capability?',
    options: [{ id: 'A', text: 'Hardware-rooted cryptographic key storage and integrity measurements (e.g., for full-disk encryption and secure boot)' }, { id: 'B', text: 'Hardware acceleration for video' }, { id: 'C', text: 'A backup of the BIOS' }, { id: 'D', text: 'A network firewall' }],
    correct: ['A'],
    explanation: 'TPMs are dedicated chips storing keys and platform measurements; used for BitLocker, secure boot, and remote attestation.' },

  // ===== Communication and Network Security (8) =====
  { domain: 'Communication and Network Security', type: QType.SINGLE,
    stem: 'Which OSI layer is responsible for end-to-end delivery, segmentation, and flow control — where TCP and UDP operate?',
    options: [{ id: 'A', text: 'Layer 2 — Data Link' }, { id: 'B', text: 'Layer 3 — Network' }, { id: 'C', text: 'Layer 4 — Transport' }, { id: 'D', text: 'Layer 7 — Application' }],
    correct: ['C'],
    explanation: 'TCP/UDP live at Layer 4 (Transport). Layer 3 routes (IP); Layer 2 frames (Ethernet); Layer 7 is application protocols (HTTP, DNS).' },
  { domain: 'Communication and Network Security', type: QType.SINGLE,
    stem: 'Which protocol enables creating an encrypted tunnel between a remote client and a corporate network, commonly used for site-to-site or remote-access VPNs?',
    options: [{ id: 'A', text: 'SNMP' }, { id: 'B', text: 'SMTP' }, { id: 'C', text: 'IPsec' }, { id: 'D', text: 'NTP' }],
    correct: ['C'],
    explanation: 'IPsec (with ESP/AH and IKE) is the standard for VPN tunnels providing confidentiality, integrity, and authentication at the network layer.' },
  { domain: 'Communication and Network Security', type: QType.SINGLE,
    stem: 'Which firewall type maintains a state table of active connections and only allows packets matching a known connection?',
    options: [{ id: 'A', text: 'Packet-filtering firewall' }, { id: 'B', text: 'Stateful inspection firewall' }, { id: 'C', text: 'Proxy firewall' }, { id: 'D', text: 'Next-gen firewall' }],
    correct: ['B'],
    explanation: 'Stateful firewalls track connection state, applying rules based on flow context. Stateless packet filters look at each packet alone; proxies terminate connections at the firewall; NGFWs add app awareness/IPS.' },
  { domain: 'Communication and Network Security', type: QType.SINGLE,
    stem: 'Which 802.11 wireless security standard introduced AES-CCMP and replaced WEP/WPA?',
    options: [{ id: 'A', text: 'WEP-128' }, { id: 'B', text: 'WPA' }, { id: 'C', text: 'WPA2' }, { id: 'D', text: 'WPS' }],
    correct: ['C'],
    explanation: 'WPA2 (IEEE 802.11i) introduced AES-CCMP. WEP is broken; WPA used TKIP as a transition; WPS is a setup feature with known weaknesses.' },
  { domain: 'Communication and Network Security', type: QType.SINGLE,
    stem: 'A company needs to segment networks so that compromise of one VLAN does not allow lateral movement to others. Which control is MOST appropriate?',
    options: [{ id: 'A', text: 'Implement private VLANs and inter-VLAN ACLs' }, { id: 'B', text: 'Disable HTTPS' }, { id: 'C', text: 'Move all traffic to a single flat VLAN' }, { id: 'D', text: 'Use only public Wi-Fi' }],
    correct: ['A'],
    explanation: 'Network segmentation with VLANs and ACLs at L3 boundaries limits lateral movement. The other options reduce security.' },
  { domain: 'Communication and Network Security', type: QType.SINGLE,
    stem: 'Which DNS attack involves an attacker injecting forged DNS records into a resolver\'s cache to redirect traffic?',
    options: [{ id: 'A', text: 'DNS amplification' }, { id: 'B', text: 'DNS cache poisoning (spoofing)' }, { id: 'C', text: 'DNS exfiltration' }, { id: 'D', text: 'DNSSEC validation' }],
    correct: ['B'],
    explanation: 'DNS cache poisoning injects forged responses into a recursive resolver\'s cache. Amplification is a DDoS technique; exfil hides data in DNS queries; DNSSEC adds integrity to defend against poisoning.' },
  { domain: 'Communication and Network Security', type: QType.SINGLE,
    stem: 'Which protocol provides authentication, integrity, and origin authentication for DNS responses, defending against spoofing?',
    options: [{ id: 'A', text: 'DNS-over-HTTPS (DoH)' }, { id: 'B', text: 'DNSSEC' }, { id: 'C', text: 'DoT' }, { id: 'D', text: 'TLS' }],
    correct: ['B'],
    explanation: 'DNSSEC signs records so resolvers can verify authenticity. DoH/DoT encrypt the DNS channel (privacy) but do not authenticate the records themselves.' },
  { domain: 'Communication and Network Security', type: QType.SINGLE,
    stem: 'Which network device operates at OSI Layer 7 to inspect application-layer payload, enforce rules, and often hide internal addressing?',
    options: [{ id: 'A', text: 'Hub' }, { id: 'B', text: 'Switch' }, { id: 'C', text: 'Router' }, { id: 'D', text: 'Application proxy / WAF' }],
    correct: ['D'],
    explanation: 'Application proxies and WAFs operate at Layer 7. Hubs are physical (L1); switches frame (L2); routers route (L3).' },

  // ===== Identity and Access Management (8) =====
  { domain: 'Identity and Access Management', type: QType.SINGLE,
    stem: 'Which authentication factor category is "something you have"?',
    options: [{ id: 'A', text: 'Password' }, { id: 'B', text: 'Hardware token / smart card' }, { id: 'C', text: 'Fingerprint' }, { id: 'D', text: 'Behavioral biometrics' }],
    correct: ['B'],
    explanation: 'Factor categories: knowledge (something you know), possession (something you have), inherence (something you are). Tokens/smart cards are possession; passwords are knowledge; biometrics are inherence.' },
  { domain: 'Identity and Access Management', type: QType.SINGLE,
    stem: 'Which access-control model assigns permissions to ROLES, and users derive permissions from their role memberships?',
    options: [{ id: 'A', text: 'DAC (Discretionary Access Control)' }, { id: 'B', text: 'MAC (Mandatory Access Control)' }, { id: 'C', text: 'RBAC (Role-Based Access Control)' }, { id: 'D', text: 'ABAC (Attribute-Based Access Control)' }],
    correct: ['C'],
    explanation: 'RBAC: permissions are bound to roles, users to roles. DAC lets owners share; MAC enforces labels system-wide; ABAC decides via attributes/policies.' },
  { domain: 'Identity and Access Management', type: QType.SINGLE,
    stem: 'Which access-control model evaluates dynamic attributes about the user, resource, action, and environment in policy decisions?',
    options: [{ id: 'A', text: 'DAC' }, { id: 'B', text: 'MAC' }, { id: 'C', text: 'RBAC' }, { id: 'D', text: 'ABAC' }],
    correct: ['D'],
    explanation: 'ABAC uses attributes (user clearance, resource sensitivity, time, location) in policy expressions, providing fine-grained, context-aware decisions.' },
  { domain: 'Identity and Access Management', type: QType.SINGLE,
    stem: 'Which protocol is commonly used for federated single sign-on between an Identity Provider (IdP) and a Service Provider (SP), exchanging XML assertions over the browser?',
    options: [{ id: 'A', text: 'SAML 2.0' }, { id: 'B', text: 'RADIUS' }, { id: 'C', text: 'Kerberos' }, { id: 'D', text: 'TACACS+' }],
    correct: ['A'],
    explanation: 'SAML uses XML assertions for browser-based SSO. RADIUS/TACACS+ are AAA protocols for network access; Kerberos is enterprise SSO via tickets.' },
  { domain: 'Identity and Access Management', type: QType.SINGLE,
    stem: 'Which protocol is the modern OAuth 2.0-based federated SSO standard widely used by web and mobile apps, returning a JSON Web Token (ID Token)?',
    options: [{ id: 'A', text: 'SAML 1.1' }, { id: 'B', text: 'OpenID Connect' }, { id: 'C', text: 'Kerberos' }, { id: 'D', text: 'Diameter' }],
    correct: ['B'],
    explanation: 'OpenID Connect (OIDC) sits on OAuth 2.0 and adds an authentication layer (ID Token as JWT). Used by Google, Microsoft Entra, Okta, etc., for modern SSO.' },
  { domain: 'Identity and Access Management', type: QType.SINGLE,
    stem: 'Which authentication mechanism uses a sequence of tickets issued by a Key Distribution Center (KDC) and is foundational to Active Directory?',
    options: [{ id: 'A', text: 'OAuth' }, { id: 'B', text: 'Kerberos' }, { id: 'C', text: 'TACACS+' }, { id: 'D', text: 'SCIM' }],
    correct: ['B'],
    explanation: 'Kerberos uses a KDC (Authentication Server + Ticket Granting Server) to issue ticket-granting and service tickets. AD is Microsoft\'s Kerberos-based directory.' },
  { domain: 'Identity and Access Management', type: QType.SINGLE,
    stem: 'Which attack involves an attacker capturing an authentication credential (e.g., NTLM hash) and re-using it to authenticate without knowing the underlying password?',
    options: [{ id: 'A', text: 'Pass-the-hash' }, { id: 'B', text: 'Phishing' }, { id: 'C', text: 'SQL injection' }, { id: 'D', text: 'Buffer overflow' }],
    correct: ['A'],
    explanation: 'Pass-the-hash uses captured NTLM hashes directly to authenticate to Windows services without cracking the password. Mitigations include LSA protection, credential guard, and tiered admin models.' },
  { domain: 'Identity and Access Management', type: QType.SINGLE,
    stem: 'Which identity lifecycle stage involves removing access promptly when an employee leaves the organization?',
    options: [{ id: 'A', text: 'Provisioning' }, { id: 'B', text: 'De-provisioning' }, { id: 'C', text: 'Recertification' }, { id: 'D', text: 'Just-in-time access' }],
    correct: ['B'],
    explanation: 'De-provisioning revokes access at termination/transfer to limit insider risk and orphan accounts. Provisioning grants access; recertification reviews existing access; JIT grants short-lived elevated access.' },

  // ===== Security Assessment and Testing (7) =====
  { domain: 'Security Assessment and Testing', type: QType.SINGLE,
    stem: 'Which assessment provides the BLACK-box perspective of an external attacker who has no prior knowledge of the system?',
    options: [{ id: 'A', text: 'White-box test' }, { id: 'B', text: 'Black-box penetration test' }, { id: 'C', text: 'Code review' }, { id: 'D', text: 'Vulnerability scan' }],
    correct: ['B'],
    explanation: 'Black-box pen tests simulate an external attacker without internal info. White-box has full knowledge; gray-box is partial. Vulnerability scans are automated scans, not full pen tests.' },
  { domain: 'Security Assessment and Testing', type: QType.SINGLE,
    stem: 'Which type of testing exercises an application by feeding it malformed/random inputs to discover crashes and memory corruption?',
    options: [{ id: 'A', text: 'Fuzz testing (fuzzing)' }, { id: 'B', text: 'Penetration testing' }, { id: 'C', text: 'Compliance audit' }, { id: 'D', text: 'Static code analysis' }],
    correct: ['A'],
    explanation: 'Fuzzing automatically generates anomalous inputs to find input-handling bugs. Pen tests are broader; compliance audits check policy; SAST inspects code statically.' },
  { domain: 'Security Assessment and Testing', type: QType.SINGLE,
    stem: 'Which attestation report describes a service organization\'s controls and is intended for limited-distribution use by users\' management and auditors?',
    options: [{ id: 'A', text: 'SOC 1 Type 2' }, { id: 'B', text: 'SOC 2 Type 2' }, { id: 'C', text: 'SOC 3' }, { id: 'D', text: 'PCI DSS RoC' }],
    correct: ['B'],
    explanation: 'SOC 2 reports are restricted-distribution and cover security, availability, confidentiality, processing integrity, and privacy. SOC 1 is for financial-reporting controls. SOC 3 is a public-distribution summary. PCI RoC reports on payment-card controls.' },
  { domain: 'Security Assessment and Testing', type: QType.SINGLE,
    stem: 'Which technique tests whether an application\'s INPUT validation correctly rejects malicious payloads, by inspecting source code WITHOUT executing it?',
    options: [{ id: 'A', text: 'SAST (static analysis)' }, { id: 'B', text: 'DAST (dynamic analysis)' }, { id: 'C', text: 'Penetration test' }, { id: 'D', text: 'Threat modeling' }],
    correct: ['A'],
    explanation: 'SAST analyzes source/binaries statically. DAST exercises a running app. Pen tests are broader manual tests. Threat modeling is design-phase analysis.' },
  { domain: 'Security Assessment and Testing', type: QType.SINGLE,
    stem: 'Which control assesses whether security controls are designed and operating effectively over a period of time, providing an opinion on their effectiveness?',
    options: [{ id: 'A', text: 'Penetration test' }, { id: 'B', text: 'Risk assessment' }, { id: 'C', text: 'Audit' }, { id: 'D', text: 'Vulnerability scan' }],
    correct: ['C'],
    explanation: 'Audits provide independent opinion on control design and effectiveness over a period. Pen tests / scans assess vulnerabilities; risk assessments quantify likelihood/impact.' },
  { domain: 'Security Assessment and Testing', type: QType.SINGLE,
    stem: 'Which tabletop-style activity walks an incident scenario through stakeholders without performing actual technical actions?',
    options: [{ id: 'A', text: 'Tabletop exercise' }, { id: 'B', text: 'Full-scale failover test' }, { id: 'C', text: 'Red-team exercise' }, { id: 'D', text: 'Penetration test' }],
    correct: ['A'],
    explanation: 'Tabletops validate plans, roles, and decisions through discussion. Failovers actually move workload; red teams execute attacks; pen tests probe technical controls.' },
  { domain: 'Security Assessment and Testing', type: QType.SINGLE,
    stem: 'Which assessment activity simulates a determined adversary across people, processes, and technology, with stealth, to test detection and response?',
    options: [{ id: 'A', text: 'Vulnerability scan' }, { id: 'B', text: 'Compliance audit' }, { id: 'C', text: 'Red-team exercise' }, { id: 'D', text: 'Risk register review' }],
    correct: ['C'],
    explanation: 'Red-team exercises simulate advanced persistent adversaries to test detection/response in addition to controls. Vulnerability scans are technical inventories; audits check policy; risk reviews are governance.' },

  // ===== Security Operations (8) =====
  { domain: 'Security Operations', type: QType.SINGLE,
    stem: 'In incident response, which phase comes IMMEDIATELY after detection and analysis?',
    options: [{ id: 'A', text: 'Containment, eradication, and recovery' }, { id: 'B', text: 'Lessons learned' }, { id: 'C', text: 'Preparation' }, { id: 'D', text: 'Identification' }],
    correct: ['A'],
    explanation: 'NIST SP 800-61 phases: preparation; detection & analysis; containment, eradication, & recovery; post-incident activity (lessons learned).' },
  { domain: 'Security Operations', type: QType.SINGLE,
    stem: 'Which technology continually collects, correlates, and analyzes security event logs across an enterprise, generating alerts on suspicious patterns?',
    options: [{ id: 'A', text: 'SIEM' }, { id: 'B', text: 'IDS' }, { id: 'C', text: 'CASB' }, { id: 'D', text: 'WAF' }],
    correct: ['A'],
    explanation: 'SIEM (Security Information and Event Management) ingests/correlates logs from many sources and alerts on patterns. IDS detects on a single sensor; CASB monitors cloud usage; WAF inspects HTTP traffic.' },
  { domain: 'Security Operations', type: QType.SINGLE,
    stem: 'Which control is the FIRST priority in a ransomware incident to limit further damage?',
    options: [{ id: 'A', text: 'Containment — isolate affected systems from the network' }, { id: 'B', text: 'Pay the ransom' }, { id: 'C', text: 'Format every disk' }, { id: 'D', text: 'Send a press release' }],
    correct: ['A'],
    explanation: 'Containment (network isolation) limits blast radius. Ransom payment is generally last resort/discouraged. Format/PR come after containment is in place.' },
  { domain: 'Security Operations', type: QType.SINGLE,
    stem: 'Which type of backup site is fully equipped and ready to take over operations within minutes to hours?',
    options: [{ id: 'A', text: 'Cold site' }, { id: 'B', text: 'Warm site' }, { id: 'C', text: 'Hot site' }, { id: 'D', text: 'Mobile site' }],
    correct: ['C'],
    explanation: 'Hot sites are continually live with replicated data and active hardware. Warm sites have hardware but data must be loaded. Cold sites are facilities only.' },
  { domain: 'Security Operations', type: QType.SINGLE,
    stem: 'Which forensic principle requires that evidence be handled in a way that preserves its admissibility — documenting every transfer of custody?',
    options: [{ id: 'A', text: 'Chain of custody' }, { id: 'B', text: 'Discovery' }, { id: 'C', text: 'Subpoena' }, { id: 'D', text: 'Hearsay rule' }],
    correct: ['A'],
    explanation: 'Chain of custody documents who handled evidence, when, and how, preserving integrity for legal admissibility.' },
  { domain: 'Security Operations', type: QType.SINGLE,
    stem: 'Which backup strategy backs up only files that have changed since the LAST FULL backup, requiring only the last full + last differential to restore?',
    options: [{ id: 'A', text: 'Differential' }, { id: 'B', text: 'Incremental' }, { id: 'C', text: 'Synthetic full' }, { id: 'D', text: 'Mirror' }],
    correct: ['A'],
    explanation: 'Differential backs up changes since the last full; restore = last full + latest differential. Incremental backs up changes since last incremental; restore = last full + every incremental.' },
  { domain: 'Security Operations', type: QType.SINGLE,
    stem: 'Which control implements the LEAST PRIVILEGE principle in an enterprise admin tier?',
    options: [{ id: 'A', text: 'Just-in-time elevation with approval and time-bounded access' }, { id: 'B', text: 'Permanent global admin rights for all engineers' }, { id: 'C', text: 'Shared root passwords' }, { id: 'D', text: 'Disabling MFA for admins' }],
    correct: ['A'],
    explanation: 'JIT elevation grants admin rights only when needed and for short windows, embodying least privilege. Permanent rights, shared credentials, and disabling MFA all violate it.' },
  { domain: 'Security Operations', type: QType.SINGLE,
    stem: 'Which principle requires that no single person can complete a sensitive transaction alone — for example, requiring two officers to approve a wire transfer?',
    options: [{ id: 'A', text: 'Separation of duties' }, { id: 'B', text: 'Least privilege' }, { id: 'C', text: 'Need to know' }, { id: 'D', text: 'Defense in depth' }],
    correct: ['A'],
    explanation: 'Separation of duties (SoD) divides critical tasks across people to prevent fraud. Least privilege limits per-user rights; need-to-know limits info access; defense in depth uses layered controls.' },

  // ===== Software Development Security (7) =====
  { domain: 'Software Development Security', type: QType.SINGLE,
    stem: 'Which OWASP Top 10 category covers SQL injection, command injection, and LDAP injection?',
    options: [{ id: 'A', text: 'A01:2021 — Broken Access Control' }, { id: 'B', text: 'A03:2021 — Injection' }, { id: 'C', text: 'A07:2021 — Identification and Authentication Failures' }, { id: 'D', text: 'A02:2021 — Cryptographic Failures' }],
    correct: ['B'],
    explanation: 'OWASP A03:2021 covers all forms of injection. SQL/command/LDAP/OS injection share the root cause: untrusted data interpreted as code/queries.' },
  { domain: 'Software Development Security', type: QType.SINGLE,
    stem: 'Which control PREVENTS SQL injection in application code?',
    options: [{ id: 'A', text: 'Parameterized queries / prepared statements' }, { id: 'B', text: 'Increasing CPU' }, { id: 'C', text: 'Putting the database on a separate server' }, { id: 'D', text: 'Using HTTPS' }],
    correct: ['A'],
    explanation: 'Parameterized queries separate SQL syntax from user data, defeating injection. Network/HTTPS/server placement are unrelated to injection prevention.' },
  { domain: 'Software Development Security', type: QType.SINGLE,
    stem: 'Which testing technique inspects source code automatically for known weaknesses without executing the program?',
    options: [{ id: 'A', text: 'Static Application Security Testing (SAST)' }, { id: 'B', text: 'Dynamic Application Security Testing (DAST)' }, { id: 'C', text: 'Fuzzing' }, { id: 'D', text: 'IAST' }],
    correct: ['A'],
    explanation: 'SAST analyzes source/binaries statically. DAST tests a running app from outside; IAST instruments the app to combine views; fuzzing inputs random data.' },
  { domain: 'Software Development Security', type: QType.SINGLE,
    stem: 'In a Software Bill of Materials (SBOM), what is the primary purpose?',
    options: [{ id: 'A', text: 'List all components/libraries in a software product so consumers can assess vulnerabilities and licensing' }, { id: 'B', text: 'Track the price of each module' }, { id: 'C', text: 'Replace source code in repositories' }, { id: 'D', text: 'Encrypt build artifacts' }],
    correct: ['A'],
    explanation: 'SBOMs (e.g., SPDX, CycloneDX) inventory components — versions, licenses, suppliers — enabling vulnerability triage (e.g., Log4Shell) and license compliance.' },
  { domain: 'Software Development Security', type: QType.SINGLE,
    stem: 'Which is a key advantage of using a Web Application Firewall (WAF) in front of a web app?',
    options: [{ id: 'A', text: 'It can block common app-layer attacks (SQLi, XSS, OWASP Top 10) at the perimeter, augmenting in-code defenses' }, { id: 'B', text: 'It replaces the need for input validation in code' }, { id: 'C', text: 'It prevents physical theft of servers' }, { id: 'D', text: 'It is only for HTTPS termination' }],
    correct: ['A'],
    explanation: 'WAFs inspect HTTP traffic and block common app-layer attacks. They complement (not replace) secure coding. Physical security is unrelated; HTTPS termination is a separate function.' },
  { domain: 'Software Development Security', type: QType.SINGLE,
    stem: 'In a CI/CD pipeline, where should secret values (API keys, DB passwords) be stored?',
    options: [{ id: 'A', text: 'In a dedicated secrets vault (Azure Key Vault, AWS Secrets Manager, HashiCorp Vault), retrieved at deploy/run time' }, { id: 'B', text: 'Hard-coded in source files' }, { id: 'C', text: 'In .env files committed to the repo' }, { id: 'D', text: 'Stored as plain text in the wiki' }],
    correct: ['A'],
    explanation: 'Secrets must live in vaults with access control, rotation, and audit. Source files, committed .env, and wikis are insecure storage that lead to leaked credentials.' },
  { domain: 'Software Development Security', type: QType.SINGLE,
    stem: 'Which secure-design principle states that the default state of a permission system should be "deny" unless explicitly allowed?',
    options: [{ id: 'A', text: 'Fail-secure / fail-closed' }, { id: 'B', text: 'Default-deny (whitelisting)' }, { id: 'C', text: 'Open design' }, { id: 'D', text: 'Defense in depth' }],
    correct: ['B'],
    explanation: 'Default-deny / whitelist: only explicitly permitted actions are allowed. Fail-secure means failure leaves the system in a safe state; open design publishes design rather than relying on secrecy.' }
];

const EXAMS: { slug: string; offset: number }[] = [
  { slug: 'isc2-cissp-p1', offset: 0 },
  { slug: 'isc2-cissp-p2', offset: 10 },
  { slug: 'isc2-cissp-p3', offset: 20 },
  { slug: 'isc2-cissp-p4', offset: 30 },
  { slug: 'isc2-cissp-p5', offset: 40 },
  { slug: 'isc2-cissp-p6', offset: 50 }
];

async function topUp(slug: string, offset: number) {
  const exam = await db.exam.findUnique({ where: { slug } });
  if (!exam) { console.log(`  - skip ${slug}: not found`); return; }
  const current = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  if (current >= TARGET) { console.log(`  - ${slug}: already at ${current}, skip`); return; }
  const need = TARGET - current;
  const tag = `${TAG_PREFIX}:${slug}`;
  const already = await db.question.count({ where: { examId: exam.id, generatedBy: tag } });
  if (already >= need) { console.log(`  - ${slug}: already topped, skip`); return; }
  for (let i = 0; i < need; i++) {
    const q = SUPPLEMENTALS[(offset + i) % SUPPLEMENTALS.length];
    await db.question.create({
      data: {
        examId: exam.id, domain: q.domain, difficulty: 3, type: q.type,
        stem: q.stem, options: q.options, correct: q.correct,
        explanation: q.explanation, references: [REF],
        status: QStatus.PUBLISHED, generatedBy: tag, isTeaser: false
      }
    });
  }
  const newTotal = await db.question.count({ where: { examId: exam.id, status: QStatus.PUBLISHED } });
  await db.exam.update({ where: { id: exam.id }, data: { questionCount: newTotal } });
  console.log(`  ✓ ${slug}: +${need} → ${newTotal} total`);
}

async function main() {
  console.log(`Topping up ISC2 CISSP exams to ${TARGET} questions each (${SUPPLEMENTALS.length} supplementals)...`);
  for (const e of EXAMS) await topUp(e.slug, e.offset);
  console.log(`✓ CISSP topup complete.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => db.$disconnect());
